### PR TITLE
Module deprecation cleanup

### PR DESCRIPTION
**Pull request by asoto-r7**
This change removes two modules marked for deprecation, as they've been relocated.  The announcement was made in late December, with a deprecation date of late February.  We're just getting around to it now.  :-D

`modules/auxiliary/scanner/http/epmp1000_cmd_exec.rb` -> 
`modules/auxiliary/scanner/http/epmp1000_ping_cmd_exec.rb`

`modules/auxiliary/scanner/snmp/cambium_snmp_loot.rb` -> 
`modules/auxiliary/scanner/snmp/epmp1000_snmp_loot.rb`

In addition, we briefly attempted to deprecate `modules/auxiliary/scanner/discovery/udp_probe.rb` back in February, but [reversed that decision](https://github.com/rapid7/metasploit-framework/pull/9557).  We didn't remove the `include Msf::Module::Deprecated` line, so this PR cleans that up.

### CODE REVIEW

**Comment by jhart-r7** [comment]
Hmm, I thought the whole udp_probe vs udp_sweep thing was a misunderstanding, that the pivot use-case does work except for some edge case that was python related?

**Comment by asoto-r7** [comment]
@jhart-r7: I'm not sure what the final decision was, but at the moment, we've got a require statement in `udp_probe` that isn't necessary.  This PR is just to clean that up.  :-D

**Comment by asoto-r7** [comment]
@jhart-r7 : I got some context from @bcook-r7 about `udp_probe`.  There was some confusion involving the UDP functionality in Python meterpreter, which did not exist at the time, but has since been implemented.  The latest seems to be that a conversation in IRC between @bcook-r7, @hdm and @mubix reversed our decision to reverse the deprecation.  So I intend to try deprecating `udp_probe` again in a future PR.

For now, let's just clean this up.  😄

Sound good?

**Comment by busterb** [comment]
Go for it. Thanks @asoto-r7

**Comment by busterb** [comment]
We'll need to remove old documentation as well from the docs tree.

**Comment by busterb** [comment]
Thanks, and sorry about not grabbing yesterday, I was only firing on half-cylinders.

**Pull request merged**
