### PR TITLE
Enhance the meterpreter 'ls' command with unicode, sorting support

### PR DESCRIPTION
**Pull request by bcook-r7**
This needs rapid7/meterpreter#137 to be fully operational, but it adds some useful features, such as unicode display support (simply by removing the current filters):
- [x] Unicode files appear

```
meterpreter > ls

Listing: E:\metasploit-framework\mytest\test
============================================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
40777/rwxrwxrwx   102   dir   2015-03-18 16:12:09 -0500  .
40777/rwxrwxrwx   1190  dir   2015-03-18 16:12:09 -0500  ..
100666/rw-rw-rw-  15    fil   2015-03-17 08:50:27 -0500  プロトタイプ.txt
```
- [x] Various sorting options:

```
meterpreter > ls -S

Listing: E:\metasploit-framework\mytest\test
============================================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
100666/rw-rw-rw-  15    fil   2015-03-17 08:50:27 -0500  プロトタイプ.txt
40777/rwxrwxrwx   102   dir   2015-03-18 16:12:09 -0500  .
40777/rwxrwxrwx   1190  dir   2015-03-18 16:12:09 -0500  ..

meterpreter > ls -S -r

Listing: E:\metasploit-framework\mytest\test
============================================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
40777/rwxrwxrwx   1190  dir   2015-03-18 16:12:09 -0500  ..
40777/rwxrwxrwx   102   dir   2015-03-18 16:12:09 -0500  .
100666/rw-rw-rw-  15    fil   2015-03-17 08:50:27 -0500  プロトタイプ.txt

meterpreter > ls -t -r

Listing: E:\metasploit-framework\mytest\test
============================================

Mode              Size  Type  Last modified              Name
----              ----  ----  -------------              ----
40777/rwxrwxrwx   102   dir   2015-03-18 16:12:09 -0500  .
40777/rwxrwxrwx   1190  dir   2015-03-18 16:12:09 -0500  ..
100666/rw-rw-rw-  15    fil   2015-03-17 08:50:27 -0500  プロトタイプ.txt
```
- [x] Help

```
meterpreter > ls -h
Usage: ls [dir] [-x] [-S] [-t] [-r]
   -x Show short file names
   -S Sort by size
   -t Sort by time modified
   -r Reverse sort order
```
- [x] Can show short names

```
meterpreter > cd c:
meterpreter > ls -x -r

Listing: C:\
============

Mode              Size      Type  Last modified              Short Name  Name
----              ----      ----  -------------              ----------  ----
100666/rw-rw-rw-  16777216  fil   2015-03-18 14:31:03 -0500              swapfile.sys
0000/---------    0         fif   1969-12-31 18:00:00 -0600              pagefile.sys
40777/rwxrwxrwx   0         dir   2015-03-17 10:33:11 -0500  METASP~1    metasploit
40777/rwxrwxrwx   0         dir   2015-02-18 23:18:39 -0600              found.000
40777/rwxrwxrwx   0         dir   2015-02-24 13:24:39 -0600              cygwin64
100444/r--r--r--  398356    fil   2014-03-18 05:14:54 -0500              bootmgr
40777/rwxrwxrwx   0         dir   2015-02-19 09:40:34 -0600              Windows.old
40777/rwxrwxrwx   0         dir   2015-03-18 14:31:01 -0500              Windows
40555/r-xr-xr-x   0         dir   2015-02-19 10:00:34 -0600              Users
40777/rwxrwxrwx   0         dir   2015-03-18 15:01:37 -0500  SYSTEM~1    System Volume Information
100666/rw-rw-rw-  0         fil   2015-02-19 09:56:39 -0600              Recovery.txt
40777/rwxrwxrwx   0         dir   2015-01-27 15:34:37 -0600              Python34
40777/rwxrwxrwx   0         dir   2015-03-18 14:21:01 -0500  PROGRA~3    ProgramData
40555/r-xr-xr-x   0         dir   2015-03-18 14:05:34 -0500  PROGRA~2    Program Files (x86)
40555/r-xr-xr-x   0         dir   2015-03-17 10:29:10 -0500  PROGRA~1    Program Files
40777/rwxrwxrwx   0         dir   2013-08-22 10:22:35 -0500              PerfLogs
40777/rwxrwxrwx   0         dir   2013-08-22 09:45:52 -0500  DOCUME~1    Documents and Settings
40777/rwxrwxrwx   0         dir   2015-03-18 14:17:10 -0500              Config.Msi
100666/rw-rw-rw-  1         fil   2013-06-18 07:18:29 -0500              BOOTNXT
40777/rwxrwxrwx   0         dir   2015-02-19 09:31:32 -0600  $SYSRE~1    $SysReset
40777/rwxrwxrwx   0         dir   2015-02-19 10:46:41 -0600              $Recycle.Bin
```

There may still be some issues with other meterpreters if they do not send UTF-8 in all cases. Testing for them is ongoing.

### CODE REVIEW

**Comment by OJ** [comment]
Added `delayed` label as this will require new meterpreter bins to support the short name stuff.

**Comment by OJ** [comment]
Meterpreter side has been landed. We just need to create new bins, release the gem, and we'll be able to land this and #4925.

**Comment by bcook-r7** [comment]
this should also work with meterpreter_bins 0.0.16

**Comment by OJ** [comment]
Bins now available, so I'll restart testing with this.

**Comment by OJ** [comment]
This looks good on Windows/POSIX Meterp.

Python meterp on *nix seems to be fine with it and renders the unicode nicely.

Python meterp on Windows works on folders that don't contain folders/filter in unicode. But it needs a look for times when it does have unicode values:
```
meterpreter> ls C:\\temp
stdapi_fs_ls: Operation failed: Windows error: The device does not recognize the command.
```
Not sure why at this point (I haven't dived into it), perhaps the masterful @zeroSteiner can offer an insight here.

**Comment by OJ** [comment]
I had a quick look at the code, and fiddled around with encodings, locales, etc. and I can't see to make it work. I think I am going to have to leave that to other pythonistas to sort out.

The break is caused when calling `os.stat(file)` when `file` is the unicode file/directory.

**Comment by zeroSteiner** [comment]
@OJ I've reproduced the error just fine and I'm pretty sure the problem is related to [strings being passed to os.listdir](https://docs.python.org/2/howto/unicode.html#unicode-filenames). I'll take a shot at fixing this and submit a PR against this branch once I've got it. Confirmed to affect Python 2.7 and 3.4 on Windows.

**Comment by bcook-r7** [comment]
Thanks @zeroSteiner - I guess PHP on windows vs linux will have a similar issue.

**Comment by bcook-r7** [comment]
Confirmed, PHP needs some work on windows - possibly not easily solvable with PHP 5:
```
Listing: E:\metasploit-framework\mytest\test
============================================

Mode            Size  Type  Last modified              Name
----            ----  ----  -------------              ----
0000/---------  0     fif   1969-12-31 18:00:00 -0600  ??????.txt
```

**Comment by hmoore-r7** [comment]
It sounds like the Python fix straightforward, but we should create tickets to track the other issues, and not block this PR on the other meterpreter platforms.

**Comment by OJ** [comment]
Thanks @zeroSteiner for taking a look. For me the `stat()` call was the issue, but I trust you more than me!

@hmoore-r7 I couldn't see breakages on non-Windows so I'd be happy to land this baby.

**Comment by hmoore-r7** [comment]
Sounds good to land, I'll open a ticket for the python issue.

**Pull request merged**
