### PR TITLE
remove old metasm remnants

### PR DESCRIPTION
**Pull request by busterb**
Noticed while @asoto-r7 was reviewing Code Climate results, and it highlighted some metasm code as having unusual code structure. Rather than fixing it, we can delete it, since this is from upstream metasm
presumably, which we've used as a Gem for some time (thanks @egypt).

All payloads should still be regenerable, and evasion modules as well.

I'm curious what I'm overlooking here...

### CODE REVIEW

**Comment by busterb** [comment]
So far, I haven't found anything, and this passed all tests. Not sure if surprised!

**Comment by wchen-r7** [comment]
I'll take a look...

**Comment by bcoles** [comment]
Spoiler: seems this test was the only failure:

https://drive.google.com/file/d/1tpW4E3gvwUzgGFXkYgKaH1Gn2bK82ub9/view

**Comment by bwatters-r7** [comment]
Valid...... still morning here.  I should have specified; the error is one I have not seen before, but given the success elsewhere, I find it hard to believe it is related to this PR.

**Pull request merged**
