### PR TITLE
new tidy_docs checks

### PR DESCRIPTION
**Pull request by h00die**
New enforcements for `msftidy_docs.rb`

1. All options should be H3 (###) instead of bold (**).  This is a change from our previous standard.  @tperry-r7 asked for this
2. Some options aren't needed because they're universal.  Every docs doesn't need to say `rhosts`, so we'll ask to not have the following (maybe more?) `rhost|rhosts|rport|lport|lhost|srvhost|srvport|ssl|uripath|session|proxies|payload`

Assigning to @tperry-r7 who is the one who recommended these changes.

### CODE REVIEW

**Review by wvu — APPROVED** [review]

**Comment by h00die** [comment]
@ccondon-r7

**Comment by tperry-r7** [comment]
@h00die Would it be easier to leave it as bold instead? I'm pretty open to whatever is easiest.

**Comment by h00die** [comment]
That's your call as an r7 employee :)

**Review by tperry-r7 — APPROVED** [review]

**Comment by tperry-r7** [comment]
Let's do this going forward, but not make it a big project for old module docs.

**Comment by wvu-r7** [comment]
# Release Notes

This adds additional checks to the `tools/dev/msftidy_docs.rb` module documentation linter.

**Pull request merged**
