### PR TITLE
Fix #7679, LoginScanner should abort if there is no creds to try

### LINKED ISSUE #7679: LoginScanner API should abort the module if no credentials are provided
If the Metasploit::Framework::CredentialCollection object does not actually have any credentials the module can try, it should inform the user about the problem and abort the module.

### PR DESCRIPTION
**Pull request by wchen-r7**
# What this does

If there is no credentials to try in the Metasploit::Framework::CredentialCollection object, there is no point to continue the module, so the API should warn the user about this, and abort.

# Verification

- [x] Start msfconsole
- [x] Do: ```use auxiliary/scanner/smb/smb_login```
- [x] Do: ```set RHOSTS [IP]``` (no need for a SMB server to be up and running)
- [x] Do: ```run```
- [x] The module should abort, and you should see this error: ```Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank```

### CODE REVIEW

**Comment by dmohanty-r7** [comment]
@wchen-r7 this fails travis

**Comment by wchen-r7** [comment]
All green now, thanks!

**Comment by bwatters-r7** [comment]
Maybe I'm doing something wrong....
I set up a share on a Win10x64 machine and verified I could get ot 445 on it from my msf machine.
I verified behavior without creds, then added some creds:

```
msf auxiliary(smb_login) > creds add-password anotheruser anotherpassword
msf auxiliary(smb_login) > creds
Credentials
===========

host  origin  service  public       private          realm  private_type
----  ------  -------  ------       -------          -----  ------------
                       anotheruser  anotherpassword         Password

```

Then set the module to use all creds in the database:
```
msf auxiliary(smb_login) > set DB_ALL_CREDS true
msf auxiliary(smb_login) > show options

Module options (auxiliary/scanner/smb/smb_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   ABORT_ON_LOCKOUT  true             yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      true             no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   DETECT_ANY_AUTH   true             no        Enable detection of systems accepting any authentication
   PASS_FILE                          no        File containing passwords, one per line
   PRESERVE_DOMAINS  true             no        Respect a username that contains a domain name.
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST      false            no        Record guest-privileged random logins to the database
   RHOSTS            <Win10x64_IP>   yes       The target address range or CIDR identifier
   RPORT             445              yes       The SMB service port
   SMBDomain         .                no        The Windows domain to use for authentication
   SMBPass                            no        The password for the specified username
   SMBUser                            no        The username to authenticate as
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts

msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[*] Error: <Win10x64_IP>: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank (Metasploit::Framework::LoginScanner::SMB)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) > 
```

I would expect this to use the creds in the database, though I am unfamiliar with this module.

**Comment by dmohanty-r7** [comment]
@wchen-r7, based on @bwatters-r7's testing, should your if statement account for respecting the `DB_ALL_CREDS` option?

**Comment by bwatters-r7** [comment]
Is this related to https://github.com/rapid7/metasploit-framework/issues/7679?

**Comment by wchen-r7** [comment]
@bwatters-r7 oh good find... Yeah that's a bug on my end. I'll need to think about how to solve this My code relies on the CredentialCollection object, but this object doesn't seem to pay attention to what comes out of the database.

**Comment by wchen-r7** [comment]
@bwatters-r7 Could you please try again when you get a chance? Thanks.

**Comment by bwatters-r7** [comment]
That fixes the DB_ALL_CREDS issue

# Testing
## Windows 10x64 Pro DB_ALL_CREDS:
```msf auxiliary(smb_login) > show options

Module options (auxiliary/scanner/smb/smb_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   ABORT_ON_LOCKOUT  true             yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   DETECT_ANY_AUTH   true             no        Enable detection of systems accepting any authentication
   PASS_FILE                          no        File containing passwords, one per line
   PRESERVE_DOMAINS  true             no        Respect a username that contains a domain name.
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST      false            no        Record guest-privileged random logins to the database
   RHOSTS            <Win10x64_IP>   yes       The target address range or CIDR identifier
   RPORT             445              yes       The SMB service port
   SMBDomain         .                no        The Windows domain to use for authentication
   SMBPass                            no        The password for the specified username
   SMBUser                            no        The username to authenticate as
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts

msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[*] Error: <Win10x64_IP>: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank (Metasploit::Framework::LoginScanner::SMB)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) > creds add-password anotheruser anotherpassword
msf auxiliary(smb_login) > creds
Credentials
===========

host  origin  service  public       private          realm  private_type
----  ------  -------  ------       -------          -----  ------------
                       anotheruser  anotherpassword         Password

msf auxiliary(smb_login) > set DB_ALL_CREDS true
DB_ALL_CREDS => true
msf auxiliary(smb_login) > show options

Module options (auxiliary/scanner/smb/smb_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   ABORT_ON_LOCKOUT  true             yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      true             no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   DETECT_ANY_AUTH   true             no        Enable detection of systems accepting any authentication
   PASS_FILE                          no        File containing passwords, one per line
   PRESERVE_DOMAINS  true             no        Respect a username that contains a domain name.
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST      false            no        Record guest-privileged random logins to the database
   RHOSTS            <Win10x64_IP>   yes       The target address range or CIDR identifier
   RPORT             445              yes       The SMB service port
   SMBDomain         .                no        The Windows domain to use for authentication
   SMBPass                            no        The password for the specified username
   SMBUser                            no        The username to authenticate as
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts

msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[+] <Win10x64_IP>:445    - SMB - Success: 'WORKSTATION\anotheruser:anotherpassword'
[*] <Win10x64_IP>:445    - SMB - Domain is ignored for user anotheruser
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) > 
```

**Comment by bwatters-r7** [comment]
Is this the expected outcome when setting the username/password within the module options?

```
msf auxiliary(smb_login) > show options

Module options (auxiliary/scanner/smb/smb_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   ABORT_ON_LOCKOUT  true             yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   DETECT_ANY_AUTH   true             no        Enable detection of systems accepting any authentication
   PASS_FILE                          no        File containing passwords, one per line
   PRESERVE_DOMAINS  true             no        Respect a username that contains a domain name.
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST      false            no        Record guest-privileged random logins to the database
   RHOSTS            <Win10x64_IP>   yes       The target address range or CIDR identifier
   RPORT             445              yes       The SMB service port
   SMBDomain         .                no        The Windows domain to use for authentication
   SMBPass           anotherpassword  no        The password for the specified username
   SMBUser           anotheruser      no        The username to authenticate as
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts

msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[*] Error: <Win10x64_IP>: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank (Metasploit::Framework::LoginScanner::SMB)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) > 
```

**Comment by wchen-r7** [comment]
Hmm, nope it is not.

**Comment by wchen-r7** [comment]
@bwatters-r7 Could you try again? Thanks.

**Comment by bwatters-r7** [comment]
@wchen-r7 Typing as we speak

**Comment by bwatters-r7** [comment]
Looks good to me; anything left to test?

# Testing on Win10x64

## No creds
```
msf auxiliary(smb_login) > show options

Module options (auxiliary/scanner/smb/smb_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   ABORT_ON_LOCKOUT  true             yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   DETECT_ANY_AUTH   true             no        Enable detection of systems accepting any authentication
   PASS_FILE                          no        File containing passwords, one per line
   PRESERVE_DOMAINS  true             no        Respect a username that contains a domain name.
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST      false            no        Record guest-privileged random logins to the database
   RHOSTS            <Win10x64_IP>   yes       The target address range or CIDR identifier
   RPORT             445              yes       The SMB service port
   SMBDomain         .                no        The Windows domain to use for authentication
   SMBPass                            no        The password for the specified username
   SMBUser                            no        The username to authenticate as
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts

msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[*] Error: <Win10x64_IP>: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank (Metasploit::Framework::LoginScanner::SMB)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed

```

## DB Creds

```

msf auxiliary(smb_login) > creds add-password anotheruser anotherpassword
msf auxiliary(smb_login) > creds
Credentials
===========

host  origin  service  public       private          realm  private_type
----  ------  -------  ------       -------          -----  ------------
                       anotheruser  anotherpassword         Password

msf auxiliary(smb_login) > set DB_ALL_CREDS true
DB_ALL_CREDS => true
msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[+] <Win10x64_IP>:445    - SMB - Success: 'WORKSTATION\anotheruser:anotherpassword'
[*] <Win10x64_IP>:445    - SMB - Domain is ignored for user anotheruser
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) > creds -d
Credentials
===========

host            origin  service        public       private          realm  private_type
----            ------  -------        ------       -------          -----  ------------
<Win10x64_IP>          445/tcp (smb)  anotheruser  anotherpassword         Password

[*] Deleted 1 creds
msf auxiliary(smb_login) > creds
Credentials
===========

host  origin  service  public  private  realm  private_type
----  ------  -------  ------  -------  -----  ------------


```

## Creds as option

```


msf auxiliary(smb_login) > set SMBPass anotherpassword
SMBPass => anotherpassword
msf auxiliary(smb_login) > set SMBUser anotheruser
SMBUser => anotheruser
msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[+] <Win10x64_IP>:445    - SMB - Success: '.\anotheruser:anotherpassword'
[*] <Win10x64_IP>:445    - SMB - Domain is ignored for user anotheruser
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) > creds
Credentials
===========

host            origin          service        public       private          realm  private_type
----            ------          -------        ------       -------          -----  ------------
<Win10x64_IP>  <Win10x64_IP>  445/tcp (smb)  anotheruser  anotherpassword         Password

msf auxiliary(smb_login) > creds -d
Credentials
===========

host            origin          service        public       private          realm  private_type
----            ------          -------        ------       -------          -----  ------------
<Win10x64_IP>  <Win10x64_IP>  445/tcp (smb)  anotheruser  anotherpassword         Password

[*] Deleted 1 creds
msf auxiliary(smb_login) > creds
Credentials
===========

host  origin  service  public  private  realm  private_type
----  ------  -------  ------  -------  -----  ------------


```

## Wrong Creds

```


msf auxiliary(smb_login) > set SMBPass wrong
SMBPass => wrong
msf auxiliary(smb_login) > run

[*] <Win10x64_IP>:445    - SMB - Starting SMB login bruteforce
[*] <Win10x64_IP>:445    - This system does not accept authentication with any credentials, proceeding with brute force
[-] <Win10x64_IP>:445    - SMB - Failed: '.\anotheruser:wrong', Login Failed: The server responded with error: STATUS_LOGON_FAILURE (Command=115 WordCount=0)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) > 
```

**Comment by wchen-r7** [comment]
I think that's it....

very nice testing.

**Comment by bwatters-r7** [comment]
# Release notes
This fixes a bug where metasploit crashed if it was not provided with credentials to try in the smb_login scan.  Instead, this provides a warning message, and gracefully exits.

**Pull request merged**
