### PR TITLE
Add ed25519 gem to bundle for ssh_login_pubkey

### LINKED ISSUE #10709: ssh_login_pubkey does not support ssh key
## Steps to reproduce
```
msf > use auxiliary/scanner/ssh/ssh_login_pubkey
msf auxiliary(scanner/ssh/ssh_login_pubkey) > set key_path /home/micke/.ssh/cuiteur
key_path => /home/micke/.ssh/cuiteur
msf auxiliary(scanner/ssh/ssh_login_pubkey) > set rhosts 10.0.6.235
rhosts => 10.0.6.235
msf auxiliary(scanner/ssh/ssh_login_pubkey) > set rport 52961
rport => 52961
msf auxiliary(scanner/ssh/ssh_login_pubkey) > set username root
username => root
msf auxiliary(scanner/ssh/ssh_login_pubkey) > run

[*] 10.0.6.235:52961 SSH - Testing Cleartext Keys
[*] Error: 10.0.6.235: NotImplementedError OpenSSH keys only supported if ED25519 is available
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "ed25519 is not part of the bundle. Add it to your Gemfile."

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

I tried logging in with ssh after getting hold of the private key.

## Expected behavior
I expected to get a ssh session.

## Current behavior
I get an error complaining that ed25519 is missing.

## System stuff
I tried this on kali linux and then on manjaro. Same behaviour on both. Installed with the official package manager in both cases.
I also tried to install ed25519, but I don't know anything about ruby, so that didn't help.

### Metasploit version
4.17.5-dev on Manjaro
4.17.13-dev on Kali

### PR DESCRIPTION
**Pull request by wvu**
Needed for that key type. cc @busterb

Fixes #10709.

### CODE REVIEW

**Comment by busterb** [comment]
Nice!

**Review by busterb — COMMENTED** [review]
Since this isn't used directly by Metasploit, rather it's used by net-ssh, should this just go into Gemfile instead? Or does it even matter?

**Comment by busterb** [comment]
I played around with it, 6 in one, half dozen in the other.

**Comment by wvu-r7** [comment]
Thanks! Yeah, let's revisit our gems later, especially when we chat about consolidating repos.

**Pull request merged**
