### PR TITLE
Add Tool MSU extractor

### PR DESCRIPTION
**Pull request by wchen-r7**
If you do patch testing/analysis/diffing, you might find this tool handy. This tool will automatically extract all the *.msu files, and then you can search for the patched files you're looking for quickly.

The workflow would be something like this:
1. You download the patches from:
   http://mybulletins.technet.microsoft.com/BulletinPages/Dashboard
2. You put all the *.msu files in one directory. Like this:

screen shot 2015-09-09 at 9 39 51 pm
1. Run this tool: extract_msu.bat [absolute directory path]. Like this:

screen shot 2015-09-09 at 10 00 24 pm
1. The tool should extract the updates. After it's done, you can
   use Windows to search for the file(s) you're looking for.

screen shot 2015-09-09 at 10 05 26 pm

### CODE REVIEW

**Comment by wchen-r7** [comment]
@jvazquez-r7 Can you give this a try when you get a chance?

**Comment by wchen-r7** [comment]
Not so ready, let me close first.

**Comment by wchen-r7** [comment]
PR reopened, no 7zip this time.

**Comment by jvazquez-r7** [comment]
I suck on ".bat" but looks safe to me to land this :) And is useful to unzip a bunch of patches.

I've just one recommendation please.

If I put my patches on the "test" folder and I type the trailing "\" it works okey:

```
C:\Users\Juan Vazquez\Downloads>test.bat test\
Microsoft (R) File Expansion Utility  Version 6.1.7600.16385
Copyright (c) Microsoft Corporation. All rights reserved.

Adding test\Windows8-RT-KB3021674-x86\WSUSSCAN.cab to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\Windows8-RT-KB3021674-x86.cab to Extractio
n Queue
Adding test\Windows8-RT-KB3021674-x86\Windows8-RT-KB3021674-x86-pkgProperties.tx
t to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\Windows8-RT-KB3021674-x86.xml to Extractio
n Queue

Expanding Files ....

Expanding Files Complete ...
4 files total.
Microsoft (R) File Expansion Utility  Version 6.1.7600.16385
Copyright (c) Microsoft Corporation. All rights reserved.

Adding test\Windows8-RT-KB3021674-x86\extracted\x86_microsoft-windows-profsvc_31
bf3856ad364e35_6.2.9200.21336_none_f91df79b1d0733a7.manifest to Extraction Queue

Adding test\Windows8-RT-KB3021674-x86\extracted\x86_microsoft-windows-profsvc_31
bf3856ad364e35_6.2.9200.17219_none_f8acfb8603d6a800.manifest to Extraction Queue

Adding test\Windows8-RT-KB3021674-x86\extracted\x86_ea215cd8705d63a74ebf5175132c
b7df_31bf3856ad364e35_6.2.9200.17219_none_0140afe5a048aadd.manifest to Extractio
n Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\x86_8c75678f20e04bfbddd1680a9724
5612_31bf3856ad364e35_6.2.9200.21336_none_2c1378267e10fec0.manifest to Extractio
n Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\update.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\update.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\update-bf.mum to Extraction Queu
e
Adding test\Windows8-RT-KB3021674-x86\extracted\update-bf.cat to Extraction Queu
e
Adding test\Windows8-RT-KB3021674-x86\extracted\x86_microsoft-windows-profsvc_31
bf3856ad364e35_6.2.9200.21336_none_f91df79b1d0733a7\profsvc.ptxml to Extraction
Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_1_for_kb3021674~31bf3856
ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_2_for_kb3021674~31bf3856
ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_2_for_kb3021674~31bf3856
ad364e35~x86~~6.2.1.2.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_1_for_kb3021674~31bf3856
ad364e35~x86~~6.2.1.2.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\x86_microsoft-windows-profsvc_31
bf3856ad364e35_6.2.9200.17219_none_f8acfb8603d6a800\profsvc.ptxml to Extraction
Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_1_for_kb3021674_bf~31bf3
856ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_2_for_kb3021674_bf~31bf3
856ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_1_for_kb3021674_bf~31bf3
856ad364e35~x86~~6.2.1.2.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\x86_microsoft-windows-profsvc_31
bf3856ad364e35_6.2.9200.21336_none_f91df79b1d0733a7\profsvc.dll to Extraction Qu
eue
Adding test\Windows8-RT-KB3021674-x86\extracted\x86_microsoft-windows-profsvc_31
bf3856ad364e35_6.2.9200.17219_none_f8acfb8603d6a800\profsvc.dll to Extraction Qu
eue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_for_kb3021674_rtm~31bf38
56ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_2_for_kb3021674_bf~31bf3
856ad364e35~x86~~6.2.1.2.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_for_kb3021674_rtm~31bf38
56ad364e35~x86~~6.2.1.2.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_for_kb3021674_rtm_bf~31b
f3856ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_for_kb3021674_rtm_bf~31b
f3856ad364e35~x86~~6.2.1.2.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_3_for_kb3021674~31bf3856
ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_3_for_kb3021674~31bf3856
ad364e35~x86~~6.2.1.2.cat to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_3_for_kb3021674_bf~31bf3
856ad364e35~x86~~6.2.1.2.mum to Extraction Queue
Adding test\Windows8-RT-KB3021674-x86\extracted\package_3_for_kb3021674_bf~31bf3
856ad364e35~x86~~6.2.1.2.cat to Extraction Queue

Expanding Files ....

Expanding Files Complete ...
28 files total.
Done
Now go to test\,
and then use the search feature from Windows to
find the files you're interested in.

```

But if I omit the trailing "\" in the command line, when providing the dir, it fails:

```
C:\Users\Juan Vazquez\Downloads>test.bat test
Microsoft (R) File Expansion Utility  Version 6.1.7600.16385
Copyright (c) Microsoft Corporation. All rights reserved.

Can't open input file: testwindows8-rt-kb3021674-x86.msu.

Microsoft (R) File Expansion Utility  Version 6.1.7600.16385
Copyright (c) Microsoft Corporation. All rights reserved.

Can't open input file: testwindows8-rt-kb3021674-x86\windows8-rt-kb3021674-x86.c
ab.

Done
Now go to test,
and then use the search feature from Windows to
find the files you're interested in.

```

I recommend to handle the trailing "\" on the directory argument to avoid the later error!

**Comment by wchen-r7** [comment]
> I recommend to handle the trailing "\" on the directory argument to avoid the later error!

Yeah I agree. I suck at bat so I'm actually not sure how to normalize this....

**Comment by wchen-r7** [comment]
Ok @jvazquez-r7, I think I got it. Can you please try again?

**Comment by jvazquez-r7** [comment]
sure, trying again!

**Pull request merged**
