### PR TITLE
Kiwi - remove duplicate entries and allow output to be written to file.

### PR DESCRIPTION
**Pull request by OJ**
This PR does a few tidies of code, as well as adds the ability to write all the kiwi output to disk as well as to the console. We can't yet add this stuff to the credential DB because it's tied to machine, where the creds that come out of kiwi are often tied to domains.

This also removes duplicate creds from the output list, and gets rid of the auth id stuff from the output too (not sure why it was useful before).
## Sample output

```
meterpreter > creds_all -h
Usage: creds_all [options]

Dump all credentails.

OPTIONS:

    -o <opt>  Write the output to the specified file.
    -h        Help menu.

meterpreter > creds_all -o /tmp/
[+] Running as SYSTEM
[*] Retrieving all credentials
all credentials
===============

Domain  User           Password                                                                                                                  LM Hash  NTLM Hash
------  ----           --------                                                                                                                  -------  ---------
PWNAGE  Administrator  <redacted>
PWNAGE  OJ Reeves      <redacted>
PWNAGE  WIN7-X86$      <redcated>

[-] Unable to write to /tmp/
meterpreter > creds_all -o /tmp/derp.txt
[+] Running as SYSTEM
[*] Retrieving all credentials
all credentials
===============

Domain  User           Password                                                                                                                  LM Hash  NTLM Hash
------  ----           --------                                                                                                                  -------  ---------
PWNAGE  Administrator  <redacted>
PWNAGE  OJ Reeves      <redacted>
PWNAGE  WIN7-X86$      <redcated>

[+] Output written to /tmp/derp.txt
```
## Verification
- [x] Get a SYSTEM shell on a box
- [x] run `use kiwi`
- [x] Make sure the `creds_*` commands still work.
- [x] Make sure the `creds_*` commands have help displayed when `-h` is specified.
- [x] Validate that the `-o` parameter usage works as expected.

Ping @wvu-r7 who was keen to see this happen (same goes for @viss I think).

### CODE REVIEW

**Comment by wvu-r7** [comment]
Review done. Will test tomorrow. Thanks!

**Comment by OJ** [comment]
Thanks for the review @wvu-r7 :)

**Comment by wvu-r7** [comment]
No problem, mate. Legendary work as always. :)

**Comment by Meatballs1** [comment]
All of the creds that come out of a machine via Kiwi should generally be valid login credentials on that machine. So are valid to place in the DB against that machine?

**Comment by OJ** [comment]
I spoke to HD about this before doing this work. They might work against
the machine, but they aren't specific to that machine. It doesn't make
sense yet to use this storage for creds pulled from kiwi.

Will look into a better long term solution, but this was still better than
dumping to the console only.

**Comment by OJ** [comment]
Thanks for landing Will!

**Comment by Meatballs1** [comment]
A number of the credentials may be local only, so should definitely be put against the machine.

The existing SSO post module doesn't care but is super broke methinks. Better to have them stored and searchable in the database, than wait 12 months for a refactor of the Credential model to better model creds against a central authentication repository, as well as MDM to tag each host against a central auth scheme. 

They should have the realm so if required people can access the db themselves and filter by the realm/domain. Most jobbing testers are reasonably smart and can work out that things with a big DOMAIN in the realm will be valid elsewhere too! 

Alternatively lookup %LOGONSERVER% and stick them against that? :) 

N.b. the bigger issue you have is not calling MSF methods from Rex to avoid adding that dependency ...

**Comment by OJ** [comment]
Yeah true that. I'm not sure how we'll get hold of the MSF-related stuff in a clean way. Will chat to the powers that be about that.

I do agree that _some_ creds will be local, but I don't think it's a simple thing to solve in the short term. This little addition was really to make ite easier to wade through lots of creds without having to deal with the console (esp if you use MSF In something like screen or tmux, which is a PITA).

I think we should definitely have a broader discussion about getting creds out of Mimikatz and sticking them in the appropriate part of the DB though. Perhaps I should open an issue for discussion..?

**Comment by Meatballs1** [comment]
Yep sounds good to me :)

**Pull request merged**
