### PR TITLE
enum_subdomains

### PR DESCRIPTION
**Pull request by interhack86**
New module to enumerate subdomains using a specific list.
## Verification
- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/discovery/enum_subdomains`
- [ ] `set DOMAIN [target]`
- [ ] `run`
- [ ] **Verify** [+] [subdomain], [resolution], [ip]
## Output

> msf auxiliary(enum_subdomains) > info
> 
> ```
>    Name: Enumerate subdomains
>  Module: auxiliary/scanner/discovery/enum_subdomains
> License: Metasploit Framework License (BSD)
>    Rank: Normal
> ```
> 
> Provided by:
>   Kevin Gonzalvo
> 
> Basic options:
>   Name      Current Setting                                                           Required  Description
> ---
> 
>   DOMAIN    xxxxxxx.com                                                           yes       The target domain
>   WORDLIST  /opt/metasploit-framework/embedded/framework/data/wordlists/namelist.txt  yes       Wordlist of subdomains
> 
> Description:
>   Enumerate subdomains of domain using a specific list.
> 
> msf auxiliary(enum_subdomains) > run
> 
> [*] Checking subdomains...
> [+] autodiscover, autodiscover.xxxxxx.com, xxx.xxx.245.79
> [+] ftp, xxxxx.com, xxx.xxx.245.79
> ^C

### CODE REVIEW

**Comment by wvu-r7** [comment]
Hi. ```auxiliary/gather/enum_dns``` and ```auxiliary/gather/dns_bruteforce``` already do this. Can you please confirm?

**Comment by interhack86** [comment]
Is a simple module, only needs the domain and a wordlist in the others need  create sessions and is possible using for other things

**Comment by wvu-r7** [comment]
Only ```post/multi/gather/dns_bruteforce``` requires a session.

**Comment by interhack86** [comment]
yes and in auxiliary/gather/enum_dns you can get a lot of information about the domain but it is not easy to get a list of subdomains using the wordlist, i thing that is util for the other users.

**Comment by wvu-r7** [comment]
Did you see the ```ENUM_BRT``` and ```WORDLIST``` options? Also, if you want easy, did you look at ```auxiliary/gather/dns_bruteforce```?

**Comment by wvu-r7** [comment]
I think I see what you mean here. Even though ```enum_dns``` *does* brute subdomains, if you want the module to do *only* that, you need to untick the other checkboxes. That's a bit of a hassle, but that's why ```dns_bruteforce``` exists.

**Comment by vysec** [comment]
CVE  reference is wrong. Lino doesn't work

**Comment by interhack86** [comment]
Remove incorrect CVE, thank you vysec.
Only check subdomains and the dns_bruteforce is deprecated.

**Comment by wvu-r7** [comment]
You're right. It's deprecated in favor of ```enum_dns``` because subdomain bruting was rolled into that module (it had that functionality already). So you're adding something that was deprecated and should have been removed in June. I'm just trying to understand your thought process here.

**Comment by interhack86** [comment]
Following that thought i think you're right. I did not like the new module so I wanted to add a simpler. But actually you're right not is necessary add this module when there is one more complete.
So I close the pull. 
Thanks for the time.

**Comment by wvu-r7** [comment]
Sorry it didn't work out. The irony here is that ```dns_bruteforce``` was created (#1466) to split off subdomain bruting from ```enum_dns```. So we've come full circle. The new ethos (#6187) is that ```enum_dns``` should contain all the functionality while retaining its a la carte behavior.

**Pull request closed without merging**
