### PR TITLE
Fix for issue #16580

### PR DESCRIPTION
**Pull request by RyeSecurity**
Rex-core downgrade to 0.1.20

Fix for issue #16580

### CODE REVIEW

**Comment by adfoster-r7** [comment]
@NathanZaldivar Thanks for creating a PR; Would you mind providing your replication steps which cause the error? That'll help us investigate further to see if there's an alternative fix that could be implemented

**Comment by NathanZaldivar** [comment]
> @NathanZaldivar Thanks for creating a PR; Would you mind providing your replication steps which cause the error? That'll help us investigate further to see if there's an alternative fix that could be implemented

Please look at issue #16580, user jtylerorr not only provided fixes which I implemented in the PR but also provided complete documentation on the issue and steps to reproduce under section **Steps to reproduce.**

**Comment by adfoster-r7** [comment]
I wished to confirm if you were triggering the issue via the same or alternative means to the original issue raiser; As different user interactions can lead to similar but different bugs that would need to be resolved

**Comment by rasheed-rd** [comment]
@adfoster-r7 For me the problem seems to be easily reproduced using `auxiliary/scanner/snmp/snmp_login`. I wrote a python script which uses pymetasploit3 to reproduce. Below are the steps I took: 
1- I pulled the latest metasploit docker image (Framework Version: 6.0.55-dev) and ran it starting msfrpcd.
2- Ran the following script several times:
```
from pymetasploit3.msfrpc import MsfRpcClient
from time import sleep

client = MsfRpcClient('kali')
r = client.call("console.create")
id = r['id']
r = client.call("console.read", [id])
cmd = 'use auxiliary/scanner/snmp/snmp_login\nset VERBOSE True\nset THREADS 1\nset ShowProgress True\nset ShowProgressPercent 10\nset PASS_FILE /usr/src/metasploit-framework/data/wordlists/snmp_default_pass.txt\nset BRUTEFORCE_SPEED 5\nset BLANK_PASSWORDS False\nset USER_AS_PASS False\nset DB_ALL_CREDS False\nset DB_ALL_USERS False\nset DB_ALL_PASS False\nset DB_SKIP_EXISTING none\nset STOP_ON_SUCCESS False\nset REMOVE_USER_FILE False\nset REMOVE_PASS_FILE False\nset REMOVE_USERPASS_FILE False\nset TRANSITION_DELAY 0\nset MaxGuessesPerService 0\nset MaxMinutesPerService 0\nset MaxGuessesPerUser 0\nset RPORT 161\nset VERSION 1\nset RHOSTS XXX.XXX.XXX.XXX\nset DisablePayloadHandler True\nrun -z\n'
client.call("console.write", [id, cmd])
data = ''
r = client.call("console.read", [id])
print(r)
data = r['data']
while r['busy']:
    sleep(.5)
    r = client.call("console.read", [id])
    print(r)
    data += r['data']

print(data)
client.call("console.destroy", [id])
```
The successful runs of the module are random, it will sometimes work right away, other times it wont, and some times it will return partial output.
Success rate using the script seems to be around 80% of the time. 
 
Success output example:
```{'data': 'VERBOSE => true\nTHREADS => 1\nShowProgress => true\nShowProgressPercent => 10\nPASS_FILE => /usr/src/metasploit-framework/data/wordlists/snmp_default_pass.txt\nBRUTEFORCE_SPEED => 5\nBLANK_PASSWORDS => false\nUSER_AS_PASS => false\nDB_ALL_CREDS => false\nDB_ALL_USERS => false\nDB_ALL_PASS => false\nDB_SKIP_EXISTING => none\nSTOP_ON_SUCCESS => false\nREMOVE_USER_FILE => false\nREMOVE_PASS_FILE => false\nREMOVE_USERPASS_FILE => false\nTRANSITION_DELAY => 0\nMaxGuessesPerService => 0\nMaxMinutesPerService => 0\nMaxGuessesPerUser => 0\nRPORT => 161\nVERSION => 1\nRHOSTS => XXX.XXX.XXX.XXX\nDisablePayloadHandler => True\n', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': True}
{'data': '', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': True}
{'data': '', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': True}
{'data': '', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': True}
{'data': '', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': True}
{'data': '', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': True}
{'data': '', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': True}
{'data': '[!] No active DB -- Credential data will not be saved!\n[+] XXX.XXX.XXX.XXX:161 - Login Successful: Public (Access level: read-only); Proof (sysDescr.0): Hardware: Intel64 Family 6 Model 158 Stepping 13 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 14393 Multiprocessor Free)\n[*] Scanned 1 of 1 hosts (100% complete)\n[*] Auxiliary module execution completed\n', 'prompt': 'msf6 auxiliary(scanner/snmp/snmp_login) > ', 'busy': False}
VERBOSE => true
THREADS => 1
ShowProgress => true
ShowProgressPercent => 10
PASS_FILE => /usr/src/metasploit-framework/data/wordlists/snmp_default_pass.txt
BRUTEFORCE_SPEED => 5
BLANK_PASSWORDS => false
USER_AS_PASS => false
DB_ALL_CREDS => false
DB_ALL_USERS => false
DB_ALL_PASS => false
DB_SKIP_EXISTING => none
STOP_ON_SUCCESS => false
REMOVE_USER_FILE => false
REMOVE_PASS_FILE => false
REMOVE_USERPASS_FILE => false
TRANSITION_DELAY => 0
MaxGuessesPerService => 0
MaxMinutesPerService => 0
MaxGuessesPerUser => 0
RPORT => 161
VERSION => 1
RHOSTS => XXX.XXX.XXX.XXX
DisablePayloadHandler => True
[!] No active DB -- Credential data will not be saved!
[+]XXX.XXX.XXX.XXX:161 - Login Successful: Public (Access level: read-only); Proof (sysDescr.0): Hardware: Intel64 Family 6 Model 158 Stepping 13 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 14393 Multiprocessor Free)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed```

Failure output example:
{'data': '', 'prompt': '', 'busy': False}

**Comment by adfoster-r7** [comment]
Unfortunately we can't revert the Gem to an older version, as there's other changes to rex-core that are still needed from after this bug was introduced

Here's an alternative solution instead https://github.com/rapid7/metasploit-framework/pull/16822 - let me know if that works for you :+1:

**Comment by smcintyre-r7** [comment]
I'm going to close this out since #16822 has been landed. If you're still experiencing this issue, just let us know. Thanks a lot!

**Pull request closed without merging**
