### PR TITLE
Update mailmap

### PR DESCRIPTION
**Pull request by egypt**
Add Jeffrey Martin, Adam Compton, and Jin Qian.

Drop names for most so only email addresses matter.

## Verification

- [x] with mailmap: `git log --author rapid7.com --format=%aE --since 2016-01-01 | sort -u`
  - [x] **VERIFY** Displays github usernames for all the `-r7` folks.
  - [x] **VERIFY** contains only *one* name for each user, e.g. `jinq102030@github` and not both `Jin_Qian@rapid7.com` and `jqian@rapid7.com`

### CODE REVIEW

**Comment by h00die** [comment]
what exactly would one need to do to get in such a file?

**Comment by egypt** [comment]
@h00die One needs remind me.  =)  	d0c7780

**Comment by wvu-r7** [comment]
```YOUR_USERNAME_FOR_EMAIL``` is my favorite.

**Comment by wvu-r7** [comment]
@egypt: It looks like you have unrelated changes in this PR?

```
 .mailmap                                                             | 135 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------
 lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/net.rb |  47 +++++++++++++++++++++++++++++++----------------
 tools/modules/module_targets.rb                                      |   9 +++++----
```

**Comment by bcook-r7** [comment]
I went ahead and backed out the unrelated changes, and added a couple more entries. Thanks!

09b5a7f162 - refine rageltman, add rwhitcroft (4 minutes ago) <Brent Cook>
f9d91d210d - add sempervictus (11 minutes ago) <Brent Cook>
9ef3112299 - move old R7 folks (12 minutes ago) <Brent Cook>
4abc5a5a2f - revert unrelated changes (26 minutes ago) <Brent Cook>

**Pull request merged**
