### PR TITLE
Fix recovery_files.rb Description grammar errors

### PR DESCRIPTION
**Pull request by karllll**

### CODE REVIEW

**Comment by wvu-r7** [comment]
@karllll: When did you change your avatar??

**Comment by karllll** [comment]
@wvu-r7 A couple days ago after seeing your knowyourmeme post - felt like a good fit. I'm a fan of the show and comic.

**Comment by wvu-r7** [comment]
Gifting this to @kgray-r7. Thanks for the contribution, @karllll. :)

**Comment by wvu-r7** [comment]
[Carl](https://www.youtube.com/watch?v=fqAe6A7s5iY)

**Comment by kgray-r7** [comment]
Merged. One of my favorite pull requests so far.

**Pull request merged**
