### PR TITLE
Fix ability to run msfconsole within msfconsole

### LINKED ISSUE #7330: Make msfconsole a command inside of msfconsole
Many new users of metasploit have made the mistake of starting msfconsole inside of msfconsole and it would be nice if there was a warning instead of allowing it to get passed to the shell.

### PR DESCRIPTION
**Pull request by bpatterson-r7**
Resolves #7330
## Verification
- [x] `export PATH+=:.` will help you repro. Do this TEMPORARILY. Even though it's at the end, you really don't want `.` in `$PATH`.
- [x] Start `msfconsole`
- [x] run `msfconsole`
- [x] run `./msfconsole`
- [x] run `msfconsole -L`
- [x] An error message should be thrown for each of the above commands and it should prevent them.

### CODE REVIEW

**Comment by h00die** [comment]
its funny when you are getting ready to push your `inception` branch to create a PR, and you want to comment which git ticket is going to be closed... except it was closed 3hrs ago... damnit.

**Comment by wvu-r7** [comment]
Doh!

**Comment by wvu-r7** [comment]
# Release Notes

This adds a warning to ```msfconsole``` telling the user they can't run ```msfconsole``` within ```msfconsole```.

**Comment by pbarry-r7** [comment]
In other words, closing the "Yo, dawg, I heard you like msfconsole..." loophole...  😜

**Pull request merged**
