### PR TITLE
Module Documentation

### PR DESCRIPTION
**Pull request by kenlacroix**
Create Documentation.

### CODE REVIEW

**Comment by h00die** [comment]
@kenlacroix Been a bit, is this one good to go?

**Comment by kenlacroix** [comment]
Yeah, go ahead and merge. Will be doing more docs in the future, just not at this moment, thanks.

**Comment by kenlacroix** [comment]
Yeah, go ahead and merge. Will be doing more docs in the future, just not at this moment, thanks.

**Comment by h00die** [comment]
https://github.com/rapid7/metasploit-framework/commit/9e1bc8afaeaa3d54ce68832f2b15fbe701d6ca1d

**Comment by h00die** [comment]
# Release Notes
This PR adds module docs to `enum_patches` and `phish_windows_credentials`

**Pull request merged**
