### PR TITLE
rollback yanked gem

### PR DESCRIPTION
**Pull request by jmartin-tech**
see: https://github.com/aws/aws-sdk-ruby/pull/2329#issuecomment-642783421

## Verification

List the steps needed to make sure this thing works

- [x] **Verify** Travis bundles and passes

### CODE REVIEW

**Review by busterb — APPROVED** [review]

**Comment by pbarry-r7** [comment]
I'm also getting the following error with current Framework master:

`Could not find aws-sdk-ec2-1.166.0 in any of the sources`

Looks like it was [yanked, too...](https://github.com/aws/aws-sdk-ruby/pull/2329/commits/0a8d654e50dbb36f1f5d2c3b20b55f5f55e1d49d#diff-ae0e9ae703b34e74e282f956dc2d6c0e)?

**Comment by jmartin-r7** [comment]
Will give this another hour and update to pickup any more yanked items.

**Comment by gwillcox-r7** [comment]
Assigning myself as @jmartin-r7 asked me to pick this up and get it landed on internal Slack. Will be landed shortly once Sanity Test Execution tests pass.

**Comment by gwillcox-r7** [comment]
Ok good to go landing this now :)

**Pull request merged**
