### PR TITLE
A dirty patch for a number of Net::DNS/enum_dns issues

### PR DESCRIPTION
**Pull request by hdm**
The Net::DNS library suffers from a number of problems:
- Use of Logger writes directly to stdout
- Hardcoded reference to "/etc/resolv.conf"
- Internal socket API ignores Rex sockets & pivots
- Numerous bugs that lead to stack traces
- Default UDP timeout of 0 leads to hangs

The enum_dns module demonstrates many of these bugs and has many of its own:
- Poor error handling in many cases (with default options, no less)
- Broken note reporting (repeatedly overwriting the same note)
- Missing data recording for some options (SRV records)

This PR fixes just enough of these problems to make enum_dns function. The Net::DNS upstream appears to be dead as of two years ago. This bug fixes in this PR also restore functionality to dns_bruteforce, which would otherwise stack trace on certain records. 

Do we want to keep the enum_dns module? Should we land this for now just to get things working while we figure out next steps for DNS modules in Metasploit?

### CODE REVIEW

**Comment by void-in** [comment]
@hmoore-r7 The fact that such horrible bugs were unnoticed for so long indicates that this module is not used by and large. dns_brute is not good as well but some multi-threaded python scripts can easily get the task done relatively fast. Landing this won't harm anyone but in the long run I think the energy will be better served else where rather than supporting the module that is pretty much ignored by the users until now.

**Comment by hmoore-r7** [comment]
@void-in Thanks! I agree the module is probably unused today. We should figure out whether these changes as good enough to keep the module in the tree, or whether we should simply delete it. The other DNS modules and the Net::DNS library still need work. In a recent assessment, I found the dns_bruteforce module to actually be faster some of the standalone tools (once the stack trace was fixed in Net::DNS for unknown types).

Either way we need to improve (or find an alternative to) Net::DNS. The big question for this PR is do we land it as-is, or remove the enum_dns module entirely, and just land the other fixes.

**Comment by sempervictus** [comment]
@hmoore-r7: Thanks for hitting the lib/net stack. I've pushed up my changes allowing for the use of Rex::Socket in the resolver in #5502. This is rather old work - i've had DNS in metasploit running like this for years. Works with pivots and proxies for TCP resolution, great with the multithreaded changes to DNS modules as well (IIRC those are either in closed or merged PRs).

**Comment by void-in** [comment]
@hmoore-r7 The library changes should be landed for sure. As far the enum_dns module, since you have already worked on it in this PR, there is no harm in landed this PR as it is. Once it is landed, we can work on the refactor. For example, I don't think tlds should be part of the module code. These should be part of a data file which can be updated easily by the user.

**Comment by jvazquez-r7** [comment]
I've tested enum_dns, dns_info, dns_reverse_lookup, dns_srv_enum successfully. I'm not pasting results from internal names here. Landing!

**Pull request merged**
