### PR TITLE
add gmail_checker

### PR DESCRIPTION
**Pull request by mateeuslinno**
Enumerating users and emails of Gmail

## Verification
- [ ] `use auxiliary/gather/gmail_checker`
- [ ] `set set chek_gmail <email> `
Exemple: https://i.imgur.com/ypq76wD.png

### CODE REVIEW

**Comment by mateeuslinno** [comment]
I need help. I used msftidy for research bugs in my code its meet the bug: `Do not read Set-Cookie header directly, use res.get_cookies instead: if resp['Set-Cookie']`but if i use `res.get_cookies or resp.get_cookies`my script not run. who can help me?

**Comment by mateeuslinno** [comment]
@wchen-r7 Do you can help me ?

**Comment by bcoles** [comment]
```ruby
##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##

require 'net/http'
require 'uri'

class MetasploitModule < Msf::Auxiliary

  include Msf::Auxiliary::Report

  def initialize(info = {})
    super(update_info(info,
      'Name'        => 'GMail User Enumeration',
      'Description' => %q{
        Enumerate valid GMail email addresses.
      },
      'Author'      => 'l2*',
      'References'  => [[ 'URL', 'https://gmail.com/' ]],
      'License'     => MSF_LICENSE))
    register_options [ OptString.new('EMAIL', [ true, 'Email adddress to validate', 'example@gmail.com' ]) ]
    deregister_options 'RHOST', 'RPORT', 'VHOST'
  end

  def email_exists?(email)
    vprint_status "Checking if #{email} is valid..."
    uri = URI.parse "https://mail.google.com/mail/gxlu?email=#{email}"
    http = Net::HTTP.new uri.host, uri.port
    http.use_ssl = true
    request = Net::HTTP::Get.new uri.request_uri
    res = http.request request
    return false if res.nil?

    cookies = res.get_fields 'set-cookie'
    return false if cookies.nil?

    cookies.each { |c| return true if c.include?('COMPASS=') }
  end

  def run
    print_status 'Enumerating email addresses...'
    email = datastore['EMAIL']
    print_status "#{email}: #{email_exists? email}"
  end
end
```

**Comment by mateeuslinno** [comment]
Hi @bcoles i changed the code. tks !

**Comment by bcoles** [comment]
Please take my name off it.

I'm not sure if the PR will be merged. This is likely against Google's terms of service.

There's a lot of functionality that could be added, such as support for proxies, multi-threading, and using a word list as input.

The [enum_wayback](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/http/enum_wayback.rb) module shows an example of implementing proxy support.

The [enum_dns](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/gather/enum_dns.rb) module shows examples of threading and using a word list.

**Comment by mateeuslinno** [comment]
Okay, I'll remove. From what I read this bug was reported to google, do you think it's better then I add the proxy query in the script?
Sorry for the questions.

**Comment by wvu-r7** [comment]
#9683, #9688

I agree with @bcoles. I don't think Metasploit is the appropriate place for this functionality.

**Pull request closed without merging**
