### PR TITLE
Fix close session

### PR DESCRIPTION
**Pull request by umerov1999**
Fix close session if remote file is permission denied

### CODE REVIEW

**Comment by wvu-r7** [comment]
You're going to have to elaborate on why removing error handling is the correct fix.

**Comment by sempervictus** [comment]
@umerov1999: if you could shed some light on the context in which this failure occurs, we should be able to work out a proper exception handling case instead of removing the rescue clause. Could you pull one of the actual request errors you're getting by reinstating that rescue and marshaling out the exception to a file/stdout and adding it to this discussion?

**Comment by busterb** [comment]
I reproduced the problem here. For instance, if I try to edit /etc/shadow, an exception gets thrown here that causes the whole session to get shutdown. Poking at it now to see if there is a less mysterious fix for the issue. Thanks!

**Comment by busterb** [comment]
This is the correct fix, since we don't want to send a ConnectionRefused exception if we can't open a _file_

**Comment by busterb** [comment]
now it lives to see another day:
```
meterpreter > edit /etc/shadow
[-] core_channel_open: Operation failed: 1
meterpreter > edit /etc/shadow
[-] core_channel_open: Operation failed: 1
```

**Comment by busterb** [comment]
Reworked the exception handling a bit so it doesn't look like we lost something: 807a27e73d

**Comment by busterb** [comment]
## Release Notes

This fixes a bug where a Meterpreter session would close when opening a file that has insufficient read permissions.

**Pull request merged**
