### PR TITLE
Re-write pattern_create/pattern_offset layout and documented options

### PR DESCRIPTION
**Pull request by finackieee**
Updated pattern_create and pattern_offset to be more consistent with other tools and modules in Metasploit.  Provided a usage example for undocumented custom set feature that allows removal of bad characters.  Pattern_offset is all you need, but without a way to deprecate older tools and leave options open, pattern_create and pattern_offset are updated.

**pattern_create**
Usage: ./pattern_create.rb [options]
Example: ./pattern_create.rb -l 50 -s ABC,def,123
Ad1Ad2Ad3Ae1Ae2Ae3Af1Af2Af3Bd1Bd2Bd3Be1Be2Be3Bf1Bf

Options:
    -l, --length <length>            The length of the pattern
    -s, --sets <ABC,def,123>         Custom Pattern Sets
    -h, --help                       Show this message

./pattern_create.rb -l 50 -s CAT,314,dog
C3dC3oC3gC1dC1oC1gC4dC4oC4gA3dA3oA3gA1dA1oA1gA4dA4

**pattern_offset**
Pattern default length is 1024 if not specified by -l.

Usage: ./pattern_offset.rb [options]
Example: ./pattern_offset.rb -q Aa3A|0x39634138|0xFFFF4138
[*] Exact match at offset 9

Options:
    -q, --query Aa0A                 Query to Locate
    -l, --length <length>            The length of the pattern
    -s, --sets <ABC,def,123>         Custom Pattern Sets
    -h, --help                       Show this message

./pattern_offset.rb -q 0x39634139
[*] No exact matches, looking for likely candidates...
[+] Possible match at offset 86 (adjusted [ little-endian: 1 | big-endian: 18996736 ] ) byte offset 0
[+] Possible match at offset 59 (adjusted [ little-endian: 150994944 | big-endian: 2219529 ] ) byte offset 3

./pattern_offset.rb -l 256 -s ABC,def,123 -q Aa3A
[*] No exact matches, looking for likely candidates...
[+] Possible match at offset 6 (adjusted [ little-endian: -768 | big-endian: -3199488 ] ) byte offset 1
[+] Possible match at offset 15 (adjusted [ little-endian: -1024 | big-endian: -3265024 ] ) byte offset 1

### CODE REVIEW

**Comment by wvu-r7** [comment]
What about ```pattern_offset```?

**Comment by nopnopnoppopopret** [comment]
@wvu-r7  I plan to combine both create and offset into one tool, but held off on anything because I wasn't sure if they would be merged.

**Comment by wvu-r7** [comment]
We don't have any good way to deprecate tools. I'm sure this is trip some people up once it's merged.

**Comment by wvu-r7** [comment]
I do like the changes, though.

**Comment by nopnopnoppopopret** [comment]
@wvu-r7 What do you suggest? Finish up pattern_offset to match? Or will this likely not be merged?

**Comment by wvu-r7** [comment]
I'd update ```pattern_offset```, and then we can discuss merging the two. I feel like the two should be separate, to be honest.

**Comment by wvu-r7** [comment]
I want to like this, but I feel like tools should be uncomplicated. I appreciate that you've added saner option parsing, but tools have always been kinda one-off hacks.

**Comment by wvu-r7** [comment]
I don't think I phrased that very well. Maybe @jlee-r7 can explain it better.

**Comment by busterb** [comment]
Hi @nop-sledding-with-my-snowshoes , if you want to update pattern_offset.rb to match, this should be mergeable. Probably better now while the Metasploit book v2 is still under production, than after printing!

**Comment by nop-sledding-with-my-snowshoes** [comment]
@busterb Awesome!  Will do!

**Comment by nop-sledding-with-my-snowshoes** [comment]
@busterb should be usable now.  It retains all previous functionality and plan to update more down the road.

**Comment by bcook-r7** [comment]
I did some cleanups as well: 7b83b06 901b793 7cfc4d4. Thanks!

**Comment by bcook-r7** [comment]
One more cleanup 680709c. After being annoyed at how long './msfvenom -h' takes to run, I modified these tools to be 'model citizens' and only spin up framework after options have been parsed. Makes '-h' come up quickly, like one would expect. msfvenom is next in another PR.

**Comment by finackieee** [comment]
Awesome, thanks for the cleanup!

**Pull request merged**
