### PR TITLE
Tool to find missing documentation and/or modules

### PR DESCRIPTION
**Pull request by hkerma**
Hi everyone,
Making this PR after a discussion on #8296 about missing documentation files.

I wrote a piece of code in Python that print a markdown-formatted list of missing documentation or a documentation that does not correspond to any module.

I'm making this PR so we can discuss the code !

### CODE REVIEW

**Comment by h00die** [comment]
@hkerma Just a heads up, I've started looking at this.  I'll most likely submit a PR to your branch (when you accept it, it'll automatically update this pull request).  It may be several PRs or revisions.

**Comment by h00die** [comment]
#12389 was generated from the latest revision.

The only other idea I had, which I haven't looked in to yet, is if the modules could link to the github page for them.  So one click, boom here's the module.  That would be awesome, but I'll look later.

**Comment by h00die** [comment]
One last change, this makes all the list items links, which is great so you don't have to browse to get he modules, it gets you right there!

**Comment by h00die** [comment]
ping @hkerma Got a PR waiting on you, once accepted this is good to go IMO and i'm ready to land!

**Comment by hkerma** [comment]
Oops sorry I didn't see the second one !
It's now merged !

**Comment by h00die** [comment]
@hkerma It's been a long process, thanks for sticking with it!  This will DEFINITELY help manage finding stray docs, and keeping tabs on what docs still need to be created.  Much appreciated.
🏆

**Comment by h00die** [comment]
# Release Notes
This PR adds a new tool to help manage docs by identifying stray docs (need to be renamed), docs which need to be created, and files which are in the wrong place.  It does this in a markdown format, with links to the modules, to help keep automatic tabs on #12389 .

**Pull request merged**
