### PR TITLE
convert IPMI protocol and modules to bindata

### PR DESCRIPTION
**Pull request by busterb**
Because bit-struct is not Ruby 2.4+ compatible and appears to be unmaintained now, this converts our IPMI modules to use bindata instead. To test this properly, it is ideal to have an actual IPMI target handy.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/ipmi/ipmi_cipher_zero`
- [x] `setg RHOSTS IP`
- [x] **Verify** that you can check if the remote host is vulnerable
- [x] `use auxiliaryscanner/ipmi/ipmi_dumphashes`
- [x] **Verify** that you can dump hashes
- [x] `use auxiliaryscanner/ipmi/ipmi_version`
- [x] **Verify** that you can identify IPMI versions

```
msf auxiliary(ipmi_cipher_zero) > run

[*] Sending IPMI requests to 192.168.1.2->192.168.1.2 (1 hosts)
[*] 192.168.1.2:623 - IPMI - NOT VULNERABLE: Rejected cipher zero with error code 17


^C[*] Caught interrupt from the console...
[*] Auxiliary module execution completed
msf auxiliary(ipmi_cipher_zero) > use auxiliary/scanner/ipmi/ipmi_version
msf auxiliary(ipmi_version) > run

[*] Sending IPMI requests to 192.168.1.2->192.168.1.2 (1 hosts)
[*] 192.168.1.2:623 - IPMI - Probe sent
[+] 192.168.1.2:623 - IPMI - IPMI-2.0 OEMID:180010 UserAuth(auth_msg, auth_user, non_null_user) PassAuth(password, md5, md2) Level(1.5, 2.0)

^C[*] Caught interrupt from the console...
[*] Auxiliary module execution completed
msf auxiliary(ipmi_version) > use auxiliary/scanner/ipmi/ipmi_dumphashes
msf auxiliary(ipmi_dumphashes) > run

[*] 192.168.1.2:623 - IPMI - Sending IPMI probes
[*] 192.168.1.2:623 - IPMI - Trying username 'ADMIN'...
[-] 192.168.1.2:623 - IPMI - Returned error code 13 for username ADMIN: Unauthorized name
[*] 192.168.1.2:623 - IPMI - Trying username 'admin'...
[-] 192.168.1.2:623 - IPMI - Returned error code 13 for username admin: Unauthorized name
[*] 192.168.1.2:623 - IPMI - Trying username 'root'...
[+] 192.168.1.2:623 - IPMI - Hash found: root:redacted
[*] 192.168.1.2:623 - IPMI - Trying username 'Administrator'...
[-] 192.168.1.2:623 - IPMI - Returned error code 13 for username Administrator: Unauthorized name
[*] 192.168.1.2:623 - IPMI - Trying username 'USERID'...
[-] 192.168.1.2:623 - IPMI - Returned error code 13 for username USERID: Unauthorized name
[*] 192.168.1.2:623 - IPMI - Trying username 'guest'...
[-] 192.168.1.2:623 - IPMI - Returned error code 13 for username guest: Unauthorized name
[*] 192.168.1.2:623 - IPMI - Trying username ''...
[+] 192.168.1.2:623 - IPMI - Hash found: redacted
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

### CODE REVIEW

**Comment by busterb** [comment]
@TomSellers it would be nice if you could give this a test run as well, thanks!

**Comment by TomSellers** [comment]
The tests ran as expected in my lab.  `auxiliary/scanner/ipmi/ipmi_version` and `auxiliary/scanner/ipmi/ipmi_cipher_zero` generated the same output as your example.  I was able to successfully dump hashes using ` auxiliary/scanner/ipmi/ipmi_dumphashes`.

I ran all three modules across multiple hosts that included one with IPMI and others without and no unexpected message/errors were generated.  I also ran it against non-IPMI UDP services such as DNS and Netbios without any unhanded exceptions.

Just a note, the testing example at the top is missing the slash between auxiliary and scanner.

**Comment by busterb** [comment]
Thanks @TomSellers fixed it. I think I'll add some module docs for these and call it done.

**Comment by busterb** [comment]
## Release Notes

The IPMI modules have been rewritten to support the bindata gem for parsing binary data.

**Pull request merged**
