### PR TITLE
Update modules to use metasploit-credential instead of report_auth_info

### PR DESCRIPTION
**Pull request by wchen-r7**
This patch updates modules to use the metasploit-credential API. It also updates existing ones to always provide :proof. There's a lot of files changed so I figured it's enough for this round.
## Verification
- [x] Start msfconsole
- [x] `loadpath test/modules`
- [x] `use test/report_auth_info`
- [x] `run`
- [x] All should be green, no red.

### CODE REVIEW

**Comment by wchen-r7** [comment]
Labeling it as delayed because I am adding some more.

**Comment by wchen-r7** [comment]
No longer delayed, please feel free to pick it up.

**Comment by bcook-r7** [comment]
Wow, nice set of conversions, thanks @wchen-r7

**Comment by void-in** [comment]
@bcook-r7 Can we have a helper module which can be called from within the modules to store credentials? I know it is too late but updating modules whenever an API changes is such a hastle. Me and @wchen-r7 are doing this conversion for a long time now. Hopefully with this PR there won't be any more modules using report_auth_info but I am thinking if in future the API change again, if there could be a helper class we could just include in the module and then changes only that single file will be a better option. 

I can see the calling info sometimes changes but in a lot of cases the parameters are the same. Just want to ask about the feasibility of such an activity.

**Pull request merged**
