### PR TITLE
Fix smb auth to host with hostname in national chars

### PR DESCRIPTION
**Pull request by crmaxx**
After I fix smb auth with logins in national chars in #7024 and [#1](https://github.com/rapid7/rex-text/pull/1) next challenge was in auth to host with 'computer name' in national characters.

In ntlm type2 response has `default_name`, `default_domain`, `dns_host_name` and `dns_domain_name` fields in blob already in UCS2 and no need to convert `to_unicode()` in module `Rex::Proto::NTLM::Utils.make_ntlmv2_clientchallenge()`

For ASCII this fields need to clear from "\x00" (it's same as convert from UTF-16be)

### CODE REVIEW

**Comment by egypt** [comment]
I'm working on moving NTLM authentication to the rubyntlm gem instead of our old version of `Net::NTLM`, which may fix this as a byproduct. Please be patient while I work out the kinks with #7009, #7074 and then we can verify that the unicode handling is working correctly.

**Comment by crmaxx** [comment]
@egypt rubyntlm has same problem (see #7024) with `String.upcase` with ruby < 2.4

**Comment by bwatters-r7** [comment]
Is this useful without the changes to rex-text?

**Comment by crmaxx** [comment]
no

**Comment by bwatters-r7** [comment]
Crap; I want to get metasploit to play better with unicode, but right now, this module does not play well with others.

**Pull request closed without merging**
