### PR TITLE
Add WS-Discovery Information Discovery module

### PR DESCRIPTION
**Pull request by bcoles**
This PR adds a WS-Discovery Information Discovery scanner module.

This module scans for, and retrieves information from, Web Services Dynamic Discovery (WS-Discovery) enabled systems.

## Verification

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/wsdd/wsdd_query`
- [x] `run`
- [x] If your network contains a WSDD enabled device, verify results are returned
- [x] If your network does not contain a WSDD enabled device, verify no results are returned

### Example Output

```
msf > use auxiliary/scanner/wsdd/wsdd_query 
msf auxiliary(wsdd_query) > set rhosts 239.255.255.250
rhosts => 239.255.255.250
msf auxiliary(wsdd_query) > run

[*] Sending WS-Discovery probe to 1 hosts
[+] 10.1.1.184 responded with:
Address: http://10.1.1.184:3911/ 
Types: wsdp:Device, wprt:PrintDeviceType, wscn:ScanDeviceType, hpd:hpDevice
Vendor Extensions: {"HardwareAddress"=>"123456789ABC", "UUID"=>"12345678-1234-1234-abcd-123456789abc", "IPv4Address"=>"10.1.1.123", "Hostname"=>"HP09AAFB", "DeviceId"=>"MFG:HP;MDL:Photosmart 5520 series;DES:CX042A;", "DeviceIdentification"=>{"MakeAndModel"=>"Photosmart 5520 series", "MakeAndModelBase"=>"Photosmart 5520 series"}, "SerialNumber"=>"123456", "Services"=>" Print9100 SclScan RESTScan CIFS DOT4 LEDM", "AdapterType"=>"WifiEmbedded"}
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

### CODE REVIEW

**Comment by sempervictus** [comment]
Oh cool, thanks as always.
Do we wanna move the probes to a proto def or leave them in the module? We have people rewriting methods which should be in lib within their modules because they may not have read all existing related code to pillage, or not yet know the code structure. Exposing from Rex or wrapping with Msf middleware might make sense if you have the cycles and or desire :-).

**Comment by bcoles** [comment]
@sempervictus perhaps.

That will have to be a future task. I'm short on devices with which to test and short on dev time.

It seems that a few vendors, such as HP and Brother, make use of the optional vendor extensions. It would be nice to have some sample data of what the extension data typically contains - are there vendor standards, what useful information can we reliably expect to exist in the response, etc.

There's also more work to be done with WSDD - in particular, apparently it can be used to identify Microsoft WCF services. I don't have WCF set up to test, and have no idea what the output format looks like. There could be useful information in these ProbeMatches too. I believe WCF requires a specific probe request format to elicit a response.

**Comment by wchen-r7** [comment]
Thanks to @bcook-r7, we have a device for testing and it works:

```
msf auxiliary(wsdd_query) > run

[*] Sending WS-Discovery probe to 1 hosts
[*] 239.255.255.250:3702 - Sending WS-Discovery probe
[+] 192.168.1.69 responded with:
Address: http://192.168.1.69:3911/ http://[fe80::ee8e:b5ff:fec7:f2ba]:3911/ 
Types: wsdp:Device, wprt:PrintDeviceType, hpd:hpDevice
Vendor Extensions: {"HardwareAddress"=>"ec8eb5c7f2ba", "UUID"=>"d6457fc3-d61b-565c-e167-df70915ac53c", "IPv4Address"=>"192.168.1.69", "IPv6Addresses"=>{"IPv6Address"=>"fe80::ee8e:b5ff:fec7:f2ba"}, "Hostname"=>"HPC7F2BA", "ManageabilityContractID"=>"wsmct:PR;wsmcl:DI;wsmcv:3.0", "DeviceId"=>"MFG:HP;MDL:HP OfficeJet Pro 8210;DES:D9L64A;", "DeviceIdentification"=>{"MakeAndModel"=>"HP OfficeJet Pro 8210", "MakeAndModelBase"=>"HP OfficeJet Pro 8210"}, "SerialNumber"=>"CN67KCT00J", "Services"=>" Print9100 LEDM", "AdapterType"=>"Ethernet"}
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by wchen-r7** [comment]
The source code and the documentation look good to me. I'll land it. Thanks @bcoles

**Comment by wchen-r7** [comment]
# Release Notes

This is an auxiliary module that relies on WSDD to discover network devices. WSDD (Web Services Dynamic Discovery) is a multicast discovery protocol utilizing SOAP over UDP to locate web services on a local network.

**Pull request merged**
