### PR TITLE
Added ECHOUA URI request type to reflect victim UA string

### PR DESCRIPTION
**Pull request by jbunderwater**
When using Veil-Evasion powershell stager and the MSF reverse http handler, the user agent string is hard coded. Network administrators are starting to scour through Veil & metasploit code to find user agent strings to blacklist on their proxies. So, to avoid getting detected, I added a new response to the reverse_http handler that echos the client's user agent string back to it in html. This is used by the Veil-Evasion powershell payload to first, navigate to the MSF meterpreter handler to receive back its own user-agent, then begin setting up the meterpreter session using the user-agent.

I did it this way because it's not really possible to determine the user agent from just the installed version of IE. By establishing the connection looking like internet explorer, I think this could greatly reduce detections.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Perhaps related to #4933.

**Comment by hmoore-r7** [comment]
@pyrohaz4good Thanks for the PR. We can't take this as is for a couple reasons:
* It directly overwrites a datastore[] entry. This is bad and should be implemented as logic within the handler to choose between the client's user-agent or the configured user-agent.
* It changes default behavior. There are cases where you don't want to reuse the stager's user-agent (its often length-restricted, so you want to patch in a specific one instead).

If you rework this to create a new datastore option (advanced, boolean, something like 'MeterpreterClientUserAgent', default to false) and implement the logic to switch to this user-agent when the option is set, we can look at integrating it.

**Comment by Meatballs1** [comment]
Wouldn't it be better to fix the root cause and let the use choose a user agent, and either randomize, or dont even bother with a user agent in the comms if the user doesn't set one?

**Comment by Meatballs1** [comment]
Maybe the ideal is to have user options to:

* Randomize UA
* Remove UA
* User-Set UA
* Reflect UA

**Comment by pyrohaz4good** [comment]
@hmoore-r7 Thanks for the feedback. This is my first contribution to MSF so not familiar with all the guidelines...I'm working on updating per your comments.

@Meatballs1 Not a bad thought, maybe an option to set the UserAgentBehavior to one of those 4 options. The randomize could be from a collection of valid UAs. Network admins can't black list them all. The reflecting or user-set is really only needed in restrictive proxy settings (although I'm running into those more often now).

**Comment by hmoore-r7** [comment]
@Meatballs1 @pyrohaz4good Having an OptEnum with those types implemented makes sense (default being User-Set UA and the current MetepreterUserAgent option).

**Comment by hmoore-r7** [comment]
@pyrohaz4good If you prefer, I can pick this up as a feature request, since this is an area I am actively working on at the moment (reworking much of the HTTP handler).

**Comment by pyrohaz4good** [comment]
@hmoore-r7 I just added some commits to get the 'standard' implementation setup according to your comments. How far along on you on your HTTP handler? I can probably do the changes over the next day or two and then you can take this branch and merge with yours if you'd like? Or if you are already far along and its faster for you to do it, thats fine too. FYI I'm in Central Euro Time.

**Comment by pyrohaz4good** [comment]
@hmoore-r7 @Meatballs1 I've now updated the implementation and ran tests to ensure it all works. You can now set UserAgentBehavior to any of the following:
Remove: Don't setup any UA
Reflect: Use the UA sent by the client when the connection request comes in
User-Set (Default): Use the UA set by the user or the default

I haven't added a "randomize" because I think that's best implemented in some sort of helper class that can be called. There's a lot of UAs out there and it makes sense to pull into MSF the ones that are most common for the last versions of IE, Chrome, Firefox, Safari. 

The only payload that can use the 'reflect' option at this point are custom payloads and the Veil powershell reverse http payload. I should make this change over on rev_https.rb as well to keep it consistent...but that will be a separate pull I think.

Let me know if there's anything else I need to change to make this acceptable.

**Comment by hmoore-r7** [comment]
Lots of code churn in this area, but this is still on my radar.

**Comment by bcook-r7** [comment]
If this isn't listed in #4895, perhaps it should be.

**Comment by pyrohaz4good** [comment]
Any news on this one? The nice folks working on Veil have a pending pull request from me for one of their payloads so they can use this reflection functionality.

**Comment by hmoore-r7** [comment]
Not yet

**Comment by bcook-r7** [comment]
Anything we can do to help with this @hmoore-r7 ?

**Comment by hmoore-r7** [comment]
@bcook-r7 If someone else wants to pick it up, I would be happy to review, apologies for dragging on this one.

**Comment by pyrohaz4good** [comment]
I think it's all good to go, just needs review in light of whatever
refractering has been done.

**Comment by bcook-r7** [comment]
Yeah, just needs a rebase on master. Since we have #5729, it should be possible to implement 'Randomize' easily as well.

**Comment by hmoore-r7** [comment]
It needed to be rebased and merged with the #5729 settings, so a bit of a refactor.

**Comment by bcook-r7** [comment]
The URI checksum processing scheme in the HTTP handler has changed too much for this PR to be easily migrated as-is. This is especially so, since the Veil side of the PR will also have to be changed to match this scheme.

After thinking about the options, it looks like need a new PR entirely, so I am closing this one.

**Pull request closed without merging**
