### PR TITLE
Check if Domain and or Enterprise Admin is logged in.

### PR DESCRIPTION
**Pull request by jamesbcook**
This module will log in with administrator credentials and check if a domain or enterprise administrator is currently logged into the system.

enum_tokens is good and works but you have to have a shell for it to work
psexec_loggedin_users is good, but only searches for one user at a time.

### CODE REVIEW

**Comment by mubix** [comment]
How about this one: `auxiliary/scanner/smb/smb_enumusers_domain` - you have to know who a domain admin are already though. But no shell and no writing text files or services being created on hosts.

**Comment by b00stfr3ak** [comment]
That is cool, and I agree writing text,bat and creating services is not ideal.

This could be another option if the user just wants to look for da without searching after/while the scan is going on.

**Comment by b00stfr3ak** [comment]
@mubix Would it be better to try and modify smb_enumusers_domain to have the option of supplying a username or a list of usernames to check for and report that a match was found.

**Comment by bcook-r7** [comment]
IMHO, extending auxiliary/scanner/smb/smb_enumusers_domain makes more sense. It could use a little cleanup as well. Let's suggest that route rather than creating a new special purpose module.

**Pull request closed without merging**
