### PR TITLE
Update Ruby Hash Syntax, foo: 'bar' instead of :foo => 'bar'

### PR DESCRIPTION
**Pull request by espreto**
This PR intends to update the hash syntax of ruby. First only the modules.

From:

``` ruby
hash = { :key => 'value' }
```

to:

``` ruby
hash = { key: 'value' }
```

Ref: [Ruby style guide](https://github.com/bbatsov/ruby-style-guide#hash-literals)

### CODE REVIEW

**Comment by bcook-r7** [comment]
This is likely to go stale quickly and is probably difficult to review without making some mistake, since it changes > 850 files.

Did you perform this conversion with a script or tool so it is reproducible? Sorry, such a big change needs to have a big level of paranoia that something strange doesn't slip in randomly in the middle.

**Comment by espreto** [comment]
The most significant changes were around report_note, report_service, report_auth_info, http_fingerprint, among others. I conducted several tests with random modules and all worked properly.

The following command was used:
```
$ find . -name \*.rb -exec perl -p -i -e 's/([^:]):(\w+)\s*=>/\1\2:/g' {} \;
```
[]'s

**Comment by wvu-r7** [comment]
I think this should be a progressive change, not a retroactive one.

**Comment by bcook-r7** [comment]
I appreciate the work that went into this, but I don't think we can take a change like this.

Maybe we should consider adding a rubocop pass back to msftidy that checks for uses of deprecated syntax in general. As is, this change will cause too much churn in other PRs and branches. Sorry!

**Pull request closed without merging**
