### PR TITLE
Add support for the interval geo/cell collection on Android

### PR DESCRIPTION
**Pull request by hdm**
This depends on a future PR in metasploit-payloads, so marked delayed for now.

### CODE REVIEW

**Comment by hdm** [comment]
This is tied to https://github.com/rapid7/metasploit-payloads/pull/55

**Comment by bcook-r7** [comment]
This is a toughie to test indoors; will need to go on a trek and see how it works out.

**Comment by timwr** [comment]
I'll give this a quick test outdoors

**Comment by timwr** [comment]
Seems to work better after https://github.com/rapid7/metasploit-payloads/pull/60/files
I only gave it a quick test though.
You can use http://www.darrinward.com/lat-long/ to plot the result :)

**Pull request merged**
