### PR TITLE
add esxi to ssh_login platforms

### LINKED ISSUE #16431: ssh_login on esxi showing unknown shell type for esxi 6.7
```
[+] 1.1.1.1:22 - Success: 'root:password' 'sh: id: not found sh: help: not found sh: ?: not found '
```

which then shows

```
msf6 auxiliary(scanner/ssh/ssh_login) > sessions -l

Active sessions
===============

  Id  Name  Type                   Information                           Connection
  --  ----  ----                   -----------                           ----------
  7         shell unknown          SSH root @                            2.2.2.2:34135 -> 1.1.1.1:22  (1.1.1.1)
```

jumping on a box like this we get some info:

```
uname -a
VMkernel <snip> ESXi
vmware -v
VMware ESXi 6.7.0
```

### PR DESCRIPTION
**Pull request by h00die**
Fixes #16431 by adding ESXi as a recognizable type on `ssh_login`.  For the time being, we just make it `linux` but it wasn't being detected in the first place. Main change is here: https://github.com/rapid7/metasploit-framework/pull/16437/files#diff-cd17a4a1116480deb152b2300338e9657a546b8509497b8c6ef1af8ed0985bb2R74-R75

Also rubocop for beautification.

## From
```
resource (esxi_login.rb)> run
[*] 2.2.2.2:22 - Starting bruteforce
[+] 2.2.2.2:22 - Success: 'root:password' 'sh: id: not found sh: help: not found sh: ?: not found '
[*] SSH session 1 opened (1.1.1.1:45405 -> 2.2.2.2:22 ) at 2022-04-10 11:19:14 -0400
[-] 2.2.2.2:22 - While a session may have opened, it may be bugged.  If you experience issues with it, re-run this module with 'set gatherproof false'.  Also consider submitting an issue at github.com/rapid7/metasploit-framework with device details so it can be handled in the future.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ssh/ssh_login) > sessions

Active sessions
===============

  Id  Name  Type           Information   Connection
  --  ----  ----           -----------   ----------
  1         shell unknown  SSH h00die @  1.1.1.1:45405 -> 2.2.2.2:22  (2.2.2.2)
```

## To (session 3)

```
msf6 auxiliary(scanner/ssh/ssh_login) > run

[*] 2.2.2.2:22 - Starting bruteforce
[+] 2.2.2.2:22 - Success: 'root:password' 'VMware ESXi 6.7.0 build-19195723 '
[*] SSH session 3 opened (1.1.1.1:40305 -> 2.2.2.2:22 ) at 2022-04-10 11:24:07 -0400
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ssh/ssh_login) > sessions -l

Active sessions
===============

  Id  Name  Type           Information   Connection
  --  ----  ----           -----------   ----------
  2         shell unknown  SSH h00die @  1.1.1.1:35331 -> 2.2.2.2:22  (2.2.2.2)
  3         shell linux    SSH h00die @  1.1.1.1:40305 -> 2.2.2.2:22  (2.2.2.2)
```

### CODE REVIEW

**Comment by h00die** [comment]
@msjenkins-r7 recheck this

**Comment by jheysel-r7** [comment]
Jenkins test this please

**Comment by jheysel-r7** [comment]
Changes look good and testing was successful 👍 

Before: 
```
msf6 auxiliary(scanner/ssh/ssh_login) > run

[*] 10.4.25.24:22 - Starting bruteforce
[+] 10.4.25.24:22 - Success: 'root:notpassword' 'sh: id: not found sh: help: not found sh: ?: not found '
[*] SSH session 1 opened (10.4.226.153:53039 -> 10.4.25.24:22 ) at 2022-04-20 06:51:30 -0700
[-] 10.4.25.24:22 - While a session may have opened, it may be bugged.  If you experience issues with it, re-run this module with 'set gatherproof false'.  Also consider submitting an issue at github.com/rapid7/metasploit-framework with device details so it can be handled in the future.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ssh/ssh_login) > sessions

Active sessions
===============

  Id  Name  Type           Information    Connection
  --  ----  ----           -----------    ----------
  1         shell unknown  SSH jheysel @  10.4.226.153:53039 -> 10.4.25.24:22  (10.4.25.24)

msf6 auxiliary(scanner/ssh/ssh_login) >
```


After:

```
msf6 auxiliary(scanner/ssh/ssh_login) > run

[*] 10.4.25.24:22 - Starting bruteforce
[+] 10.4.25.24:22 - Success: 'root:notpassword' 'VMware ESXi 6.5.0 build-8294253 '
[*] SSH session 1 opened (10.4.226.153:53138 -> 10.4.25.24:22 ) at 2022-04-20 06:58:08 -0700
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ssh/ssh_login) > sessions

Active sessions
===============

  Id  Name  Type         Information    Connection
  --  ----  ----         -----------    ----------
  1         shell linux  SSH jheysel @  10.4.226.153:53138 -> 10.4.25.24:22  (10.4.25.24)
```

**Comment by dwelch-r7** [comment]
# Release Notes

Adds ESXi as a recognizable type on ssh_login

**Pull request merged**
