### PR TITLE
Cisco SMI (Smart Install) scanner

### PR DESCRIPTION
**Pull request by jhart-r7**
This adds a simple TCP scanner module that can be used to identify exposed and likely vulnerable Cisco SMI (Smart Install) endpoints.  This mimics the behavior of Cisco's official tool that they released for this called [smi_check](https://github.com/Cisco-Talos/smi_check/blob/master/smi_check.py)

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/misc/cisco_smart_install`
- [x] `set RHOSTS <some hosts that might be vulnerable>`
- [x] `run`
- [x] **Verify** that an endpoint exposing SMI has SMI identified and marked vulnerable
- [x] **Verify** that an endpoint that isn't SMI does not identify SMI and is not marked vulnerable
- [x] Sanity check my docs

In this list I know there is a host exposing SMI:

```
msf auxiliary(cisco_smart_install) > set RHOSTS <hosts>
RHOSTS => <hosts>
msf auxiliary(cisco_smart_install) > set ConnectTimeout 1
ConnectTimeout => 1
msf auxiliary(cisco_smart_install) > set THREADS 50
THREADS => 50
msf auxiliary(cisco_smart_install) > run

[*] Scanned  57 of 512 hosts (11% complete)
[*] Scanned 105 of 512 hosts (20% complete)
[*] Scanned 157 of 512 hosts (30% complete)
[*] Scanned 212 of 512 hosts (41% complete)
[*] Scanned 256 of 512 hosts (50% complete)
[*] Scanned 310 of 512 hosts (60% complete)
[*] Scanned 368 of 512 hosts (71% complete)
[*] Scanned 413 of 512 hosts (80% complete)
[*] Scanned 466 of 512 hosts (91% complete)
[+] a.b.c.d:4786   - Fingerprinted the Cisco Smart Install protocol
[*] Scanned 512 of 512 hosts (100% complete)
[*] Auxiliary module execution completed
```

Testing against an endpoint that isn't SMI:

```
msf auxiliary(cisco_smart_install) > set RHOSTS localhost
RHOSTS => localhost
msf auxiliary(cisco_smart_install) > run

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(cisco_smart_install) > set VERBOSE 
VERBOSE => false
msf auxiliary(cisco_smart_install) > set VERBOSE  true
VERBOSE => true
msf auxiliary(cisco_smart_install) > run

[*] 127.0.0.1:4786        - No match for 'HTTP/1.1 400 Bad Request 
Content-Type: text/html; charset=ISO-8859-1
Server: WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21)
Date: Tue, 22 Aug 2017 21:49:14 GMT
Content-Length: 392
Connection: close

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Bad Request</TITLE></HEAD>
  <BODY>
    <H1>Bad Request</H1>
    bad Request-Line `\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\b\x00\x00\x00\x01\x00\x00\x00\x00'.
    <HR>
    <ADDRESS>
     WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21) at
     host:4786
    </ADDRESS>
  </BODY>
</HTML>
'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

(Note: if a Rapid7 employee picks up this PR, I have an internal scan target you can use for this) #

### CODE REVIEW

**Review by sempervictus — APPROVED** [review]
Neat, very neat. Thank you.

**Comment by busterb** [comment]
Thanks @jhart-r7 I'll take a look today.

**Comment by busterb** [comment]
Tweaked docs slightly: a304df265c, thanks

**Comment by busterb** [comment]
## Release Notes

This adds a simple TCP scanner module that can be used to identify exposed and likely vulnerable Cisco SMI (Smart Install) endpoints. This mimics the behavior of Cisco's official tool that they released for this called smi_check.

**Pull request merged**
