### PR TITLE
Correct a bad spelling in ms15_034_ulonglongadd.rb

### PR DESCRIPTION
**Pull request by wchen-r7**
I made a typo: "denail of service", and @dmiller-nmap found it.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Denailing sounds very painful.

**Comment by wvu-r7** [comment]
I prefer the original.

**Comment by todb-r7** [comment]
we have ways of making you crash

**Comment by void-in** [comment]
Typo was consistent with the pronunciation. English is weird.

**Pull request merged**
