### PR TITLE
PHP meterpreter kb

### PR DESCRIPTION
**Pull request by cbrnrd**
Addresses #7141 by adding KB for php/meterpreter/reverse_tcp

### CODE REVIEW

**Comment by void-in** [comment]
@thecarterb There are still irrelevant files which are part of this PR. I think you are creating PRs from your master branch that is why these files creeped in. You will have to create a separate branch to keep it clean. For example:
```bash
git pull upstream/master
git checkout -b kb-php-reverse-tcp
<create the reverse_tcp.md file>
git add  documentation/modules/payload/php/meterpreter/reverse_tcp.md
git commit -m "create reverse_tcp.md"
git push origin kb-php-reverse-tcp
```

**Comment by thecarterb** [comment]
Hi, yeah originally made the PR from master, but for this one i'm pretty sure I used a separate branch

**Comment by void-in** [comment]
Then you might be using ```git commit -a``` or there is some other issue with your environment. Can you follow the steps outlined above and give it another try? Git can be confusing somethings.

**Comment by thecarterb** [comment]
Okay, will do

**Comment by thecarterb** [comment]
@void-in I'm going to delete my fork and fork again. I'm going to close this PR and open another one that is cleaner

**Pull request closed without merging**
