### PR TITLE
Resolve #4507 - Preserve the necessary evilness of respond_to? + send

### LINKED ISSUE #4507: Double check respond_to? for Ruby 2.1 compat
In [this comment](https://github.com/rapid7/metasploit-framework/issues/4219#issuecomment-66727019), @jlee-r7 raised a concern about the usage of `respond_to?` and how it may affect 2.1 functionality.

There are 14 uses in `modules/` and 132 uses in `lib/`. Let's validate that we're not going to suddenly cause 2.1 breakage there.

Note that nearly all developers have been on 2.1 since early November if they [followed these instructions](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#moving-to-ruby-21x), so it seems unlikely that there are remaining breakages, but let's be (more) sure.

### PR DESCRIPTION
**Pull request by wchen-r7**
Since Ruby 2.1, the respond_to? method is more strict because it does not check protected methods. So when you use send() to go with that type of check, clearly you're ignoring the access control, and it's evil. The patch is meant to preserve evil... I mean, preserve the original behavior to avoid potential breakage. 

Resolve #4507

### CODE REVIEW

**Comment by todb-r7** [comment]
Seems weird that you'd have to do this, since as of 1.9.3, you're supposed to already be defaulting to `false` for the private method inclusion anyway:

http://ruby-doc.org/core-1.9.3/Object.html#method-i-respond_to-3F

Regardless, I don't mind.

**Comment by todb-r7** [comment]
```ruby
ruby-1.9.3-p551@metasploit-framework](upstream-master) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ irb
1.9.3-p551 :001 > class Foo
1.9.3-p551 :002?>   def one
1.9.3-p551 :003?>     end
1.9.3-p551 :004?>   private
1.9.3-p551 :005?>   def two
1.9.3-p551 :006?>     end
1.9.3-p551 :007?>   end
 => nil 
1.9.3-p551 :008 > a = Foo.new
 => #<Foo:0x00000001e7b2f0> 
1.9.3-p551 :009 > a.respond_to? :one
 => true 
1.9.3-p551 :010 > a.respond_to? :two
 => false 
1.9.3-p551 :011 > a.respond_to? :two, true
 => true 
1.9.3-p551 :012 > 

```

**Comment by wchen-r7** [comment]
I was thinking protected methods, actually.

**Comment by todb-r7** [comment]
Ah ha! That's the stuff. Thanks @wchen-r7:

````
[ruby-1.9.3-p551@metasploit-framework](upstream-master) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ irb
1.9.3-p551 :001 > class Foo
1.9.3-p551 :002?>   def one; end
1.9.3-p551 :003?>   protected
1.9.3-p551 :004?>   def two;end
1.9.3-p551 :005?>   private
1.9.3-p551 :006?>   def three;end
1.9.3-p551 :007?>   end
 => nil 
1.9.3-p551 :008 > Foo.new.respond_to? :one
 => true 
1.9.3-p551 :009 > Foo.new.respond_to? :two
 => true 
1.9.3-p551 :010 > Foo.new.respond_to? :three
 => false 
1.9.3-p551 :011 > exit
[ruby-1.9.3-p551@metasploit-framework](upstream-master) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ rvm use 2.1.5@metasploit-framework
Using /home/todb/.rvm/gems/ruby-2.1.5 with gemset metasploit-framework
[ruby-2.1.5@metasploit-framework](upstream-master) 
todb@mazikeen:~/git/rapid7/metasploit-framework$ irb
2.1.5 :001 > class Foo
2.1.5 :002?>   def one; end
2.1.5 :003?>   protected
2.1.5 :004?>   def two;end
2.1.5 :005?>   private
2.1.5 :006?>   def three;end
2.1.5 :007?>   end
 => :three 
2.1.5 :008 > Foo.new.respond_to? :one
 => true 
2.1.5 :009 > Foo.new.respond_to? :two
 => false 
2.1.5 :010 > Foo.new.respond_to? :three
 => false 
2.1.5 :011 > 

````

**Pull request merged**
