### PR TITLE
Bump actions/github-script to v6

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@bwatters-r7 @jheysel-r7 please approve workflows

**Comment by bwatters-r7** [comment]
@gliptak I don't know what this does exactly, or why it is needed.  I'm generally totally down for updating releases, but I'd want someone more familiar with our build process to weigh in on this change.  I'm sure it will come up on the week's PR reviews, so I'd expect feedback and movement by the end of the week.  Thanks!

**Comment by adfoster-r7** [comment]
Hi @gliptak - it looks like this may need additional code changes from what I can see:
https://github.com/actions/github-script/tree/7dff1a87643417cf3b95bb10b29f4c4bc60d8ebd#breaking-changes

Were you able to verify/test this upgrade beforehand? 👀

**Comment by gliptak** [comment]
@adfoster-r7 the PR is green on my fork https://github.com/gliptak/metasploit-framework/pull/4/checks

**Comment by adfoster-r7** [comment]
I believe it's green as the codepath isn't triggered with the required event, which only occurs when specific labels are added to issues/pull requests:

```
on:
  pull_request_target:
    types: [labeled]
  issues:
    types: [labeled]
```

From the change log https://github.com/actions/github-script/tree/7dff1a87643417cf3b95bb10b29f4c4bc60d8ebd#breaking-changes it looks like there is API changes:

> ### Breaking changes in V5
> [...] For example, `github.issues.createComment` in V4 becomes `github.rest.issues.createComment` in V5

Which looks like the pattern we're using over here:

https://github.com/rapid7/metasploit-framework/blob/a73461e96b7c34cc13e5b8c2bd2f3bd85e86df74/.github/workflows/labels.yml#L203-L220

**Comment by gliptak** [comment]
thank you for all the pointers @adfoster-r7 

updated results https://github.com/gliptak/metasploit-framework/actions/runs/3186246986/jobs/5196651945

**Comment by gliptak** [comment]
any other updates for this PR?

**Comment by adfoster-r7** [comment]
Thanks for pushing additional updates; I should be able to do a final verification next week :+1:

**Comment by gwillcox-r7** [comment]
Alan I'm going to assign this issue to you in the meantime given your last comment. This should help clear up the PR queue a little bit, but let me know if this is an issue.

**Comment by adfoster-r7** [comment]
Thanks! :+1:

**Pull request merged**
