### PR TITLE
Fix -h exit status for Omnibus

### PR DESCRIPTION
**Pull request by wvu**
Asking for help isn't bad.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Thanks @wvu-r7

**Comment by hmoore-r7** [comment]
Is it worth doing the same for ./tools/*.rb?

**Comment by wvu-r7** [comment]
@hmoore-r7: Checking, thanks!

**Comment by wvu-r7** [comment]
Looks like the ```tools``` directory is good to go!

**Comment by busterb** [comment]
Now we can test all of the commands consistently.

**Pull request merged**
