### PR TITLE
Added the link for 'COPYING' file

### PR DESCRIPTION
**Pull request by Seniru**
This PR will link the word 'COPYING' in the README to 'COPYING' file.
- [ ] Open [README](https://github.com/Seniru/metasploit-framework/blob/master/README.md)

### CODE REVIEW

**Comment by dwelch-r7** [comment]
> Do create a topic branch to work on instead of working directly on master. This helps protect the process, ensures users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes, and allows contributors to make progress while a PR is still being reviewed.

https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md

Please feel free to re-open this PR from a topic branch rather than master

**Comment by Seniru** [comment]
Sorry for that.  I didn't understand what was it saying.

**Comment by dwelch-r7** [comment]
No problem, it's a lot to take in

you need to make a new branch on _your_ fork of the repo, then make a PR from your new branch to rapid7:master

**Comment by Seniru** [comment]
You mean like `Seniru:patch`

**Comment by dwelch-r7** [comment]
yup that'd be just fine

**Pull request closed without merging**
