### PR TITLE
Remove some anti-patterns, in the same spirit than #7372

### PR DESCRIPTION
**Pull request by jvoisin**
This PR is almost the same as #7372

@wvu-r7 ^

### CODE REVIEW

**Comment by wvu-r7** [comment]
<3

**Comment by wvu-r7** [comment]
@jvoisin: Hey, can you create a topic branch for your PRs from now on? Check out [CONTRIBUTING.md](https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md) for contribution anti-patterns. Thanks!

**Comment by wvu-r7** [comment]
(That page is in fact linked to when you create a new PR. :)

**Comment by jvoisin** [comment]
Ho, sure :)

**Comment by h00die** [comment]
I'm guilty, +1 to this, @jvoisin thanks for catching that!

**Comment by wvu-r7** [comment]
@h00die: https://github.com/rapid7/metasploit-framework/pull/7372#discussion_r81019576.

**Comment by wvu-r7** [comment]
# Release Notes

This replaces a particular ```cmd_exec``` anti-pattern in a few modules with the correct ```read_file``` call.

**Pull request merged**
