### PR TITLE
run msfconsole as non root user in docker

### PR DESCRIPTION
**Pull request by firefart**
This is based on the work of @ilyaglow in https://github.com/rapid7/metasploit-framework/pull/8308

### CODE REVIEW

**Comment by ilyaglow** [comment]
You rock @FireFart!

It should be noted that at first I cloned clean metasploit-framework repo as root and got:
```
ruby: Permission denied -- ./msfconsole (LoadError)
````
But if clone as regular user everything run smoothly.

**Comment by busterb** [comment]
That's a neat idea - I think I might apply it to some non-docker environments as well!

**Comment by FireFart** [comment]
@busterb any chance to get this merged?

**Comment by busterb** [comment]
Yep, sorry we've been distracted with BSides Austin prep this week largely.

**Comment by busterb** [comment]
## Release Notes

This adds Linux capabilities to provide the ability to capture raw network traffic and bind to privileged TCP ports from Metasploit Framework without running as a root user from within a Docker image.

**Comment by busterb** [comment]
Thanks @FireFart & @ilyaglow !

**Comment by chocohub1** [comment]
thanks a million!

Marcus Harris

**Pull request merged**
