### PR TITLE
Fix incorrect check when verifying that users exist within the nwauth.add file

### PR DESCRIPTION
**Pull request by Ryuuuuu**
## Summary
when i use this module it prints always vulnerable and try to save Credential file like this.
but in Credential file, there is no info in it.

```
msf6 auxiliary(scanner/elasticsearch/indices_enum) > use auxiliary/scanner/http/surgenews_user_creds
msf6 auxiliary(scanner/http/surgenews_user_creds) > set RHOSTS 192.168.138.129
RHOSTS => 192.168.138.129
msf6 auxiliary(scanner/http/surgenews_user_creds) > run


SurgeNews User Credentials
==========================

 Username  Password  Password Hash  Admin
 --------  --------  -------------  -----

[+] Credentials saved in: /home/ryuuu/.msf4/loot/20230412061400_default_192.168.138.129_surgenews.user.c_324598.txt
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

I don't know much about this vulnerability, but I think exception handling is wrong when user is nil

i fixed that point.

### CODE REVIEW

**Comment by bcoles** [comment]
This is not the correct fix for this issue. The following is a more suitable fix:

```diff
diff --git a/modules/auxiliary/scanner/http/surgenews_user_creds.rb b/modules/auxiliary/scanner/http/surgenews_user_creds.rb
index acafff148e..dc31f3495a 100644
--- a/modules/auxiliary/scanner/http/surgenews_user_creds.rb
+++ b/modules/auxiliary/scanner/http/surgenews_user_creds.rb
@@ -149,12 +149,13 @@ class MetasploitModule < Msf::Auxiliary
 
     # Read user credentials from nwauth.add
     users = parse_user_db read_file 'nwauth.add'
-    if users.nil?
+    if users.blank?
       vprint_error 'Found no user credentials in nwauth.add'
-    else
-      vprint_status "Found #{users.length} users in nwauth.add"
+      return
     end
 
+    vprint_status "Found #{users.length} users in nwauth.add"
+
     users.each do |user|
       next if user.empty?
````

**Comment by Ryuuuuu** [comment]
>I changed it to the code you suggested. if there is any other problem, please tell me

**Comment by Ryuuuuu** [comment]
> This is not the correct fix for this issue. The following is a more suitable fix:
> 
> ```diff
> diff --git a/modules/auxiliary/scanner/http/surgenews_user_creds.rb b/modules/auxiliary/scanner/http/surgenews_user_creds.rb
> index acafff148e..dc31f3495a 100644
> --- a/modules/auxiliary/scanner/http/surgenews_user_creds.rb
> +++ b/modules/auxiliary/scanner/http/surgenews_user_creds.rb
> @@ -149,12 +149,13 @@ class MetasploitModule < Msf::Auxiliary
>  
>      # Read user credentials from nwauth.add
>      users = parse_user_db read_file 'nwauth.add'
> -    if users.nil?
> +    if users.blank?
>        vprint_error 'Found no user credentials in nwauth.add'
> -    else
> -      vprint_status "Found #{users.length} users in nwauth.add"
> +      return
>      end
>  
> +    vprint_status "Found #{users.length} users in nwauth.add"
> +
>      users.each do |user|
>        next if user.empty?
> ```



> This is not the correct fix for this issue. The following is a more suitable fix:
> 
> ```diff
> diff --git a/modules/auxiliary/scanner/http/surgenews_user_creds.rb b/modules/auxiliary/scanner/http/surgenews_user_creds.rb
> index acafff148e..dc31f3495a 100644
> --- a/modules/auxiliary/scanner/http/surgenews_user_creds.rb
> +++ b/modules/auxiliary/scanner/http/surgenews_user_creds.rb
> @@ -149,12 +149,13 @@ class MetasploitModule < Msf::Auxiliary
>  
>      # Read user credentials from nwauth.add
>      users = parse_user_db read_file 'nwauth.add'
> -    if users.nil?
> +    if users.blank?
>        vprint_error 'Found no user credentials in nwauth.add'
> -    else
> -      vprint_status "Found #{users.length} users in nwauth.add"
> +      return
>      end
>  
> +    vprint_status "Found #{users.length} users in nwauth.add"
> +
>      users.each do |user|
>        next if user.empty?
> ```

I changed it to the code you suggested. If threre is any other problems, please tell me

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
Changes look good but I'm guessing RuboCop may be complaining due to you removing some characters at the end of the file. Will give this a crack and try to see if I can fix that so long.

**Comment by gwillcox-r7** [comment]
# Release Notes
A bug has been fixed in the `modules/auxiliary/scanner/http/surgenews_user_creds.rb` module whereby the code did not properly check if there were no users in the `nwauth.add` file prior to proceeding to operate on it.

**Pull request merged**
