### PR TITLE
Removing kissfft.gemspec file since it shouldn't be necessary

### PR DESCRIPTION
**Pull request by cdoughty-r7**
#### Description:

This file shouldn't be necessary and is actually causing some issues in our package migration.

Requesting that we remove this file from the repo.

### CODE REVIEW

**Comment by cdoughty-r7** [comment]
@bcook-r7  Here's the change we discussed.

**Comment by jlee-r7** [comment]
Do we need this library at all?  I can't find anything that uses it.  If we really do need it, perhaps it should be brought in with bundler just like everything else instead of copied into `external/`.

@hmoore-r7 you look like the initial committer, what is this for?

**Comment by bcook-r7** [comment]
It doesn't appear to have been used or touched in 3 years, and of course will remain in the git history. I vote that we delete it.

**Comment by hmoore-r7** [comment]
Original reason for it was to implement wardialing capabilities with tone analysis within Metasploit. This got as a far as IAX2 being moved to Rex and a dialer added, but not analysis.

**Comment by hmoore-r7** [comment]
This can be removed from the framework source since it is in its own repo now: https://github.com/rapid7/ruby-kissfft

**Comment by bcook-r7** [comment]
I went ahead and removed entirely in #6060, will land now.

**Pull request closed without merging**
