### PR TITLE
Enable usage of usernames in cred collections

### LINKED ISSUE #12274: metasploit issue ActiveRecord::RecordInvalid
## Steps to reproduce

hello . I have an issue  , it happened when I was trying to do login bruteforce by "smb-login 
I do not know why is that ,so  I tried  many solutions that I fond on the internet none of them work ,even I tried to remove the Metasploit than install it again that also dose not work . in addition , the password and the user name are include in the lists that I'm using . 
last time it was working , I was running  bruteforce attack for first time it worked successfully , but I did not  save it so I run it again to crack  it  but it showed me that no password and user found , that is weird because  the password and username on the list files ,and it work for the fist one but not this time .
## Expected behavior
gives the correct password and user  
What should happen?
I should crak the password and the username  because the correct user and pass include in my list 
## Current behavior
it tried the first user on my list that  shows me this massage    "ActiveRecord::RecordInvalid Validation failed: Last attempted at can't be nil if status is tried "
What happens instead?

I'm user 
-Debian 5.2.9-2kali1 (2019-08-22)
 -metasploit v5.0.43-dev 

ruby : ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

### I installed Metasploit with:
- [* ] Kali package via apt

### OS
Debian 5.2.9-2kali1 (2019-08-22)
What OS are you running Metasploit on?
kali linux

Screenshot 2019-09-02 21 17 06

Screenshot 2019-09-03 22 15 24

### PR DESCRIPTION
**Pull request by space-r7**
This adds two methods that will allow a user to use stored usernames in the database with login scanner modules Ex. `auxiliary/scanner/smb/smb_login`. PR #12929 relies on this due to the stored usernames not being added to the credential_collection that is created to scan with.

This also fixes #12274 by setting `last_attempted_at` in `smb_login`.

## Verification

- [x] Start `msfconsole`
- [x] Add some user names to the database
- [x] Use `auxiliary/scanner/smb/smb_login`
- [x] Set `DB_ALL_USERS` true
- [ ] Set `SMBPASS` PASSWORD
- [ ] **Verify** that the usernames are included in the scanner's `cred_collection`
- [ ] **Verify** that the following errors are not in the module's output:

```
Error: 192.168.37.158: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank 
```

```
ActiveRecord::RecordInvalid Validation failed: Last attempted at can't be nil if status is tried
```

## Scenarios

On `master`:

```
msf5 > creds add user:test_user
msf5 > creds add user:another_user
msf5 > creds add user:administrator
msf5 > use smb_login

Matching Modules
================

   #  Name                             Disclosure Date  Rank    Check  Description
   -  ----                             ---------------  ----    -----  -----------
   0  auxiliary/scanner/smb/smb_login                   normal  No     SMB Login Check Scanner


[*] Using auxiliary/scanner/smb/smb_login
msf5 auxiliary(scanner/smb/smb_login) > set rhosts 192.168.37.158
rhosts => 192.168.37.158
msf5 auxiliary(scanner/smb/smb_login) > set smb_pass password
smb_pass => password
msf5 auxiliary(scanner/smb/smb_login) > set db_all_users true
db_all_users => true
msf5 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.37.158:445    - 192.168.37.158:445 - Starting SMB login bruteforce
[*] 192.168.37.158:445    - Error: 192.168.37.158: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SMB)
[*] 192.168.37.158:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_login) > edit
msf5 auxiliary(scanner/smb/smb_login) > rerun
[*] Reloading module...

[*] 192.168.37.158:445    - 192.168.37.158:445 - Starting SMB login bruteforce

From: /Users/space/metasploit-framework/modules/auxiliary/scanner/smb/smb_login.rb @ line 117 Msf::Modules::Auxiliary__Scanner__Smb__Smb_login::MetasploitModule#run_host:

    112: 
    113:     cred_collection = prepend_db_passwords(cred_collection)
    114:     cred_collection = prepend_db_hashes(cred_collection)
    115:     require 'pry';binding.pry
    116: 
 => 117:     @scanner.cred_details = cred_collection
    118: 
    119:     @scanner.scan! do |result|
    120:       case result.status
    121:       when Metasploit::Model::Login::Status::LOCKED_OUT
    122:         if datastore['ABORT_ON_LOCKOUT']

[1] pry(#<Msf::Modules::Auxiliary__Scanner__Smb__Smb_login::MetasploitModule>)> cred_collection
=> #<Metasploit::Framework::CredentialCollection:0x00007fd91a419c68
 @additional_privates=[],
 @additional_publics=[],
 @blank_passwords=false,
 @pass_file=nil,
 @password="",
 @prepended_creds=[],
 @realm=".",
 @user_as_pass=false,
 @user_file=nil,
 @username="",
 @userpass_file=nil>
[2] pry(#<Msf::Modules::Auxiliary__Scanner__Smb__Smb_login::MetasploitModule>)> exit
[*] 192.168.37.158:445    - Error: 192.168.37.158: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SMB)
[*] 192.168.37.158:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

With changes:

```
msf5 > creds
Credentials
===========

host  origin  service  public         private  realm  private_type  JtR Format
----  ------  -------  ------         -------  -----  ------------  ----------
                       test_user                                    
                       another_user                                 
                       administrator                                

msf5 > use smb_login

Matching Modules
================

   #  Name                             Disclosure Date  Rank    Check  Description
   -  ----                             ---------------  ----    -----  -----------
   0  auxiliary/scanner/smb/smb_login                   normal  No     SMB Login Check Scanner


[*] Using auxiliary/scanner/smb/smb_login
msf5 auxiliary(scanner/smb/smb_login) > edit
msf5 auxiliary(scanner/smb/smb_login) > git diff
[*] exec: git diff

diff --git a/modules/auxiliary/scanner/smb/smb_login.rb b/modules/auxiliary/scanner/smb/smb_login.rb
index 0fbd2cf7f1..761f13aa72 100644
--- a/modules/auxiliary/scanner/smb/smb_login.rb
+++ b/modules/auxiliary/scanner/smb/smb_login.rb
@@ -112,6 +112,8 @@ class MetasploitModule < Msf::Auxiliary
 
     cred_collection = prepend_db_passwords(cred_collection)
     cred_collection = prepend_db_hashes(cred_collection)
+    cred_collection = prepend_db_usernames(cred_collection)
+    require 'pry';binding.pry
 
     @scanner.cred_details = cred_collection
 
msf5 auxiliary(scanner/smb/smb_login) > reload
[*] Reloading module...
msf5 auxiliary(scanner/smb/smb_login) > set rhosts 192.168.37.158
rhosts => 192.168.37.158
msf5 auxiliary(scanner/smb/smb_login) > set db_all_users true
db_all_users => true
msf5 auxiliary(scanner/smb/smb_login) > set smbpass password
smbpass => password
msf5 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.37.158:445    - 192.168.37.158:445 - Starting SMB login bruteforce

From: /Users/space/metasploit-framework/modules/auxiliary/scanner/smb/smb_login.rb @ line 118 Msf::Modules::Auxiliary__Scanner__Smb__Smb_login::MetasploitModule#run_host:

    113:     cred_collection = prepend_db_passwords(cred_collection)
    114:     cred_collection = prepend_db_hashes(cred_collection)
    115:     cred_collection = prepend_db_usernames(cred_collection)
    116:     require 'pry';binding.pry
    117: 
 => 118:     @scanner.cred_details = cred_collection
    119: 
    120:     @scanner.scan! do |result|
    121:       case result.status
    122:       when Metasploit::Model::Login::Status::LOCKED_OUT
    123:         if datastore['ABORT_ON_LOCKOUT']

[1] pry(#<Msf::Modules::Auxiliary__Scanner__Smb__Smb_login::MetasploitModule>)> cred_collection
=> #<Metasploit::Framework::CredentialCollection:0x00007fb1df87fb98
 @additional_privates=[],
 @additional_publics=["test_user", "another_user", "administrator"],
 @blank_passwords=false,
 @pass_file=nil,
 @password="password",
 @prepended_creds=[],
 @realm=".",
 @user_as_pass=false,
 @user_file=nil,
 @username="",
 @userpass_file=nil>
[2] pry(#<Msf::Modules::Auxiliary__Scanner__Smb__Smb_login::MetasploitModule>)> exit
[-] 192.168.37.158:445    - 192.168.37.158:445 - Failed: '.\test_user:password',
[-] 192.168.37.158:445    - 192.168.37.158:445 - Failed: '.\another_user:password',
[+] 192.168.37.158:445    - 192.168.37.158:445 - Success: '.\administrator:password' Administrator
[*] 192.168.37.158:445    - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_login) > 
```

### CODE REVIEW

**Review by smcintyre-r7 — APPROVED** [review]
Reviewed the changes and they all look good. I have no comments regarding them, so I'm moving on to testing now.

**Comment by smcintyre-r7** [comment]
Verified that I can reproduce the original issue and that the proposed changes fix it. I'll merge this in momentarily. Thanks @space-r7 !

**Before the patch**
```
msf5 auxiliary(scanner/smb/smb_login) > show options 

Module options (auxiliary/scanner/smb/smb_login):

   Name               Current Setting  Required  Description
   ----               ---------------  --------  -----------
   ABORT_ON_LOCKOUT   false            yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS    false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED   5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS       false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS        false            no        Add all passwords in the current database to the list
   DB_ALL_USERS       true             no        Add all users in the current database to the list
   DETECT_ANY_AUTH    false            no        Enable detection of systems accepting any authentication
   DETECT_ANY_DOMAIN  false            no        Detect if domain is required for the specified user
   PASS_FILE                           no        File containing passwords, one per line
   PRESERVE_DOMAINS   true             no        Respect a username that contains a domain name.
   Proxies                             no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST       false            no        Record guest-privileged random logins to the database
   RHOSTS             192.168.159.138  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT              445              yes       The SMB service port (TCP)
   SMBDomain          .                no        The Windows domain to use for authentication
   SMBPass            Password1        no        The password for the specified username
   SMBUser                             no        The username to authenticate as
   STOP_ON_SUCCESS    false            yes       Stop guessing when a credential works for a host
   THREADS            1                yes       The number of concurrent threads (max one per host)
   USERPASS_FILE                       no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS       false            no        Try the username as the password for all users
   USER_FILE                           no        File containing usernames, one per line
   VERBOSE            true             yes       Whether to print output for all attempts

msf5 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.159.138:445   - 192.168.159.138:445 - Starting SMB login bruteforce
[*] 192.168.159.138:445   - Error: 192.168.159.138: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SMB)
[*] 192.168.159.138:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_login) >
```

**After the patch**
```
msf5 auxiliary(scanner/smb/smb_login) > show options 

Module options (auxiliary/scanner/smb/smb_login):

   Name               Current Setting  Required  Description
   ----               ---------------  --------  -----------
   ABORT_ON_LOCKOUT   false            yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS    false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED   5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS       false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS        false            no        Add all passwords in the current database to the list
   DB_ALL_USERS       true             no        Add all users in the current database to the list
   DETECT_ANY_AUTH    false            no        Enable detection of systems accepting any authentication
   DETECT_ANY_DOMAIN  false            no        Detect if domain is required for the specified user
   PASS_FILE                           no        File containing passwords, one per line
   PRESERVE_DOMAINS   true             no        Respect a username that contains a domain name.
   Proxies                             no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST       false            no        Record guest-privileged random logins to the database
   RHOSTS             192.168.159.138  yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT              445              yes       The SMB service port (TCP)
   SMBDomain          .                no        The Windows domain to use for authentication
   SMBPass            Password1        no        The password for the specified username
   SMBUser                             no        The username to authenticate as
   STOP_ON_SUCCESS    false            yes       Stop guessing when a credential works for a host
   THREADS            1                yes       The number of concurrent threads (max one per host)
   USERPASS_FILE                       no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS       false            no        Try the username as the password for all users
   USER_FILE                           no        File containing usernames, one per line
   VERBOSE            true             yes       Whether to print output for all attempts

msf5 auxiliary(scanner/smb/smb_login) > run

[*] 192.168.159.138:445   - 192.168.159.138:445 - Starting SMB login bruteforce
[+] 192.168.159.138:445   - 192.168.159.138:445 - Success: '.\jdoe:Password1'
[-] 192.168.159.138:445   - 192.168.159.138:445 - Failed: '.\test_user:Password1',
[-] 192.168.159.138:445   - 192.168.159.138:445 - Failed: '.\another_user:Password1',
[*] 192.168.159.138:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/smb/smb_login) >
```

**Comment by space-r7** [comment]
Thanks, @smcintyre-r7!

**Comment by smcintyre-r7** [comment]
# Release Notes
This PR updates login scanners to work with usernames stored in the database and sets the `last_attempted_at` value in `scanner/smb/smb_login`.

**Pull request merged**
