### PR TITLE
Fix #9232 corruption of non-latin characters in W methods

### LINKED ISSUE #9232: Railgun does not handle wide char strings
## Steps to reproduce

0. On Linux/MSF system: `apt install fonts-indic` then close all terminal windows and open a new one
1. Start a handler
2. Make a reverse meterpreter payload, name it नमस्ते.exe and run it on a Windows box
3. In the meterpreter prompt, run `irb`
4. Run `client.railgun.kernel32._library.add_function('QueryFullProcessImageNameW', 'BOOL',[["DWORD","hProcess","in"],["DWORD","dwFlags","in"],["PWCHAR","lpExeName","out"],["PDWORD","lpdwSize","inout"],])
puts client.railgun.kernel32.QueryFullProcessImageNameW(0xFFFFFFFF,0,260,260)['lpExeName']`

## Expected behavior

Your process name is properly displayed

## Current behavior

The terminal vomits

### Metasploit version

4.16.17-dev

### I installed Metasploit with:
- [ ] Kali package via apt (on this box anyway)

### PR DESCRIPTION
**Pull request by scriptjunkie**
Fix corruption of non-latin characters in W methods

## Verification

Same as #9232

### CODE REVIEW

**Comment by bwatters-r7** [comment]
Why do we need to install the fonts?  The linux terminal should be able to display them if they are encoded properly?

**Comment by busterb** [comment]
Yes. Or if you run Metasploit within Powershell ISE, it also miraculously has utf-8 support in the terminal out of the box.

**Comment by scriptjunkie** [comment]
The linux terminal in the Kali VM I was testing displayed boxes since it did not have those fonts by default. YMMV. That part of course isn't a metasploit issue, just something worth checking while validating.

**Comment by bwatters-r7** [comment]
It is not working for me:
```
tmoose@ubuntu:~/rapid7/metasploit-framework$ ./msfvenom -p windows/x64/meterpreter/reverse_tcp -f exe -o नमस्ते.exe LHOST=192.168.135.111 LPORT=4567
```
```
meterpreter > sysinfo
Computer        : WIN10X64-1703
OS              : Windows 10 (Build 15063).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > irb
[*] Starting IRB shell
[*] The "client" variable holds the meterpreter client
>> client.railgun.kernel32._library.add_function('QueryFullProcessImageNameW', 'BOOL',[["DWORD","hProcess","in"],["DWORD","dwFlags","in"],["PWCHAR","lpExeName","out"],["PDWORD","lpdwSize","inout"],])
=> #<Rex::Post::Meterpreter::Extensions::Stdapi::Railgun::LibraryFunction:0x000000000cc5fb00 @return_type="BOOL", @params=[["DWORD", "hProcess", "in"], ["DWORD", "dwFlags", "in"], ["PWCHAR", "lpExeName", "out"], ["PDWORD", "lpdwSize", "inout"]], @remote_name="QueryFullProcessImageNameW", @calling_conv="stdcall">
>> puts client.railgun.kernel32.QueryFullProcessImageNameW(0xFFFFFFFF,0,260,260)['lpExeName']
䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁䅁
```

**Comment by scriptjunkie** [comment]
My initial guess is that you need to be in a 32-bit process for 0xFFFFFFFF to work. For a 64-bit process you'd need 0xFFFFFFFFFFFFFFFF to represent the current process pseudo-handle (HANDLE)-1

**Comment by bwatters-r7** [comment]
# Release notes
This PR fixes an issue where unicode filenames got mangled in railgun.

**Pull request merged**
