### PR TITLE
reporting creds can have linked task

### PR DESCRIPTION
**Pull request by jmartin-tech**
When reporting creds the credential model will link to a task provided by `task_id`.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [ ] **Verify** #11695 steps still validate

### CODE REVIEW

**Comment by jmartin-r7** [comment]
Future changes may be desired to pass the `Task` itself and update `metasploit-credential` gem as a breaking api change.

**Comment by h00die** [comment]
does this solve https://github.com/h00die/metasploit-framework/issues/13 as well?

**Comment by jmartin-r7** [comment]
@h00die unfortunately not the task is not involved in https://github.com/h00die/metasploit-framework/issues/13, however since I am working in that area I have things setup to be able to dig into that more now.

**Comment by pbarry-r7** [comment]
Testing via the examples in the module docs in #11695 looks good!  👏 

Are we concerned about the Travis failures related to "swtich" device spec credentials tests...?

**Comment by jmartin-r7** [comment]
Sorry missed those... looks like tests need update will complete shortly.

**Comment by pbarry-r7** [comment]
All looks good, will land...!

**Comment by pbarry-r7** [comment]
## Release Notes

When reporting creds, also set the associated task_id if one is present.

**Pull request merged**
