### PR TITLE
New auxiliary

### PR DESCRIPTION
**Pull request by SaxHornet**
Hello,
I make an auxiliary , but I have a problem with the parsing in JSON and I don't know how to correct it by myself.I give you the code and the errors in attached with this message. 

Best Wishes

Drx

## Where to put the code

Copy the code in this path : /../metasploit-framework/modules/auxiliary/gather

## How to run my module

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/gather/censys_search 
- [ ] set CenSYS_APIKEY
- [ ] set query < what you want>
- [ ] run

## The errors

[-] Call stack:
[-]   /usr/lib/ruby/vendor_ruby/json/common.rb:156:in `parse'
[-]   /usr/lib/ruby/vendor_ruby/json/common.rb:156:in `parse'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/json/decoding.rb:26:in `decode'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/censys_search.rb:66:in `censys_query'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/censys_search.rb:106:in `run'

## The Code##
[auxiliary.txt](https://github.com/rapid7/metasploit-framework/files/783795/auxiliary.txt)

### CODE REVIEW

**Comment by busterb** [comment]
Hi. Take a look at the existing censys module:

modules/auxiliary/gather/censys_search.rb

I'd suggest enhancing that module before creating a new one. Thanks!

**Comment by busterb** [comment]
If you need help writing a new module, also we suggest dropping in on #metasploit on IRC rather than using the github PR mechanism this way.

**Comment by Drx51** [comment]
hy,
Thanks for your answer. Ah ok. I didn't see that it exists. Sorry. 
That's why I make it

**Comment by Drx51** [comment]
I've tried the module and it doesn't work for me. 

I've got this error : 

-] Auxiliary failed: NoMethodError undefined method `each' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/censys_search.rb:98:in `parse_certificates'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/censys_search.rb:75:in `search'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/censys_search.rb:168:in `run

**Comment by Drx51** [comment]
And an other question, could you help me to resolve my pb of my script ? my parsing. 

Thanks in advance

**Pull request closed without merging**
