### PR TITLE
send_sms + wlan_geolocate

### PR DESCRIPTION
**Pull request by Jack64**
Added WiFi-based geolocation for android.
Added send_sms extension for android.
(Payload @ https://github.com/rapid7/metasploit-payloads/pull/12)

DEMO:

```
Android Commands
================

    Command         Description
    -------         -----------
    check_root      Check if device is rooted
    dump_calllog    Get call log
    dump_contacts   Get contacts list
    dump_sms        Get sms messages
    geolocate       Get current lat-long using geolocation
    send_sms        Sends SMS from target session
    wlan_geolocate  Get current lat-long using WLAN information

meterpreter > wlan_geolocate 
[*] Google indicates that the target is within 150 meters of XX.XXXXXX,-X.XXXXXXX.
[*] Google Maps URL:  https://maps.google.com/?q=XX.XXXXXX,-X.XXXXXX
meterpreter > send_sms 
[-] You must enter both a destination address -d and the SMS text body -t
[-] e.g. send_sms -d +351961234567 -t "GREETINGS PROFESSOR FALKEN."

OPTIONS:

    -d <opt>  Destination number
    -dr        Wait for delivery report
    -h        Help Banner
    -t <opt>  SMS body text


meterpreter > send_sms -dr -d XXXXXXXXX -t "Hello World"
[+] SMS sent - Transmission successful
[+] SMS delivered - Transmission successful
```

### CODE REVIEW

**Comment by bcook-r7** [comment]
metasploit-payloads-1.0.8 has the required functionality - mind giving it a shot to make sure it still works for you?

**Comment by busterb** [comment]
I have a bunch of fixes for this that I've been working on. Almost done with the last one.

**Comment by Jack64** [comment]
Waiting for it... :)

**Comment by busterb** [comment]
It got a little more extensive because I found a few bugs running the original wlan_geolocate module as well. Changes made:

 - 3aab9aa : Moved embedded sample code to tools
 - 3615bd0 : limited number of BSSIDs sent to google, it fails if there are too many sent at once.
 - f4031d8 422bba8 : style cleanups
 - 875ac28 : properly handle waiting for commands to return (fixes wlan_geolocate on OS X through meterpreter)
 - 1db376b : fix a race closing processes in python meterpreter that hangs channels
 - 9720e8e : make sure darwin = osx when checking the OS

Thanks Jack64!

**Comment by Jack64** [comment]
Thank you, sir !

**Pull request merged**
