### PR TITLE
Add KB for post/windows/gather/enum_ie

### LINKED ISSUE #7146: Add KB for post/windows/gather/enum_ie
Add KB for post/windows/gather/enum_ie

For instructions on how to write documentation for modules, see https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation.

### PR DESCRIPTION
**Pull request by daniel-wer**
Resolves #7146. This PR adds the KB for post/windows/gather/enum_ie.

FWIW while writing the documentation and doing some testing I noticed that this module does not work for IE Version 11.0 on Windows 7 as the paths to the history data and so on seem to be different.

## Verification

- [x] No typos
- [x] Factually correct
- [x] Nothing important missing

### CODE REVIEW

**Comment by h00die** [comment]
This looks good to me, although I'd like to see an ie7+ in there as well since I think its more likely (especially in the future) to see such, as well as there's added functionality that would be good to see the output for.
That doesn't necessarily have to be in this PR, could always land this and put in a second w/ that added run!

**Comment by daniel-wer** [comment]
Good point, I'll spin up a VM and add an ie7+ run!

**Comment by h00die** [comment]
looks good to me, I'm going to learn to merge in the next day or two, and this will be the second one I ever do!

**Comment by h00die** [comment]
# Release Notes

This patch adds markdown docs for the post/windows/gather/enum_ie module.

**Pull request merged**
