### PR TITLE
Add TLV_TYPE_FILE_HASH

### PR DESCRIPTION
**Pull request by timwr**
This change adds a raw (not String) TLV_TYPE_FILE_HASH type.
This is because you can't losslessly convert from UTF-8 to binary back and forth, as discussed here:
https://github.com/rapid7/metasploit-javapayload/pull/29

This change depends on:
https://github.com/rapid7/meterpreter/pull/157
and
https://github.com/rapid7/metasploit-javapayload/pull/32

To verify this change you will need to run the post/test/meterpreter module on a every type of meterpreter session (java, linux/86, python, php). e.g:

```
loadpath test/modules
use post/test/meterpreter
run
```

### CODE REVIEW

**Comment by timwr** [comment]
Couple of things:
- The high level point of this pull request is to fix UTF-8 filenames on the java/android meterpreter (https://github.com/rapid7/metasploit-framework/issues/4954). I couldn't find a simpler way of doing this.
- post/test/meterpreter is currently failing on Android, see https://github.com/rapid7/metasploit-javapayload/issues/33
- No rush to merge this, it has potential to break everything for the sake of fixing a minor bug fix (lack of Unicode filenames in java/android).

**Comment by hmoore-r7** [comment]
Makes the most sense for Brent to coordinate this

**Comment by bcook-r7** [comment]
Sounds like the right fix. I couldn't see a way in Java to convert just a single return value either without changing it for the entire type.

**Comment by busterb** [comment]
I added backward-compatibility for meterpreter sessions that are already running: 93ba08738c219bba33940fa1f92026ca266e724b. The rest of the payloads will land in another PR, but it works fine in the mean time.

**Comment by timwr** [comment]
Nice one @busterb 
thanks!

**Pull request merged**
