### PR TITLE
Bug/ms 899/string sql eager load

### PR DESCRIPTION
**Pull request by farias-r7**
MS-899

DEPRECATION WARNING: It looks like you are eager loading table(s) that are referenced in a string SQL snippet.
# Verification Steps
## `metasploit_data_models`
- [ ] Complete [Verification Steps for `metasploit_data_models`](https://github.com/rapid7/metasploit_data_models/pull/150)
## `metasploit-framework`
- [ ] `bundle install`
### `rake spec`
- [ ] `rake spec`
- [ ] VERIFY no failures
### `rake cucumber`
- [ ] `rake cucumber cucumber:boot`
- [ ] VERIFY no failures
# Pre-merge Steps
## Updating metasploit_data_models
- [ ] Complete [Release for `metasploit_data_models`](https://github.com/rapid7/metasploit_data_models/pull/85#issue-53195463)
- [ ] Change the `metasploit_data_models` version in `metasploit-framework-db.gemspec` to released version: `spec.add_runtime_dependency 'metasploit_data_models', '~> 2.0.0'`
- [ ] Remove `metasploit_data_models` from `Gemfile`.
## Test changes
- [ ] `bundle install`
- [ ] `rake spec`
- [ ] VERIFY no failures
## Commit & Push update
- [ ] `git commit -a`
- [ ] `git push`

### CODE REVIEW

**Comment by OJ** [comment]
Is this in need of a rebase/merge?

**Comment by bcook-r7** [comment]
Yeah - @farias-r7 it looks like something went wrong with your PR. I can help you sort it out.

**Comment by bcook-r7** [comment]
Closing for now, that'll be easier.

**Comment by bcook-r7** [comment]
aha, the base branch is way out of date, will fix that

**Pull request closed without merging**
