### PR TITLE
Update banner for MSF5

### PR DESCRIPTION
**Pull request by jeffmcjunkin**
Tiny update to one of my favorite banners. Mostly I want to get used to the process of sending PR's to the upstream repo.

Before:
image

### CODE REVIEW

**Comment by jeffmcjunkin** [comment]
After: 
image

**Comment by wvu-r7** [comment]
Hah, I love it. Good eye.

**Review by wvu — APPROVED** [review]

**Comment by wvu-r7** [comment]
# Release Notes

This updates the `null-pointer-deref.txt` banner to MSF5.

**Comment by jeffmcjunkin** [comment]
Woot! Y'all are awesome, thanks for the quick response :+1:

**Pull request merged**
