### PR TITLE
Orchestrator variable decrypt

### PR DESCRIPTION
**Pull request by rindert-fox**
It is possible to store variables with encrypted content within Microsoft's System Center Orchestrator. The encryption key is stored in the SYS table. If you have access to the SYS table it is possible to decrypt the secret variables. Since these kind of variables are used for storing credentials this usable information for hackers and security researchers.
Integrated authentication will be used unless DBA_USERNAME and DBA_PASSWORD are specified.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] Create meterpreter session on server with access to Orchestrator database
- [ ] Make sure the meterpreter runs under a user account with read access to the Orchestrator database and the SYS database
- [ ] `use post/windows/gather/orchestrator_secret_variables_decrypt`
- [ ] run
- [ ] **Verify** result:
msf_output
- [ ] Blogpost: https://blog.fox-it.com/2018/05/09/introducing-orchestrator-decryption-tool/

### CODE REVIEW

**Comment by asoto-r7** [comment]
Orchestrator is part of Microsoft System Center 2012, which requires Windows 2008 R2 SP1, and is available for download [directly from Microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=40842).

@rindert-fox:  Thanks for contributing, and sorry for the delay.  @bwatters-r7 and I are eager to see this landed!  Would you mind submitting some documentation alongside this request?  It would help us configure the environment for testing, as well as demonstrate how everything works.  We ask that you submit a Markdown file, but here's a [starter template](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md) and some [instructions](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation).

**Comment by bwatters-r7** [comment]
I have spent a few hours trying to get a test environment together.  It all ended in tears.  The evaluation download here requires a domain and is in hyper-V format, so you need a hyper-v machine and a DC to connect to.  After building both, the eval VM it still does not work as expected.

**Comment by rindert-fox** [comment]
Hi @asoto-r7 , @bwatters-r7 ,

I will create some documentation about setting up a test environment probably in the next few weeks.
In the meantime; the evaluation download is in VHD format. You don't need HyperV for that; you can mount the VHD as harddrive in a new virtual machine in VMWare. To do that; create a new VM without harddrive and add the VHD as harddrive once the VM has been created.

The evaluation version should run fine after that. To develop the module I created a meterpreter session on the orchestrator evaluation server to my pentest machine. No need for a domain controller, unless the  SQL server was configured to use AD authentication. If I recall correctly, it defaults to integrated login. That means that having a meterpreter running under the local admin user account should suffice.

**Comment by bwatters-r7** [comment]
OK, FWIW, I tried to launch the SC vm without adding it to a domain, and it claimed my password was wrong, despite providing it during setup.  I assumed it needed a password store from a domain controller, so I added a DC and used that as the password.  It still says my password is wrong.  The documentation says pretty clearly that you log in with the domain credentials.  If the instructions are wrong, let me know.

**Comment by bwatters-r7** [comment]
@rindert-fox any update on the docs for setting up a test machine?

**Pull request closed without merging**
