### PR TITLE
iis_shortname fixes

### PR DESCRIPTION
**Pull request by L-codes**
No Threads in datastore

### CODE REVIEW

**Review by bcoles — APPROVED** [review]

**Comment by bcoles** [comment]
I think (?) this shouldn't be a problem, as the `datastore` options are case insensitive. Merging.

**Comment by L-codes** [comment]
> I think (?) this shouldn't be a problem, as the `datastore` options are case insensitive. Merging.

My `osx` `datastore` options are case sensitive
```datastore['Threads'] #=> nil```

**Comment by bcoles** [comment]
lame

**Comment by bcoles** [comment]
### Release Notes

This PR fixes incorrect capitalization used for a `datastore` option in the iis_shortname_scanner module.

**Comment by busterb** [comment]
I think this issue only occurs if the datastore option is not registered in the first place. Consider registering THREADS and it will do the correct thing.

I looked into making all datastore options normalized, even if they were not registered, but this caused some rspec tests fail. The tests are likely making an incorrect assertion.

**Comment by bcoles** [comment]
> 
> 
> I think this issue only occurs if the datastore option is not registered in the first place. Consider registering THREADS and it will do the correct thing.
> 
> I looked into making all datastore options normalized to be case-insensitive, even if they were not registered, but this caused some rspec tests fail. The tests are likely making an incorrect assertion.

But... the `THREADS` datastore option *is* registered:

```ruby
    register_options([
      Opt::RPORT(80),
      OptString.new('PATH', [ true, "The base path to start scanning from", "/" ]),
      OptInt.new('THREADS', [ true, "Number of threads to use", 20])
    ])
```

**Comment by busterb** [comment]
Hmm, that's different. Let's fix that.

**Comment by busterb** [comment]
Updated #11027 to just revert the two extra datastore commits that went in last week, since they weren't needed to fix the original problem with unregister not deleting aliases. That fixes the root cause here too . There's still an issue with unregistered options becoming case-sensitive, but I made #11026 for that.

**Pull request merged**
