### PR TITLE
Fix msfdb init command failure when opting not to initialize webservices

### LINKED ISSUE #15981: msfdb init fails with error when choosing to not init webservice
## Steps to reproduce

How'd you do it?

1. Install MSF on windows 10 using latest MSI installer
2. MSF BIN directory added to `%PATH%`
2. Run `msfdb init`
3. when asked to init webservice pick no

## Were you following a specific guide/tutorial or reading documentation?
No

## Expected behavior

The init script should continue to init databse

## Current behavior

Init script fails with the following error:
```
Clearing http web data service credentials in msfconsole
E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - ./msfconsole -qx 'db_disconnect --clear; exit' (Errno::ENOENT)
        from E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
        from E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:398:in `capture2e'
        from E:/metasploit-framework/embedded/framework/lib/msfdb_helpers/db_interface.rb:55:in `run_cmd'
        from E:/metasploit-framework/bin/../embedded/framework/msfdb:653:in `run_msfconsole_command'
        from E:/metasploit-framework/bin/../embedded/framework/msfdb:672:in `clear_default_data_service'
        from E:/metasploit-framework/bin/../embedded/framework/msfdb:1067:in `<main>'
```

### Metasploit version

Framework: 6.1.21-dev-69e67db13575983983b4011eb9f5a203733827f0
Console  : 6.1.21-dev-69e67db13575983983b4011eb9f5a203733827f0

## Additional Information
N/A

### PR DESCRIPTION
**Pull request by 3V3RYONE**
This PR fixes #15981   

## Cause of bug  
The cause of this issue was the disparity in the msf-command syntax (`./command`) in the `msfdb` file. The `./` part of the command in the beginning would not be the correct way to get executed in a windows environment (cmd). (https://github.com/rapid7/metasploit-framework/blob/master/msfdb#L661-L673).  
  
The `run_msfconsole_command` method attempts to run the command in 2 ways. First, it runs the command with the default env settings and then with the path set to current directory (by adding a `.` in the beginning of the input command). (https://github.com/rapid7/metasploit-framework/blob/master/msfdb#L655). Since `run_msfconsole_command` itself adds a `.` to the command (if it doesn't get executed in the default env), we need to change the command syntax from `./command` to `command`. This ensures the command works both in windows and linux systems.  
  
## Approach  
The mere solution was to modify the syntax of the commands by removing the initial `./` part (done in commit 1). However, to make the code more maintainable and avoid the same issue in the future, it is better that we consolidate the whole 
   `./msfconsole -qx` initial part of the command into the `run_msfconsole_command` method and only take the command to be executed by `msf_console` as its argument (done in commit 2).  
  
This will ensure that we are not prone to the same error in future, as any new command now would only consist of the optional commands to be run (eg: `db_disconnect --clear; exit`) ; and not the whole command (eg: `./msfconsole -qx 'db_disconnect --clear; exit'`). So, there would be no confusion of whether to include `./` before the command or not.  
  
## Before  
```  
C:\Windows\system32>msfdb init
C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - ./msfconsole -qx 'db_disconnect --clear; exit' (Errno::ENOENT)
        from C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
        from C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:398:in `capture2e'
        from C:/metasploit-framework/embedded/framework/lib/msfdb_helpers/db_interface.rb:55:in `run_cmd'
        from C:/metasploit-framework/bin/../embedded/framework/msfdb:655:in `run_msfconsole_command'
        from C:/metasploit-framework/bin/../embedded/framework/msfdb:674:in `clear_default_data_service'
        from C:/metasploit-framework/bin/../embedded/framework/msfdb:1069:in `<main>'  
```  
  
## After  
```  
C:\Windows\system32>msfdb init
C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at C:/Users/IEUser/.msf4/db
Starting database at C:/Users/IEUser/.msf4/db...  
```  
  
## Verification
  
- [ ] Install MSF on Windows 10 using the latest MSI installer
- [ ] Add `MSF BIN` directory to `%PATH%` environment variable
- [ ] Copy the modified `msfdb` file (of this PR) and place it in the `C:\metasploit-framework\embedded\framework` directory, deleting the original `msfdb` file.
- [ ] Open `cmd` as administrator
- [ ] Run `msfdb init`
- [ ] Type `no` when asked to init webservice
- [ ] **Verify** that the init script continues to **create and start the database** (it may hang at the step of `starting the database`, which is its sister issue I am working on next.)
- [ ] **Verify** that the init script **does not result in a crash** or raise an error.

### CODE REVIEW

**Comment by 3V3RYONE** [comment]
Any updates on this?

**Comment by dwelch-r7** [comment]
I can take a look at this for you @3V3RYONE

**Comment by 3V3RYONE** [comment]
Sure! Thank you @dwelch-r7  : )

**Comment by 3V3RYONE** [comment]
Any updates on this @dwelch-r7 ?

**Comment by dwelch-r7** [comment]
@3V3RYONE yes sorry, I was testing this the other day and wasn't able to replicate the original issue, in fact I ran into this issue instead https://github.com/rapid7/metasploit-framework/issues/15980 and I'm not sure what's causing it either

**Comment by 3V3RYONE** [comment]
@dwelch-r7 , Strange, #15980 should not happen before #15981 ..  
So when you are opting `no` for webservices, the script isnt failing with the error? Rather its hanging at the `Starting database` line?

**Comment by dwelch-r7** [comment]
@3V3RYONE that's right, it's very weird :shrug:

**Comment by 3V3RYONE** [comment]
@dwelch-r7 , do you mind sharing the cmd log for `msfdb init`? Just curious.. :open_mouth:

**Comment by dwelch-r7** [comment]
Sorry not sure what you mean by cmd log @3V3RYONE

**Comment by 3V3RYONE** [comment]
@dwelch-r7 I mean the cmd output when you run `msfdb init`

**Comment by dwelch-r7** [comment]
Sure thing here ya go
```
C:\metasploit-framework\bin>msfdb init
C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
[?] Would you like to init the webservice? (Not Required) [no]:
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at C:/Users/windows/.msf4/db
Starting database at C:/Users/windows/.msf4/db...
```

**Comment by 3V3RYONE** [comment]
Strange thing, because I just did a fresh install of msf from the latest msi installer here. (https://windows.metasploit.com/metasploitframework-latest.msi) And I am still able to reproduce this issue.   
  
The specific version is v6.1.27. @dwelch-r7 , what do you think? 
  
cmd output:
```
C:\Windows\system32>msfdb init
C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
[?] Would you like to init the webservice? (Not Required) [no]: no
Clearing http web data service credentials in msfconsole
C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - ./msfconsole -qx 'db_disconnect --clear; exit' (Errno::ENOENT)
        from C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
        from C:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:398:in `capture2e'
        from C:/metasploit-framework/embedded/framework/lib/msfdb_helpers/db_interface.rb:55:in `run_cmd'
        from C:/metasploit-framework/bin/../embedded/framework/msfdb:653:in `run_msfconsole_command'
        from C:/metasploit-framework/bin/../embedded/framework/msfdb:672:in `clear_default_data_service'
        from C:/metasploit-framework/bin/../embedded/framework/msfdb:1067:in `<main>'
```

**Comment by 3V3RYONE** [comment]
Okay.. I got it,  
we are not getting this error when we try to run `msfdb init` from the `C:\metasploit-framework\bin` directory in cmd.  (As you did)
But if we run `msfdb init` right after opening cmd, from the default directory, we can reproduce this issue.  
  
Can you confirm @dwelch-r7 ?  
  
This should not happen, because installing MSF from the msi version, itself adds the `C:\metasploit-framework\bin` directory to the `PATH` environment variable. Strange 🤔

**Comment by 3V3RYONE** [comment]
Anything yet? @dwelch-r7

**Comment by dwelch-r7** [comment]
Sorry I'll try and take a look today

**Comment by dwelch-r7** [comment]
@3V3RYONE apologies for taking so long, just replicated it there now, running it from outside of the `C:\metasploit-framework\bin` directory triggered the error and then with your changes the problem is fixed but it continues to hang afterwards, I think I'd be happy to land this now although I'd still love to know what's causing the hanging issue but that can be looked at separately

**Comment by dwelch-r7** [comment]
# Release Notes

Fixes an issue with msfdb init on windows when opting not to initialize webservices

**Comment by 3V3RYONE** [comment]
@dwelch-r7 , sure thing.. Even I would love to work to fix the hang thing. Took a look on it for a long time now.. Let me know if you want to work together.. probably that can give a new view to the issue.. and thanks! :) :smile:

**Comment by gwillcox-r7** [comment]
@dwelch-r7 Please remember to add release note tags, will add the missing `rn-fix` tag so long now.

**Pull request merged**
