### PR TITLE
Print file contents

### PR DESCRIPTION
**Pull request by jnqpblc**
robots_txt: Added a print_good statement at line 63 in order to print to contents of the newly discovered robots.txt file.

smb_enumusers: Changed line 315 print type to good instead of the general status indication, so that the result output is easier to see.

### CODE REVIEW

**Comment by mubix** [comment]
Often hated that the robots.txt module didn't output to the screen, just never took the time to fix it. Thanks @jnqpblc - Definitely like both of these. I constantly forget the commit procedures so I'll try and get this in tonight

**Comment by wvu-r7** [comment]
I'm labeling and assigning this PR for posterity. Thanks for the land, @mubix!!

**Comment by wvu-r7** [comment]
# Release Notes

This PR displays the contents of ```robots.txt``` and corrects some output to use ```print_good``` over ```print_status``` in ```auxiliary/scanner/http/robots_txt```.

**Comment by wvu-r7** [comment]
And release notes. :)

**Pull request merged**
