### PR TITLE
get latest MDM for unique services

### PR DESCRIPTION
**Pull request by thelightcosine**
pull in the latest MDM to get the uniqueness validation
for Service objects

MSP-11643

VERIFICATION STEPS
- [ ] LAND https://github.com/rapid7/metasploit-credential/pull/95
- [ ] ping me to update the branch and run migrations. when i've done that proceed:
- [ ] `bundle install`
- [ ] `rake spec`
- [ ] VERIFY all specs pass

### CODE REVIEW

**Comment by todb-r7** [comment]
@dmaloney-r7 looks like this busts Travis. See the error -- missing gem versions.

**Comment by dmaloney-r7** [comment]
@todb-r7 yes, the steps reflect that, the first step is to land the earlier PRs in the chain, then notify me so that I can update this branch with the new gem and run the migrations

**Comment by trosen-r7** [comment]
PR shan't bust Travis now

**Comment by todb-r7** [comment]
@dmaloney-r7 @trosen-r7 Travis looks pretty busted since this landed.

https://travis-ci.org/rapid7/metasploit-framework/builds

Since this PR, we have errors in the schema:

```
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -102,7 +102,7 @@ ActiveRecord::Schema.define(:version => 20150212214222) do
 
   create_table "hosts", :force => true do |t|
     t.datetime "created_at"
-    t.string   "address",                                               :null => false
+    t.string   "address",               :limit => nil,                  :null => false
     t.string   "mac"
     t.string   "comm"
     t.string   "name"
@@ -686,7 +686,7 @@ ActiveRecord::Schema.define(:version => 20150212214222) do
 
   create_table "wmap_requests", :force => true do |t|
     t.string   "host"
-    t.string   "address"
+    t.string   "address",    :limit => nil
     t.integer  "port"
     t.integer  "ssl"
     t.string   "meth",       :limit => 32
@@ -703,7 +703,7 @@ ActiveRecord::Schema.define(:version => 20150212214222) do
 
   create_table "wmap_targets", :force => true do |t|
     t.string   "host"
-    t.string   "address"
+    t.string   "address",    :limit => nil
     t.integer  "port"
     t.integer  "ssl"
     t.integer  "selected"
The command "git diff --exit-code && bundle exec rake $RAKE_TASKS" exited with 1.
cache.2
store build cache
$ bundle clean
Resolving dependencies...
Removing metasploit_data_models (0.22.8)
Removing metasploit-credential (0.13.19)
23.91schange detected: /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.1.0/cache/metasploit_data_models-0.23.0.gem
changes detected, packing new archive
uploading archive
Done. Your build exited with 1.
```

**Pull request merged**
