### PR TITLE
convert myworkspace.id to myworkspace_id for no db compat

### LINKED ISSUE #14188: myworkspace.id to myworkspace_id conversion
https://github.com/rapid7/metasploit-framework/pull/14161#pullrequestreview-496882886

I'll take this since most (if not all) is my code

### PR DESCRIPTION
**Pull request by h00die**
Fixes #14188 as noted https://github.com/rapid7/metasploit-framework/pull/14161#pullrequestreview-496882886

`myworkspace.id` came from the cisco module, which all the other networking modules are based on, and was an unsafe call if no database was connected.

As noted in Arista testing:
```
[*] Importing config
[-] Auxiliary failed: NoMethodError undefined method `id' for nil:NilClass
[-] Call stack:
[-]   /tmp/metasploit-framework/lib/msf/core/auxiliary/arista.rb:20:in `arista_eos_config_eater'
[-]   /tmp/metasploit-framework/modules/auxiliary/admin/networking/arista_config.rb:40:in `run'
[*] Auxiliary module execution completed
```

This PR is a quick and easy conversion for all `myworkspace.id` calls to `myworkspace_id` to prevent crashes within the `lib/msf/core/auxiliary` directory.

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
So I wasn't able to get the verification steps to test this but from what I can see https://github.com/rapid7/metasploit-framework/blob/0d99e78047fb18d3e998ec64dbbc1d5e466148fb/lib/msf/core/auxiliary/report.rb#L83 basically describes this solution exactly, which is to say that `workspace_id` is just a function that will return `nil` if the database is not connected, or `myworkspace.id` if the database is connected.

**Comment by gwillcox-r7** [comment]
@h00die Looks like there are two cases of this issue within `juniper.rb` but you only fixed one of them. There are also additional modules affected, which include `post/multi/gather/enum_hexchat.rb`, `post/solaris/escalate/srsexec_readline.rb` and `post/windows/escalate/golden_ticket.rb`.

**Comment by h00die** [comment]
Funny, I think 2 of those modules were mine... Copy pasta is strong!

**Comment by gwillcox-r7** [comment]
# Release Notes
Fix a number of modules and libraries that were using `myworkspace.id`, which will cause a `nil` dereference stack trace if the database is not connected, and replace the calls to `myworkspace.id` with a call to the function `myworkspace_id`. This function will first check if the database is connected before trying to retrieve the value of `myworkspace.id`, thereby preventing potential stack traces from occurring.

**Comment by pbarry-r7** [comment]
# Release Notes

Fixed a <code>nil</code> dereference stack trace triggered by some modules and libraries attempting to use <code>myworkspace.id</code> when no database is connected.

**Pull request merged**
