### PR TITLE
Added auxiliary/scanner/http docs

### PR DESCRIPTION
**Pull request by Yashvendra**
Added `auxiliary/scanner/http/http_put` and `auxiliary/scanner/http/scraper` modules doc.

### CODE REVIEW

**Comment by Yashvendra** [comment]
This is a newbie question but I want to know that why the commits made in `master` branch are being piled up as a part of this PR even I made only 2 new file in new branch `http_doc`.

**Comment by Yashvendra** [comment]
@bcoles @h00die  can you guys tell me what I did wrong in this PR. I should just have 2 commits instead of 4. Is this a wrong way to submit a PR? There are lot of PR's that i want to submit but I'm facing issue with every new branch i make.

**Comment by bcoles** [comment]
Are you branching from `master`?

```sh
git checkout master
git checkout -b my_awesome_new_pr
git add my/awesome/files
git commit -m "Add awesomeness"
git push origin my_awesome_new_pr
```

**Comment by h00die** [comment]
Make sure your master is up to date as well with a `git pull`

**Comment by Yashvendra** [comment]
> Are you branching from `master`?
> 
> ```shell
> git checkout master
> git checkout -b my_awesome_new_pr
> git add my/awesome/files
> git commit -m "Add awesomeness"
> git push origin my_awesome_new_pr
> ```

I did exactly the same!

**Comment by Yashvendra** [comment]
> Make sure your master is up to date as well with a `git pull`

Okay  that might be the issue, will do that. Thanks @h00die @bcoles

**Comment by Yashvendra** [comment]
So I just did-
1. `git pull` in `master` branch. 
2. `git checkout -b test_httpDoc`
3. `git add newfiles`
4. `git commit -m 'added'
5. `git push origin test_httpDoc`

Then again when I checked i saw this:
sss

When i click on compare and pull i again get this:
sssss


 The commit I made in test_httpDoc branch is highlighted in the box, on the top of it are again the previous commits that I didn't committed in this branch. What should I do now !!

**Comment by bcoles** [comment]
https://xkcd.com/1597/

**Comment by bcoles** [comment]
I'm guessing your `master` is out of sync. Here's a non-ideal solution that's guaranteed to work:

1. Manually backup all your branches/files/diffs.
1. `rm` your local repo.
1. Delete your fork from GitHub.
1. Fork Metasploit on GitHub.
1. `git clone` your fork to your local system.
1. Follow the instructions [here](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) to set up a development environment
1. Make a mental note to always `git checkout mater && git fetch upstream && git merge upstream/master && git push origin master` before you create a new branch. Make another note to always `git checkout master` before creating a new branch.
1. fixt

**Comment by bcoles** [comment]
When you're doing:

```
`git pull` in `master` branch. 
```

You're pulling changes from your repo on GitHub, which is out of sync with upstream:

image

If you want to fix it the proper way, without rm'ing your repo, you'll need to `git fetch upstream` from `master` on `rapid7/metasploit-framework` into `master` on your repo; then `git merge upstream/master`;  then fix any conflicts which arose from de-syncing; and `git push origin master` push your changes to your `master` on GitHub.

**Pull request closed without merging**
