### PR TITLE
Fix #3816 by deleting print_debug

### LINKED ISSUE #3816: print_debug
Currently `print_debug` output is shown if the `VERBOSE` option is enabled. To be consistent, I think this output should only be shown if `DEBUG=true` (which automatically implies `VERBOSE=true`).

vprint_debug: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/module.rb#L244

### PR DESCRIPTION
**Pull request by jvazquez-r7**
Like explained on #3816, this PR:
- Delete (v)print_debug method
- Take care of (v)print_debug uses
- Adds a msftidy check to detect modules trying to use the (v)print_debug method
- Adds a msftidy check to detect modules registering a 'DEBUG' option in production
- Adds a msftidy check to detect modules using the 'DEBUG' option in production
- Take care of modules using the 'DEBUG' option in production
## Verification
- [x] Verify which there aren't modules registering the 'DEBUG' datastore option
- [x] Verify which there aren't modules using the 'DEBUG' datastore option
- [x] Verify which there aren't modules using the (v)print_debug methods
- [x] **IMPORTANT** PRO people should verify and take care of any (v)print_debug usage before this is landed

### CODE REVIEW

**Comment by jvazquez-r7** [comment]
@trosen-r7 I'm assigning you because someone from PRO should verify and take care usages of the ```(v)print_debug``` method before we land this. I guess you're better positioned than me to assign someone to review :)

**Comment by jvazquez-r7** [comment]
@shuckins-r7 assigning to you because I've learn proably you're probably the best positioned to decide who could give a look to avoid waste nothing in PRO.

**Comment by bcook-r7** [comment]
Looks good to me, landing.

**Pull request merged**
