### PR TITLE
expand hashes identify library and add spec

### PR DESCRIPTION
**Pull request by h00die**
This PR adds additional checks to the `identify_hash` function such as length and character type when appropriate.  It adds checks for des, windows, osx, phpass (wordpress/drupal/phpbb3), mysql, mssql, oracle, and postgres.

Also add a spec to make sure things are working as expected.

This is my first test written in metasploit, ruby, or ever, so I'm very open to input on how to do it right/better.

```
# rspec spec/lib/metasploit/framework/hashes/identify_spec.rb 
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0.8.7)
      thor (< 2.0, >= 0.18.1)
      pg (>= 0)
      crass (~> 1.0.2)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 61794
hashes/identify ...................................

Top 10 slowest examples (0.08621 seconds, 78.1% of total time):
  hashes/identify identify_blofish_a returns bf
    0.06527 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:38
  hashes/identify identify_oracle11_S returns raw-sha1,oracle
    0.01476 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:200
  hashes/identify identify_blofish_y returns bf
    0.00091 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:60
  hashes/identify identify_qnx_md5 returns qnx,md5
    0.0008 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:102
  hashes/identify identify_empty_string returns empty string
    0.00078 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:235
  hashes/identify identify_mysql returns mysql
    0.00078 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:158
  hashes/identify identify_blofish_x returns bf
    0.00076 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:53
  hashes/identify identify_sha512_rounds returns sha512,crypt
    0.00073 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:74
  hashes/identify identify_md5 returns md5
    0.00072 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:24
  hashes/identify identify_nil returns empty string
    0.00071 seconds ./spec/lib/metasploit/framework/hashes/identify_spec.rb:242

Finished in 0.11045 seconds (files took 16 seconds to load)
35 examples, 0 failures

Randomized with seed 61794
Coverage report generated for RSpec to /root/metasploit-framework/coverage. 755 / 5624 LOC (13.42%) covered.
```

### CODE REVIEW

**Comment by h00die** [comment]
@h00die add the python script to generate lots of the OS level hashes

**Comment by h00die** [comment]
Thinking more about this, I think forcing/hoping each person to add a call to this library before they pass to the `create_credential` function may be a hassle.  What about adding the call inside of that function?  This way no one needs to call it, it sets the hash type automatically, and then when everyone forgets to set `jtr` anyways, we'll have no issues!
Thoughts?

**Comment by h00die** [comment]
Now has OSX as well

**Comment by busterb** [comment]
So `create_credential` can automatically identify a hash type if it isn't overridden by the caller? Seems like a reasonable default behavior to me!

**Comment by busterb** [comment]
Regarding the spec, I think you did capture the correct idea of how to write a test: given a set of test inputs, do you get the expected outputs.

No complaints here about the approach you took, though you might throw in some non-empty strings that are also not valid or understood password hashes, and verify those are no-match as well.

**Comment by h00die** [comment]
@busterb bingo! if given, let be. If not, throw it at the library for an educated guess.
This will MASSIVELY help out.  I won't have time to implement, a few jobs about to kick off, but can put in an issue for reference if you want.
While whoever is looking at the DB creds stuff, #11686 and #11668 may be easy to solve as well.

**Comment by h00die** [comment]
Added a few more checks, but I think this is ready

**Comment by busterb** [comment]
While you're in there, do you think you could poke at why that credential spec is still failing?

**Comment by jrobles-r7** [comment]
It looks like the spec is checking that `creds -u` will be used as a regex but that was changed in https://github.com/rapid7/metasploit-framework/pull/11742.

**Comment by jrobles-r7** [comment]
Spec fix https://github.com/rapid7/metasploit-framework/pull/11749

**Comment by bcoles** [comment]
@msjenkins-r7 test this please

**Comment by busterb** [comment]
## Release Notes

This updates the password hash identification library code to handle many more hash types.

**Pull request merged**
