### PR TITLE
Wordpress Scanner

### PR DESCRIPTION
**Pull request by firefart**
This PR adds a Wordpress Scanner to find Wordpress versions on the network.
This should replace PR #2621 from @0pc0deFR

Wasn't sure which report info should be used. I wanted to use the report_web_site, but it looks like there is no option for a path. Maybe you have some feedback on this.

Output from this module:

```
msf auxiliary(wordpress_scanner) > run
[*] Trying ip 192.168.18.127
[-] 192.168.18.127:80 - Error connecting to /wordpress/
[*] Scanned 1 of 4 hosts (025% complete)
[*] Trying ip 192.168.18.128
[-] 192.168.18.128:80 - Error connecting to /wordpress/
[*] Scanned 2 of 4 hosts (050% complete)
[*] Trying ip 192.168.18.129
[+] 192.168.18.129 running Wordpress 3.6.1
[*] Scanned 3 of 4 hosts (075% complete)
[*] Trying ip 192.168.18.130
[-] 192.168.18.130:80 - Error connecting to /wordpress/
[*] Scanned 4 of 4 hosts (100% complete)
[*] Auxiliary module execution completed
```

### CODE REVIEW

**Comment by VKSHRIMALII** [comment]
please refer to following to link 
https://github.com/VKSHRIMALII/metasploitclasscerror

**Comment by h00die** [comment]
Please post issues in the issues section, not in a PR that was merged 3 years ago.
Post the issue there, not in your own repo with a link we have to follow, which makes for disjointed issue tracking.

**Comment by VKSHRIMALII** [comment]
hello man this is solution not issue

**Comment by VKSHRIMALII** [comment]
tell me what do now 

    On Friday, 9 June 2017 4:30 AM, h00die <notifications@github.com> wrote:
 

 Please post issues in the issues section, not in a PR that was merged 3 years ago.
Post the issue there, not in your own repo with a link we have to follow, which makes for disjointed issue tracking.—

**Pull request merged**
