### PR TITLE
Port windows reverse_tcp & bind_tcp to Metasm

### PR DESCRIPTION
**Pull request by hdm**
This patch converts the Windows x86 reverse_tcp and bind_tcp stagers to Metasm and implements nicer error handling when space permits. The plan would be to use these stagers as a base to replace the other bind_tcp and reverse_tcp variants in addition to making them more reliable and automatically reconnect if staging failed.

### CODE REVIEW

**Comment by hmoore-r7** [comment]
Basic functionality is working and tested, but holding off on review until additional features are merged.

**Comment by OJ** [comment]
Is this still blocked @hmoore-r7 ? Or do you want me to get into landing this one?

**Comment by hmoore-r7** [comment]
Still blocked for now, current dependencies are UUID -> Reliability (retry on failed download), planning to rebase from UUID soon.

**Comment by OJ** [comment]
@hmoore-r7 I'm going to leave this as delayed, but I'm going to pull your changes into my work for the new transport reliability work that is going on in Meterpreter. So I'll take your changes and shove them into my branch.

Let me know if that's a problem. Cheers!

**Comment by hmoore-r7** [comment]
Sounds good; we can figure out whether to kill his branch entirely based on timing next week. If your branch lands first, I can rebase my reliability & UUID work from it instead of this one.

**Comment by OJ** [comment]
I'm including this work in #5214 now, so I'll close this and keep going over there if that's ok. If that's a problem, please reopen. Cheers @hmoore-r7 !

**Pull request closed without merging**
