### PR TITLE
Fix msfconsole -L

### PR DESCRIPTION
**Pull request by wvu**
```
wvu@kharak:~/metasploit-framework:master$ ./msfconsole -L
[*] Starting the Metasploit Framework console...|/home/wvu/metasploit-framework/lib/msf/ui/console/driver.rb:728:in `choose_readline': undefined method `gem_dir' for nil:NilClass (NoMethodError)
    from /home/wvu/metasploit-framework/lib/msf/ui/console/driver.rb:57:in `initialize'
    from /home/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:52:in `new'
    from /home/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:52:in `driver'
    from /home/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
    from /home/wvu/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    from ./msfconsole:48:in `<main>'
wvu@kharak:~/metasploit-framework:master$ 
```

s/rb-readline/rb-readline-r7/

Should have been in #4816 (#4128).
- [x] `./msfconsole -L`
- [x] See the error
- [x] Be the error
- [x] Merge this
- [ ] Be happy

### CODE REVIEW

**Comment by todb-r7** [comment]
This didn't fix my happiness problem.

**Comment by wvu-r7** [comment]
:(

**Comment by todb-r7** [comment]
Oh no I think I'm becoming InfoSec Taylor Swift.

https://twitter.com/SwiftOnSecurity/status/569661326202515456

**Comment by wwalker-r7** [comment]
@todb-r7 I think you need to shake it off https://www.youtube.com/watch?v=nfWlot6h_JM

**Comment by wvu-r7** [comment]
I think @todb-r7's already got https://www.youtube.com/watch?v=-CmadmM5cOk.

**Pull request merged**
