### PR TITLE
Remove some old and crufty /tools

### PR DESCRIPTION
**Pull request by todb-r7**
It's possible someone still wants the Webscarab stand-alone importer, but I cannot imagine that after years of bitrot that is even viable in its current state.

The rest of them are all older development tools that are no longer needed (normal vim/rubymine auto-formatting will do the trick). Also, the module_changelog.rb relied on SVN logs. Heh.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Self-assigned because I like ```rm```'ing things.

**Comment by hmoore-r7** [comment]
Why remove ```tools/dev/set_binary_encoding.rb```? This is still necessary once in a while.

**Comment by todb-r7** [comment]
I don't really mind keeping `set_binary_encoding.rb`. I don't get the division between the `dev` path and non-dev path, though -- many of the tools are secretly dev-ish. But, no big deal for now.

I'll update the PR accordingly.

**Comment by wvu-r7** [comment]
It should probably be an ```msftidy``` check. ```check_comment_splat``` in ```msftidy``` should probably be updated, too.

**Comment by todb-r7** [comment]
I don't believe every module does or should set binary encoding. We can for lols I guess, but it seems sort of superstitious.

The libs, though, should (assuming they're standalone).

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/commit/ab70223107a6819c54397f22eb8ff1d52e006132

**Pull request merged**
