### PR TITLE
Spelling correction in udp_sweep.rb

### PR DESCRIPTION
**Pull request by danhedonia**
Fixed spelling error: "Intialize" to "Initialize"

### CODE REVIEW

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jenetiks** [comment]
tested and working on my end. What do you need to validate this test?

**Comment by jmartin-r7** [comment]
Sorry the comment may have been confusing, the automation account responds to keywords from committer users.  The comment to @msjenkins-r7 triggered automation to re-execute.

**Comment by jenetiks** [comment]
gotcha. Thank you

**Comment by h00die** [comment]
Fixed a few others while I was there: https://github.com/rapid7/metasploit-framework/commit/7718992ea4b01ccd7d92588fc365061cfe832467

**Comment by h00die** [comment]
# Release Notes
Fixed spelling error: "Intialize" to "Initialize"

**Pull request merged**
