### PR TITLE
Simplified UX + enhancements for msfdb

### PR DESCRIPTION
**Pull request by ebleiweiss-r7**
MS-3710

The `msfdb` script currently asks the user a whole bunch of overwhelming questions, especially when you do an `init`. All we really need to know is their desired webservice username, password, and whether they want to delete existing configs. This PR condenses the list of questions that the user has to answer.

Other enhancements:
- Colored terminal output to help visually distinguish prompts and errors
- A big ol' obvious info/warning message that lets a user know they should save/store their web token
- A password prompt/command line option, in case the user wants to specify a password instead of having one randomly generated
- A `use-defaults` command line option, which makes the whole script non-interactive, and uses all default values instead of prompting the user on an `init`
- A `[no-]msf-data-service` command option, which allows a user to specify a name for the local msfconsole data service connection
- `start_db` no longer loops forever if it encounters a database error, such as an incompatible version of postgres

screen shot 2019-01-23 at 12 51 45 pm

## Verification

**Test that the `init` process still works as expected, but with enhancements**
- [x] `./msfdb delete`
- [x] `./msfdb status`
- [x] **Verify** that the database and web services are deleted
- [x] `./msfdb init`
- [x] **Verify** that you get prompted for a password
- [x] **Verify** that you receive display output with your username, password, and web token
- [x]  **Verify** that the web service gets created correctly (https://localhost:8080/api/v1/api-docs)

---

**Test that you don't get prompted about deletion unnecessarily** 
- [x] `./msfdb delete --component database`
- [x] `./msfdb init --component database`
- [x] **Verify** that you _do not_ see the prompt `Would you like to delete your existing data and configurations?:` (Since you just deleted the database, there's nothing left to delete)
- [x] `./msfdb reinit --component webservice` to get things back into a working state, since you just deleted the database

**Test the new `--use-defaults` command line option**
- [x] `./msfdb reinit --use-defaults`
- [x] **Verify** that you received no prompts, but that you still get a nice display of your creds and web token

---

**Test the new `--pass` command line option**
- [x] `./msfdb reinit --pass Password123`
- [x] **Verify** that you _do not_ receive a password prompt
- [x] **Verify** that the password output (`MSF web service password`) matches the input

---

**Test the new `[no-]msf-data-service` command line option**
- [x] `./msfdb reinit --msf-data-service custom_data_service`
- [x] **Verify** that you _do not_ receive a prompt to either add _or_ name a data service connection
- [x] Open msf console `./msfconsole`
- [x] `db_connect -l`
- [x] **Verify** that `custom_data_service` is present and set as default
- [x] `./msfdb reinit --no-msf-data-service`
- [x] **Verify** that you _do not_ receive a prompt to either add _or_ name a data service connection
- [x] Open msf console `./msfconsole`
- [x] `db_connect -l`
- [x] **Verify** that no additional data service connections have been added

### CODE REVIEW

**Comment by jbarnett-r7** [comment]
We probably don't need to address this in this PR, but it looks like `msfdb delete` only deletes the database data and config files. The webservice files still persist:

```
jbarnett@AUS-MBP-5726 ~/rapid7/msf_jbarnett ((HEAD detached at upstream/pr/11299)) $ ./msfdb delete
[?] Would you like to delete your existing data and configurations?: y
Stopping database at /Users/jbarnett/.msf4/db
Deleting all data at /Users/jbarnett/.msf4/db
MSF web service is no longer running
jbarnett@AUS-MBP-5726 ~/rapid7/msf_jbarnett ((HEAD detached at upstream/pr/11299)) $ ls ~/.msf4/
config			john.pot		logos			loot			modules			msf-ws-config.ru	plugins
history			local			logs			loot_bak		msf-ws-cert.pem		msf-ws-key.pem		store
jbarnett@AUS-MBP-5726 ~/rapid7/msf_jbarnett ((HEAD detached at upstream/pr/11299)) $ ./msfdb init
[?] Would you like to delete your existing data and configurations?: 
```

Since the `--component` options exist I would assume the default is to delete everything.

**Comment by jbarnett-r7** [comment]
According to the JIRA ticket, we were going to remove prompts confirming if the user wanted to add the local data service and just add it with the `local-https-data-service` name by default. Did we decide in a conversation that wasn't going to be the case?

**Comment by jbarnett-r7** [comment]
> Yeah, right now an `msfdb delete` behaves identically to `stop` the webservice. I can look into adding that if you think it's in scope for this PR.

If it's simple, go ahead and do it here. If not, let me know and I'll throw a ticket on the backlog.

**Comment by jbarnett-r7** [comment]
I just noticed that now that we automatically add the web service to console, the output text should probably be changed. Here is what it looks like currently:

```
jbarnett@AUS-MBP-5726 ~/rapid7/msf_jbarnett ((HEAD detached at upstream/pr/11299)) $ ./msfdb reinit --msf-data-service blah
[?] Would you like to delete your existing data and configurations?: y
Stopping database at /Users/jbarnett/.msf4/db
Deleting all data at /Users/jbarnett/.msf4/db
Creating database at /Users/jbarnett/.msf4/db
Starting database at /Users/jbarnett/.msf4/db...success
Creating database users
Writing client authentication configuration file /Users/jbarnett/.msf4/db/pg_hba.conf
Stopping database at /Users/jbarnett/.msf4/db
Starting database at /Users/jbarnett/.msf4/db...success
Creating initial database schema
Stopping MSF web service PID 13470
[?] Initial MSF web service account username? [jbarnett]: 
[?] Initial MSF web service account password? (Leave blank for random password): 
Generating SSL key and certificate for MSF web service
Attempting to start MSF web service...success
MSF web service started and online
Creating MSF web service user jbarnett

    ############################################################
    ##              MSF Web Service Credentials               ##
    ##                                                        ##
    ##        Please store these credentials securely.        ##
    ##    You will need them to connect to the webservice.    ##
    ############################################################

MSF web service username: jbarnett
MSF web service password: <REDACTED>
MSF web service user API token: <REDACTED>


MSF web service configuration complete
Connect to the data service in msfconsole using the command:
db_connect --token <REDACTED> --cert /Users/jbarnett/.msf4/msf-ws-cert.pem --skip-verify https://localhost:8080

The username and password are credentials for the API account:
https://localhost:8080/api/v1/auth/account
```

We should probably change it to something like:

```
MSF web service configuration complete
The web service has been configured as your default data service named "<name>".

If needed, manually reconnect to the data service with the following command in msfconsole:
db_connect --token <REDACTED> --cert /Users/jbarnett/.msf4/msf-ws-cert.pem --skip-verify https://localhost:8080

The username and password are credentials for the API account:
https://localhost:8080/api/v1/auth/account
```

**Comment by ebleiweiss-r7** [comment]
Updated that message

**Comment by jbarnett-r7** [comment]
# Release Notes

Enhance the usability of the msfdb script. This is done by simplifying the questions asked during the init and reinit options. New flags were also added to improve scripting.

**Pull request merged**
