### PR TITLE
Generic module for detecting UDP amplification vulnerabilities

### PR DESCRIPTION
**Pull request by jhart-r7**
This adds a simple module for detecting and researching UDP amplification vulnerabilities.  It is very simplistic.  While it can detect previously undisclosed UDP amplification vulnerabilities under the right conditions, in general it requires a lot of trial and error of `PROBE` and `PORT` options to "discover" anything.  IOW, this module is only suited for broad classes of UDP amplification vulnerabilities (empty or single-byte UDP datagrams, for example) or for specific UDP amplification vulnerabilities already known to exist in specific protocols.

See the provided module documentation for my testing.

### CODE REVIEW

**Comment by bpatterson-r7** [comment]
#7488 has been merged into master

**Comment by bpatterson-r7** [comment]
I tested the module as per the example in your documentation and didn't get any messages such as:

192.168.3.64:19 - susceptible to UDP amplification: No packet amplification and a 18x, 70-byte bandwidth amplification

Does that mean that no UDP amplification vulnerabilities were detected?  I used the exact same hosts and ports you did. If this is expected behavior, then it looks good.

**Comment by jhart-r7** [comment]
Thanks, @bpatterson-r7.  In the interest of security through obscurity, I obfuscated the IP addresses used.  So, if you tried to use those same `RHOSTS`, no output is totally expected.

**Comment by bpatterson-r7** [comment]
That seems reasonable. I'll try to test them on some other hosts and continue from there.

**Comment by tdoan-r7** [comment]
# Release Notes

This module detects and researches UDP  amplification vulnerabilities. It should only be used for broad classes of UDP amplification vulnerabilities (e.g., empty or single-byte UDP datagrams) or for specific UDP amplification vulnerabilities that are already known to exist in specific protocols.

**Pull request merged**
