### PR TITLE
add timing options to owa_ews_login

### PR DESCRIPTION
**Pull request by rwhitcroft**
The module now accepts options `PASSWORDS_PER_CYCLE` and `CYCLE_DELAY` which can be used with long-running jobs to avoid account lockouts, e.g., if the AD lockout policy is 3 failures in 30 minutes, you might set these to 1 and 31 respectively.

Better code welcome. FWIW, I tried using MaxGuessesPerUser but it seems busto.

```
msf5 auxiliary(scanner/http/owa_ews_login) > cat /tmp/u /tmp/p
[*] exec: cat /tmp/u /tmp/p

user1
user2
user3
pass1
pass2
pass3
msf5 auxiliary(scanner/http/owa_ews_login) > set user_file /tmp/u
user_file => /tmp/u
msf5 auxiliary(scanner/http/owa_ews_login) > set pass_file /tmp/p
pass_file => /tmp/p
msf5 auxiliary(scanner/http/owa_ews_login) > set cycle_delay 0
cycle_delay => 0
msf5 auxiliary(scanner/http/owa_ews_login) > set passwords_per_cycle 2
passwords_per_cycle => 2
msf5 auxiliary(scanner/http/owa_ews_login) > set verbose true
verbose => true
msf5 auxiliary(scanner/http/owa_ews_login) > run

[+] Found NTLM service at /ews/ for domain ADTEST.
[-] 10.1.4.18:443 - [1/9] - Failed login: user1:pass1
[-] 10.1.4.18:443 - [2/9] - Failed login: user2:pass1
[-] 10.1.4.18:443 - [3/9] - Failed login: user3:pass1
[-] 10.1.4.18:443 - [4/9] - Failed login: user1:pass2
[-] 10.1.4.18:443 - [5/9] - Failed login: user2:pass2
[-] 10.1.4.18:443 - [6/9] - Failed login: user3:pass2
[*] Sleeping 0 minutes between cycles
[-] 10.1.4.18:443 - [7/9] - Failed login: user1:pass3
[-] 10.1.4.18:443 - [8/9] - Failed login: user2:pass3
[-] 10.1.4.18:443 - [9/9] - Failed login: user3:pass3
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

### CODE REVIEW

**Comment by acammack-r7** [comment]
Hmm, it looks like this is using a bit of a mix of the old-style scanning and the new credential stuff. Since a lot of services could take advantage of this sort of pattern, I think the first step would be to put this code into a login scanner class, like these Buffalo NAS ones:
https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/http/buffalo_login.rb
https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/buffalo.rb

Then, we can add the cycle options to the [`#scan!`](https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/login_scanner/base.rb#L193) method of all login scanners.

**Comment by rwhitcroft** [comment]
Gotcha, will take a look at those.

**Comment by rwhitcroft** [comment]
Hey @acammack-r7 , it seems like PASSWORD_SPRAY is part AuthBrute and isn't honored in the LoginScanner stuff. I'm having trouble understanding how/where the creds collection is "flipped" to rotate around passwords instead of usernames (as seems to be desirable most of the time anyway). Any tips?

**Comment by rwhitcroft** [comment]
Opening a new PR for this.

**Pull request closed without merging**
