### PR TITLE
Deprecate checkvm script and update checkvm post module

### PR DESCRIPTION
**Pull request by bcoles**
Removes `./scripts/meterpreter/checkvm.rb`.

Scripts are deprecated and no longer supported. #7789

Leaving this script lying around is confusing for users. #16777

I'm not sure if this script has been left untouched for so long because it is required for some workflows. Scripts were deprecated over 5 years ago. If it should not be removed now, then when?

---

The `checkvm` script supports Windows only:

https://github.com/rapid7/metasploit-framework/blob/1b5e172f2986efc86be7cf994bc7ec9c78d54481/scripts/meterpreter/checkvm.rb#L347-L359

The `checkvm` script is effectively replaced by `post/windows/gather/checkvm`.

Where as we now have multiple `post` modules which can detect virtual machines for various platforms, including a Windows replacement:

* ./modules/post/solaris/gather/checkvm.rb
* ./modules/post/windows/gather/checkvm.rb
* ./modules/post/linux/gather/checkvm.rb

While the module is not a one-for-one replacement for the original script, the features overlap and the module is more up-to-date and generally more complete.

The script appears to include some additional checks which the module does not (and vice versa). I'm going to presume that this is because they are no longer relevant, and that the module has since been updated rather than the script. Generally, the module is more complete than the script. Differences documented below.

# Hyper-V

The script checks for several services:

```ruby
      if srvvals.include?("vmicheartbeat")
        print_status("This is a Hyper-V Virtual Machine")
        vm = true
      elsif srvvals.include?("vmicvss")
        print_status("This is a Hyper-V Virtual Machine")
        vm = true
      elsif srvvals.include?("vmicshutdown")
        print_status("This is a Hyper-V Virtual Machine")
        vm = true
      elsif srvvals.include?("vmicexchange")
        print_status("This is a Hyper-V Virtual Machine")
        vm = true
      end
```

Where as the module only checks for `vmicexchange`.

# Virtual PC

The scripts checks for several services:

```ruby
    if srvvals.include?("vpcbus")
      print_status("This is a VirtualPC Virtual Machine")
      vm = true
    elsif srvvals.include?("vpc-s3")
      print_status("This is a VirtualPC Virtual Machine")
      vm = true
    elsif srvvals.include?("vpcuhub")
      print_status("This is a VirtualPC Virtual Machine")
      vm = true
    elsif srvvals.include?("msvmmouf")
      print_status("This is a VirtualPC Virtual Machine")
      vm = true
    end
```

The module only checks for `vpc-s3 vpcuhub msvmmouf`. (excludes `vpcbus`).

### CODE REVIEW

**Comment by adfoster-r7** [comment]
I'd be good to land this if the script's contents were replaced with a printed message saying it has been removed, and suggesting which post modules should be run instead.

**Comment by bcoles** [comment]
> I'd be good to land this if the script's contents were replaced with a printed message saying it has been removed, and suggesting which post modules should be run instead.

I believe this code already takes care of that?

https://github.com/bcoles/metasploit-framework/blob/bd8d4d3f7885e827f96a198350df99749e014c6a/lib/msf/base/sessions/scriptable.rb#L54-L60

This was the approach taken when deprecating the `pml_driver_config` script in #11505.

**Comment by h00die** [comment]
Out of scope of this PR but combining all those post modules into one `multi` seems like a good idea

**Comment by gwillcox-r7** [comment]
With this change this is the message that will come up, re @AlanFoster's concern. Seems to be sufficient for what was requested:

```
meterpreter > run checkvm

[!] Meterpreter scripts are deprecated. Try post/windows/gather/checkvm.
[!] Example: run post/windows/gather/checkvm OPTION=value [...]
[-] The specified meterpreter session script could not be found: checkvm
meterpreter > 
```

Agree with @h00die's point on combining. I'll also put up a PR to try make the changes that @bcoles pointed out so we aren't losing out on any features contained in this script.

**Comment by gwillcox-r7** [comment]
Seems to be working well btw:

```
msf6 payload(windows/x64/meterpreter/reverse_tcp) > 
[*] Sending stage (200774 bytes) to 172.27.120.164
[*] Meterpreter session 2 opened (172.27.117.95:4444 -> 172.27.120.164:50267) at 2022-07-20 16:50:55 -0500

msf6 payload(windows/x64/meterpreter/reverse_tcp) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > run checkvm

[!] Meterpreter scripts are deprecated. Try post/windows/gather/checkvm.
[!] Example: run post/windows/gather/checkvm OPTION=value [...]
[-] The specified meterpreter session script could not be found: checkvm
meterpreter > background
[*] Backgrounding session 2...
msf6 payload(windows/x64/meterpreter/reverse_tcp) > use post/windows/gather/checkvm 
msf6 post(windows/gather/checkvm) > show options

Module options (post/windows/gather/checkvm):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on

msf6 post(windows/gather/checkvm) > set SESSION 2 
SESSION => 2
msf6 post(windows/gather/checkvm) > run

[*] Checking if the target is a Virtual Machine ...
[+] This is a Hyper-V Virtual Machine running on physical host *redacted cause this is my actual corporate hostname here*
[+] This is a Hyper-V Virtual Machine
[*] Post module execution completed
msf6 post(windows/gather/checkvm) >
```

Latest update from https://github.com/rapid7/metasploit-framework/pull/16778/commits/09ffd7f11526fcc1798804a5ac3dcb02c68ea13a should pull in the changes from the script into the post module now and also update the code a little bit to reduce some code reuse.

**Comment by gwillcox-r7** [comment]
# Release Notes
The checkvm script at `./scripts/meterpreter/checkvm.rb` has been removed as `post/windows/gather/checkvm.rb` now replaces it. Additionally the `post/windows/gather/checkvm.rb` script has been updated to include missing features from `./scripts/meterpreter/checkvm.rb` to ensure backwards compatibility.

**Pull request merged**
