### PR TITLE
use new rex-bin_tools gem

### PR DESCRIPTION
**Pull request by thelightcosine**
This PR moves all the binary parsing and scanning tools (msfbinscan, msfpescan,msfelfscan,msfmachscan) as well as all of their supporting libraries, out into the new rex-bin_tools gem.
## Verification
- [x] `rake spec`
- [x] VERIFY all specs pass
- [x] `msfpescan`
- [x] `msfelfscan`
- [x] `msfmachscan`
- [x] `msfbinscan`
- [x] VERIFY these commands all still work

### CODE REVIEW

**Comment by busterb** [comment]
So, I'm a Kali linux packager, or omnibus packager. How do I fix the wrappers that this breaks?

**Comment by busterb** [comment]
For instance, what would the patch for this look like:

https://github.com/rapid7/metasploit-omnibus/blob/master/config/software/metasploit-framework-wrappers.rb

https://github.com/rapid7/metasploit-omnibus/blob/master/config/software/metasploit-framework-wrappers-windows.rb

Here is the corresponding Kali control directory that also would need a solution:

http://git.kali.org/gitweb/?p=packages/metasploit-framework.git;a=tree;f=debian;h=cf2524d1933c5c504b137f8f9f2d498d23f403d8;hb=refs/heads/kali/master

**Comment by dmaloney-r7** [comment]
@busterb i don't believe any wrappers are needed for those bins anymore. the gem should handle all of it.  the gem itself makes the bins available through PATH

**Comment by bcook-r7** [comment]
I think we got omnibus sorted anyway. Don't forget to update the metasploit-framework.gemspec to exclude the bins from here.

**Comment by pbarry-r7** [comment]
# Release Notes

None needed for this item, I don't think.

**Comment by tdoan-r7** [comment]
Are you sure @pbarry-r7?

**Comment by pbarry-r7** [comment]
I'll defer to @dmaloney-r7.  :)  We've not release noted other "gemification" items, but maybe this one is a little different since we've moved some of the bin tools folks use on the cmdline out of MSF and into a new gem.

@dmaloney-r7, what say you, sir?

**Comment by busterb** [comment]
I'd say double check whether mspro actually wraps these or not. I suspect not, but it may need a similar fix to omnibus.

**Comment by pbarry-r7** [comment]
Good point, @busterb.  Checking into it...

**Pull request merged**
