### PR TITLE
replace factory_girls with factory_bot fixes #9736

### LINKED ISSUE #9736: factory_girl deprecation warning
## Steps to reproduce

1. `rake spec`
2. Note the first bit of output:

```
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /home/todb/git/metasploit-framework/config/application.rb:10)
/home/todb/.rvm/rubies/ruby-2.4.3/bin/ruby -I/home/todb/.rvm/gems/ruby-2.4.3@metasploit-framework/gems/rspec-core-3.7.1/lib:/home/todb/.rvm/gems/ruby-2.4.3@metasploit-framework/gems/rspec-support-3.7.1/lib /home/todb/.rvm/gems/ruby-2.4.3@metasploit-framework/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /home/todb/git/metasploit-framework/config/application.rb:10)
Run options: include {:focus=>true}

```
This is on a fresh clone of metasploit-framework.

## Expected behavior

We shouldn't be using gems with deprecation warnings.

## Current behavior

We are currently depending on deprecated gems.

### Metasploit version

26bf96b3ce1e97bfb997432ba532e9823f885750 Land #9723, Require dependencies conditionally in msfvenom

```
todb@mazikeen:~/git/metasploit-framework$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
todb@mazikeen:~/git/metasploit-framework$ gem -v
2.6.14
```

### I installed Metasploit with:

- [ x ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Ubuntu 16.04.4 LTS (lsb_release -a output below)

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

### PR DESCRIPTION
**Pull request by firefart**
See https://github.com/rapid7/metasploit-framework/issues/9736 for details.
This replaces factory_girls (deprecated) with factory_bot

### CODE REVIEW

**Comment by busterb** [comment]
Darn, is there a strange dependency with metasploit_data_model after all?

**Comment by FireFart** [comment]
I don't get why this fails as there was no change from factory_girl to factory_bot except the rename : dizzy_face:

**Comment by busterb** [comment]
I think we will have to update https://github.com/rapid7/metasploit_data_models first, because someone added this to it, sigh...

```
lib/metasploit_data_models/engine.rb:# `FactoryGirl` factories, sequences, and traits.
lib/metasploit_data_models/engine.rb:    if defined? FactoryGirl
lib/metasploit_data_models/engine.rb:      FactoryGirl.definition_file_paths.unshift definition_file_path
```

**Comment by FireFart** [comment]
I think it also has to do with the rename because we are updating already existing factories from `metasploit_data_models` with `Factory(Bot|Girl).modify` and the factories can't be found because they are still 'FactoryGirl` instead of `FactoryBot` inside metasploit_data_models.

**Comment by busterb** [comment]
Let's see if we can get mdm to at least pass on its own, release it, then try again here.

**Comment by busterb** [comment]
I think that takes care of it all. Thanks @FireFart !

**Pull request merged**
