### PR TITLE
Add GitStack v2.3.10 Unauth REST API Aux Module

### PR DESCRIPTION
**Pull request by jrobles-r7**
This module sends requests to REST API endpoints on GitStack v2.3.10. The application allows unauthenticated REST API requests to several endpoints.

## Verification

- [ ] Install a vulnerable GitStack application
- [ ] Create a few application user accounts
- [ ] Create a few application repositories
- [ ] `./msfconsole`
- [ ] `use auxiliary/admin/http/gitstack_rest`
- [ ] `set rhost <rhost>`
- [ ] `run`
- [ ] Verify the application user list that is returned
- [ ] `set action LIST_REPOS`
- [ ] `run`
- [ ] Verify the repository list that is returned
- [ ] `set username <username>`
- [ ] `set password <password>`
- [ ] `set action CREATE`
- [ ] `run`
- [ ] On the application verify that the user has been created
- [ ] On the application verify that the user has access to the repositories
- [ ] `set action CLEANUP`
- [ ] `run`
- [ ] On the application verify that the user doesn't have access to the repositories
- [ ] On the application verify that the user has been deleted

### CODE REVIEW

**Comment by jrobles-r7** [comment]
I'm working on splitting up the list and list repo actions into different functions because the functionality provided by list repos is used in a couple of other places in the code. Also, I need to add a check for `datastore['USERNAME']` in the `clean_app` function.

**Comment by h00die** [comment]
before someone @r7 yells at you, you may want to switch this to a new branch :)
However, since no ones looked at it, i'll see if i can take a look over the next few days!  If I don't say anything, ping me by Tuesday

**Comment by jrobles-r7** [comment]
@h00die why a new branch for this PR?

**Comment by h00die** [comment]
apparently my eyes deceived me, i swear it said master.  Erasing previous comment.

**Comment by wchen-r7** [comment]
# Release Notes

This PR adds an auxiliary module for GitStack v2.3.10 to perform unauthenticated REST API calls.

**Pull request merged**
