### PR TITLE
Dramatic speed-up in bleeding, improved verbose output of leaked data.

### PR DESCRIPTION
**Pull request by tomspencer**
Massive speed-up in bleeding out data by pulling and parsing SSL record headers and then pulling appropriate data lengths directly instead of waiting for a response timeout.

**Details**
- The existing code running against a straight SSL listener (so no callbacks) creates two connections, which incurs two RESPONSE_TIMEOUT penalties for every run. The default value for RESPONSE_TIMEOUT is 10 seconds, so with that default nearly 20 seconds is wasted on each run.
- The first of these connections (and therefore penalties) is unnecessary except for the "KEYS" action, so it can easily be moved from running for every action to only run for KEYS.
- More importantly, by parsing the server's SSL record lengths we can pull the appropriate amount of data directly without ever waiting for a timeout. This drops both connections from taking RESPONSE_TIMEOUT seconds to being nearly instant (i.e. as fast as you can send an SSL Client HELLO and receive a SERVER HELLO DONE).
- The function in question (establish_connect) is used by every action and callback option, so this speedup affects all aspects of the module, including hugely speeding up recovering private keys.
- Against a vulnerable straight SSL connection, there are no remaining inherent RESPONSE_TIMEOUT delays left unless the system does not return HEARTBEAT_LENGTH bytes of data. Even in this case, you can simply lower HEARTBEAT_LENGTH to be within the range of the data being returned. Once you do this, the heartbleed response from a vulnerable server is basically instant, bounded only by network latency.
- The verbose display of leaked memory was also changed to represent unprintable characters as periods instead of removing them altogether which caused things to run together in ways that made interesting data hard to spot. Long runs of repeated characters are replaced with a "repeated X times" message with some padding on each side so that relative spacing of leaked info is still clear but without overwhelming the user with junk data.
- Slightly better error checking. We now explicitly check that we've received a SERVER_HELLO_DONE.
- A few very minor typo / stylistic consistency changes

**Remaining Issues**
- Most or all of the callback handlers use similar unbounded get_data calls of their own which will each result in RESPONSE_TIMEOUT delays. I have not touched those functions, so at least those portions of the callbacks will remain slow.

**Testing**
- I have tested quite a bit against straight SSL listeners, but not at all against callbacks, so those should get tested thoroughly. Nothing that has been changed _should_ cause any problems with callbacks, but you never know.

If there's anything I've done that should be revamped, please let me know.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Dang, Heartbleed was a while ago.

**Comment by tomspencer** [comment]
Yup, just over 18 months now. There is still quite a bit of it out there though, especially in internal networks, and the metasploit module as it stands now is extremely slow compared to the various standalone scripts out there.

This patch brings metasploit's performance in line with the other implementations, and in line with where it should be:

Condition | Current Performance | Patch Performance
------------ | --------------------------- | ------------------------
Not Vulnerable | 3 x RESPONSE_TIMEOUT | 1 x RESPONSE_TIMEOUT
Vulnerable (returns < HEARTBEAT_LENGTH data) | 3 x RESPONSE_TIMEOUT | 1 x RESPONSE_TIMEOUT
Vulnerable (returns >= HEARTBEAT_LENGTH data) | 2 x RESPONSE_TIMEOUT | Nearly instant (bound only by network latency)

**Comment by wvu-r7** [comment]
Impressive documentation, @tomspencer. Thank you.

**Comment by wvu-r7** [comment]
Great changes, thanks. https://github.com/rapid7/metasploit-framework/commit/ce3f9e2fab9a98d23978626021bd1019a523ddff

**Comment by tomspencer** [comment]
You're welcome, appreciate your time on it!

**Pull request merged**
