### PR TITLE
Fix blank username bug (#4634)

### LINKED ISSUE #4634: Blank username can cause an "undefined method `username'" error for the creds -u command
I have some creds on my database, and then when I do this:

```
msf > creds -u Administrator
```

I get the following:

```
[-] Error while running command creds: undefined method `username' for nil:NilClass

Call stack:
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:872:in `block (2 levels) in creds_search'
/Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:866:in `block in creds_search'
/Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:861:in `creds_search'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:973:in `cmd_creds'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/shell.rb:200:in `run'
/Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/console.rb:38:in `start'
/Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

### PR DESCRIPTION
**Pull request by jlee-r7**
Fixes #4634. I thought I was going to need some changes to Mdm, but this turned out better, IMO.
# Verification
## Bug
- [x] get a vnc cred (one with no username)
  - [x] `use auxiliary/scanner/vnc/vnc_login`, set appropriate options, `run`
- [x] get an smb cred (I had a username "administrator", reflected below. Use whatever works for you)
  - [x] `use auxiliary/scanner/smb/smb_login`, set appropriate options, `run`
- [x] `creds -u administrator`
- [x] **VERIFY** shows the smb cred, doesn't explode
## Regex username/password
- [x] `creds -u ^[a]dmin(istrator)$`
- [x] **VERIFY** shows the smb cred
- [x] with an NTLM hash
  - [x] `creds -P ^[a-f0-9]{32}:[a-f0-9]{32}$`
## Ports and service names
- [x] `creds -p 445`
- [x] **VERIFY** shows the smb cred
- [x] `creds -s smb`
- [x] **VERIFY** shows the smb cred
- [x] `creds -s smb -p 445`
- [x] **VERIFY** shows the smb cred
- [x] `creds -s smb -p 5900`
- [x] **VERIFY** shows nothing

### CODE REVIEW

**Comment by jlee-r7** [comment]
This needs more specs, but I wanted to get a pull request up today. Will take a stab at some more specs in the morning.

**Comment by wchen-r7** [comment]
Here's my initial test (works for me on the same workspace that contains the empty user VNC login cred):

```
sinn3r$ git checkout upstream/pr/4643
Previous HEAD position was 63c3832... Also test for nonmatching passwords
HEAD is now at 964d37d... Add a simple spec for -u
sinn3r$ ./msfconsole -q
msf > creds -u Administrator
Credentials
===========

host           service        public         private   realm            private_type
----           -------        ------         -------   -----            ------------
10.8.0.21      445/tcp (smb)  administrator  12345678                   Password
192.168.1.64   445/tcp (smb)  administrator  12345678                   Password
192.168.1.81   445/tcp (smb)  Administrator  abcd1234  WEI-3B699B1A81A  Password
192.168.1.82   445/tcp (smb)  Administrator  12345678                   Password
192.168.1.83   445/tcp (smb)  administrator  12345678                   Password
192.168.1.129  445/tcp (smb)  administrator  12345678  asdf             Password
192.168.1.130  445/tcp (smb)  administrator  12345678                   Password

msf >
```

**Comment by wchen-r7** [comment]
We just landed #4642, it looks like it might be conflicting your PR too.

**Comment by jlee-r7** [comment]
Deconflicted.

**Comment by jlee-r7** [comment]
Bah, i borked the empty username search.  Hold please.

**Comment by jlee-r7** [comment]
OK, fixed `creds -u ""`, although I'm not sure why @todb-r7 's specs didn't catch the bug.

**Comment by wchen-r7** [comment]
The regex for the NTLM format seems to work better with just: ```[a-f0-9]{32}:[a-f0-9]{32}```

**Pull request merged**
