### PR TITLE
Bump metasploit-payloads to 1.2.11 to incorporate changes to metasplo…

### PR DESCRIPTION
**Pull request by bwatters-r7**
This just bumps the metasploit-framework to use the latest payloads Gem, 1.2.11 to incorporate payload PR https://github.com/rapid7/metasploit-payloads/pull/163

### CODE REVIEW

**Comment by bwatters-r7** [comment]
(Shakes fist at payload sizes......)

**Comment by busterb** [comment]
That's weird, why did python change?

**Comment by busterb** [comment]
Oh, because of https://github.com/rapid7/metasploit-payloads/commit/63326f76aa98f9df5440381357a4a7c27890ab1d - no worries, that's correct.

**Comment by bwatters-r7** [comment]
Yeah; I'd assumed that previous Gem was a fail, but it looks like metasploit-framework never got updated for PR 166, so unless I misunderstand, this functionally implements both https://github.com/rapid7/metasploit-payloads/pull/163 and https://github.com/rapid7/metasploit-payloads/pull/166

**Comment by bwatters-r7** [comment]
# Release Notes
Updates gemspec file to grab the updated version of the metasploit-payloads gem.

**Comment by busterb** [comment]
Yeah, the other one didn't have any functional change.

**Pull request merged**
