### PR TITLE
Remove unused netware console session

### PR DESCRIPTION
**Pull request by dwelch-r7**
This PR is just to remove the netware console session, it's not being used within framework, came across it during the zeitwerk PR and noticed the namespacing was wrong anyway (Sessions vs. Session) so rather than fix it I decided to just remove it as a separate PR to avoid confusion

- [x] Double check that there are no references to netware console in framework
- [ ] Double check that there are no references to netware console in pro

### CODE REVIEW

**Comment by adfoster-r7** [comment]
Just wanted to confirm that this isn't being used by as part of any meta programming? 👀 

From checking Git it looks like it was first added as part of this larger commit:
https://github.com/rapid7/metasploit-framework/commit/6677beb174c7ac26a15ea530a11a026f4c5c0202#diff-b5ebe5524a6c9c5a205c5da4f37720a12489644dd04bad8fb013ef0b81992994R13

Were the payload was also created:
https://github.com/rapid7/metasploit-framework/commit/6677beb174c7ac26a15ea530a11a026f4c5c0202#diff-7bffdb6e41e75a95b08ab02d71dd94c080677662b43398f838ca3fcbdec7c5e1R18

Which still exists in the codebase today, but with its name being updated:

https://github.com/rapid7/metasploit-framework/blob/a53d86c78fd173468c09077bece3d66db519859d/modules/payloads/stages/netware/shell.rb#L10

The initial commit doesn't have any static references to `NetwareConsole` either, so it was either introduced as dead code, or there's meta programming involved, or I'm missing something obvious 😄 

As an aside, it looks like this software and company no longer exist - it might be appropriate to delete this its entirety?

**Comment by agalway-r7** [comment]
From the wikipedia article on Netware:

> The final update release was version 6.5SP8 of May 2009; NetWare is no longer on Novell's product list. NetWare 6.5SP8 General Support ended in 2010, with Extended Support until the end of 2015, and Self Support until the end of 2017. The replacement is Open Enterprise Server.

So no type of support for three years, a modern replacement every user will have hopped over to, and a check on master that backs up `NetwareConsole` isn't being used anywhere has me happy to nuke this from framework. I will look through Pro now.

**Comment by agalway-r7** [comment]
Pro's all good, merging

**Comment by agalway-r7** [comment]
## Release Notes
Removes unused `NetwareConsole` Session for the codebase.

**Pull request merged**
