### PR TITLE
Turla Driver Loader wrapper module

### PR DESCRIPTION
**Pull request by wwebb-r7**
This is a simple module that wraps the [Turla Driver Loader](https://github.com/hfiref0x/TDL), which itself allows you to inject a driver into kernel address space while sidestepping driver signing enforcement on 64 bit targets with a few caveats.  There are some other tools that do the same thing; however, I've found TDL to be the least problematic.

Since the tool contains copyrighted code, users will need to obtain a copy of it themselves from the provided link and place it in ~/.msf4/local/tdl/.  In the future, I think it's worth exploring the licensing issues and working to more stealthily inject the tool or a derivative versus simply uploading and running it, but for now, this is a first step towards some other goals I want to see realized. 

## Verification

List the steps needed to make sure this thing works

- [ ] Get a session on your target with administrator privileges
- [ ] Choose the driver you want to install and place it in the correct location, or set the location via module options.  You can use one of the compiled dummy drivers bundled with the Turla release
- [ ] Have Debug View, Windbg, or some other tool running on the target such that you can verify DbgPrint() messages
- [ ] `use post/windows/manage/turla`
- [ ] `set SESSION 1` - or whatever your session number is obviously
- [ ] Configure the other options as needed
- [ ] `run`
- [ ] **Verify** that it uploads and executes the tool
- [ ] **Verify** that you see DbgPrint() messages in your tool of choice on the target

### CODE REVIEW

**Comment by sempervictus** [comment]
Your timing is impecable. Adding this, thank you.
I think we may want to reach out to the Turla folks to ask for a license format change if they're amenable in order to include it more directly in the meterp/mettle codebase.

**Comment by wwebb-r7** [comment]
Well, the one license we're really concerned with (since the tool doesn't seem to have any itself) is the Virtualbox driver, which is included within the tool.  @bcook-r7 and I took a brief look and it appeared it may be GPL and good to go, but that will take a little more confirmation as licenses at my previous jobs have been nothing to get worried about.  I started work on a similar tool using the same concept last year that would have accomplished the same thing while touching the disk much less--and I would like to see this morph into such eventually--but the biggest problem aside from becoming a Rube Goldberg machine was picking a vulnerable, copyrighted driver to distribute.

If that portion checks out, I'll definitely reach out to them (although IIRC I may be banned or deactivated on kernelmode.info - someone else may need to ask nicely)

**Comment by sempervictus** [comment]
wweb-r7: any chance you could push your effort to a public repo?
I'm not a fan of the file dropping either, especially for something this easily signed for... encoding/evasion tricks may give us some entropy, but its still a forensic footprint the size of a mortar blast. Curious to see how you got around the initial loading semantics to avoid that.
There are other drivers which can be used if GPL becomes an issue for commercial distribution (Pro that is), one of the candidates for our pivot approach was the PCUSA driver which may also be useful - the company no longer exists far as i can tell (a shame, spoke with the owner a few years back, seemed a nice guy).
Sniffer/pivot are already noisy in this manner, and if we can find a way to strap drivers without writing to disk (or the event log) then i'd say thats the brass ring.

**Comment by wwebb-r7** [comment]
Sent you an invite on freenode as I imagine this could become a long discussion, and I typically have a terminal up more often than GH.

I'll have to sort through my code and see what I have.  As far as not touching the disk with the driver file, that's a problem I've approached many times in the past and never solved.  Reflectively injecting the tool executable itself is entirely possible though.

**Comment by sempervictus** [comment]
@wwebb-r7: can we bury this in a meterp ext? The usage potential is very high, and I learned with PSH, there is no pleasing the masses on access.

**Comment by wwebb-r7** [comment]
I've been working sporadically on just that for the last two weeks.

**Comment by wwebb-r7** [comment]
@sempervictus I have a working branch up [here](https://github.com/wwebb-r7/metasploit-payloads/tree/driver-ext), along with a identically named framework branch if you're up for testing it or anything else that would utilize it.  It's rough and noisy at the moment, and will likely change a good bit over the next few days, but it works.

**Comment by wwebb-r7** [comment]
This shall soon be replaced.  Closing for now.

**Pull request closed without merging**
