### PR TITLE
move autoroute to a more sensible location

### PR DESCRIPTION
**Pull request by busterb**
This moves the autoroute module, which used to be an autoroute meterpreter script, to a place where any meterpreter can use it, since multiple meterpreters actually support autoroute.

## Verification

- [ ] Start `msfconsole` and get a linux meterpreter session (use mettle or python meterpreter)
- [ ] `use post/multi/manage/autoroute`
- [ ] `set session -1` and run it
- [ ] **Verify** that you get routes automatically added

Sorry, I'm not a huge user of this module yet, so I'm not sure how to better test its ins and outs. This also fixes a bug using the autoroute meterpreter script where the '-h' help command fails the first time you run it on a session.

https://www.youtube.com/watch?v=hdcTmpvDO0I

### CODE REVIEW

**Comment by sn0wfa11** [comment]
@busterb, I'm happy to help test this out. I wrote the update for this module a while back and know how it works. In hindsight it should have been made a multi module back then. Thanks for working on this.

If you can update the author line to: `Josh Hale "sn0wfa11"` in this PR too, I would appreciate it ;)

**Comment by sn0wfa11** [comment]
And... I immediately remember a lot of the issues with routing from working on the PR #7664. I will have some commits coming to this PR to better make this a "multi" module. Not all Meterpreter sessions report routes the same way.

**Comment by sn0wfa11** [comment]
Pushed some commits to bcook-r7#8 that should shore up the multi functionality and fix a few other issues. Please test and get back to me if there are any problems.

**Comment by busterb** [comment]
thanks @sn0wfa11 , checking it out now

**Comment by busterb** [comment]
Looks good, merged your changes @sn0wfa11

**Comment by busterb** [comment]
rebased to fix merge conflicts

**Comment by egypt** [comment]
# Release Notes

This moves `post/windows/manage/autoroute` to `post/multi`, since it works with Meterpreters on more than just Windows.

**Comment by busterb** [comment]
Thanks @egypt - I'll hunt for any straggler references next. Also thanks a lot @sn0wfa11 for the help here!

**Pull request merged**
