### PR TITLE
Feature/allow nexpose certificate validation

### PR DESCRIPTION
**Pull request by jmartin-tech**
Expands on https://github.com/rapid7/metasploit-framework/pull/7963 to allow connection validation based on a known trusted certificate as supported by nexpose-client gem

## Verification

List the steps needed to make sure this thing works

- [x] Configure a Rapid7 Nexpose console
- [x] Replace default certificate, ensure hostname match for "Common Name"
- [x] Obtain certificate as pem file on disk
- [x] Start `msfconsole`
- [x] `load nexpose`
- [x] **Verify** nexpose_connect using matching hostname and pem from above succeeds
- [x] **Verify** execute each of the remaining nexpose_* commands
- [x] **Verify** nexpose_connect with "ok" in place of trusted certificate succeeds
- [x] **Verify** nexpose_connect with missing file of other pem in place of trusted certificate fails
- [x] **Verify** nexpose_save for each connect scenario above functions as expected
- [x] **Verify** modules/auxiliary/admin/http/nexpose_xxe_file_read.rb functions as expected

### CODE REVIEW

**Comment by jbarnett-r7** [comment]
Seeing an issue when executing the `nexpose_scan <ip address>` command. It looks like it tries to delete the temporary Nexpose site before the scan is fully complete:

```
msf > nexpose_scan 1.1.1.1
[*] Scanning 1 addresses with template pentest-audit in sets of 32
[*]  >> Deletion of temporary site and report failed: #<Nexpose::APIError: NexposeAPI: Action failed: The site cannot be deleted since there is an active scan associated with it.>
[*] Completed the scan of 1 addresses
```

This leaves the site leftover on the Nexpose side. and creates clutter. This works correctly on master.

So far other functions seem to be working the same as master. Will continue testing.

**Comment by jmartin-r7** [comment]
Addressed scan not complete on delete, conflict on Gemfile.lock should be resolved while landing to master.

**Comment by jbarnett-r7** [comment]
The nexpose_scan command is now working correctly. I encountered an error when verifying the /auxiliary/admin/http/nexpose_xxe_file_read.rb module, but it looks like that occurs on master as well. I was able verify the login is successful with the gem, so the changes made here seem to be working.

Good to land.

**Comment by busterb** [comment]
## Release Notes

This upgrades Metasploit to use the latest Nexpose client libraries, also allowing Metasploit to validate that it is communicating with a trusted Nexpose instance via a preconfigured SSL certificate.

**Pull request merged**
