### PR TITLE
Fixed Typos

### PR DESCRIPTION
**Pull request by Biswajee**
Simply removed some typing mistakes.

### CODE REVIEW

**Comment by h00die** [comment]
Changes look good to me. If no one lands this in 3hrs, I'll take care of it

**Comment by h00die** [comment]
# Release Notes
This PR adds a spelling fix for the wmap rc file.

**Comment by h00die** [comment]
Thanks for the fix, and congrats on a VERY quick first contribution land!

**Comment by Biswajee** [comment]
Thank You.

**Pull request merged**
