### PR TITLE
Add some meterpreter specs

### PR DESCRIPTION
**Pull request by jlee-r7**
This is old as hell, I'm just going through some old forgotten git stashes.
# Verification
- [ ] it doesn't blow up

### CODE REVIEW

**Comment by bcook-r7** [comment]
I love specs. Kicking off travis again to see if it passes the second time.

**Comment by jlee-r7** [comment]
image

**Comment by OJ** [comment]
run tests

**Comment by kernelsmith** [comment]
OK, I actually LOL'd on that OJ

**Comment by bcook-r7** [comment]
The new spec works fine, thanks!
```
bundle exec rspec spec/lib/msf/base/sessions/meterpreter_spec.rb
Msf::Sessions::Meterpreter .......

Finished in 0.0232 seconds
7 examples, 0 failures
```

As a side note, the weak SSL cipher specs appear fail (through no fault of this PR) if your system has a new version of OpenSSL.

**Pull request merged**
