### PR TITLE
add a DISABLE_RDBCOMPRESSION option for redis file_upload

### PR DESCRIPTION
**Pull request by nixawk**
[#6351](https://github.com/rapid7/metasploit-framework/issues/6351). The rdbcompression option is yes by default, and redis can break our payload content. It 's useful to disable rdbcompression option.

```
msf auxiliary(file_upload) > show options

Module options (auxiliary/scanner/redis/file_upload):

   Name                    Current Setting  Required  Description
   ----                    ---------------  --------  -----------
   DISABLE_RDBCOMPRESSION  true             no        Disable string compression when dump .rdb databases
   LocalFile               /tmp/123.txt     no        Local file to be uploaded
   Password                redispass        no        Redis password for authentication test
   RHOSTS                  10.0.250.238     yes       The target address range or CIDR identifier
   RPORT                   6379             yes       The target port
   RemoteFile              /tmp/test        no        Remote file path
   THREADS                 1                yes       The number of concurrent threads

msf auxiliary(file_upload) > 
```

```
┌─[]─[~]
└──╼   cat /tmp/test 
REDIS0006� nzTARfubSWJfNSTGFYsSjnamxpIDJOiH@�
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCC
```

### CODE REVIEW

**Comment by jhart-r7** [comment]
Sorry, @gmikeska-r7, I neglected to assign myself before I started working on it, but there were several issues with what was done here and I dropped @all3g a PR in https://github.com/open-security/metasploit-framework/issues/5 (linked above) to fix those.

**Comment by bcook-r7** [comment]
Hmm, and there was some confusion on the merge message; would it make sense to redirect your PR to metasploit-framework and we can land both with the proper merge message? Any issues with @jhart-r7's updates @all3g ? No rush, I can help when you guys are ready.

**Comment by bcook-r7** [comment]
I just had a quick look at open-security#5 and those changes make sense to me.

**Comment by all3g** [comment]
Thanks @jhart-r7 . My pull is merged by @gmikeska-r7 . Please give a PR to rapid7's metasploit-framework and fix my issues.

**Comment by bcook-r7** [comment]
I took care of merging the missing commits, thanks!

**Comment by jhart-r7** [comment]
Thanks @bcook-r7!

**Comment by all3g** [comment]
Thanks all.

**Pull request merged**
