### PR TITLE
chinese caidao backdoor bruteforce

### PR DESCRIPTION
**Pull request by nixawk**
This module is used to brute chinese caidao php/asp/aspx backdoor.

### CODE REVIEW

**Comment by hmoore-r7** [comment]
Hello! Thank you for the PR. Brute force modules should use the existing mixins for this task and abstract the authentication logic to a LoginScanner class. For an example of this, take a look at pull request #4787. This ensures that all brute force modules have a similar syntax and that a successful brute force will record the information properly.

**Comment by all3g** [comment]
Thanks !
I'll learn more about LoginScanner, and come back soon.

**Comment by all3g** [comment]
Excuse me, This is a problem for how to exit bruteforce loop.
[/lib/msf/core/auxiliary/auth_brute.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/auxiliary/auth_brute.rb) show us :
- **:next_user** # This means success for that user.
- **:skip_user** # Skip the user in non-success cases.
-  **:connection_error** # Report an error, skip this cred, but don't neccisarily abort.

But if password is the only bruteforce variable, what can it do to exit the bruteforce loop ? 
Is there a way called **:next_pass** ? 

Code is [here](https://github.com/all3g/metasploit-framework/blob/ae5934659c625d419ef62d5940d6d893474a1950/modules/auxiliary/scanner/http/cn_caidao_backdoor_bruteforce.rb)

I'm a newbie, thanks for the help !

**Comment by all3g** [comment]
"auxiliary/scanner/http/cn_caidao_backdoor_bruteforce is still calling the deprecated"  error appears here.
-------------------------------
What I've done as follow: 

```
msf auxiliary(cn_caidao_backdoor_bruteforce) > show options 

Module options (auxiliary/scanner/http/cn_caidao_backdoor_bruteforce):

   Name              Current Setting                                                                        Required  Description
   ----              ---------------                                                                        --------  -----------
   BLANK_PASSWORDS   false                                                                                  no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                                                                                      yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false                                                                                  no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false                                                                                  no        Add all passwords in the current database to the list
   DB_ALL_USERS      false                                                                                  no        Add all users in the current database to the list
   PASSWORD                                                                                                 no        A specific password to authenticate with
   PASS_FILE         /home/all3g/sectools/metasploit-framework/data/wordlists/backdoor_passwords.txt  no        File containing passwords, one per line
   Proxies                                                                                                  no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            10.5.123.10                                                                            yes       The target address range or CIDR identifier
   RPORT             80                                                                                     yes       The target port
   STOP_ON_SUCCESS   false                                                                                  yes       Stop guessing when a credential works for a host
   TARGETURI         /bk.php                                                                                yes       The URI to authenticate against
   THREADS           5                                                                                      yes       The number of concurrent threads
   TYPE              PHP                                                                                    yes       backdoor type (accepted: PHP, ASP, ASPX)
   USERNAME          caidao                                                                                 no        A specific username to authenticate as
   USERPASS_FILE                                                                                            no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false                                                                                  no        Try the username as the password for all users
   USER_FILE                                                                                                no        File containing usernames, one per line
   VERBOSE           true                                                                                   yes       Whether to print output for all attempts
   VHOST                                                                                                    no        HTTP server virtual host

msf auxiliary(cn_caidao_backdoor_bruteforce) > run

[*] 10.5.123.10:80 - Trying to crack php backdoor
[*] 10.5.123.10:80 - Trying "/bk.php" : ""
[*] 10.5.123.10:80 - Trying "/bk.php" : "."
[*] 10.5.123.10:80 - Trying "/bk.php" : """
[*] 10.5.123.10:80 - Trying "/bk.php" : "*"
[*] 10.5.123.10:80 - Trying "/bk.php" : "#"
[*] 10.5.123.10:80 - Trying "/bk.php" : "0"
[*] 10.5.123.10:80 - Trying "/bk.php" : "1"
[*] 10.5.123.10:80 - Trying "/bk.php" : "2"
[*] 10.5.123.10:80 - Trying "/bk.php" : "3"
[+] 10.5.123.10:80 - Successful login: password - "3"
[-] *** auxiliary/scanner/http/cn_caidao_backdoor_bruteforce is still calling the deprecated report_auth_info method! This needs to be updated!
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(cn_caidao_backdoor_bruteforce) > set PASSWORD "3"
PASSWORD => 3
msf auxiliary(cn_caidao_backdoor_bruteforce) > unset PASS_FILE 
Unsetting PASS_FILE...
msf auxiliary(cn_caidao_backdoor_bruteforce) > run

[*] 10.5.123.10:80 - Trying to crack php backdoor
[*] 10.5.123.10:80 - Trying "/bk.php" : "3"
[+] 10.5.123.10:80 - Successful login: password - "3"
[-] *** auxiliary/scanner/http/cn_caidao_backdoor_bruteforce is still calling the deprecated report_auth_info method! This needs to be updated!
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed

```

**Comment by hmoore-r7** [comment]
The ```report_auth_info()``` method is deprecated, this needs to be reworked to use LoginScanner and the new type of credential reporting. The previous example for Zabbix is a decent reference. 

Regarding the password issue, I am not sure, maybe @dmaloney-r7 or @jlee-r7 has an idea.

**Comment by jvazquez-r7** [comment]
@all3g as already @hmoore-r7 explained this module should be a ```LoginScanner```. Here is the documentation necessary to create a ```LoginScanner```: https://github.com/rapid7/metasploit-framework/wiki/Creating-Metasploit-Framework-LoginScanners

Also, the framework is now plenty of modules acting as ```LoginScanner```, as ones pointed by @hmoore-r7 (#4787)

Please let us know if you're interested in finishing it! Otherwise we'll move it to unstable so maybe in the future someone finishes it!

Thanks!

**Comment by jvazquez-r7** [comment]
This module has been landed into unstable here https://github.com/rapid7/metasploit-framework/pull/5406, since it needs to use the LoginScanner/Credentials code like explained on: https://github.com/rapid7/metasploit-framework/wiki/Creating-Metasploit-Framework-LoginScanners and https://github.com/rapid7/metasploit-framework/wiki/How-to-write-a-HTTP-LoginScanner-Module

@all3g feel free to open a new pull request at any moment if you would like to finish it and land into master! Thanks!

**Pull request closed without merging**
