### PR TITLE
Issue/7853 address tlv enum consistency

### PR DESCRIPTION
**Pull request by jmartin-tech**
Address consistency for TLV_TYPE_MIGRATE_LEN.

https://github.com/rapid7/metasploit-framework/issues/7853

## Verification

List the steps needed to make sure this thing works

- [x] from master branch `git cherry-pick 7cf812e --no-commit`
- [x] `rake rspec`
- [x] **Verify** Rex::Post::Meterpreter::Packet tests fail
- [x] **Verify** Travis tests passed here

### CODE REVIEW

**Comment by busterb** [comment]
Ah, got it backwards. Thanks!

**Comment by OJ** [comment]
This is pre-7am OJ wondering how TLV_TYPE_MIGRATE_LEN is still a thing when
he replaced it with TLV_TYPE_MIGRATE_PAYLOAD_LEN during the stub work...

**Comment by jmartin-r7** [comment]
TLV_TYPE_MIGRATE_LEN is all over metasploit-payloads so it made more sense to me to create consistency by holding that constant name, than to impact the 18+ place in many languages in payloads.

**Comment by busterb** [comment]
I think I see the issue - metasploit-payloads was using _both_ still.
```
metasploit-payloads$ git grep TLV_TYPE_MIGRATE_LEN
c/meterpreter/source/extensions/python/Lib/meterpreter/core.py:TLV_TYPE_MIGRATE_LEN           = TLV_META_TYPE_UINT    | 403
java/meterpreter/meterpreter/src/main/java/com/metasploit/meterpreter/TLVType.java:    public static final int TLV_TYPE_MIGRATE_LEN  = TLVPacket.TLV_META_TYPE_UINT   | 403;
java/meterpreter/meterpreter/src/main/java/com/metasploit/meterpreter/command/NotYetImplementedCommand.java:        typeNames.put(new Integer(TLVType.TLV_TYPE_MIGRATE_LEN), "TLV_TYPE_MIGRATE_LEN");
php/meterpreter/meterpreter.php:define("TLV_TYPE_MIGRATE_LEN",         TLV_META_TYPE_UINT   | 403);
python/meterpreter/meterpreter.py:TLV_TYPE_MIGRATE_LEN           = TLV_META_TYPE_UINT    | 403
```

**Comment by busterb** [comment]
```
metasploit-payloads$ git grep TLV_TYPE_MIGRATE_PAYLOAD_LEN
c/meterpreter/source/common/arch/posix/base_dispatch.c: l.length = packet_get_tlv_value_uint(packet, TLV_TYPE_MIGRATE_PAYLOAD_LEN);
c/meterpreter/source/common/arch/win/i386/base_dispatch.c:              dwPayloadLength = packet_get_tlv_value_uint(packet, TLV_TYPE_MIGRATE_PAYLOAD_LEN);
c/meterpreter/source/common/core.h:     TLV_TYPE_MIGRATE_PAYLOAD_LEN = TLV_VALUE(TLV_META_TYPE_UINT,      403),   ///! Represents a migration payload size/length in bytes (unsigned integer).
```
sounds like @jmartin-r7 was using the non-windows meterpreters as the source of truth. we should change them to match Windows meterpreter's name?

**Comment by OJ** [comment]
That's correct. Given that none of the other Meterpreters support migration, I would have thought that Windows would be the source of truth.

This was renamed because there are now 2 lengths that are sent a part of the migration TLV, one is the length of the payload, and the other is the length of the stub. A generate `MIGRATE_LEN` doesn't say which one.

I know I sound picky, but I prefer to leave it `TLV_TYPE_MIGRATE_PAYLOAD_LEN` as it is a more accurate description.

The question is, what do we do with the references in the other Meterpreters? Update them, or remove them entirely? I'm for the latter, given the lack of support for the feature.

**Comment by busterb** [comment]
Cool, we can remove from payloads, then rename back on framework.

**Comment by OJ** [comment]
```
$ grep -r MIGRATE_LEN . | grep -v Binary | grep -v compat | wc -l
       5
```
Not sure where 18 came from, unless you're including generated source and binaries.

**Comment by OJ** [comment]
The java version has a stack of code that throws exceptions for all of the TLVs it doesn't support. I guess we should carry that on with the new stuff too.

**Pull request merged**
