### PR TITLE
RFC (as in, "please look over this and weigh in"): Overload Net::DNS Socket use for Rex Sockets

### PR DESCRIPTION
**Pull request by sempervictus**
Replace the use of ::Socket during DNS resolution with Rex::Socket.
Reduce leakage of data, and provide implicit proxy and L3 pivot
support.

### CODE REVIEW

**Comment by sempervictus** [comment]
For a bit of context on this: these changes were initially made in support of the multithreaded dns enum changes to allow for rapid reconnaissance of domain controllers over L3 pivots and performing external reconnaissance via TOR or other proxy services to avoid source address disclosure/leakage. 

If there's interest, similar changes exist for Net::HTTP, LDAP, NTP, and RTSP. They're all intended to allow us to work with existing libraries leveraging standard socket implementations until we have native Rex support for the functionality they present.

**Comment by sempervictus** [comment]
After some discussion in IRC last night, @hmoore-r7 suggested we get some review on this from the community to decide how we want to proceed. The issue in question is as follows:

Do we use the hackey-patch here to provide this functionality to all components (modules for most people) using net/dns for the actual resolution of addresses, or is there enough momentum in the community to build a native Rex::DNS stack which only uses net/dns to parse out records or compose them, but utilizes Rex for all socket/transport operations. 

Ideally someone from the community would pick up the core of a native DNS implementation for sockets, configuration, Msf callbacks, and all that jazz. I'd be glad to lend a hand, but personally wont have bandwidth until at least July timeframe for this, and i have SSH to address anyway (an even older, more swollen, can of whoop...).
Otherwise, if we believe this to be a sufficiently important issue to apply this bandaid framework-wide, we should do so and put native implementation into the relevant work queues of anyone spending time in /lib.

**Comment by hmoore-r7** [comment]
Related: #5498

**Comment by sempervictus** [comment]
The crickets are almost deafening. 
@community: RFC means request for comment, so please, comment - if we put the entire burden of decision making and implemention of /lib on the shoulders of people who have immediate customer needs to serve, it might take a while before MSF can affect the alien mothership's shields... or whatever you plan to use it for.

**Comment by OJ** [comment]
Sorry @sempervictus, this isn't really my area of expertise, so I haven't chimed in because I don't have an educated opinion on Ruby sockets vs Rex sockets.

**Comment by hmoore-r7** [comment]
@sempervictus Agree that this is still an issue, but there are far bigger issues with the library right now. the use of @logger is a bad fit for Framework and the other hacks in this code are pretty awful. Not your fault, but I think we need to take a harder look at this as a long-term rewrite versus a short-term fix for Rex support.

**Pull request closed without merging**
