### PR TITLE
New password from Nicholas Hathaway

### PR DESCRIPTION
**Pull request by wchen-r7**
So my buddy Nicholas Hathaway from college found this password in the middle of a pentest, and would like to put this in Metasploit. Obviously he can't say what he used this for, but he provided a screenshot to prove legitimacy.

screen shot 2015-01-19 at 9 07 22 pm

### CODE REVIEW

**Comment by kernelsmith** [comment]
There's a non-private IP and user info in that screenshot.

**Comment by kernelsmith** [comment]
Oh, nm, looks like it was altered. My bad

**Comment by g33xter** [comment]
Is this screenshot from "BlackHat" movie?

**Comment by wchen-r7** [comment]
https://www.youtube.com/watch?v=5NBKwRXDTJY

**Comment by wvu-r7** [comment]
Wow, haha, that was fast.

**Comment by jcran** [comment]
:tophat:

**Comment by kernelsmith** [comment]
Good thing it wasn't from American Sniper or Michael Moore or Tod may have unceremoniously closed your PR. ;)

**Pull request merged**
