### PR TITLE
Cambium snmp

### PR DESCRIPTION
**Pull request by juushya**
Cambium devices (ePMP, PMP, Force, others) can be administered using SNMP. The device configuration contains IP addresses, keys, and passwords, amongst other information. This module uses SNMP to extract Cambium ePMP device configuration. On certain software versions, specific device configuration values can be accessed using SNMP RO string, even though only SNMP RW string should be able to access them, according to MIB documentation.

The module also triggers full configuration backup, and retrieves the backup url. The configuration file can then be downloaded without authentication. The module has been tested primarily on Cambium ePMP current version (3.2.x, as of today), PMP, and Force units.

Note: If the backup url is not retrieved, it is recommended to increase the TIMEOUT and reduce the THREADS. Backup url can also be retrieved by quering the OID as follows:

```
snmpget -v2c -c public 1.3.3.7 1.3.6.1.4.1.17713.21.6.4.13.0
```

## Verification Steps

1. Do: ```use auxiliary/scanner/snmp/epmp_snmp_loot```
2. Do: ```set RHOSTS [IP]```
3. Do: ```set RPORT [PORT]```
4. Do: ```run```

## Checks run
```
msftidy
rubocop
```

### CODE REVIEW

**Comment by trylinux** [comment]
FYI this was first discussed here 
https://blog.cari.net/carisirt-defaulting-on-our-passwords-pt-2-attacker-friendly-security/

**Comment by juushya** [comment]
@trylinux Thanks for the link. But it doesn't seem to discuss anything about broken / misconfigured access privileges of SNMP RO community strings. It also doesn't discuss access control flaws that allow dumping backup files without any authentication. Is there something else to be checked there?

**Comment by wwebb-r7** [comment]
### Release Notes

This update adds an auxiliary module which downloads the configuration file of a Cambium ePMP device via SNMP

**Comment by juushya** [comment]
@wwebb-r7 I just noticed the References is still a placeholder. References URL:
`(https://ipositivesecurity.com/2017/04/07/cambium-snmp-security-vulnerabilities/)`. Any pointers on how to update the landed module please.? Thanks.

**Comment by h00die** [comment]
Just submit a new PR with the change. If you do, I'll land it in the next few hours

**Pull request merged**
