### PR TITLE
Refactor proxy-enabled payload handling

### PR DESCRIPTION
**Pull request by hdm**
This fixes a couple bugs and generally cleans up the proxy option parsing code.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Can you provide us some test cases so we can verify the fixes? Is the rebase still in progress?

**Comment by sempervictus** [comment]
Been running this for a while now by the way, no issues so far, despite my consistent attempts at mangling the framework.

**Comment by bcook-r7** [comment]
Rebasing this wasn't too much trouble, I pushed a new branch here: https://github.com/bcook-r7/metasploit-framework/commits/land-4295-refactor-proxy

I have a squid proxy setup from an earlier PR, anything else that should be tested to verify proxy support works properly?

**Comment by bcook-r7** [comment]
Also, the changes from PROXY* to PROXY_* - don't these cause backward compatibility issues that we should be aware of with upstream tools/scripts?

**Comment by bcook-r7** [comment]
@hmoore-r7 I believe there are some future PRs that may be waiting on this one to land. Do you mind if I rebase with a new PR, or do you want to update this one?

**Comment by hmoore-r7** [comment]
@bcook-r7 Please do! Feel free to close this and push up your rebased PR. Not concerned with back-compat given the newness of proxy support in general.

**Comment by hmoore-r7** [comment]
@bcook-r7 Feel free to close this out once the new PR is up. I took a different approach with the reverse_http(s) factor in terms of the option names ```StagerProxy(Host|Port|User|Pass)``` but am happy to change so long as were consistent.

**Comment by bcook-r7** [comment]
Updated PR at #4935, still double-checking it myself since I just re-rebased it on master.

**Comment by bcook-r7** [comment]
I incorrectly rebased this PR since it undid the refactoring work in 1930eb1bf8a1515c8ebf4917cd6c069bc93b6d6c, resurrecting this PR.

**Pull request merged**
