### PR TITLE
 Printing Version speed is improved

### PR DESCRIPTION
**Pull request by Prady2006**
This is the patch for the issue #13044 .

### CODE REVIEW

**Comment by Prady2006** [comment]
this is the patch for #13044.

**Comment by dwelch-r7** [comment]
hey @Prady2006 appreciate you re-upping this PR
I've just given it a quick test though and there are a couple issues which I don't think I explained very well in the PR I closed out

```
./msfconsole -x 'exit'
Exception encountered: invalid option: -x
```
there are other options that can be passed into msfconsole your PR seems to _only_ allow for the version parameter to work now (although it is super quick now) 
you could potentially put some work in to allow anything to be passed in but if the paramter is `version` return early rather than continuing on to load up the whole framework

**Comment by Prady2006** [comment]
this is the patch for issue  #13044. I have tried to make changes according to what you told me . I am only checking for version and rest all arguments are being executed ,after the initialization of framework .

**Comment by Prady2006** [comment]
this is the patch for  #13044. I have tried to make changes please review them and tell me if something more needs to be done .

**Comment by nsa** [comment]
image

As @wvu-r7 said in my issue:

>  Splitting off the code for msfconsole's help or version is a little more involved

**Comment by Prady2006** [comment]
I dont get you .When you can easily get the version , then why to complicate things ?

**Comment by Prady2006** [comment]
I guess the issue is more  about the --version flag . If i am wrong please tell me , maybe i am not getting you @nsa .

**Comment by Prady2006** [comment]
hey , any nudges on what should i do, if the way i implemented is not correct . @dwelch-r7

**Comment by jmartin-r7** [comment]
Currently this PR simply add a new parser early in the code path, while that gets to a stated goal it does not account for impacts to the rest of the execution. Please look at the problem from a more holistic approach.  Find where the code already parses options and determine how to improve or break apart the workflow to get a better result.  By consuming the arguments and only handling the `--version` flag this code could mangle the original command or change the environment in an unexpected way causing other location that need to parse to change behaviour.

**Pull request closed without merging**
