### PR TITLE
Bump Ruby version to 2.1.6

### PR DESCRIPTION
**Pull request by todb-r7**
Note, this should also happen for pretty much every other repo that wants to be on "latest" Ruby in the 2.1.x line.

The justification is a minor security issue with the way hostnames are validated on SSL certificates. This does not appear to affect Metasploit directly at all, but may impact other, unrelated Ruby-based tasks. For more, see: https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-1-6-released/ .

Also, it's nice to stay abreast of Ruby versioning.
## Local implementation

On this branch, or after merged (assuming an RVM environment as described on http://r-7.co/MSF-DEV)
- [x] `cd .`
- [x] Note the message to install Ruby 2.1.6.
- [x] `rvm install ruby-2.1.6`
- [x] `ruby -e "puts RUBY_VERSION"`
- [x] Note that 2.1.6 was installed.
- [x] `cd .`
- [x] Note the empty gemset
- [x] `gem install bundler && bundle install`
## After landing
- [x] Update the wiki at http://r-7.co/MSF-DEV to recommend `ruby-2.1.6`
## Verification
- [x] Travis passes with all green
- [x] See the wiki is updated: Ctrl-F 2.1.5 should return no hits.

### CODE REVIEW

**Comment by todb-r7** [comment]
Ping @shuckins-r7 and @cdoughty-r7 and @lsanchez-r7  there are likely upstream steps to take here as well. Don't want you surprised by this.

**Comment by bcook-r7** [comment]
I've been updating omnibus to ruby-2.1.6 (along with bumping a few other things) - will let you know if I run into any snags.

**Comment by todb-r7** [comment]
Hmm Travis doesn't automatically bump to 2.1.6, looks like:

https://travis-ci.org/rapid7/metasploit-framework/jobs/61661802#L117

Experimenting with naming it directly, one sec.

**Comment by lsanchez-r7** [comment]
Is there a reason to bump this before rails 4?

**Comment by lsanchez-r7** [comment]
Just caught the changelog, we should let GES know that we should put this in the rails 4 build

From: Lance Sanchez <lance_sanchez@rapid7.com<mailto:lance_sanchez@rapid7.com>>
Date: Thursday, May 7, 2015 at 1:45 PM
To: rapid7/metasploit-framework <reply@reply.github.com<mailto:reply@reply.github.com>>, rapid7/metasploit-framework <metasploit-framework@noreply.github.com<mailto:metasploit-framework@noreply.github.com>>
Cc: Lance Sanchez <lance_sanchez@rapid7.com<mailto:lance_sanchez@rapid7.com>>
Subject: Re: [metasploit-framework] Bump Ruby version to 2.1.6 (#5317)

Is there a reason to bump this before rails 4?

**Comment by todb-r7** [comment]
Slightly more offline convo with @bcook-r7 -- actually landing this PR only affects:

1. Source checkouts of metasploit-framework
1. Travis testing

This is because binary installs (Metasploit Pro, Kali's apt source, and other builds) already specifically pick a version of Ruby to ship, and don't care about `.ruby-version`.

**Comment by bcook-r7** [comment]
```
ruby-2.1.5 is not installed.
To install do: 'rvm install ruby-2.1.5'
bcook@toaster:~/projects/metasploit-framework$ rvm install ruby-2.1.6
```
...much compiling later...
```
bcook@toaster:~/projects/metasploit-framework$ ruby -e "puts RUBY_VERSION"
2.1.6
bcook@toaster:~/projects/metasploit-framework$ cd .
ruby-2.1.6 - #gemset created /home/bcook/.rvm/gems/ruby-2.1.6@metasploit-framework
ruby-2.1.6 - #generating metasploit-framework wrappers..........
bcook@toaster:~/projects/metasploit-framework$ gem install bundler && bundle install
```
...much more compiling later...
```
bcook@toaster:~/projects/metasploit-framework$ ruby -e "puts RUBY_VERSION"
2.1.6
bcook@toaster:~/projects/metasploit-framework$ ./msfconsole -q
msf >
```

**Comment by bcook-r7** [comment]
Apologies in advance to all those with slow machines, this does require a bit of time to update.

**Pull request merged**
