### PR TITLE
9092513778

### PR DESCRIPTION
**Pull request by jacksupinu**
Looks like this:

```
50 character commit title

Longer description, if needed, wrapped at 72 characters.

[See #XXXX]
```

### CODE REVIEW

**Comment by todb-r7** [comment]
Hi @Jacksupinu. What were you trying to do here? That branch isn't ready for a PR yet.

**Comment by jacksupinu** [comment]
im trying to get pen number or access to sms

**Comment by wvu-r7** [comment]
@jacksupinu: Can you clarify what you mean?

**Comment by todb-r7** [comment]
@jacksupinu this is a Pull Request queue for the Metasploit Framework, a penetration testing framework used by thousands world-wide to safely and efficiently test and validate the security posture of organizations. It is not the place to ask for assistance for an engagement.

You should be aware that anything you write on public repositories on GitHub is, in fact, public.

For more information on Metasploit or to request a free 7-day trial of Metasploit Pro, you should visit https://www.metasploit.com/ .

**Pull request closed without merging**
