### PR TITLE
Edit spaces within the powershell session command

### PR DESCRIPTION
**Pull request by benpturner**
Tidying up the powershell shell_command output to clean the spaces.

### CODE REVIEW

**Comment by mubix** [comment]
Can you provide a before and after as to why you made this edit?

**Comment by benpturner** [comment]
@mubix It's fairly straight forward, the new PS session used to respond like this when you run a sessions -c whoami.The reason i've changed this is to make it easier when you write post modules and utilise the shell_command in the powershell session. You will not get any redundant white space, this should have been done at the start.

**Comment by benpturner** [comment]
output

**Comment by benpturner** [comment]
ses

**Pull request merged**
