### PR TITLE
bump ruby version for latest goodies

### PR DESCRIPTION
**Pull request by jmartin-tech**
Just bumps rvm to use the latest released ruby 2.6 version.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] **Verify** some random things
- [ ] **Verify** all Travis automated testing passes

### CODE REVIEW

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by bwatters-r7** [comment]
Looks like the session for one of the linux targets died in the middle of the test:
image
```
[*] Setup: changing working directory to /tmp
[*] Running against session 1
[*] Session type is meterpreter and platform is linux
[*] Starting process tests
[*] Pid: 845
[+] should return its own process id
[-] FAILED: should return a list of processes
```

**Comment by jmartin-r7** [comment]
New test run succeed, error seem to be intermittent issue on the payload test.

**Comment by busterb** [comment]
I bumped Ruby 2.5 in Travis and docker as well.

**Pull request merged**
