### PR TITLE
Add smb1 scanner

### PR DESCRIPTION
**Pull request by loftwing**
Was asked how many computers on a network still supported SMBv1.  This is an attempt to port an SMBv1 scanner into metasploit:

# Description
This module scans for hosts that support the SMBv1 protocol.  It works by sending an SMB_COM_NEGOTATE request to each host specified in RHOSTS and claims that it only supports the following SMB dialects:
```PC NETWORK PROGRAM 1.0
LANMAN1.0
Windows for Workgroups 3.1a
LM1.2X002
LANMAN2.1
NT LM 0.12
```
If the SMB server has SMBv1 enabled it will respond to the request with a dialect selected.
If the SMB server does not support SMBv1 a RST will be sent.

___
# Usage

The following is an example of its usage, where x.x.x.x allows SMBv1 and y.y.y.y does not.

#### A host that does support SMBv1.

```
msf auxiliary(smb1) > use auxiliary/scanner/smb/smb1
msf auxiliary(smb1) > set RHOSTS x.x.x.x
RHOSTS => x.x.x.x
msf auxiliary(smb1) > run

[+] x.x.x.x:445        - x.x.x.x supports SMBv1 dialect.
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb1) > services -S x.x.x.x

Services
========

host        port  proto  name  state  info
----        ----  -----  ----  -----  ----
x.x.x.x  445   tcp    smb1  open
```

#### A host that does not support SMBv1

```
msf auxiliary(smb1) > use auxiliary/scanner/smb/smb1
msf auxiliary(smb1) > set RHOSTS y.y.y.y
RHOSTS => y.y.y.y
msf auxiliary(smb1) > run

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

### CODE REVIEW

**Comment by sempervictus** [comment]
Awesome, thank you. Adding to teat queue

**Comment by bwatters-r7** [comment]
# Testing
## Success Criteria: "supports SMBv1 dialect"

The test range is default Windows installations, so SMBv1 is on.  Testing negative will take a little longer.
image

**Comment by bwatters-r7** [comment]
# Testing
Same success criteria as above.  Automated testing cannot test for a negative currently, so I turned off SMBv1 and reran, expecting failures.
image
[auxiliary-scanner-smb-smb1_192.168.134.160_1505845501.rc.txt](https://github.com/rapid7/metasploit-framework/files/1315479/auxiliary-scanner-smb-smb1_192.168.134.160_1505845501.rc.txt)
[auxiliary-scanner-smb-smb1_192.168.134.162_1505845501.rc.txt](https://github.com/rapid7/metasploit-framework/files/1315483/auxiliary-scanner-smb-smb1_192.168.134.162_1505845501.rc.txt)
[auxiliary-scanner-smb-smb1_192.168.134.164_1505845501.rc.txt](https://github.com/rapid7/metasploit-framework/files/1315478/auxiliary-scanner-smb-smb1_192.168.134.164_1505845501.rc.txt)
[auxiliary-scanner-smb-smb1_192.168.134.165_1505845501.rc.txt](https://github.com/rapid7/metasploit-framework/files/1315481/auxiliary-scanner-smb-smb1_192.168.134.165_1505845501.rc.txt)
[auxiliary-scanner-smb-smb1_192.168.134.174_1505845501.rc.txt](https://github.com/rapid7/metasploit-framework/files/1315482/auxiliary-scanner-smb-smb1_192.168.134.174_1505845501.rc.txt)
[auxiliary-scanner-smb-smb1_192.168.134.181_1505845501.rc.txt](https://github.com/rapid7/metasploit-framework/files/1315480/auxiliary-scanner-smb-smb1_192.168.134.181_1505845501.rc.txt)

**Comment by bwatters-r7** [comment]
# Release notes
This module allows users to scan for SMBv1 devices in a network

**Pull request merged**
