### PR TITLE
Juniper config processor enhancements

### LINKED ISSUE #16552: lib/msf/core/auxiliary/juniper.rb
line 210 needs to have the regex changed to:
`community "?(?<snmp_community>[\w\d\s\(\)\.\*\/-:_\?=@\,&%\$\+\!]+)"? {(\s+view [\w\-]+;)?\s+authorization read-(?<snmp_permission>only|write)`

with test data `aAa321$+!AaAaaa` (add it to the spec)

### PR DESCRIPTION
**Pull request by h00die**
fixes #16552

Fixes the user, tacas, radius, and snmp sections. also cleans up the formatting

To test this module:

- [ ] ensure spec passes `bundle exec rspec spec/lib/msf/core/auxiliary/juniper_spec.rb`
- [ ] See testing notes below for running module.

## Test Run

Use the following file as test data, which is based on the [outdated one](https://raw.githubusercontent.com/h00die/MSF-Testing-Scripts/master/juniper_ex2200.config):

<details>
<summary>Test Data based on Outdated juniper_ex2200.config</summary>

```
show configuration 
## Last commit: 2016-08-15 13:35:48 UTC by root
version 12.3R7.7;
system {
    host-name h00dieJuniperEx2200;
    root-authentication {
        encrypted-password "$1$pz9b1.fq$foo5r85Ql8mXdoRUe0C1E."; ## SECRET-DATA
    }
    tacplus-server {
        1.1.1.1 secret "$9$aaAAAAAeAA1AAAb2AAjAqmAA"; ## SECRET-DATA
        2.2.2.2 secret "$9$aaaAa/1aAAAa1aaaAAaa11aAA"; ## SECRET-DATA
    }
    login {
        class EXAMPLE {
            idle-timeout 10;
            permissions all;
        }
        user newuser {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$1$rm8FaMFY$k4LFxqsVAiGO5tKqyO9jJ/"; ## SECRET-DATA
            }
        }
        user newuser2 {
            uid 2002;
            class operator;
            authentication {
                encrypted-password "$1$aDZi44AP$bQGGjqPJ.F.Cm5QvX2yaa0"; ## SECRET-DATA
            }
        }
        user newuser3 {
            uid 2003;
            class read-only;
            authentication {
                encrypted-password "$1$1.YvKzUY$dcAj99KngGhFZTpxGjA93."; ## SECRET-DATA
            }
        }
        user newuser4 {
            uid 2004;
            class unauthorized;
            authentication {
                encrypted-password "$1$bdWYaqOE$z6oTSJS3p1R8CoNaos9Ce/"; ## SECRET-DATA
            }
        }
        user newuser5 {
            uid 2005;
            class EXAMPLE;
            authentication {
                encrypted-password "$1$aDZi44AP$bQGGjqPJ.F.Cm5QvX2yaa0"; ## SECRET-DATA
            }
        }
        user newuser6 {
            full-name "full name";
            uid 2006;
            class EXAMPLE;
            authentication {
                encrypted-password "$1$aDZi44AP$bQGGjqPJ.F.Cm5QvX2yaa0"; ## SECRET-DATA
            }
        }
    }
    services {
        ssh {
            root-login allow;
        }
        web-management {
            http;
        }
        dhcp {
            traceoptions {
                file dhcp_logfile;
                level all;
                flag all;
            }
            pool 192.168.10.0/24 {
                address-range low 192.168.10.2 high 192.168.10.254;
            }
        }
    }
    syslog {
        user * {
            any emergency;
        }
        file messages {
            any notice;
            authorization info;
        }
        file interactive-commands {
            interactive-commands any;
        }
    }
}
chassis {
    alarm {
        management-ethernet {
            link-down ignore;
        }
    }
    auto-image-upgrade;
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 192.168.1.3/32;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 192.168.1.4/32;
            }
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 192.168.1.5/24;
            }
        }
    }
    ge-0/0/3 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/4 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/5 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/6 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/7 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/8 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/9 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/10 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/11 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/12 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/13 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/14 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/15 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/16 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/17 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/18 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/19 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/20 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/21 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/22 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/23 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/24 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/25 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/26 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/27 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/28 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/29 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/30 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/31 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/32 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/33 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/34 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/35 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/36 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/37 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/38 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/39 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/40 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/41 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/42 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/43 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/44 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/45 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/46 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/0/47 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/1/0 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/1/1 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/1/2 {
        unit 0 {
            family ethernet-switching;
        }
    }
    ge-0/1/3 {
        unit 0 {
            family ethernet-switching;
        }
    }
    me0 {
        unit 0 {
            family inet {
                address 192.168.1.1/24;
            }
        }
    }
    pp0 {
        unit 0 {
            ppp-options {
                pap {
                    local-name "'pap_username'";
                    local-password "$9$he4revM87-dsevm5TQCAp0BErvLxd4JDNdkPfT/9BIR"; ## SECRET-DATA
                }
            }
        }
    }
    st0 {
        unit 1;
    }
    vlan {
        unit 0 {
            family inet {
                dhcp {
                    vendor-id Juniper-ex2200-48t-4g;
                }
            }
        }
    }
}
snmp {
    name "snmp name";
    description "snmp description";
    location basement;
    contact admin;
    view jweb-view-all {
        oid .1 include;
    }
    community read {
        authorization read-only;
    }
    community write {
        view jweb-view-all;
        authorization read-write;
    }
    community public {
        authorization read-only;
    }
    community private {
        authorization read-write;
    }
    community secretsauce {
        authorization read-write;
    }
    community "hello there" {
        authorization read-write;
    }
    community "aAa321$+!AaAaaa" {
        authorization read-write;
    }
}
routing-options {
    static {
        route 0.0.0.0/0 next-hop 192.168.1.254;
    }
}
protocols {
    igmp-snooping {
        vlan all;
    }
    rstp;
    lldp {
        interface all;
    }
    lldp-med {
        interface all;
    }
}
access {
    radius-server {
        1.1.1.1 secret "$9$Y-4GikqfF39JGCu1Ileq.PQ6AB1hrlMBIyKvWdV"; ## SECRET-DATA
    }
}
ethernet-switching-options {
    storm-control {
        interface all;
    }
}
vlans {
    default {
        l3-interface vlan.0;
    }
}

{master:0}
newuser@h00dieJuniperEx2200>
```
</details>

Now run it with the following command (adjust for file location):
```
use auxiliary/admin/networking/juniper_config
set rhosts 127.0.0.1
set config /tmp/juniper.config
```

### Pre

```
[*] Running module against 127.0.0.1

[*] Importing config
[+] root password hash: $1$pz9b1.fq$foo5r85Ql8mXdoRUe0C1E.
[+] User 2000 named newuser in group super-user found with password hash $1$rm8FaMFY$k4LFxqsVAiGO5tKqyO9jJ/.
[+] User 2002 named newuser2 in group operator found with password hash $1$aDZi44AP$bQGGjqPJ.F.Cm5QvX2yaa0.
[+] User 2003 named newuser3 in group read-only found with password hash $1$1.YvKzUY$dcAj99KngGhFZTpxGjA93..
[+] User 2004 named newuser4 in group unauthorized found with password hash $1$bdWYaqOE$z6oTSJS3p1R8CoNaos9Ce/.
[+] SNMP community read with permissions read-only
[+] SNMP community write with permissions read-write
[+] SNMP community public with permissions read-only
[+] SNMP community private with permissions read-write
[+] SNMP community secretsauce with permissions read-write
[+] SNMP community hello there with permissions read-write
[+] radius server 1.1.1.1 password hash: $9$Y-4GikqfF39JGCu1Ileq.PQ6AB1hrlMBIyKvWdV
[+] PPTP username 'pap_username' hash $9$he4revM87-dsevm5TQCAp0BErvLxd4JDNdkPfT/9BIR via PAP
[+] Config import successful
[*] Auxiliary module execution completed
```

### Post

```
[*] Running module against 127.0.0.1

[*] Importing config
[+] root password hash: $1$pz9b1.fq$foo5r85Ql8mXdoRUe0C1E.
[+] User 2000 named newuser in group super-user found with password hash $1$rm8FaMFY$k4LFxqsVAiGO5tKqyO9jJ/.
[+] User 2002 named newuser2 in group operator found with password hash $1$aDZi44AP$bQGGjqPJ.F.Cm5QvX2yaa0.
[+] User 2003 named newuser3 in group read-only found with password hash $1$1.YvKzUY$dcAj99KngGhFZTpxGjA93..
[+] User 2004 named newuser4 in group unauthorized found with password hash $1$bdWYaqOE$z6oTSJS3p1R8CoNaos9Ce/.
[+] User 2005 named newuser5 in group EXAMPLE found with password hash $1$aDZi44AP$bQGGjqPJ.F.Cm5QvX2yaa0.
[+] User 2006 named newuser6 in group EXAMPLE found with password hash $1$aDZi44AP$bQGGjqPJ.F.Cm5QvX2yaa0.
[+] SNMP community read with permissions read-only
[+] SNMP community write with permissions read-write
[+] SNMP community public with permissions read-only
[+] SNMP community private with permissions read-write
[+] SNMP community secretsauce with permissions read-write
[+] SNMP community hello there with permissions read-write
[+] SNMP community aAa321$+!AaAaaa with permissions read-write
[+] radius server 1.1.1.1 password hash: $9$Y-4GikqfF39JGCu1Ileq.PQ6AB1hrlMBIyKvWdV
[+] tacplus server 1.1.1.1 with password hash $9$aaAAAAAeAA1AAAb2AAjAqmAA
[+] tacplus server 2.2.2.2 with password hash $9$aaaAa/1aAAAa1aaaAAaa11aAA
[+] PPTP username 'pap_username' hash $9$he4revM87-dsevm5TQCAp0BErvLxd4JDNdkPfT/9BIR via PAP
[+] Config import successful
[*] Auxiliary module execution completed
```

Note that we are now processing the following things which we had previously missed: `newuser5`, `newuser6` , `[+] SNMP community aAa321$+!AaAaaa with permissions read-write`, and the 2 `tacplus` lines.

### CODE REVIEW

**Comment by h00die** [comment]
```
└─$ bundle exec rspec spec/lib/msf/core/auxiliary/juniper_spec.rb                        
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 32
Msf::Auxiliary::Juniper .......................

Top 10 slowest examples (1.72 seconds, 68.0% of total time):
  Msf::Auxiliary::Juniper#juniper_junos_config_eater deals with root credentials
    0.35255 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:248
  Msf::Auxiliary::Juniper#create_credential_and_login associates the Metasploit::Credential::Core with a task if passed
    0.28627 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:75
  Msf::Auxiliary::Juniper#create_credential_and_login creates a Metasploit::Credential::Login
    0.17111 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:72
  Msf::Auxiliary::Juniper#juniper_junos_config_eater deals tacplus-server blocks with two cred
    0.14679 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:307
  Msf::Auxiliary::Juniper#juniper_screenos_config_eater deals with snmp-server community with Read permission
    0.13095 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:143
  Msf::Auxiliary::Juniper#juniper_junos_config_eater deals with snmp-server community with Read-Write permissions and view
    0.1292 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:574
  Msf::Auxiliary::Juniper#juniper_junos_config_eater deals with snmp-server community with special characters in the community string
    0.12917 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:629
  Msf::Auxiliary::Juniper#juniper_screenos_config_eater deals with snmp-server community with Read-Write permission
    0.1277 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:164
  Msf::Auxiliary::Juniper#juniper_junos_config_eater deals with snmp-server community with Read permissions
    0.12569 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:547
  Msf::Auxiliary::Juniper#juniper_junos_config_eater deals with snmp-server community with a space in the community string
    0.12395 seconds ./spec/lib/msf/core/auxiliary/juniper_spec.rb:602

Finished in 2.53 seconds (files took 4.29 seconds to load)
23 examples, 0 failures

Randomized with seed 32
Coverage report generated for RSpec to /metasploit-framework/coverage. 2942 / 13024 LOC (22.59%) covered.
```

**Comment by h00die** [comment]
There actually aren't that many "real" code changes, most of it is just formatting changes from rubocop.  However, I totally get what you're saying, from an outside perspective it looks like a nightmare.

I tried to make commit 1 all the rubocop changes, and then the next 2 commits the actual code updates... however it looks like there was significant bleedover.

You should just be able to run the test case to confirm the changes are good. 

What if I close this PR, and re-try so that its 2 commits:
1. rubocop changes (significant)
2. the code and spec updates

does that sound like a plan?

**Comment by gwillcox-r7** [comment]
> 

I'm happy to review this as is, however the question is more that I don't know what your test cases are. Your information in https://github.com/rapid7/metasploit-framework/issues/16552 isn't enough to do testing of this issue.

If you feel that breaking this apart into two PRs would be helpful though I'd be happy to proceed on that basis.

**Comment by h00die** [comment]
@gwillcox-r7 sorry for the 3 week delay, finally getting back around to MSF now.  Updated the original comment with 2 things to test, and a file to test against which will show the improvements!

**Comment by gwillcox-r7** [comment]
Excellent thanks @h00die this was exactly what I was looking for, much appreciated!

**Pull request merged**
