### PR TITLE
Add post/multi/recon/reverse_lookup

### PR DESCRIPTION
**Pull request by bcoles**
Deprecates these modules in favor of the new module:

```
  moved_from 'post/windows/gather/reverse_lookup'
  moved_from 'post/windows/recon/resolve_ip'
```

This PR was originally intended to add support for PowerShell sessions. Everything else is scope creep.

This PR is a substantial improvement over the existing code by virtue of supporting multiple addition platforms and session types. There is further room for improvement but I'm not interested. See #17096 for context.

This module has been tested on Windows, Linux and Solaris. It is presumed to work on FreeBSD and OpenBSD based on the output of `host` from manual tests. I haven't confirmed on OSX as my test environment is currently broken.

### CODE REVIEW

**Comment by adfoster-r7** [comment]
## shell 🟢 

```
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.13 session=-1
                                                                                                 
[*] Resolving 192.168.123.13                                                                     
[-] Post aborted due to failure: bad-config: Unsupported sesssion type shell                     
[*] Post module execution completed   
```

## payload/cmd/windows/powershell_reverse_tcp 🟢 

```
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.13 session=-1

[*] Resolving 192.168.123.13
[+] 192.168.123.13 resolves to dc3.adf3.local
[*] Post module execution completed
```

## payload/windows/meterpreter_reverse_tcp 🟢 

invalid ip:
```
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.50 session=-1

[*] Resolving 192.168.123.50

[-] Failed to resolve 192.168.123.50
[*] Post module execution completed
```

valid ip:

```
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.13 session=-1

[*] Resolving 192.168.123.13
[+] 192.168.123.13 resolves to dc3.adf3.local
[*] Post module execution completed
```

## windows/x64/meterpreter_reverse_tcp 🟢 

invalid ip:

```
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.15 session=-1

[*] Resolving 192.168.123.15
[-] Failed to resolve 192.168.123.15
[*] Post module execution completed
```

valid ip:
```
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.13 session=-1

[*] Resolving 192.168.123.13
[+] 192.168.123.13 resolves to dc3.adf3.local
[*] Post module execution completed
```

---

I noticed a crash after running `sessions -u -1`, will investigate further now

**Comment by bcoles** [comment]
> I noticed a crash after running `sessions -u -1`, will investigate further now

I'm not sure what you mean. What crashed?

There are many different bugs related to `sessions -u` that are unrelated to this module. bwaters also encountered an error when attempting to run this module on a session created with `psexec`. Most likely unrelated.

**Comment by adfoster-r7** [comment]
Sorry, jumped into a meeting before i had a chance to post more details

Replication steps:

```
# Get a session
use windows/x64/shell_reverse_tcp
generate -f exe -o shell.exe
to_handler

# Upgrade the opened session
sessions -u -1

# Run the module, and it crashes Meterpreter
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.13 session=-1

[*] Resolving 192.168.123.13
[*] 192.168.123.13 - Meterpreter session 2 closed.  Reason: Died
```

<details>
<summary>TLV logs</summary>

```
msf6 post(multi/recon/reverse_lookup) > run address=192.168.123.13 session=-1

SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1028 command=stdapi_railgun_api>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="38108598755263339702324839273350">
  #<Rex::Post::Meterpreter::Tlv type=oneOf(UNHOOK_ERROR_CODE,WINPMEM_ERROR_CODE) meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=unknown-282146  meta=RAW        value="\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\ ...">
  #<Rex::Post::Meterpreter::Tlv type=PYTHON_CODE     meta=RAW        value="ws2_32.dll\x00\x00\x00\x00\x00\x00">
  #<Rex::Post::Meterpreter::Tlv type=LANATTACKS_RAW  meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=INCOGNITO_SERVERNAME meta=STRING     value="kernel32">
  #<Rex::Post::Meterpreter::Tlv type=oneOf(INCOGNITO_GROUPNAME,SNIFFER_ADDITIONAL_FILTER) meta=STRING     value="GetModuleHandleA">
  #<Rex::Post::Meterpreter::Tlv type=unknown-85551   meta=STRING     value="stdcall">
]>

RECV: #<Rex::Post::Meterpreter::Packet type=Response        tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1028 command=stdapi_railgun_api>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="38108598755263339702324839273350">
  #<Rex::Post::Meterpreter::Tlv type=unknown-151080  meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=unknown-1068583 meta=QWORD      value=140733749592064>
  #<Rex::Post::Meterpreter::Tlv type=POWERSHELL_ASSEMBLY meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=unknown-282150  meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=unknown-85552   meta=STRING     value="The operation completed successfully.\r\n">
  #<Rex::Post::Meterpreter::Tlv type=RESULT          meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=UUID            meta=RAW        value="\xC2\xFC\xE6\xA9\x17\x91\x1CN?V>T\\<x%">
]>

SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1028 command=stdapi_railgun_api>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="16032798977121668352388194112598">
  #<Rex::Post::Meterpreter::Tlv type=oneOf(UNHOOK_ERROR_CODE,WINPMEM_ERROR_CODE) meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=unknown-282146  meta=RAW        value="\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'!\xFF\x7 ...">
  #<Rex::Post::Meterpreter::Tlv type=PYTHON_CODE     meta=RAW        value="gethostbyaddr\x00\x00\x00">
  #<Rex::Post::Meterpreter::Tlv type=LANATTACKS_RAW  meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=INCOGNITO_SERVERNAME meta=STRING     value="kernel32">
  #<Rex::Post::Meterpreter::Tlv type=oneOf(INCOGNITO_GROUPNAME,SNIFFER_ADDITIONAL_FILTER) meta=STRING     value="GetProcAddress">
  #<Rex::Post::Meterpreter::Tlv type=unknown-85551   meta=STRING     value="stdcall">
]>

RECV: #<Rex::Post::Meterpreter::Packet type=Response        tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1028 command=stdapi_railgun_api>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="16032798977121668352388194112598">
  #<Rex::Post::Meterpreter::Tlv type=unknown-151080  meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=unknown-1068583 meta=QWORD      value=140733749768672>
  #<Rex::Post::Meterpreter::Tlv type=POWERSHELL_ASSEMBLY meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=unknown-282150  meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=unknown-85552   meta=STRING     value="The operation completed successfully.\r\n">
  #<Rex::Post::Meterpreter::Tlv type=RESULT          meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=UUID            meta=RAW        value="\xC2\xFC\xE6\xA9\x17\x91\x1CN?V>T\\<x%">
]>

[*] Resolving 192.168.123.13

SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1028 command=stdapi_railgun_api>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="66993824329126702768326031155901">
  #<Rex::Post::Meterpreter::Tlv type=oneOf(UNHOOK_ERROR_CODE,WINPMEM_ERROR_CODE) meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=unknown-282146  meta=RAW        value="\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\ ...">
  #<Rex::Post::Meterpreter::Tlv type=PYTHON_CODE     meta=RAW        value="\xC0\xA8{\r\x00\x00\x00\x00">
  #<Rex::Post::Meterpreter::Tlv type=LANATTACKS_RAW  meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=INCOGNITO_SERVERNAME meta=STRING     value="ws2_32">
  #<Rex::Post::Meterpreter::Tlv type=oneOf(INCOGNITO_GROUPNAME,SNIFFER_ADDITIONAL_FILTER) meta=STRING     value="gethostbyaddr">
  #<Rex::Post::Meterpreter::Tlv type=unknown-85551   meta=STRING     value="stdcall">
]>

RECV: #<Rex::Post::Meterpreter::Packet type=Response        tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1028 command=stdapi_railgun_api>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="66993824329126702768326031155901">
  #<Rex::Post::Meterpreter::Tlv type=unknown-151080  meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=unknown-1068583 meta=QWORD      value=2278366238896>
  #<Rex::Post::Meterpreter::Tlv type=POWERSHELL_ASSEMBLY meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=unknown-282150  meta=RAW        value="">
  #<Rex::Post::Meterpreter::Tlv type=unknown-85552   meta=STRING     value="The operation completed successfully.\r\n">
  #<Rex::Post::Meterpreter::Tlv type=RESULT          meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=UUID            meta=RAW        value="\xC2\xFC\xE6\xA9\x17\x91\x1CN?V>T\\<x%">
]>

SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1030 command=stdapi_railgun_memread>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="19767010649323309931281026267974">
  #<Rex::Post::Meterpreter::Tlv type=unknown-1068588 meta=QWORD      value=2033572016>
  #<Rex::Post::Meterpreter::Tlv type=EXT_SERVICE_ENUM_STATUS meta=INT        value=255>
]>
[*] 192.168.123.13 - Meterpreter session 10 closed.  Reason: Died

SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=23 command=core_shutdown>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="37095819455575513118435497044438">
]>

[-] Post interrupted by the console user
[*] Post module execution completed
```
</details>

**Comment by adfoster-r7** [comment]
> There are many different bugs related to sessions -u that are unrelated to this module.

Let me know if you think this is an unrelated issue or not, and I can create a separate issue for it to not block this PR :+1:

**Comment by bcoles** [comment]
> Replication steps

Thanks. Looks like it died in `memread`. There were some patches to Railgun `memread` related to NetAPI recently, although I don't think it's the same issue here.

> Let me know if you think this is an unrelated issue or not, and I can create a separate issue for it to not block this PR :+1:

This modules uses existing `memread` code from two modules: one reads 100 bytes the other reads 255. This module blindly reads 255 (which is not great).

As much as I hate killing sessions, so long as this is an existing issue in existing code then this is a WontFix for me, but I'll change it to read only 100 bytes if that makes the problem go away on your system (I doubt it).

I wasn't able to reproduce this issue on Windows 7 SP1 with staged and unstaged shell payloads. Using latest version from master with freshly generated payload executables.

I was able to reproduce this on Windows Server 2016.  However, I was also able to reproduce the issue with the existing modules:

* post/windows/gather/reverse_lookup
* post/windows/recon/resolve_ip

---

There are many many many bugs related `sessions -u`. While trying to reproduce the above issue I encountered another. On Windows 7 SP1 (windows Server 2016 seemed to behave similarly), running `sessions -u` on a `windows/shell/reverse_tcp` or `windows/shell_reverse_tcp` session causes `powershell.exe` to crash on the target, and does not upgrade the session... *unless* you have interacted with the session first, in which case it work as expected.

---

I'm new to the new Meterpreter TLV logs and I'm not sure what this is trying to tell me. `EXT_SERVICE_ENUM_STATUS` should not be relevant.

```
SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=1030 command=stdapi_railgun_memread>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="19767010649323309931281026267974">
  #<Rex::Post::Meterpreter::Tlv type=unknown-1068588 meta=QWORD      value=2033572016>
  #<Rex::Post::Meterpreter::Tlv type=EXT_SERVICE_ENUM_STATUS meta=INT        value=255>
]>
```

**Comment by adfoster-r7** [comment]
> I'll change it to read only 100 bytes if that makes the problem go away on your system

Swapping to 100 fixed the crash on my windows server 2016 box; It's not a perfect solution - but I think it's good enough for the PR to land :+1:

> I'm new to the new Meterpreter TLV logs and I'm not sure what this is trying to tell me. EXT_SERVICE_ENUM_STATUS should not be relevant.

Looks like the railgun TLV types aren't being cross-referenced in the logging, will fix :+1:

**Comment by adfoster-r7** [comment]
## Release notes

Adds a new `post/multi/recon/reverse_lookup` module that reverse resolves an IP address or IP address range to hostnames. The old `post/windows/gather/reverse_lookup` and `post/windows/recon/resolve_ip` modules have been removed.

**Comment by adfoster-r7** [comment]
Cross-referencing the fix for the tlv packet logging for railgun type names - https://github.com/rapid7/metasploit-framework/pull/17243

**Comment by adfoster-r7** [comment]
> That seems unlikely.

Looks like I didn't follow my own replication steps; I incorrectly tested with psexec to running the module, instead of via `sessions -u -1`

**Pull request merged**
