### PR TITLE
Add a reload_lib command

### PR DESCRIPTION
**Pull request by mdisec**
This PR adds a `loadlib` command that takes a ruby file as a parameter and then loads it. During the development of libraries while using msf module, `reload|rerun` commands does not reload included libraries. For this reason, it would be handy to be able to reload a single rb file while flying between different libraries and doing minor changes by using IDE.

```
msf5 > loadlib 
[-] Nothing to load.
msf5 > loadlib -h
Usage: loadlib [lib/to/load.rb]

Load a library from specified path
msf5 >
```

But I need a help for one issue. While on module usage, I'm getting following errors and have no clue how to fix em.

I've edited snmp.rb libraries and successfully reloaded it.
```
msf5 auxiliary(scanner/snmp/snmp_login) > loadlib lib/metasploit/framework/login_scanner/snmp.rb
[*] Reloading lib/metasploit/framework/login_scanner/snmp.rb
lib/metasploit/framework/login_scanner/snmp.rb:16: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::DEFAULT_TIMEOUT
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:16: warning: previous definition of DEFAULT_TIMEOUT was here
lib/metasploit/framework/login_scanner/snmp.rb:17: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::DEFAULT_PORT
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:17: warning: previous definition of DEFAULT_PORT was here
lib/metasploit/framework/login_scanner/snmp.rb:18: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::DEFAULT_VERSION
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:18: warning: previous definition of DEFAULT_VERSION was here
lib/metasploit/framework/login_scanner/snmp.rb:19: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::DEFAULT_QUEUE_SIZE
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:19: warning: previous definition of DEFAULT_QUEUE_SIZE was here
lib/metasploit/framework/login_scanner/snmp.rb:20: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::LIKELY_PORTS
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:20: warning: previous definition of LIKELY_PORTS was here
lib/metasploit/framework/login_scanner/snmp.rb:21: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::LIKELY_SERVICE_NAMES
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:21: warning: previous definition of LIKELY_SERVICE_NAMES was here
lib/metasploit/framework/login_scanner/snmp.rb:22: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::PRIVATE_TYPES
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:22: warning: previous definition of PRIVATE_TYPES was here
lib/metasploit/framework/login_scanner/snmp.rb:23: warning: already initialized constant Metasploit::Framework::LoginScanner::SNMP::REALM_KEY
/Users/mince/Desktop/pentest/metasploit-framework/lib/metasploit/framework/login_scanner/snmp.rb:23: warning: previous definition of REALM_KEY was here
msf5 auxiliary(scanner/snmp/snmp_login) > run
```

Of course this feature most probably will be used by msf devs or maybe only me :)

Thanks to @timwr for their awesome help on IRC.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Funny, I added one myself but didn't think it'd be useful enough as a console command. The `edit` command does this already, too.

**Comment by wvu-r7** [comment]
Those errors look fine. The constants are already initialized, and you're trying to do it again.

**Comment by wvu-r7** [comment]
Honestly, after @timwr's #8925, I didn't feel the need to add a separate command for it. I use `edit` for everything now.

I think we should still add it because there's a `reload` (and `reload_all`) command for modules. I suggest naming it `reload_lib` to match. (But I'm biased, since this is what I named it before. :)

Can the code be consolidated with the `edit` command's? Some of it looks pretty similar. Hat tip @jmartin-r7.

**Comment by wvu-r7** [comment]
And this split always bothered me:

```
wvu@hiigara:~/metasploit-framework:master$ git grep 'def cmd_reload'
lib/msf/ui/console/command_dispatcher/modules.rb:          def cmd_reload_all_help
lib/msf/ui/console/command_dispatcher/modules.rb:          def cmd_reload_all(*args)
lib/msf/ui/console/module_command_dispatcher.rb:  def cmd_reload(*args)
lib/msf/ui/console/module_command_dispatcher.rb:  def cmd_reload_help
wvu@hiigara:~/metasploit-framework:master$
```

**Comment by mmetince** [comment]
@wvu-r7 I'm aware of this behaviour of `edit` command but I use Rubymine or Vstudio Code while library development. Whenever I updated the library code by using IDEs, I need to reload it because I dont use `edit` command. Thus I had needed to add this command. 

At the beginning, I tried to detect included libraries in order to automatically reload them with `rerun` command. But I couldn't find a way to do it -I'm not an expert at ruby-. Thus, I've chosen this approach.

Ofc, I will rename cmd name with `reload_lib`.

As a final word, splitting info and actual stuff to the separated functions bothered me too but I sticked with existing approach.

**Comment by wvu-r7** [comment]
Agreed, that is the perfect use case for this command. Sometimes I edit outside Framework, too. :)

Now the real question is if we can move some methods around so that `edit` and `reload_lib` are in the same class. Then we can pull out the common functionality into a new method. How does that sound?

**Comment by wvu-r7** [comment]
What you've done is fine, btw. IIRC, you'll get a `LoadError` at worst. The stuff you're loading still has to be eval'd, so that's where your real errors can be thrown.

It looks like `reload_lib` is already in the same class as `edit`. See if you can DRY any functionality?

**Comment by mmetince** [comment]
That sounds great @wvu-r7 , but checking existence of given file and looking for `.rb` extension can't be done with in single method as far as I can see. `edit` method checks extension of given file and then loads it if `editing_module` is true while `reload_lib` performs both operation in a row. 

For these reason, I've decided to pull out extension check part and put it in another method so we can use it whenever we need (in this case reload_lib and edit methods)

```
def reload_file(path, err_msg = 'Only library files can be loaded.')
  if path.end_with?('.rb')
    print_status("Reloading #{path}")
    load path
  else
    print_error(err_msg)
  end
end
```

On the other hand, I've considered to create an another method for "checking existence of file" but I believe it's not gonna shorten the number of line since we need to check out returned value from that new method so we can terminate the execution within `edit|reload_lib` methods. Thus, I'm planning to leave that part as is.  Any comment ? @wvu-r7

**Review by sempervictus — COMMENTED** [review]
Reload is along the lines of
```
$LOADED_LIBRARIES.select! {|lib| lib != path} && load path
```
IIRC

**Comment by wvu-r7** [comment]
This looks great as is, @mmetince. Thank you!

**Comment by wvu-r7** [comment]
# Release Notes

This adds a `reload_lib` command to `msfconsole`, allowing developers who don't use the `edit` command (such as IDE users) to reload library files on the fly (no restart of `msfconsole` required).

**Pull request merged**
