### PR TITLE
Rpc shell read fix

### PR DESCRIPTION
**Pull request by ivonutar**
This fixes the bug from https://github.com/allfro/pymetasploit/issues/21. When using rpc sessions (eg. in pymetasploit python module), error was thrown because rpc_shell_read was basically a copy of rpc_shell_write function.

## Verification

List the steps needed to make sure this thing works
- [x] Start msfrpcd
- [x] Use pymetasploit python module to open a RPC session
- [x] Try to read data from session
- [x] Verify that _no_ error is thrown ( metasploit.msfrpc.MsfRpcError: Session Disconnected: NameError undefined local variable or method `data' for #Msf::RPC::RPC_Session:0x000055f37858e398
)

### CODE REVIEW

**Comment by busterb** [comment]
Thanks, checking it out now.

**Comment by ivonutar** [comment]
Sorry for not including more detailed steps for the bug verification, but, considering the triviality of the bug (basically a typo), I do not find it very important :) Of course, I can attach it, if needed.

**Comment by busterb** [comment]
That's alright. I'm familiar with the code since I probably introduced the bug!

**Comment by busterb** [comment]
## Release Notes

This fixes an error in the Metasploit RPC handler for reading data from a session.

**Pull request merged**
