### PR TITLE
Bump recog to 2.0.6

### PR DESCRIPTION
**Pull request by hdm**
This adds Windows 10 SMB support along with SSH and FTP fingerprints.

### CODE REVIEW

**Comment by jhart-r7** [comment]
Looks good.  I tried this before and after.  Before, we don't get the Win10 fingerprint:

```
resource (/tmp/rc)> run
[*] 10.4.18.184:445 could not be identified: Windows 10 Enterprise Insider Preview 10074 (Windows 10 Enterprise Insider Preview 6.3)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
resource (/tmp/rc)> hosts

Hosts
=====

address      mac  name  os_name  os_flavor  os_sp  purpose  info  comments
-------      ---  ----  -------  ---------  -----  -------  ----  --------
10.4.18.184             Unknown                    device         

resource (/tmp/rc)> services

Services
========

host         port  proto  name  state  info
----         ----  -----  ----  -----  ----
10.4.18.184  445   tcp    smb   open   Windows 10 Enterprise Insider Preview 10074 (Windows 10 Enterprise Insider Preview 6.3)
```

After, we get it:

```
resource (/tmp/rc)> run
[*] 10.4.18.184:445 is running Windows 10 Enterprise (build:10074) (name:WIN10-PRE-10074) (domain:WIN10-PRE-10074)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
resource (/tmp/rc)> hosts

Hosts
=====

address      mac  name             os_name     os_flavor   os_sp  purpose  info  comments
-------      ---  ----             -------     ---------   -----  -------  ----  --------
10.4.18.184       WIN10-PRE-10074  Windows 10  Enterprise         device         

resource (/tmp/rc)> services

Services
========

host         port  proto  name  state  info
----         ----  -----  ----  -----  ----
10.4.18.184  445   tcp    smb   open   Windows 10 Enterprise (build:10074) (name:WIN10-PRE-10074) (domain:WIN10-PRE-10074)
```

Landing.

**Comment by todb** [comment]
Heads up for Metasploit Pro, @lsanchez-r7

**Comment by hmoore-r7** [comment]
@lsanchez-r7 I am pretty sure Pro doesn't depend on recog directly, but we should make sure the recog version from the MDM include isn't being cached anywhere.

**Comment by shuckins-r7** [comment]
@todb @hmoore-r7 @lsanchez-r7 I think just Pro and MSF Gemfile.lock would need to be updated. I am going to chat with Lance on the process we want to follow for recog here, will send out info.

**Comment by hmoore-r7** [comment]
I didn't see a Pro Gemfile.lock when I last looked, but there might be a build-time version generated that I am not aware of.

**Comment by shuckins-r7** [comment]
@hmoore-r7 Here's the Pro one: https://github.com/rapid7/pro/blob/master/Gemfile.lock#L421 It's up a dir from where it was a while back.

**Comment by shuckins-r7** [comment]
In this particular case it will get pulled in by this MSF PR: https://github.com/rapid7/metasploit-framework/pull/5587/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R177

I'll go ahead and update Pro right after I get that merged.

**Comment by hmoore-r7** [comment]
@shuckins-r7 Ah, thanks! Will keep this in mind for future updates. cc @jhart-r7

**Comment by jhart-r7** [comment]
@shuckins-r7 @hmoore-r7 the same change that was done in this PR wrt `Gemfile.lock` was also done in https://github.com/rapid7/metasploit-framework/pull/5587/files.  Am I missing something here, or was the only skipped step the PR for Pro?  

IOW, in the future for updating recog, we should bump Gemfile.lock just as this and #5587 did, and submit a similar PR for Pro?

**Comment by shuckins-r7** [comment]
@jhart-r7 Yep, that's it. Once recog update is pushed you just need the two Gemfile.lock updates on MSF and Pro and we are set.

**Pull request merged**
