### PR TITLE
Adds RSA key extraction via Heartbleed

### PR DESCRIPTION
**Pull request by jjarmoc**
This pull adds the ability to retrieve Private Keys from memory.  There's also significant refactoring, mostly splitting things into functions to allow for better reuse.

msftidy comes back clean.

I've tested this against my own vulnerable nginx box (set up similar to https://news.ycombinator.com/item?id=7577659), and it works well with 1024 and 2048 bit keys.  After restart it gets the key every time.  Under light load it takes a little longer, as expected. I also used this on www.cloudflarechallenge.com successfully (see https://gist.github.com/jjarmoc/10890697) 

Some new options are added.  Notably;

MODE is an Enum that determines how the module operates.  Choices are:
- SCAN - A generic scan for vulnerable hosts.
- DUMP - Stores retrieved memory (same as STOREDUMP true in the previous version)
- KEYS - Try to get private keys from memory (This is my new stuff)

In KEYS mode, two new options are used;
- MAX_KEYTRIES - This is the maximum number of times to try for a private key on each host
- STATUS_EVERY - status is reported modulo this may retries when trying for keys.  Just lets us adjust how noisy reporting is/isn't.

Some caveats:
- STARTTLS isn't currently supported for KEYS mode.  I need to work out how to parse the public key....
- Doesn't address non-RSA certs (but that's uncommon)
- I changed the heartbeat response read to use sock.get() instead of sock.get_once.  The latter was badly truncating the response data; I'd see lots of data on the wire that never got read.  See https://github.com/rapid7/metasploit-framework/issues/3261

### CODE REVIEW

**Comment by gozubuyukoglu** [comment]
Hi jjarmoc, first of all thank you for that wonderful plugin, unfortunately I am unsuccesful , Please advice me where I am doing wrong. detailes below
Regards,
Arda


Module options (auxiliary/scanner/ssl/openssl_heartbleed):

   Name              Current Setting             Required  Description
   ----              ---------------             --------  -----------
   DUMPFILTER                                    no        Pattern to filter leaked memory before storing
   MAX_KEYTRIES      50                          yes       Max tries to dump key
   RESPONSE_TIMEOUT  10                          yes       Number of seconds to wait for a server response
   RHOSTS            heartbleed.hacking-lab.com  yes       The target address range or CIDR identifier
   RPORT             443                         yes       The target port
   STATUS_EVERY      5                           yes       How many retries until status
   THREADS           20                          yes       The number of concurrent threads
   TLS_CALLBACK      None                        yes       Protocol to use, "None" to use raw TLS sockets (accepted: None, SMTP, IMAP, JABBER, POP3, FTP, POSTGRES)
   TLS_VERSION       1.1                         yes       TLS/SSL version to use (accepted: SSLv3, 1.0, 1.1, 1.2)


Auxiliary action:

   Name  Description
   ----  -----------
   KEYS  Recover private keys from memory


msf auxiliary(openssl_heartbleed) >


Also tried SslV3 TLS 1.2 & 1.0 but no success yet...

**Comment by gozubuyukoglu** [comment]
additionally I receive response and all of them are 65k

[*] 192.168.200.179:443 - Sending Client Hello...
[!] SSL record #1:
[!]     Type:    22
[!]     Version: 0x0301
[!]     Length:  54
[!]     Handshake #1:
[!]             Length: 50
[!]             Type:   Server Hello (2)
[!]             Server Hello Version:           0x0301
[!]             Server Hello random data:       5376c1523d79ed236718d4c866abaf1a8b469c4c2bae12ea6ef9c2831855e016
[!]             Server Hello Session ID length: 0
[!]             Server Hello Session ID:
[!] SSL record #2:
[!]     Type:    22
[!]     Version: 0x0301
[!]     Length:  631
[!]     Handshake #1:
[!]             Length: 627
[!]             Type:   Certificate Data (11)
[!]             Certificates length: 624
[!]             Data length: 627
[!]             Certificate #1:
[!]                     Certificate #1: Length: 621
[!]                     Certificate #1: #<OpenSSL::X509::Certificate subject=/C=CH/ST=SG/L=Jona/O=Hacking-Lab/OU=Heartbleed/CN=heartbleed.hacking-lab.com, issuer=/C=CH/ST=SG/L=Jona/O=Hacking-Lab/OU=Heartbleed/CN=heartbleed.hacking-lab.com, serial=10767679993171866209, not_before=2014-04-23 10:19:01 UTC, not_after=2015-04-23 10:19:01 UTC>
[!] SSL record #3:
[!]     Type:    22
[!]     Version: 0x0301
[!]     Length:  203
[!]     Handshake #1:
[!]             Length: 199
[!]             Type:   Server Key Exchange (12)
[!] SSL record #4:
[!]     Type:    22
[!]     Version: 0x0301
[!]     Length:  4
[!]     Handshake #1:
[!]             Length: 0
[!]             Type:   Server Hello Done (14)
[*] 192.168.200.179:443 - Sending Heartbeat...
[*] 192.168.200.179:443 - Heartbeat response, 65535 bytes
[*] 192.168.200.179:443 - Sending Client Hello...

**Comment by FireFart** [comment]
@gozubuyukoglu dumping keys can take a while and maybe needs some tries. Some time ago I tried the module against the hacking lab server and it worked. I ran a script in the background to generate some traffic on the server like
`while true; do curl -sk 'https://heartbleed.hacking-lab.com/RANDOM_STRING'; sleep 1; done`
Just try the DUMP action and if data is returned, the module is working.

**Comment by jjarmoc** [comment]
*nod*  @FireFart pretty much nails it.  You may need more than the 50 tries you're configured for (like, as many as several thousand) and/or might need to send other requests to the server to get it to move memory around, etc.  Finding keys in memory isn't entirely deterministic - it depends on the values being there which requires some degree of stars aligning.

Also, commenting on a close pull for help probably isn't appropriate.  You may want to jump in #metasploit on freenode or open an issue or something in the future.

**Comment by varkum19** [comment]
I only have the scan option. Instead of 
Auxiliary action:

   Name  Description
   ----  -----------
   KEYS  Recover private keys from memory

it gives me SCAN, and no KEYS.

**Comment by wvu-r7** [comment]
@varkum19: Please submit an issue if you have a bug report. You are using ```show options``` instead of ```show actions```. The former shows the currently selected action, while the latter shows all possible actions.

**Comment by varkum19** [comment]
@wvu-r7: thanks! I figured that problem out. Now, when I try "run," it scans for private keys but fails, stating that I should increase max_keytries or heartbeat length. I am not sure what I can do.

**Pull request closed without merging**
