### PR TITLE
Multi-Platform Railgun Support

### PR DESCRIPTION
**Pull request by zeroSteiner**
This pull request adds support for railgun to be used on non-Windows platforms, beginning with Linux. Most of the changes are refactoring the existing code to not have a railgun instance be polluted with definitions that are not applicable to the session's platform. This also provides some initial definitions for Linux's `libc.so.6` library, adds Linux to the supported platforms for the `railgun` tests. The Linux specific `railgun` tests cover all of the same core functionality that the Windows tests do, resulting in the output being very similar with the API differences being under the hood so to speak.

This PR is dependent on and related to rapid7/metasploit-payloads#194.

## Change Overview
Some of the more noteworthy changes include
  * Refactored DLL definitions to exist in a platform-specific subfolder
  * DLLs use a platform-specific `ApiConstant` manager
    * Constants are defined next to the DLL definitions in a file named `def/$platform/api_constants.rb`
    * Constant manager's still have a platform-specific `manager_semaphore` for synchronization
  * Added `SIZE_T` type which is a new type that is dynamically sized based on the architecture (4-bytes on `x86`, 8-bytes on `x86-64`)
  * New definitions for `libc.so.6` and some hand selected constants

## Verification

The verification on this is going to be very dependent on running the new functionality in the `post/test/railgun` module in different configurations.

- [x] The Windows meterpreter still passes all railgun checks.
- [x] The Python meterpreter on Windows still passes all railgun checks.
- [x] The Python meterpreter on Linux with 2.7 still passes all railgun checks.
- [x] The Python meterpreter on Linux with 3.x still passes all railgun checks.
- [x] Railgun instances get the platform appropriate `ApiConstant` class

## Example Output
**Running post/test/railgun**
```
metasploit-framework (S:2 J:0) payload(reverse_tcp) > to_handler 
[*] Payload Handler Started as Job 3
metasploit-framework (S:2 J:1) payload(reverse_tcp) > 
[*] [2017.04.25-17:31:34] Started reverse TCP handler on 172.20.220.166:4444 
[*] [2017.04.25-17:31:34] Starting the payload handler...
[*] [2017.04.25-17:31:42] Sending stage (40043 bytes) to 172.20.220.166
[*] Meterpreter session 4 opened (172.20.220.166:4444 -> 172.20.220.166:60692) at 2017-04-25 17:31:42 -0400
[*] [2017.04.25-17:31:43] Session ID 4 (172.20.220.166:4444 -> 172.20.220.166:60692) processing AutoRunScript 'post/test/railgun'
[*] [2017.04.25-17:31:43] Running against session 4
[*] [2017.04.25-17:31:43] Session type is meterpreter and platform is linux
[+] [2017.04.25-17:31:43] Should include error information in the results
[+] [2017.04.25-17:31:43] Should support functions with no parameters
[+] [2017.04.25-17:31:43] Should support functions with literal parameters
[+] [2017.04.25-17:31:43] Should support functions with in/out/inout parameter types
[+] [2017.04.25-17:31:43] Should support calling multiple functions at once
[+] [2017.04.25-17:31:43] Should support writing memory
[+] [2017.04.25-17:31:43] Should support reading memory
[*] [2017.04.25-17:31:43] Testing complete in 0.035746383
[*] [2017.04.25-17:31:43] Passed: 7; Failed: 0
```

**Checking the constants**
```
metasploit-framework (S:4 J:0) post(meterpreter) > sessions -i 5
[*] Starting interaction with 5...


meterpreter > sysinfo
Computer        : PWNME-PC
OS              : Windows 7 (Build 7601, Service Pack 1)
Architecture    : x64
System Language : en_US
Meterpreter     : python/windows
meterpreter > irb
[*] Starting IRB shell
[*] The 'client' variable holds the meterpreter client

>> session.railgun.api_constants
=> Rex::Post::Meterpreter::Extensions::Stdapi::Railgun::Def::DefApiConstants_windows
>> exit
meterpreter > background
[*] Backgrounding session 5...
metasploit-framework (S:4 J:0) post(meterpreter) > sessions -i 4
[*] Starting interaction with 4...

meterpreter > sysinfo
Computer        : localhost.localdomain
OS              : Linux 4.10.10-200.fc25.x86_64 #1 SMP Thu Apr 13 01:11:51 UTC 2017
Architecture    : x64
System Language : en_US
Meterpreter     : python/linux
meterpreter > irb
[*] Starting IRB shell
[*] The 'client' variable holds the meterpreter client

>> session.railgun.api_constants
=> Rex::Post::Meterpreter::Extensions::Stdapi::Railgun::Def::DefApiConstants_linux
>> 
```

On a side note, refactoring railgun library code for non-Windows platforms be like

image

### CODE REVIEW

**Comment by sempervictus** [comment]
Going through it. Just curious, is this like the programming equivalent of flagellation as penance for some ungodly use of global variables? ;)
Thank you as always sir, RG needed some serious rethinking.

**Comment by sempervictus** [comment]
No concerns jump out on first pass, one question comes up:
Is this a logical point to start discussion on the notion of application-specific RG namespacing? The definitions are for 'windows' and 'linux' at present, but to be fair, Linux is a kernel implementation, with libc being up to the user (MUSL, uclibc, etc). A more common example would be systems using GNUTLS vs OpenSSL, or the plethora of libcurl versions in the wild (especially when taken in consideration with Mettle's platform coverage). Would it make sense to segment the definitions namespace into "platform" and "library" such that a session's runtime context could be queried to marshal up call structures into, for example,an old 32bit Linux box with an old libc where someone compiled the newest possible version of openssl compatible with said libc?
Looking at payloads when i have a break later this evening, thanks again, merge test will likely occur tonight.

**Comment by sempervictus** [comment]
So far so good, merged framework and payloads sides, framework hasnt blown up, and i'll poke at a python meterpreter session shortly to test functionality.

**Comment by zeroSteiner** [comment]
@sempervictus the constants are shared by the platform so if two different libraries defined the same thing with two different values there'd be an issue. For the different libraries though, I thought they'd just use their own dll definition so you'd have a `def_libmusl.rb` and a `def_libuclibc.rb` files. Are there instances that you can think of that I'm missing where two libraries would share the same name but have a different API exposed?

In the case where the version becomes relevant, maybe the RG lib could simply be suffixed with it such as `def_libc.rb` would become `def_libc_6.rb` etc.

**Comment by busterb** [comment]
Nice work @zeroSteiner !

**Comment by busterb** [comment]
## Release Notes

This adds initial Python Meterpreter support for the Railgun extension on Linux Glibc-based systems. Railgun allows a Metasploit module or user to interact with arbitrary system libraries on a remote target directly from a Meterpreter session.

**Pull request merged**
