### PR TITLE
Add support for the show_mount command (windows)

### PR DESCRIPTION
**Pull request by OJ**
For quite some time we've all been wanting a feature this lists the mount points in Meterpreter. This PR is the first pass of enabling this feature, and is currently Windows only. I'd like to call on wise folks such as @bcook-r7 and @mubix to chat about the best approach for gathering this kind of information on other platforms.

This work relies on Meterpreter changes that can be found here: https://github.com/rapid7/metasploit-payloads/pull/43

The goal here is to show the different drives that are available for use under the current user context.

Code has been put under `stdapi`. Originally I had it in `extapi`, but given it'll end up cross-platform I felt that `stdapi` was a better option (and I had pressure from @mubix too ;)).

This PR includes a new gem called `filesize` which "pretty prints" the number of bytes. I chose to pull this in because I was lazy, then ended up fudging around with it anyway. I've left it in this PR as a discussion point, and am open to other options.
## Sample run

```
meterpreter > show_mount 

Mounts / Drives
===============

Name  Type       Size (Total)  Size (Free)  Mapped to
----  ----       ------------  -----------  ---------
A:\   removable    0.00 B        0.00 B     
C:\   fixed       60.00 GiB     26.09 GiB   
D:\   cdrom        0.00 B        0.00 B     
N:\   remote       7.15 TiB      6.04 TiB   \\X.X.X.X\code\
Z:\   remote      15.68 GiB     15.66 GiB   \\vmware-host\Shared Folders\


Total mounts/drives: 5
```
## Verification
- [ ] Get a meterpreter session on windows
- [ ] make sure the target machine has various types of drives mapped
- [ ] run `show_mount` and get a list of info that matches the state of play

### CODE REVIEW

**Comment by void-in** [comment]
@OJ Considering https://github.com/rapid7/metasploit-framework/pull/6057, can be pull the bitlocker status info?

**Comment by OJ** [comment]
@void-in Unfortunately there's no way to get the Bitlocker status of a drive using direct Win32 API calls. The best, and recommended option, is to use WMI to query the drive instead. Given that the `extapi` extension provides a generic WMI query facility, it'd be better to use that I think.

**Comment by mubix** [comment]
I like that it's moving towards universal compatibility, hopefully we will see the same thing in php_meterpreter next ;-) @jlee-r7 , and I think it's awesome that it shows network mounts !! w00tw00t

Nothing really to add to the "commit or not" discussion, other than the fact that converting file sizes to "human readable" probably should have been a library a long time ago with directory listings and such already built in.

**Comment by jlee-r7** [comment]
I'm not sure it's possible in PHP.

**Comment by bcook-r7** [comment]
A WMI fallback should work in just about any language I think, even if the native win32 API is not available.

**Comment by bcook-r7** [comment]
LGTM:
```
meterpreter > show_mount

Mounts / Drives
===============

Name  Type    Size (Total)  Size (Free)  Mapped to
----  ----    ------------  -----------  ---------
C:\   fixed    97.31 GiB     53.85 GiB
D:\   cdrom    56.26 MiB      0.00 B
E:\   remote  464.80 GiB    240.96 GiB   \\VBOXSVR\projects\
F:\   remote  464.80 GiB    240.96 GiB   \\vboxsrv\projects\
```

**Comment by OJ** [comment]
Thanks Brent.

I've got the wmi stuff on my list of things to address. In particular the
com security issues that raise their heads a bit. When I've nailed that
I'll get the fallback in place.

Cheers!

**Pull request merged**
