### PR TITLE
Save the data collected by resolve_hosts

### PR DESCRIPTION
**Pull request by egypt**
Instead of just throwing it away after printing.

## Verification

- [x] get a meterp session
- [x] `use post/multi/gather/resolve_hosts`
- [x] `set session -1`
- [x] `set hostnames google.com`
- [x] `run`
- [x] `hosts`
- [x] **Verify** you have a host in the db with name "google.com"

### CODE REVIEW

**Comment by h00die** [comment]
If no one else gets to this in a day or two, I'll take it.

**Comment by sempervictus** [comment]
I have this in my framework:
```
$ git diff rapid7/master modules/post/multi/gather/resolve_hosts.rb
diff --git c/modules/post/multi/gather/resolve_hosts.rb w/modules/post/multi/gather/resolve_hosts.rb
index 8b731de5ee..03fc88d2a6 100644
--- c/modules/post/multi/gather/resolve_hosts.rb
+++ w/modules/post/multi/gather/resolve_hosts.rb
@@ -20,6 +20,7 @@ class MetasploitModule < Msf::Post
       register_options([
         OptString.new('HOSTNAMES', [false, 'Comma seperated list of hostnames to resolve.']),
         OptPath.new('HOSTFILE', [false, 'Line separated file with hostnames to resolve.']),
+        OptBool.new('REPORT_HOSTS', [false, 'Report found hosts to DB', true ]),
         OptEnum.new('AI_FAMILY', [true, 'Address Family', 'IPv4', ['IPv4', 'IPv6'] ])
       ])
   end
@@ -73,6 +74,9 @@ class MetasploitModule < Msf::Post
         table << [result[:hostname], '[Failed To Resolve]']
       else
         table << [result[:hostname], result[:ip]]
+        if datastore['REPORT_HOSTS']
+          report_host(:host => result[:ip],:name => result[:hostname])
+        end
       end
     end
```
(this PR looked strange to me, turns out upstream didnt do this). Hasn't eaten my dog yet... so its prolly safe

**Comment by h00die** [comment]
Funny, I had the same idea to make it a datastore option, default to `true` so that you could avoid reporting this if you wanted. Had planned to send a PR to @egypt, but you beat me to it!

**Comment by h00die** [comment]
https://github.com/egypt/metasploit-framework/pull/2 is along the lines of what @sempervictus added.

**Comment by egypt** [comment]
What's the use case for *not* reporting? I can't think of why you'd want to look it up and then not save it.

**Comment by h00die** [comment]
I could see two use cases:
1. You're internal to the network and testing an external site like Google where you're checking for a proxy or other network muckery. In this case I wouldn't want it to polite my db
2. You're looking up internal host names where I def want to database it all.

I haven't specifically used this module, so these test cases may not be accurate. Was thinking of a first run you'd do when new on a box to test out network stuff like proxies etc

**Comment by h00die** [comment]
@egypt any thoughts on the last comments? I'd like to get this landed soon since its so trivial.

**Comment by h00die** [comment]
```
msf5 post(multi/gather/resolve_hosts) > set session 2
session => 2
msf5 post(multi/gather/resolve_hosts) > run

[!] SESSION may not be compatible with this module.
[*] Attempting to resolve 'google.com' on 222.222.2.222
Hostname    IP
--------    --
google.com  172.217.7.174
[*] Post module execution completed
msf5 post(multi/gather/resolve_hosts) > hosts

Hosts
=====

address        mac  name           os_name                                 os_flavor  os_sp  purpose  info  comments
-------        ---  ----           -------                                 ---------  -----  -------  ----  --------
172.217.7.174       google.com                                                                              
222.222.2.222       222.222.2.222  Ubuntu 16.04 (Linux 4.4.0-116-generic)                    server         

msf5 post(multi/gather/resolve_hosts) > set database false
database => false
msf5 post(multi/gather/resolve_hosts) > set hostnames yahoo.com
hostnames => yahoo.com
msf5 post(multi/gather/resolve_hosts) > run

[!] SESSION may not be compatible with this module.
[*] Attempting to resolve 'yahoo.com' on 222.222.2.222
Hostname   IP
--------   --
yahoo.com  98.138.219.231
[*] Post module execution completed
msf5 post(multi/gather/resolve_hosts) > hosts

Hosts
=====

address        mac  name           os_name                                 os_flavor  os_sp  purpose  info  comments
-------        ---  ----           -------                                 ---------  -----  -------  ----  --------
172.217.7.174       google.com                                                                              
222.222.2.222      222.222.2.222  Ubuntu 16.04 (Linux 4.4.0-116-generic)                    server         
```

works as expected!

**Comment by h00die** [comment]
# Release Notes
This PR databases the results of `multi/gather/resolve_hosts` instead of just printing them to the screen

**Pull request merged**
