### PR TITLE
Get ready for stageless mettle

### PR DESCRIPTION
**Pull request by acammack-r7**
Does a couple of things to prepare for stageless mettle payloads:

* Adds new arches to rex-arch UUIDs
* Factors out some common mettle config generation
* Don't touch payloads that are already ELF files in `Msf::Util::Exe`

This needs the changes in rapid7/mettle#42 to be pulled in. These PRs move base64 encoding of UUIDs to MSF in order to avoid dependency inversion.

Verification
========

**DELAYED**
- [x] Tests should still pass
- [x] Mettle payloads should still stage and work

### CODE REVIEW

**Comment by OJ** [comment]
giphy

**Comment by busterb** [comment]
Wooo

**Comment by busterb** [comment]
Merged mettle bits, build gem, looks good

**Comment by bcook-r7** [comment]
Thanks @acammack-r7 , ready for the next step.

**Comment by tdoan-r7** [comment]
# Release Notes

This enhancement adds new architectures for rex-arch UUIDs, factors out common Mettle configuration generation, and does not modify payloads that are already ELF files in Msf::Util::Exe.

**Pull request merged**
