### PR TITLE
Adding auxiliary/scanner/http/dir_listing documentation

### PR DESCRIPTION
**Pull request by Yashvendra**
This PR adds the documentation for `auxiliary/scanner/http/dir_listing`

### CODE REVIEW

**Comment by h00die** [comment]
would it be possible to add in some 'how to make this vulnerable' type instructions?  `nginx` and `apache` would be awesome, but not super pressed about it.  See https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/auxiliary/gather/ipcamera_password_disclosure.md#setup while that is different, its awesome to have some instructions for making the target vulnerable to test the module.

**Comment by h00die** [comment]
I believe you also set verbose to true since it printed the NOT vulnerable part, but i dont see that in the instructions

**Comment by Yashvendra** [comment]
> would it be possible to add in some 'how to make this vulnerable' type instructions? `nginx` and `apache` would be awesome, but not super pressed about it. See https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/auxiliary/gather/ipcamera_password_disclosure.md#setup while that is different, its awesome to have some instructions for making the target vulnerable to test the module.

Yes it would be awesome, will surely look into it.

**Comment by Yashvendra** [comment]
> I believe you also set verbose to true since it printed the NOT vulnerable part, but i dont see that in the instructions

Yeah, didn't mention the verbose part.  Should I add it or remove the NOT part ?

**Comment by h00die** [comment]
I would just add the 2 lines showing you marked verbose (set verbose true, verbose => true).  that's easier than removing all the non-vuln hosts, plus it shows what to expect in that use case which is a bonus

**Comment by Yashvendra** [comment]
> I would just add the 2 lines showing you marked verbose (set verbose true, verbose => true). that's easier than removing all the non-vuln hosts, plus it shows what to expect in that use case which is a bonus

Surely will do it. And about the 'how to make this vulnerable' part, can I simply create a php file enabling the directory listing and run it on the server then test it or should I use `nginx` and `apache`. What do you suggest?

**Comment by h00die** [comment]
Whatever makes it vulnerable works for me!

**Comment by bcoles** [comment]
>  can I simply create a php file enabling the directory listing

Whatever works; however a `.htaccess` file with `Indexes` is more traditional.

**Comment by Yashvendra** [comment]
Done.

**Comment by h00die** [comment]
I did a slight cleanup, so minor i didn't want to hold up the rest of this by pushing back again.
Typically we sanitize IPs to 1) not give away your network architecture, 2) save space (192.168.1. is 4 characters larger than 1.1.1., and that space adds up over a few hundred or thousand modules).  I also summarized your `.htaccess` file generation down to one line.
Nice docs, thanks for the contribution!!!!!

https://github.com/rapid7/metasploit-framework/commit/53e5f882f7f8adabb15cb7433b870bb55eebd1f3

**Comment by h00die** [comment]
# Release Notes
This PR adds docs for auxiliary/scanner/http/dir_listing module

**Comment by Yashvendra** [comment]
> I did a slight cleanup, so minor i didn't want to hold up the rest of this by pushing back again.
> Typically we sanitize IPs to 1) not give away your network architecture, 2) save space (192.168.1. is 4 characters larger than 1.1.1., and that space adds up over a few hundred or thousand modules). I also summarized your `.htaccess` file generation down to one line.
> Nice docs, thanks for the contribution!!!!!
> 
> [53e5f88](https://github.com/rapid7/metasploit-framework/commit/53e5f882f7f8adabb15cb7433b870bb55eebd1f3)

Thanks @h00die I'll keep this in mind for the next time.

**Pull request merged**
