### PR TITLE
server/capture docs and consistency updates

### PR DESCRIPTION
**Pull request by h00die**
Sorry to cram so many things in one PR, but little issues were bothering me.

1. Fix a typo in `auxiliary/server/capture/ftp` docs
2. add `auxiliary/server/capture/http_basic` docs.  I hope that I made it clear enough that there was no actual vuln at the wordpress.com site, @todb-r7  can you give it a quick look over plz (See HTML Injection Social Engineering section), and let me know if it needs to be more obvious, or if another example (suggest a site?) should be used.
3. Add `auxiliary/server/capture/imap` docs
4. Add `auxiliary/server/capture/mysql` docs
5. `auxiliary/server/capture/http_basic` used a unique string for printing the creds it got, so i synced it (more or less) to what the other modules were printing for consistency
6. `auxiliary/server/capture/imap` now has a configurable banner, like I did for ftp, and gave some examples of ones I saw in shodan.io as examples
7. `auxiliary/server/capture/imap` had a `print_status` instead of `print_good` which was not consistent with other modules, nor correct
8. corrected the link to docs within `auxiliary/server/capture/mysql`
9. `auxiliary/server/capture/mysql` was not properly storing the hash, it saved to `pass` then referenced `password`.  Also saved it as a `nonreplayable hash` instead of a `password`.  Fixed, example below.

## Verification

- [ ] check docs for spelling/grammar/examples
- [ ] try `http_basic` to make sure it prints the creds correctly
- [ ] try `imap` to see if it prints good instead of status, also check the banner
- [ ] click the link in the mysql comment

## Pre mysql creds fix:
```
msf5 > use auxiliary/server/capture/mysql 
msf5 auxiliary(server/capture/mysql) > run
[*] Auxiliary module running as background job 0.
msf5 auxiliary(server/capture/mysql) > 
[*] Started service listener on 0.0.0.0:3306 
[*] Server started.

msf5 auxiliary(server/capture/mysql) > creds
Credentials
===========

host  origin  service  public  private  realm  private_type
----  ------  -------  ------  -------  -----  ------------

msf5 auxiliary(server/capture/mysql) > mysql -u user -ppassword -h 127.0.0.1
[*] exec: mysql -u user -ppassword -h 127.0.0.1

ERROR 1045 (28000): Access denied for user 'user'@'127.0.0.1' (using password: YES)

[+] 127.0.0.1:35610 - User: user; Challenge: 112233445566778899aabbccddeeff1122334455; Response: 42e3928bba9eec017860b977a1700d7a774656f5
msf5 auxiliary(server/capture/mysql) > creds
Credentials
===========

host       origin     service                  public  private  realm  private_type
----       ------     -------                  ------  -------  -----  ------------
127.0.0.1  127.0.0.1  3306/tcp (mysql_client)  user                    Blank password

```

## post fix

```
msf5 auxiliary(server/capture/mysql) > run
[*] Auxiliary module running as background job 1.
msf5 auxiliary(server/capture/mysql) > 
[*] Started service listener on 0.0.0.0:3306 
[*] Server started.

msf5 auxiliary(server/capture/mysql) > mysql -u user -ppassword -h 127.0.0.1
[*] exec: mysql -u user -ppassword -h 127.0.0.1

ERROR 1045 (28000): Access denied for user 'user'@'127.0.0.1' (using password: YES)

[+] 127.0.0.1:35618 - User: user; Challenge: 112233445566778899aabbccddeeff1122334455; Response: 42e3928bba9eec017860b977a1700d7a774656f5
msf5 auxiliary(server/capture/mysql) > creds
Credentials
===========

host       origin     service                  public  private                                                                                        realm  private_type
----       ------     -------                  ------  -------                                                                                        -----  ------------
127.0.0.1  127.0.0.1  3306/tcp (mysql_client)  user    user:$mysql$112233445566778899aabbccddeeff1122334455$42e3928bba9eec017860b977a1700d7a774656f5         Nonreplayable hash
```

### CODE REVIEW

**Comment by Green-m** [comment]
Is it supposed to be a `markdown` file? https://github.com/rapid7/metasploit-framework/pull/10938/files#diff-a0b01b85d0faa0408123beade77260d8

**Comment by h00die** [comment]
@Green-m sorry for adding 2 more things, but when i woke up a few min ago i realized `mysql` was not storing the hash, and it was saving it as a password not a hash.  Fixed that up so its storing right.  This PR has lots and lots in it, but theyre all relatively minor at least

**Review by bcoles — COMMENTED** [review]
LGTM

**Comment by Green-m** [comment]
I am going to land this since most r7 employees are busy with CTF.

**Comment by Green-m** [comment]
## Release Notes

This PR adds docs for auxiliary module `http_basic/imap/mysql`, 
and fix a bug in `modules/auxiliary/server/capture/mysql.rb`

**Pull request merged**
