### PR TITLE
License and Copying year updated to 2022

### PR DESCRIPTION
**Pull request by thunder-007**
License and copying year updated . they remained the same since 2020

### CODE REVIEW

**Comment by adfoster-r7** [comment]
Thanks for the PR @thunder-007 :+1:

It looks like you've accidentally branched off the Metasploit 4.x branch instead of `master`

**Comment by bcoles** [comment]
> @adfoster-r7 yesterday I made a pull request on master and it got closed with label need-unique-branch.

Create a new branch from master. #11224

**Comment by gwillcox-r7** [comment]
```
git checkout master
git pull && git fetch <- To check for updates and pull any of them down locally to the master branch
git checkout -b update-license-and-copying-year-2022
<make the necessary changes you want to make to the respective files>
git push origin update-license-and-copying-year-2022:update-license-and-copying-year-2022
```

That should work for updating your fork and making a new `update-license-and-copying-year-2022` branch assuming `origin` points to your fork. The output should then show a link you can click to open a PR request.

Hope that helps!

**Comment by gwillcox-r7** [comment]
Closing this PR as we are trying to pull in version 4.x of Metasploit into the master branch which is on version 6.2 now. Please follow the instructions I provided above as well as the info in @bcoles's link. If your stuck let us know and we'll be happy to assist. I'd also be interested to know if there is anything we can do to make this process easier and I'll update the documentation accordingly. @bcoles thanks for pointing out that issue I'll see if I can't hop onto trying to get some documentation up to address that better 👍

**Pull request closed without merging**
