### PR TITLE
Kb for ms15 034 http sys memory dump

### PR DESCRIPTION
**Pull request by itsmeroy2012**
Issue:- Add KB for auxiliary/scanner/http/ms15_034_http_sys_memory_dump #7132

## Description
Documentation on auxiliary/scanner/http/ms15_034_http_sys_memory_dump.

### CODE REVIEW

**Comment by h00die** [comment]
in general this looks good.  However, one could argue a few things:

1. None of the outputs actually show any contents. We're dumping memory (which may or may not be empty), can we show one where something is actually dumped?
2. Since none of the outputs show anything, do we need more than 1 since anything more is pretty much redundant

**Comment by h00die** [comment]
check #5577 for some results

**Comment by h00die** [comment]
similar to that other docs you did, can we put the `Note` on its own line, and bold it? I'd like it to be called out specifically since its a BSOD.
Other than that, looks good to me, i'll land once thats done (prob on the 22nd)

**Comment by itsmeroy2012** [comment]
Done as required @h00die .... I'll need the output of the other docs related issues. I'll make the docs no problem :) :)

**Comment by itsmeroy2012** [comment]
I mistakenly did close and comment. Opening now...

**Comment by h00die** [comment]
sorry, life caught up with me this week (and next). landing now.

**Comment by h00die** [comment]
# Release Notes
Adds docs for auxiliary/scanner/http/ms15_034_http_sys_memory_dump

**Pull request merged**
