### PR TITLE
Adding carders.cc password list

### PR DESCRIPTION
**Pull request by shipcod3**

### CODE REVIEW

**Comment by todb-r7** [comment]
I'm not sure of the value of another wordlist of weak passwords, given the ones we ship today.

 These passwords are pretty generic and are associated with a criminal forum; they're not statistically vetted as being particularly common or associated to a unique service.

Also, I suspect it's garbled. It contains the password `d8e8fca2dc0f896fd7cb4cb0031ba249` which is really the md5sum of `test`, and the sorting seems weird. Alphabetical chunks, but not in any particular order.

Can you make a case for landing this, @shipcod3?

**Comment by wvu-r7** [comment]
I can't really justify accepting this one either. The others were okay to me, but this one is pretty far out there. I don't think it'd be especially useful even for vigilantism.

**Comment by shipcod3** [comment]
copy on this one

**Comment by wvu-r7** [comment]
Thanks for understanding, @shipcod3. :)

**Comment by shipcod3** [comment]
:+1: yeah np @wvu-r7

**Pull request closed without merging**
