### PR TITLE
dynamic DNS update module

### PR DESCRIPTION
**Pull request by busterb**
This rebases #7017, original verification steps are the same.

### CODE REVIEW

**Comment by busterb** [comment]
@mubix could you give this another whirl? we made some preflight checks that are pretty useful.
 Source IP spoofing will come in another PR after DNS mixin exists.

**Comment by mubix** [comment]
Just a quick mention regarding usage that might help documentation - https://technet.microsoft.com/en-us/library/cc995158.aspx - WPAD is a blocked DNS name

more info: https://technet.microsoft.com/en-us/library/cc995261.aspx

**Comment by mubix** [comment]
Pre-flight checks fail of the local system doesn't have ability to resolve the remote domain.

**Comment by KINGSABRI** [comment]
Thanks man for all the awesome support!

**Comment by alrosenthal-r7** [comment]
# Release Notes

The ability to add or delete DNS records on any DNS server that allows unrestricted dynamic updates has been added.

**Pull request merged**
