### PR TITLE
Connection recovery

### PR DESCRIPTION
**Pull request by OJ**
This is the sister PR of the Meterpreter work found in: https://github.com/rapid7/meterpreter/pull/151

This PR contains MSF side functionality for connection resiliency. It's early days though, and more to be done. There's already some detail in the Meterpreter PR so please read that.
- Session timeouts are now available in the TCP payloads well.
- Timeouts can be modified on the fly.
- Porting work done by @hmoore-r7 is in here too, I need to build on this more though as we need to get the stager resiliency stuff in.
- Bind payloads now have an option which keeps the listen socket open or shuts it down. In the case of Meterpreter payloads, the listen socket is kept open. This allows Meterpreter to figure out the comms channel in place so that it can "do it again" if things fail. Meterpreter closes the listen socket once it has taken over comms.

Extra stuff to do includes more work on the stagers (that's up next).

Submitting PR now so that we have a talking point for work that is coming in.

Verification and Samples can be found in the Meterpreter PR.

Thanks!

### CODE REVIEW

**Comment by jlee-r7** [comment]
Travis failures are relevant.  You need to update payload sizes, please.

**Comment by OJ** [comment]
I get this wrong every. Damn. Time.

Thanks egypt.

**Comment by OJ** [comment]
When I run `tools/update_payload_cached_sizes.rb` it updates some of them but the specs still fail. When I run the script again, it updates some others, and the specs still fail. Each run of the script seems to oscillate between two values of broken.

Anyone got an idea why this might be happening?

**Comment by hmoore-r7** [comment]
Make sure the payloads are returning a static size in the call to generate(). If this isn't practical, you can set the CachedSize to dynamic, but at a the cost of startup performance.

**Comment by OJ** [comment]
HOORAY!

**Comment by bcook-r7** [comment]
I encountered some problems migrating processes with Windows, e.g. migrating to a  chrome process with 32-bit staged does not finish. I suspect there are some fixes coming down the pipe with the new config block work, so I might wait a bit more to land everything at once.

**Comment by OJ** [comment]
That only works if you migrate to the top-most chrome process. If you
migrate to a child, you'll end up with dead connections. I've seen this in
the past.

Are you saying in this case that this behavior is new for you and doesn't
happen with older binaries?

**Comment by bcook-r7** [comment]
I didn't just try chrome, but it is also probable that I was just lucky and chose the right/wrong process when testing with the old versus the new binaries.

**Comment by OJ** [comment]
This does sound odd. I will take a look at it myself and see if I can repro. Migration behaviour is certainly changing in an upcoming PR but I this should still not be happening.

Can you please confirm the payloads you were using? Were they reverse/bind/http/ etc?

Cheers!

**Comment by bcook-r7** [comment]
windows/meterpreter/reverse_tcp and windows/meterpreter/reverse_http both show it

**Comment by OJ** [comment]
I'll check it out this afternoon once I've got this report done. Thanks @bcook-r7

**Comment by bcook-r7** [comment]
No sweat - I tracked it down to 1447df1fac683a8883cfcd9efab74d36d38c708f in the meterpreter repo, maybe the default connection timeout settings aren't getting set on migrate.

**Comment by OJ** [comment]
That's exactly what it is mate. The wiring isn't patching the timeouts.
Fixing that as soon as I get the chance. Thanks!

**Comment by OJ** [comment]
Also, yes, this is fixed with the next PR that does all the configuration differently ;) But this still needs to be fixed/landed first imho.

Cheers again Brent.

**Comment by OJ** [comment]
Thanks for your patience @bcook-r7. The latest commit should fix this issue properly.

**Comment by bcook-r7** [comment]
Much appreciated OJ, I'll get this tested and pulled in the morning.

**Comment by bcook-r7** [comment]
This pulls in metasploit-payloads for linux and windows meterpreter bins for the first time as well. I'll make a new PR to enable the java/php/python bits individually since I didn't pull that part into MSF yet.

**Comment by OJ** [comment]
Thanks so much for all your help and patience @bcook-r7 !

**Pull request merged**
