### PR TITLE
Sanity check file: arguments for size and move into msfconsole

### PR DESCRIPTION
**Pull request by hdm**
This moves processing of datastore options with `file:` prefixes into msfconsole, sets a size limit (1Mb), and verifies that the argument is a file. Its too easy to accidentally read a giant file with the old method and this should be specific to console users and not all callers.

I couldn't find any third-party code that depended on `file:` outside of the console context, but for anyone who depends on this, the correct approach would be to set the datastore to the full value instead of passing the file argument.

### CODE REVIEW

**Comment by todb-r7** [comment]
I can fix up the rspec tests on this and ensure the new limitations are rspec'ed as well.

**Comment by jvazquez-r7** [comment]
@hmoore-r7 do you mind to check https://github.com/hmoore-r7/metasploit-framework/pull/12 and land once you feel comfortable with my proposed changes, feel free to discuss any point, of course!

If you could solve conflicts after landing https://github.com/hmoore-r7/metasploit-framework/pull/12 I'd be happy of landing this one!

**Comment by hmoore-r7** [comment]
@jvazquez-r7 Thanks! Landed your PR

**Comment by hmoore-r7** [comment]
@jvazquez-r7 Need some more time to eyeball the conflict and figure out intended behavior, looks like some substantial / weird changes.

**Comment by jvazquez-r7** [comment]
@hmoore-r7 see https://github.com/hmoore-r7/metasploit-framework/pull/13, please double check because I'm an specialist wasting things when solving conflicts =)

**Comment by jvazquez-r7** [comment]
Also, noticed which after this changes, some behavior has changed, and I'm a little bit concerted about the new behavior.

On ```Scanner``` auxiliary modules ```RHOSTS``` is an ```OptAddressRange``` so you can use the ```file:``` options. With the new changes, the ```RHOSTS``` is filled with the file contents at the time of the ```set RHOSTS``` command. 

So if you change the file contents between two runs, the new file contents are not read unless you make ```set RHOSTS``` again.

Example:

```
msf auxiliary(energizer_duo_detect) > set RHOSTS file:/tmp/test
RHOSTS => 127.0.0.1
127.0.0.1
127.0.0.1

msf auxiliary(energizer_duo_detect) > run

[*] Scanned 1 of 3 hosts (33% complete)
[*] Scanned 2 of 3 hosts (66% complete)
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
```

Now change /tmp/test contents to delte one entry, run the module again:

```
msf auxiliary(energizer_duo_detect) > run

[*] Scanned 1 of 3 hosts (33% complete)
[*] Scanned 2 of 3 hosts (66% complete)
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
```

It isn't true on master, since file contents are normalized at runtime:

```
msf auxiliary(energizer_duo_detect) > set rhosts file:/tmp/test
rhosts => file:/tmp/test
msf auxiliary(energizer_duo_detect) > run

[*] Scanned 1 of 2 hosts (50% complete)
[*] Scanned 2 of 2 hosts (100% complete)
[*] Auxiliary module execution completed
```

Now modify /tmp/test to add an entry and run again the module, the file is read again, without need to ```set RHOSTS``` again:

```
msf auxiliary(energizer_duo_detect) > run

[*] Scanned 1 of 3 hosts (33% complete)
[*] Scanned 2 of 3 hosts (66% complete)
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by hmoore-r7** [comment]
@jvazquez-r7 The change in behavior is expected (the file isn't re-read between runs.

**Comment by jvazquez-r7** [comment]
@hmoore-r7 ooom okey, if that's the desired behavior then everything is okey :-)

**Comment by jvazquez-r7** [comment]
@hmoore-r7 in that case just waiting for https://github.com/hmoore-r7/metasploit-framework/pull/13 to solve conflicts or feel free to close that one and make it by yourself if you feel more comfortable.

**Comment by hmoore-r7** [comment]
Seems OK here, feel free to land, thanks!

**Comment by bcook-r7** [comment]
We're thinking of backing this out for now. Are there any reasons we need this right away?

**Comment by hmoore-r7** [comment]
There may be some alternatives to doing this in the ```set``` command, but this fix is pretty important. Lets discuss via IRC.

**Comment by hmoore-r7** [comment]
Consensus is that reverting this is the best path forward.

**Comment by todb-r7** [comment]
:+1:

**Pull request merged**
