### PR TITLE
Addition of multiple read/write to auxiliary/scanner/scada/modbusclie…

### PR DESCRIPTION
**Pull request by alexandrinetorrents**
…nt.rb

### CODE REVIEW

**Comment by wchen-r7** [comment]
Hi @alexandrinetorrents, could you please provide a brief description about your pull request, and maybe some verification steps? Thanks.

**Comment by alexandrinetorrents** [comment]
Hi, I used the existing module modbusclient. Initially, we could only read or write a single coil/register at a time. So I modified the two read actions so that the user could choose the number of coils/registers to read. I also created two new actions to allow writing multiple coils/registers, as these are completely different functions in Modbus. I tested the new module with my Schneider PLC.
Let me know if you need further information.

**Comment by wchen-r7** [comment]
Cool thanks.

**Comment by wchen-r7** [comment]
I don't have a PLC for testing, but I'll see what I can do to verify at least this module runs.

**Comment by alexandrinetorrents** [comment]
Great, thank you!

**Pull request merged**
