### PR TITLE
Varnish cli login module

### PR DESCRIPTION
**Pull request by h00die**
Part of #7558 taking modules in EDB that were never imported.  This module had a lot of re-write to get it up to standardization.  After this passes, I'll incorporate a new aux module to read the first line of an arbitrary file, but felt the need to divide the module up in to two distinct pieces.

This module is a login scanner for Varnish-cli

## Verification

List the steps needed to make sure this thing works

- [x] Install the application
- [x] Start msfconsole
- [x] Do: ```use auxiliary/scanner/varnish/varnish_cli_login```
- [x] Optionally: set a new pass_file
- [x] Do: ```run```
- [x] Find a valid login.
- [x] Redo this with varnish set to no authentication.  Check the md docs.

I also want to note that if you are using `nano` to edit the secret file, nano may add an extra newline to the end of the file, which may alter the password validation.

### CODE REVIEW

**Comment by h00die** [comment]
thanks to @hdm @wvu-r7 and @busterb for their help on this.

**Comment by h00die** [comment]
Can this get some love @wchen-r7 :) almost 2 months old (maybe older?)

**Comment by h00die** [comment]
where is the love

**Comment by h00die** [comment]
@wchen-r7 is this on the docket still?  Its been almost 5 months w/o a review

**Comment by busterb** [comment]
Looks good authenticated:
```
[*] 192.168.1.10:6082    - 192.168.1.10:6082 - Authentication Required
[+] 192.168.1.10:6082    - 192.168.1.10:6082 - LOGIN SUCCESSFUL: secret
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

Tried a lot of negative cases as well. With newer versions of Varnish, it is difficult to disable authentication. If you specify -S "" it fails to start (though it is documented differently: https://varnish-cache.org/docs/5.1/users-guide/run_security.html)

**Comment by busterb** [comment]
Looks good h00die, landing.

**Comment by busterb** [comment]
Added a couple of documentation fixes: 0c3ef4bf47 deb7701d3e

**Comment by tdoan-r7** [comment]
# Release Notes

The Varnish CLI  login module has been added to the framework. It attempts to log into the Varnish Cache  CLI instance using a list of passwords.

**Pull request merged**
