### PR TITLE
User Hunter Plugin

### PR DESCRIPTION
**Pull request by jabra-**
Plugin to compare a list of known users with those that have been found via smb_enumuser_domain. Any users that are identified will be returned in the console

example usage: 

```
 msf> load user_hunter
   [*] Successfully loaded plugin: user_hunter
   msf > user_hunt_smb 
   Usage: user_hunt_smb [options] <username> [username] .. [username]

   OPTIONS:

    -f <opt>  A file containing a list of users to search for (one per line)
    -h        This help menu
    -v        Verbose flag

   msf > user_hunt_smb -f /tmp/da.txt
   [+] >> FOUND USER: 192.168.1.50- ACME\joe-admin
```

### CODE REVIEW

**Comment by jduck** [comment]
@brandonprry says why isn't this an aux module

**Comment by jabra-** [comment]
@jduck @brandonprry @hmoore-r7 I havent seen an aux module query the DB to just do a search for specific data, so i figured this would be best as a plugin. if there was a way to regex search the DB for a list of items that would be really handy.

**Comment by brandonprry** [comment]
Ignore @jduck it's not even my business. I think it's a great idea for a plugin.

**Comment by wchen-r7** [comment]
Hey @hmoore-r7, so Jabra suggested I should reach out to you about this PR.

How about we do:

```
msf > creds –o /tmp/creds.csv –m auxiliary/scanner/smb/smb_enumusers_domain –u file://tmp/users.txt --status 'successful'
```

**Comment by hmoore-r7** [comment]
@wchen-r7 Reworking this as an update to ``creds`` works for me, although I think the data is stored as notes right now, not credentials?

**Comment by hmoore-r7** [comment]
Like this might make more sense as a change to the ``notes`` command versus ``creds``, but if its a common enough use case, the plugin still works.

**Comment by wchen-r7** [comment]
> although I think the data is stored as notes right now, not credentials?

Hmm if I understand this, I don't think the new cred API is saving notes at all? I might be wrong, please double check.

So it looks like he needs to access notes to grab:

1. The username, which we know it's also provided by the Metasploit::Credential::Core object, so we can use that.
2. The "smb_loggedin_users" ntype. It looks like the new API is using note types, so perhaps a workaround is trying to access the credential status (being used successfully, invalid, etc, etc). Unfortunately I have not figured out how to do this. However, Jabra also says he's actually just trying to find users collected by smb_enumuser_domain, which I know how to do. Basically you can check the module name for that.

To support the new API, I think the code would look a bit more like this:

```ruby
def get_users(opts={})
  module_full_name = opts[:module_full_name]
  usernames = opts[:usernames]

  users = []

  query = Metasploit::Credential::Core.where( workspace_id: framework.db.workspace )
  query = query.includes(:private, :public, :logins)
  query = query.includes(logins: [ :service, { service: :host } ])
  query = query.where('"metasploit_credential_publics"."username" ~* ?', usernames)
  users = []
  query.each do |e|
    if e.origin.kind_of?(Metasploit::Credential::Origin::Service) && e.origin.module_full_name == module_full_name
      users << e.public.username
    elsif e.origin.kind_of?(Metasploit::Credential::Origin::Session) && e.origin.post_reference_name == module_full_name
      users << e.public.username
    end
  end

  users
end

users = get_users(
  module_full_name: 'auxiliary/scanner/smb/smb_enumusers_domain',
  usernames: ''
)
```

I used the following ERD to figure out how to use the API:

core erd

**Comment by jabra-** [comment]
I'm going to hold off on testing/making updates to this until the aux module is done.

**Comment by jabra-** [comment]
I refactored the code to work with the updated module. It's working with the exception that it isnt finding all of the IPs that are related to the specific user.

```
[+] << FOUND USER: ACME\jsmith - 1.1.1.1
[+] << FOUND USER: ACME\test2 - 10.10.10.50
2015-07-28 14:42:34 -0400 S:0 J:0> creds 
Credentials
===========

host         service        public        private  realm  private_type
----         -------        ------        -------  -----  ------------
1.1.1.1      445/tcp (smb)  ACME\jsmith                   
1.1.1.2      445/tcp (smb)  ACME\jsmith2                  
1.1.1.3      445/tcp (smb)  ACME\jsmith3                  
1.2.1.1      445/tcp (smb)  ACME\jsmith                   
1.3.1.1      445/tcp (smb)  ACME\jsmith                   
10.10.10.50  445/tcp (smb)  ACME\test2                    
10.10.10.50  445/tcp (smb)  ACME\test3                    
10.10.10.50  445/tcp (smb)  test           
```

the lookup and print part contains this bit:
```
      query = Metasploit::Credential::Core.where( workspace_id: framework.db.workspace )
      query = query.where('"metasploit_credential_publics"."username" = ?', find_user)
      query = query.includes(:private, :public, :logins)
      query = query.includes(logins: [ :service, { service: :host } ])
      
      query.each do |e|
        if e.origin.kind_of?(Metasploit::Credential::Origin::Service) && e.origin.module_full_name == module_full_name
          print_good("<< FOUND USER: #{find_user} - #{e.origin.service.host.address}")
          addrs << e.origin.service.host.address
        end
      end   
```

There should be multiple IPs related to ACME\jsmith, instead of just the one.

**Comment by wchen-r7** [comment]
@jabra- can you try this?


```ruby
      query = Metasploit::Credential::Core.where( workspace_id: framework.db.workspace )
      query = query.where('"metasploit_credential_publics"."username" = ?', find_user)
      query = query.includes(:private, :public, :logins)
      query = query.includes(logins: [ :service, { service: :host } ])

      query.each do |e|
        if e.origin.kind_of?(Metasploit::Credential::Origin::Service) && e.origin.kind_of?(Metasploit::Credential::Origin::Session)
          print_good("<< FOUND USER: #{find_user} - #{e.origin.service.host.address}")
          addrs << e.origin.service.host.address
        end
      end   
```

**Comment by jabra-** [comment]
@wchen-r7 got the same end-result.

**Comment by wchen-r7** [comment]
hmmmmmmm..... ok I need to think about how to do this.

@rapid7/framework-rapid7-committers anybody have an advice??

**Comment by jabra-** [comment]
@wchen-r7 i think the verifying the module piece should be included in a where clause as well as the service piece.

**Comment by jabra-** [comment]
@bcook-r7 @hmoore-r7 @wchen-r7 @jvazquez-r7  any feedback on this?

**Comment by bcook-r7** [comment]
@jabra- it's not clear what we need to do to finish this. What would we use this plugin for outside of the aux module it seems you are working on. I think without that context, it is hard to understand what this plugin is for.

**Comment by jabra-** [comment]
@bcook-r7 the plugin works around a limitation in-terms of msfconsole. There is no good way to search the DB for a list of specific users from a file. The plugin allow this to be done pretty easily. It's very useful when targeting specific users that have already been enumerated using the new aux module capabilities.

The use-case is you enumerate once and follow-up with targeting specific users, but you dont need to re-do the enumeration again.

**Comment by bcook-r7** [comment]
Sorry, it does not seem there is interest in adding this as a plugin, so I am going to close this PR.

**Pull request closed without merging**
