### PR TITLE
Add CSV and vCard support to dump_contacts

### PR DESCRIPTION
**Pull request by wvu**
I have no idea if this works or not, but it's been sitting in a branch since September.

### CODE REVIEW

**Comment by timwr** [comment]
Works great thanks @wvu-r7 
```
meterpreter > dump_contacts -h
Usage: dump_contacts [options]
Get contacts list.

OPTIONS:

    -f <opt>  Output format for contacts list (text, csv, vcard)
    -h        Help Banner
    -o <opt>  Output path for contacts list


meterpreter > dump_contacts -f csv
[*] Fetching 4 contacts into list
[*] Contacts list saved to: contacts_dump_20170121174248.csv
meterpreter > dump_contacts -f vcard
[*] Fetching 4 contacts into list
[*] Contacts list saved to: contacts_dump_20170121174258.vcf
```
There is an issue with the display name being duplicated in the phone number list but I'll fix that in meterpreter (where the issue actually exists).

**Comment by wvu-r7** [comment]
@timwr: Wow, it actually worked? I nearly rewrote the code without testing it again, lol. Thank you!

**Comment by wvu-r7** [comment]
@timwr: Wow, it actually worked? I rewrote the code without testing it again, lol. Thank you!

**Comment by wvu-r7** [comment]
# Release Notes

This adds CSV and vCard support to the `dump_contacts` command in Android Meterpreter.

**Pull request merged**
