### PR TITLE
Add an activity_start command to the Android meterpreter

### PR DESCRIPTION
**Pull request by timwr**
This pr adds a simple activity_start command to the android meterpreter prompt. This can be used to launch any external app or uri.
- [x] Merge the metasploit-payloads change
- [x] Get an Android meterpreter session
- [x] Launch a valid intent uri, and ensure it opens on the device e.g:

```
meterpreter > activity_start intent://reddit.com#Intent;scheme=http;action=android.intent.action.VIEW;end
[*] Intent started
```
- [ ] Try launch an invalid intent, and see an error, e.g:

```
meterpreter > activity_start intent://reddit.com#Intent;scheme=http;action=android.intent.action.VIEW;en
[-] Error: illegal Intent URI format at index 73: intent://reddit.com#Intent;scheme=http;action=android.intent.action.VIEW;en
```

This pr also allows some future work e.g: post/multi/manage/play_youtube on android and fixing remove_lock on 4.3 devices: https://github.com/timwr/metasploit-framework/commit/39fba426729b5d8d2dbf0715be398179e19ca9e9

### CODE REVIEW

**Comment by bcook-r7** [comment]
Nice, so we can launch arbitrary intents with this? Looks pretty useful.

**Comment by bcook-r7** [comment]
Works as advertised!

**Comment by bcook-r7** [comment]
landed, thanks!

**Comment by wvu-r7** [comment]
Great stuff. Now I don't have to use ```am```.

**Pull request merged**
