### PR TITLE
Fix #4645 for real

### PR DESCRIPTION
**Pull request by todb-r7**
## Verification
- [x] Run the post module, bask in results.
- [x] Note the lack of errors on trying to strip and array.
- [x] Learn how to test modules before submitting pull requests. :)

### CODE REVIEW

**Comment by todb-r7** [comment]
nm, @wvu-r7 got it.

**Comment by todb-r7** [comment]
@wvu-r7 did fix my strip placement, but it can still `NoMethodError` if you don't actually ever get a key file parsed right. This puts the strip against guaranteed strings.

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/commit/7d7139d769d344f2ec2f1895669cb5142ad0eece

**Comment by todb-r7** [comment]
Thanks @wvu-r7 !

Will see how we want to handle this in the next day or two -- e-mailing @claudijd to fill him in.

**Pull request merged**
