### PR TITLE
Move SECURITY.md from root folder to the .github folder

### PR DESCRIPTION
**Pull request by todb-r7**
This moves ~some files~ SECURITY.md from the root directory to the `.github` directory, per https://github.com/rapid7/metasploit-framework/pull/14062#pullrequestreview-477066463

~Moving these makes the root directory slightly tidier.~ Moving other things is likely to break links, so don't.

## Verification

List the steps needed to make sure this thing works

- [ ] After landing, make sure that SECURITY.md is still viewable as expected.
~- [ ] Ditto for CONTRIBUTING.md~
~- [ ] Ditto for CODE_OF_CONDUCT.md~
- [ ] Ensure nothing else is moved.

~Note, I didn't move LICENSE.md because that, to me, is not merely a GitHub thing, but is core to the distribution.~

### CODE REVIEW

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by adfoster-r7** [comment]
Just confirming if any links will need to be updated? Such as read me files / wiki articles / automated scripts?

https://github.com/rapid7/metasploit-framework/blob/e01d9e701b1be4f665852488d26b52ec0c4cd68a/README.md#L40
https://github.com/rapid7/metasploit-framework/blob/76954957c740525cff2db5a60bcf936b4ee06c42/.yardopts#L5
https://github.com/rapid7/metasploit-framework/blob/3518b9465ccc8928872ef3904938111be4a74744/documentation/modules/post/windows/gather/checkvm.md#L3

---

My 2 cents: I'm not sure if we'd want to hide these files in the `.github` folder. I think having these files at the top level makes them more discoverable to the average user - which is particularly important for the `CONTRIBUTING.md`/`CODE_OF_CONDUCT.md` files.  I'm also not sure what automation tools this will break behind the scenes either, even beyond the scripts that exist inside this repository.

**Comment by smcintyre-r7** [comment]
>My 2 cents: I'm not sure if we'd want to hide these files in the .github folder. I think having these files at the top level makes them more discoverable to the average user - which is particularly important for the CONTRIBUTING.md/CODE_OF_CONDUCT.md files.

They'll still automatically show up in the GitHub UI when a user goes to contribute. 
image
See: https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

I also think it's safe to say that we have a lot more users that are not contributors than are so these files aren't necessarily relevant to them all.

**Comment by todb-r7** [comment]
> Just confirming if any links will need to be updated? Such as read me files / wiki articles / automated scripts?

Oh, that's a good call. There's probably a fair amount of grepping to do to make those updates simultaneously. I'll do that and use the fancy new "convert to draft" for this PR.

**Comment by adfoster-r7** [comment]
Just making an additional note that this will also break links that are outside of source control.

A quick Google for `https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md` shows links from Github issues, third party blogs, tutorials, as well as our own Framework blogs.

For instance https://blog.rapid7.com/2019/01/10/metasploit-framework-5-0-released/ - which has a `Start Here` link to the contributing file.

This will also introduce dead links to the wiki too, a quick ripgrep shows the wiki files which would be impacted:

```
$ rg -l CONTRIBUTING.md
Common-Metasploit-Module-Coding-Mistakes.md
Committer-Rights.md
So-Your-PR-was-closed.md
Guidelines-for-Accepting-Modules-and-Enhancements.md
_Sidebar.md
Contributing-to-Metasploit.md
Style-Tips.md
Writing-External-GoLang-Modules.md
dev/_Sidebar.md
dev/Setting-Up-a-Metasploit-Development-Environment.md
```

Unless Github will handle these redirects transparently for us, this change seems like it might introduce more overhead than benefit - but let me know if I'm missing something here :+1:

**Comment by todb-r7** [comment]
@adfoster-r7, you are convincing me that this is a Bad Idea :) Tidiness for tidiness's sake isn't a great motivator for a project that has this kind of out-in-the-world crosslinking history.

How's about I scale this back to just SECURITY.md as @smcintyre-r7 originally requested?

**Comment by todb-r7** [comment]
Fun fact, `git revert` doesn't prompt for commit signing. But, the last commit here is signed, which implies signing for everything before.

**Comment by gwillcox-r7** [comment]
@todb-r7 Looks good, just renamed the title of this PR to reflect the fact that it is now just the SECURITY.md file rather than all the other files as it was before.

**Comment by gwillcox-r7** [comment]
@todb-r7 Did a rebase to clean up the commit history as we only really needed the last commit and this makes the commit history neater. Will merge this in now.

**Pull request merged**
