### PR TITLE
fix #9019 - Travis Timeouts on build

### LINKED ISSUE #9019: Travis docker-compose Build Jobs failed with timeouts
## Steps to reproduce

Trigger travis builds with a commit and docker-compose job failed with a timeout.

Details: https://travis-ci.org/rapid7/metasploit-framework/jobs/281087764

### PR DESCRIPTION
**Pull request by firefart**
This fixes the timeouts occuring on the docker build step.

Fixes #9019

### CODE REVIEW

**Comment by pbarry-r7** [comment]
Merged and Travis build restarted.  🤞 

Thx, @FireFart!

**Comment by pbarry-r7** [comment]
LOL, I need more coffee this morning.  Folks should pull this fix into their PR branches, *then* restart the Travis jobs...

**Comment by pbarry-r7** [comment]
CC @mpizala and @bigendiansmalls ^^^

**Comment by bigendiansmalls** [comment]
Cheers thx

**Comment by mpizala** [comment]
@pbarry-r7 Thanks!

**Pull request merged**
