### PR TITLE
add automation test for smb_ms17_010 scanner module

### PR DESCRIPTION
**Pull request by jmartin-tech**
Since someone asked recently if smb_ms17_010 scanner module was working, here is a test we can run to validate.

## Verification

List the steps needed to make sure this thing works

- [x] **Verify** PR automation testing passes

### CODE REVIEW

**Comment by Auxilus** [comment]
Hi, The problem I am having is that the scanner module gives `Errno:: ECONNRESET: Connection reset by peer`, the ms17_010_psexec module works fine and gives me session.
screenshot_20180818-143232
screenshot_20180818-143533

**Comment by Auxilus** [comment]
pcaps are at:
https://github.com/Auxilus/Auxilus.github.io/raw/master/smb_ms17_010.pcap
https://github.com/Auxilus/Auxilus.github.io/raw/master/ms17_010_psexec.pcap

**Comment by bwatters-r7** [comment]
@Auxilus that pcap for the scanner seems odd.  No reset packet or smb error is in it, though I am not an SMB expert.  I think there's something the scanner module is not catching and we will need to deeper dive to determine what that is.  I do not think it is something that should hold this test up.  I'm going to go ahead and land this, but please file an issue if you have not already done so and attach the pcaps, a description of the the machine, and any other customization.  It is entirely possible that we are not prepared for all the responses, and we are misidentifying one.  Unfortunately, that could be happening in lots of places, and running it down could take some time, so it's own issue would be best place for us to research it.

**Comment by bwatters-r7** [comment]
# Release Notes
This PR adds automated tests to ensure the ms17-010 scanner functions properly

**Pull request merged**
