### PR TITLE
Remove metcli.exe from data/meterpreter

### PR DESCRIPTION
**Pull request by OJ**
The metcli.exe binary doesn't get used any more and the source was removed from Meterpreter ages ago. No point in having it in the repo any more.

See discussion here: https://github.com/rapid7/meterpreter_bins/issues/11

### CODE REVIEW

**Comment by bcook-r7** [comment]
PR 4567 - lucky guy.

**Comment by OJ** [comment]
ooh! I'll go buy a lottery ticket :moneybag:

**Comment by bcook-r7** [comment]
Don't forget about me when you're rich and famous.

**Comment by OJ** [comment]
This PR is the pinnacle of my career.

**Pull request merged**
