### PR TITLE
Fix travis builds (temporary fix)

### PR DESCRIPTION
**Pull request by bcook-r7**
This should fix our build fallout from bundler 1.10.0 being released.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Hmm, this seems like the wrong approach. Downgrading bundler breaks gem caching in bundler. Having to manually 'bundle install' makes it rebuild all the gems. One of our gems needs libpcap-dev installed. To install that, we need to use sudo, which cascades into no longer being able to use container builds.

**Comment by FireFart** [comment]
@bcook-r7 as of git 1.9 you can do:
`git diff -- . ':!Gemfile.lock'`
to exclude this specific file from git diff. May be a better approach?

**Comment by bcook-r7** [comment]
Sounds good to me. Basically bundler 1.10 and up are going to be randomly causing breakage. As a longer-term solution, we're filing an issue with bundler for a way to disable the bundled by tag.

**Comment by FireFart** [comment]
@bcook-r7 crap seems like the installed git version on travis is too old :(
`git diff --exit-code -- . ':!Gemfile.lock' && bundle exec rake $RAKE_TASKS

fatal: Unimplemented pathspec magic '!' in ':!Gemfile.lock'`

**Comment by bcook-r7** [comment]
Hmm, apparently not - the environment travis runs in cannot grok the pathspec.

**Comment by shuckins-r7** [comment]
@bcook-r7 Any update on that ticket to bundler to not include the 'BUNDLED BY'? Seeing breakages on Travis due to this: https://travis-ci.org/rapid7/metasploit-framework/jobs/65137103  I can't see how this wouldn't continually cause breakage since every time a new version of bundler comes out and Travis uses it, we would get a diff, build fails, and we'd have to update the Gemfile.lock.

**Comment by bcook-r7** [comment]
Awful isn't it? Yes, it will break every time. For now I have deferred to GES to help arrive at a solution.

**Comment by shuckins-r7** [comment]
@bcook-r7 Ah, so bundler crew was not receptive to the suggestion? I can't imagine we are alone in struggling with this. Not sure what GES will be able to do since this is Travis, not an internal service. I naively suggest pinning to 1.9.2: https://github.com/rapid7/metasploit-framework/pull/5458 From this PR, though, it sounds like that would cause some undesired change, although I am not clear on what. Were we calling bundle install before when on older bundler with sudo? Or did you mean that explicitly specifying the downgrade to bundler would require bundle install to be called?

**Comment by bcook-r7** [comment]
I experimented with downgrading bundler, which caused Travis' bundle cache feature to stop working, requiring one to call 'bundle install'. That had the side-effect of needing to not only rebundle all of the modules, but the pcaprub gem needs system headers that are not installed by default, needing to use sudo to install them. When then slows builds down more, because sudo puts you in the VM rather than container tier.

Maybe there is a nicer way to downgrade bundler, but I didn't see a way yet. GES-3103 for additional info

**Comment by bcook-r7** [comment]
Also, issues filed with bundler itself about this new behavior:

https://github.com/bundler/bundler/issues/3697#issuecomment-107943607

**Comment by kernelsmith** [comment]
Unfortunately, at least one bundler dev doesn't seem to give a rat's ass about the problem

**Comment by shuckins-r7** [comment]
@bcook-r7 Thanks very much for the explanation! What had me scratching my bald pate was that other PRs and current MSF master are passing Jenkins, while release branch was failing. Then I discovered that you recently changed the Travis git diff check to just schema.rb vs the entire repo: https://github.com/rapid7/metasploit-framework/commit/00b8dbfe9b72e4dd5722deccc00716463593d4d2 I'll get that pulled into release to get it passing, so I've closed https://github.com/rapid7/metasploit-framework/pull/5458 since not needed now.

**Pull request merged**
