### PR TITLE
Resolve #5753, Support Origin for the creds command

### LINKED ISSUE #5753: Have an Origin column for the creds command
If a credential is from Metasploit::Credential::Origin::Service or Metasploit::Credential::Origin::Session, the creds command should say which host it comes from.

Note: Metasploit::Credential::Origin::Import might not have this info.

Related to #5725

### PR DESCRIPTION
**Pull request by wchen-r7**
Resolve #5753. Add an Origin column and allow the user to search by origin.
## Verification
- [x] To test this, make sure your database has some credentials.
- [x] Do `creds -h`
- [x] You should see the new -O (or --origins) option
- [x] Do `creds`
- [x] You should see all the creds listed
- [x] Pick an origin from the list, and then do `creds -O [origin IP]`
- [x] You should see all the creds with the same origin
- [x] Pick a host (not origin) from the list, and then do `creds -R [host IP]`
- [x] You should see all the creds with the same host

### CODE REVIEW

**Comment by jvazquez-r7** [comment]
When I do `creds -O` I see also credentials without origin, is it intended?

```
msf > creds -O 172.16.158.132
Credentials
===========

host            origin          service         public         private                                                                                                                                                 realm  private_type
----            ------          -------         ------         -------                                                                                                                                                 -----  ------------
                                                Administrator  Administrator::DEMO:1122334455667788:d31fc32e7fd54a93156ab42a835e8858:0101000000000000480d4cb707b8d001651d522b97de03cc00000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:48f0498daf234ade9093aec35d48e0d9:b80769ef1b3ceb13                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:1907b1db2d9b5327fcc78dceba2e3878:0101000000000000a4f1908d07b8d001b80769ef1b3ceb1300000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:869c1ad4e25fcc10cf5632b9b671c887:20615c36ea62e0b1                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:e05880c1d1f6f8e7b39889bdeca99b9c:0101000000000000dbf9d58d07b8d00120615c36ea62e0b100000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:d17a87cda81efc85fbb5f99a75bae1c3:d6d2a7101c9868b6                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:d22aaf9e1b091e40ce2db7eed20ec175:651d522b97de03cc                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:ff21fd3c4555c474b307d41ea8c2ae92:c316b20f02346c1e                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:2fa47ea759abc68d3fde89fb8d95198e:0101000000000000978b10b707b8d001c316b20f02346c1e00000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:70fc7ca843da7c8f39270e6fecbdf3a6:d74b244aa844069d                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:822e52e7c50865a684b0c07830d76ab3:0101000000000000964a47b707b8d001d74b244aa844069d00000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:d93e206fb8f2bb9132e8c3d8e985166e:0101000000000000041edd8d07b8d001d6d2a7101c9868b600000000020000000000000000000000         Nonreplayable hash
172.16.158.132  172.16.158.132  5900/tcp (vnc)                 admin                                                                                                                                                          Password
```

**Comment by jvazquez-r7** [comment]
Does -O requires an argument? From the description I'd say yes (origins to match). But I can just run `creds -O`, even when an error message is printed (`[-] Invalid host parameter, .`) all the creds are showed:

```
msf > creds -O
[-] Invalid host parameter, .
Credentials
===========

host            origin          service          public         private                                                                                                                                                 realm  private_type
----            ------          -------          ------         -------                                                                                                                                                 -----  ------------
                                                 Administrator  Administrator::DEMO:1122334455667788:d31fc32e7fd54a93156ab42a835e8858:0101000000000000480d4cb707b8d001651d522b97de03cc00000000020000000000000000000000         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:d22aaf9e1b091e40ce2db7eed20ec175:651d522b97de03cc                                                                         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:822e52e7c50865a684b0c07830d76ab3:0101000000000000964a47b707b8d001d74b244aa844069d00000000020000000000000000000000         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:70fc7ca843da7c8f39270e6fecbdf3a6:d74b244aa844069d                                                                         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:2fa47ea759abc68d3fde89fb8d95198e:0101000000000000978b10b707b8d001c316b20f02346c1e00000000020000000000000000000000         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:ff21fd3c4555c474b307d41ea8c2ae92:c316b20f02346c1e                                                                         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:d93e206fb8f2bb9132e8c3d8e985166e:0101000000000000041edd8d07b8d001d6d2a7101c9868b600000000020000000000000000000000         Nonreplayable hash
                                                 juan           7f:5f:b3:09:b0:55:97:0e:e3:c6:05:d7:9a:d5:62:cc                                                                                                                SSH key
                                                 Administrator  Administrator::DEMO:1122334455667788:48f0498daf234ade9093aec35d48e0d9:b80769ef1b3ceb13                                                                         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:1907b1db2d9b5327fcc78dceba2e3878:0101000000000000a4f1908d07b8d001b80769ef1b3ceb1300000000020000000000000000000000         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:d17a87cda81efc85fbb5f99a75bae1c3:d6d2a7101c9868b6                                                                         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:e05880c1d1f6f8e7b39889bdeca99b9c:0101000000000000dbf9d58d07b8d00120615c36ea62e0b100000000020000000000000000000000         Nonreplayable hash
                                                 Administrator  Administrator::DEMO:1122334455667788:869c1ad4e25fcc10cf5632b9b671c887:20615c36ea62e0b1                                                                         Nonreplayable hash
172.16.158.132  172.16.158.132  5900/tcp (vnc)                  admin                                                                                                                                                          Password
172.16.158.133  172.16.158.133  80/tcp (http)    admin
172.16.158.136  172.16.158.136  4848/tcp (http)  admin          123456                                                                                                                                                         Password
172.16.158.136  172.16.158.136  4848/tcp (http)  admin          admin1234                                                                                                                                                      Password
172.16.158.136  172.16.158.136  4848/tcp (http)  admin          admin12345                                                                                                                                                     Password
192.168.1.123   192.168.1.123   80/tcp (http)    admin          mypass                                                                                                                                                         Password
192.168.1.123   192.168.1.122   445/tcp (smb)    fakeuser       fakepass                                                                                                                                                       Password
```

**Comment by wchen-r7** [comment]
Yeah -O requires an argument.

**Comment by wchen-r7** [comment]
@jvazquez-r7 So if you actually see empty origins, I suppose that means there's something weird with this:

https://github.com/rapid7/metasploit-framework/pull/5772/files#diff-2cbd0086dda03d12d7a84d971eddadbaR1073

```!origin.empty?``` really should filter out the empty origins though.... can you please maybe #.blank?

**Comment by jvazquez-r7** [comment]
```Yeah -O requires an argument (an origin IP)``` 

* so should just show an error when running it without argument :? just asking I'm not sure what is the original purpose I mean.

```!origin.empty? really should filter out the empty origins though.... can you please maybe try #.blank?```

* sure, sitched to blank?, I still see these entries without origin even when I'm adding the filter

```
msf > creds -O 172.16.158.132
Credentials
===========

host            origin          service         public         private                                                                                                                                                 realm  private_type
----            ------          -------         ------         -------                                                                                                                                                 -----  ------------
                                                Administrator  Administrator::DEMO:1122334455667788:d31fc32e7fd54a93156ab42a835e8858:0101000000000000480d4cb707b8d001651d522b97de03cc00000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:48f0498daf234ade9093aec35d48e0d9:b80769ef1b3ceb13                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:1907b1db2d9b5327fcc78dceba2e3878:0101000000000000a4f1908d07b8d001b80769ef1b3ceb1300000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:869c1ad4e25fcc10cf5632b9b671c887:20615c36ea62e0b1                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:e05880c1d1f6f8e7b39889bdeca99b9c:0101000000000000dbf9d58d07b8d00120615c36ea62e0b100000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:d17a87cda81efc85fbb5f99a75bae1c3:d6d2a7101c9868b6                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:d22aaf9e1b091e40ce2db7eed20ec175:651d522b97de03cc                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:ff21fd3c4555c474b307d41ea8c2ae92:c316b20f02346c1e                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:2fa47ea759abc68d3fde89fb8d95198e:0101000000000000978b10b707b8d001c316b20f02346c1e00000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:70fc7ca843da7c8f39270e6fecbdf3a6:d74b244aa844069d                                                                         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:822e52e7c50865a684b0c07830d76ab3:0101000000000000964a47b707b8d001d74b244aa844069d00000000020000000000000000000000         Nonreplayable hash
                                                Administrator  Administrator::DEMO:1122334455667788:d93e206fb8f2bb9132e8c3d8e985166e:0101000000000000041edd8d07b8d001d6d2a7101c9868b600000000020000000000000000000000         Nonreplayable hash
172.16.158.132  172.16.158.132  5900/tcp (vnc)                 admin                                                                                                                                                          Password

msf >
```

**Comment by jvazquez-r7** [comment]
Works as expected now:

```
msf > creds -O
[-] Argument required for -O
msf > creds -O 172.16.158.132
Credentials
===========

host            origin          service         public  private  realm  private_type
----            ------          -------         ------  -------  -----  ------------
172.16.158.132  172.16.158.132  5900/tcp (vnc)          admin           Password

```

Thanks @wchen-r7 , landing!

**Comment by wchen-r7** [comment]
Cool thanks!

**Pull request merged**
