### PR TITLE
HNAP vs UPnP

### PR DESCRIPTION
**Pull request by m-1-k-3**
the vulnerability is not in UPnP, it is in the HNAP (Home Network Administration Protocol) implementation from Dlink

thx to Craig for pointing me to this

### CODE REVIEW

**Comment by OJ** [comment]
3 commits for a name/description change?

**Comment by m-1-k-3** [comment]
sorry @OJ  ... typing faster than thinking ;)

**Comment by OJ** [comment]
No biggie mate. If you could please rebase those commits into one that'd be
awesome thanks 👍

**Comment by kernelsmith** [comment]
@m-1-k-3 you can just squash the commits w/rebase like this http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html and this PR will get updated automatically

**Pull request closed without merging**
