### PR TITLE
Fix nil bug in loot -a and nix hostless loot

### PR DESCRIPTION
**Pull request by wvu**
So, hostless loot doesn't actually store. At least I can't ever retrieve it. Making a host required now.

- [x] Test `loot -a`
- [x] See that all the bugs in `CommandDispatcher` have been fixed

### CODE REVIEW

**Comment by sempervictus** [comment]
What happens to old loot stored with no host data, or loot for hosts which don't exist anymore?
Agree though, we want this tied to an entity (host for now) to avoid dangling data elements. Thank you much sir.

**Comment by wvu-r7** [comment]
@sempervictus: I tried to store loot without any host data, and it simply wouldn't stick. As far as I can tell, it's (now?) a no-op. If we're concerned, I can add back the code for hostless loot... Probably ideal to see if and when it diverged before landing this. Thanks for the comment!

**Comment by wvu-r7** [comment]
While it might be dead code now - or I'm just an idiot - it was probably not dead code before, so I've readded the hostless loot display for folks who might need it.

**Comment by jbarnett-r7** [comment]
I verified that the `loot -a` command is now giving useful output when no host is specified and no longer throwing a stack trace. I'm not sure about the "See that all the bugs in CommandDispatcher have been fixed" step of verification, though, since I don't really have the time to verify there are no bugs in CommandDispatcher at all. I'm guessing there are still some, but in other commands, but for the sake of this PR I think the requirements are met.

**Comment by wvu-r7** [comment]
Oh, that was a joke. Thanks for landing!

**Comment by jmartin-r7** [comment]
### Release Notes

This update fixes an issue when attempting to store loot without host details.

**Pull request merged**
