### PR TITLE
Update to the latest meterpreter_bins

### PR DESCRIPTION
**Pull request by bcook-r7**
This removes checked-in sniffer extension in favor of the gem-packaged version, fixing rapid7/meterpreter_bins#11.

It also pulls in the changes for verifying #4411.
# Steps to Verify
- [x] Run 'bundler install' to get the latest meterpreter_bins gem.
- [x] Start a meterpreter session and ensure that 'load sniffer' works as loaded from the gem .dll file

You can also verify the steps for #4411 and make sure that the things there still work on master without the actual #4411 changes (ensure backward compatibility).

### CODE REVIEW

**Comment by OJ** [comment]
Processing now.

**Comment by wvu-r7** [comment]
Yeah, @OJ!

**Comment by OJ** [comment]
Hey @bcook-r7 the binaries appear to still be in the repo in `data/meterpeter`: https://github.com/bcook-r7/metasploit-framework/tree/meterpreter_bins-11/data/meterpreter . Should they be removed as part of this PR?

**Comment by bcook-r7** [comment]
binaries? what binaries? (checks - oh, they got added back)

Yes, they should! Updated the PR.

**Comment by OJ** [comment]
Much better :)
```
~/c/metasploit-framework git:buster-meterpreter ❯❯❯ ls data/meterpreter
ext_server_android.jar    ext_server_stdapi.jar     ext_server_stdapi.py      meterpreter.php           metsvc.exe
ext_server_networkpug.lso ext_server_stdapi.lso     metcli.exe                meterpreter.py            msflinker_linux_x86.bin
ext_server_sniffer.lso    ext_server_stdapi.php     meterpreter.jar           metsvc-server.exe
```

**Comment by OJ** [comment]
Yay new gem.
```
~/c/metasploit-framework git:buster-meterpreter ❯❯❯ bundle install
Resolving dependencies...
 ... snip ...
Installing meterpreter_bins 0.0.13
 ... snip ...
```

**Comment by OJ** [comment]
@bcook-r7 Is going through #4411 necessary for this PR to be deemed legit?

**Comment by OJ** [comment]
Looking good on x64
```
meterpreter > use sniffer
Loading extension sniffer...success.
meterpreter > sysinfo
Computer        : WIN-TV01I7GG7JK
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : en_US
Meterpreter     : x64/win64
```

**Comment by OJ** [comment]
Loads fine in x86 as well:
```
meterpreter > use sniffer
Loading extension sniffer...success.
meterpreter > sysinfo
Computer        : WIN-TV01I7GG7JK
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64 (Current Process is WOW64)
System Language : en_US
Meterpreter     : x86/win32
```

**Comment by OJ** [comment]
This looks fine to me and I'm ready to land it, assuming that I don't have to run through #4411 stuff as well :) @bcook-r7 ?

**Comment by bcook-r7** [comment]
That's fine with me.

I'm actually thinking it won't kill anyone if #4411 sits out a little longer. I'm fixing the PHP meterpreter, and would love to start the next cycle with all of them on the same footing.

**Comment by bcook-r7** [comment]
Plus, if there's a bug in the next release, we can just blame @Meatballs1 :)

**Comment by OJ** [comment]
Awesome :) OK, landing.

**Comment by OJ** [comment]
Doneski! Thanks @bcook-r7.

**Pull request merged**
