### PR TITLE
fix snmp library to run correct version

### LINKED ISSUE #15922: scanner/snmp/snmp_login does not obey selected snmp version
metasploit module scanner/snmp/snmp_login does not use Version 1 at all, not when selecting "all", nor when directly selecting "1". I had issues with this module in the past. I just tested it, when setting "Version 1" as the option, the UDP package is send with v2c. Checked this with wireshark, added the screenshots.

Metasploit version 6.1.14-dev

Did you install Metasploit with...

* [X] Kali package via apt ()
* [ ] Omnibus installer (nightly)
* [ ] Commercial installer (from https://www.rapid7.com/products/metasploit/download/)
* [ ] Source install (please specify Ruby version)

### PR DESCRIPTION
**Pull request by h00die**
fixes #15922

also runs `rubocop -a` and `rubocop -A`.  Confirmed working correctly now via wireshark.

### CODE REVIEW

**Comment by h00die** [comment]
https://github.com/rapid7/metasploit-framework/pull/15984/files#diff-66927a887782236a20ac283b95503c935a883797a0b35d55da992aead7a98b33R261

and

https://github.com/rapid7/metasploit-framework/pull/15984/files#diff-66927a887782236a20ac283b95503c935a883797a0b35d55da992aead7a98b33R281

are the lines that fix the original issue

**Comment by h00die** [comment]
I used https://hub.docker.com/r/polinux/snmpd to test against if you need a docker image

**Comment by h00die** [comment]
@usd-markus if you have time to test this, let me know if it fixes your issue

**Review by jmartin-tech — APPROVED** [review]
LGTM

**Comment by bwatters-r7** [comment]
image

**Comment by bwatters-r7** [comment]
# Release Notes
This PR fixes a bug in the snmp library which caused it to ignore version 1, despite specifically set options.

**Comment by usd-markus** [comment]
> @usd-markus if you have time to test this, let me know if it fixes your issue

@h00die sorry for the late response, everything working as expected :) thank you!

**Pull request merged**
