### PR TITLE
Add wordlists for enumerating WordPress plugin/theme directories

### PR DESCRIPTION
**Pull request by NoodleOfDeath**
This file is useful for enumerating WordPress plugin directories located at `wp/wp-content/plugins` and theme directories located at `wp/wp-content/themes`

## Verification

- [x] Run in terminal `dirb http://target:port/path/to/wordpress/wp-content/plugins /usr/share/metasploit-framework/data/wordlists/wp-plugins.txt `
- [x] Run in terminal `dirb http://target:port/path/to/wordpress/wp-content/themes /usr/share/metasploit-framework/data/wordlists/wp-themes.txt `

### CODE REVIEW

**Comment by bcoles** [comment]
Where is this list from? Is it licensed?

**Comment by NoodleOfDeath** [comment]
I retrieved most of this list from http://hacks.rocks/wordpress-plugin-wordlist/ added in wp-forum and intend to add more.

**Comment by NoodleOfDeath** [comment]
Perhaps if I generated my own list by hand would this not be an issue?

**Comment by wchen-r7** [comment]
Let me leave a comment on that page and see if the author responds :-)

**Comment by wchen-r7** [comment]
Waiting for a reply:

Screen Shot 2019-05-24 at 10 37 46 AM

**Comment by NoodleOfDeath** [comment]
I actually commented myself as well a few days ago
Screenshot from 2019-05-24 14-05-16

**Comment by FireFart** [comment]
No need for copyright stuff. Just parse these two repos for the slugs:
https://plugins.svn.wordpress.org/
https://themes.svn.wordpress.org/

**Comment by NoodleOfDeath** [comment]
Updated the files to reflect the lists provided publicly by WordPress removing the possibility for infringing copyrights. Both lists can be used to enumerate plugins and themes directories

**Comment by h00die** [comment]
It would be a good idea to post the code here so it could be replicated in the future. See https://github.com/rapid7/metasploit-framework/pull/11199#issue-242415518 as an example

**Comment by NoodleOfDeath** [comment]
the following script can be used to generate these word lists:

```
#!/bin/bash

$(curl -s https://plugins.svn.wordpress.org) | while IFS="" read -r p; do 
	if [[ $p =~ \<a.*?\>(.*?)/\</a\> ]]; then 
		echo "${BASH_REMATCH[1]}" 
	fi
done > wp-plugins.txt

$(curl -s https://themes.svn.wordpress.org) | while IFS="" read -r p; do 
	if [[ $p =~ \<a.*?\>(.*?)/\</a\> ]]; then 
		echo "${BASH_REMATCH[1]}" 
	fi
done > wp-themes.txt
```

**Comment by NoodleOfDeath** [comment]
The following script can be used to generate these wordlists:

```
#!/bin/bash

curl -s http://10.11.0.73/test | while IFS="" read -r p; do 
	if [[ $p =~ \<a.*?\>(.*?)/\</a\> ]]; then 
		echo "${BASH_REMATCH[1]}" 
	fi
done > wp-plugins.txt

curl -s https://themes.svn.wordpress.org | while IFS="" read -r p; do 
	if [[ $p =~ \<a.*?\>(.*?)/\</a\> ]]; then 
		echo "${BASH_REMATCH[1]}" 
	fi
done > wp-themes.txt
```

**Comment by wchen-r7** [comment]
Ok, looks like this is good to go? I can land this?

**Comment by NoodleOfDeath** [comment]
I am happy with it if you are!

**Comment by wchen-r7** [comment]
# Release Notes

This adds wordlists for WordPress plugin/theme directories.

**Pull request merged**
