### PR TITLE
Make vulns and notes with -o similar to services and hosts

### PR DESCRIPTION
**Pull request by jhart-r7**
Now all of them will simply save the requested information to an output file if specified and will let you know where the file is when done. Previously, notes would also print out all of the notes, which just felt weird and inconsistent.  So, I fixed it.

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [x] Start `msfconsole`
- [x] Create a new workspace with `workspace -a `
- [x] scan with some module that reports notes
- [x] Run `notes` to confirm that it lists notes, and `notes -o /tmp/notes` and simply says that it saved the notes to /tmp/notes but didn't print them out.

```
msf5 > notes
[*] Time: 2018-03-07 18:22:37 UTC Note: host=10.4.29.171 type=host.virtual_machine data={:vendor=>"VMWare", :method=>"netbios"}
msf5 > notes -o /tmp/notes
[*] Notes saved as /tmp/notes
msf5 > services -o /tmp/services
[*] Wrote services to /tmp/services

```

### CODE REVIEW

**Comment by mkienow-r7** [comment]
I made changes to standardize the behavior of the `vulns` command (table output and suppressed console display when output to file) as a part of Goliath changes for `vulns` back on 2/22/2018 (ecad74cf990bf6ba5e9b5785f0acac07ab3584fa). Those changes just landed as a part of #9717.

**Comment by jhart-r7** [comment]
@mkienow-r7 thanks for pointing that out.  I've resolve the conflict and reworked the PR to just focus on notes and the annoying blank services line.

**Comment by wvu-r7** [comment]
I'll reevaluate my own changes once this is landed. Thanks for handling, @mkienow-r7!

**Comment by mkienow-r7** [comment]
# Release Notes

Makes the `notes` command file output option behave similar to the `services` and `hosts` commands. If an output file is specified, it simply displays the location of the output file not all of the notes as well.

**Pull request merged**
