### PR TITLE
Add #get_hidden_inputs for Rex::Proto::Http::Response

### PR DESCRIPTION
**Pull request by wchen-r7**
This is a patch that allows Rex HTTP Response to retrieve hidden inputs from a form. The reason for this is because sometimes hidden inputs contain important information that are required to pass on to the authenticator, for example: the view state, session ID, user id, token, etc. This API should be sort of handy.
## Verification
- [x] Travis is green
- [x] `cd lib/rex/proto/http/`
- [x] `yard doc response.rb`
- [x] It should generate a new doc directory
- [x] Open doc/index.html, and find the API doc for get_hidden_inputs. Make sure it reads fine.

Try the API:
- [x] Create the following file as /tmp/test.html

``` html
      <html>
      <head>
      <body>
      <form action="test.php">
        <input name="input_1" type="hidden" value="some_value_1" />
      </form>
      <form>
        <input name="input_0" type="text" value="Not a hidden input" />
        <input name="input_1" type="hidden" value="some_value_1" />
        <INPUT name="input_2" type="hidden" value="" />
      </form>
      </body>
      </head>
      </htm>
```
- [x] Under /tmp, start a web server: `ruby -run -e httpd . -p 8181`
- [x] Start msfconsole
- [x] Go to IRB
- [x] Send a HTTP request to the Ruby web server like the following in IRB:

```
cli = Rex::Proto::Http::Client.new('127.0.0.1', 8181)
cli.connect
req = cli.request_cgi({'uri'=>'/test.html'})
res = cli.send_recv(req)
inputs = res.get_hidden_inputs
```
- [x] Inspect the inputs variable, and it should look like this:

```
>> puts inputs.inspect
[{"input_1"=>"some_value_1"}, {"input_1"=>"some_value_1", "input_2"=>""}]
```

### CODE REVIEW

**Comment by FireFart** [comment]
aren't you missing a selector for the hidden keyword? currently it selects all input elements or am I missing smth?

**Comment by wchen-r7** [comment]
Oh yes, I need to check hidden. I removed that code at one point but forgot to put it back. Nice catch.

**Comment by jlee-r7** [comment]
This feels like it should be on the response object, not all the way up in `LoginScanner`.

**Comment by wchen-r7** [comment]
I can put this over there.

**Comment by wchen-r7** [comment]
Just moved all this to Rex, updated rspec, and updated the PR verification steps. Should be good to go again.

**Comment by bcook-r7** [comment]
Looks good to me, thanks @wchen-r7:
```
>> inputs = res.get_hidden_inputs
=> [{"input_1"=>"some_value_1"}, {"monkey_1"=>"some_value_1", "monkey_2"=>""}]
```

**Pull request merged**
