### PR TITLE
Update SMB admin modules to use Scanner, more; Fixes #3994

### LINKED ISSUE #3994: auxiliary/admin/smb modules to support RHOSTS and FILE_LIST options for mass processing
It would be awesome if all `auxiliary/admin/smb` modules, notably `upload_file` and `download_file`, could support the following options:
* `RHOSTS`, instead of the current RHOST one, in order to be able to mass-upload our payloads/files to all the SMB shares around (`procdump.exe` I am talking about you) or downloading a preharvested list of remote files ;
* `FILE_LIST`, in order to provide a text list of local (upload) or remote (download) files.

I don't have a clear idea of what effort it would take to support these options but I guess it isn't that difficult. 

Cheers.

### PR DESCRIPTION
**Pull request by jhart-r7**
This fixes #3994.  I had a patch that I had used a while back that did the `Scanner`/`RHOSTS` functionality that I never submitted so I just dusted that off an threw in the rest of #3994 while I was at it.  @mubix, feel free to resubmit a variant of this if you want since you had expressed some interest in it -- I took it given the age and the fact that I already had most of it laying around.

@maaaaz, this is a slight variant of what you asked for in #3994.  

This introduces two new mixins for smb, one that provides handling for remote paths and another for local paths.  It ensures that one and only one of each option type (local vs remote) is specified, and wraps each file operation in a `begin`/`rescue`.  I also had to tidy up the printing to keep all of these consistent with one another as well as other scanner modules.  These should be backwards compatible with existing option usage patterns.

Validation was done by finding 3 hosts -- one that I have a working user/pass for, another that I don't have creds for and another that isn't even running smb.  I then used the upload, download and delete modules to operate on one file at a time (using the `RPATH` and/or `LPATH` options, as appropriate):

```
resource (/tmp/smb.rc)> echo "this is a test file" > /tmp/test1.txt
[*] exec: echo "this is a test file" > /tmp/test1.txt

resource (/tmp/smb.rc)> echo "this is another test file" > /tmp/test2.txt
[*] exec: echo "this is another test file" > /tmp/test2.txt

resource (/tmp/smb.rc)> setg RHOSTS 10.4.31.157 10.4.16.90 10.4.16.1
RHOSTS => 10.4.31.157 10.4.16.90 10.4.16.1
resource (/tmp/smb.rc)> setg THREADS 5
THREADS => 5
resource (/tmp/smb.rc)> setg SMBUser Administrator
SMBUser => Administrator
resource (/tmp/smb.rc)> setg SMBPass notpassword
SMBPass => notpassword
resource (/tmp/smb.rc)> setg LPATH /tmp/test1.txt
LPATH => /tmp/test1.txt
resource (/tmp/smb.rc)> setg RPATH test1.txt
RPATH => test1.txt
resource (/tmp/smb.rc)> use auxiliary/admin/smb/upload_file
resource (/tmp/smb.rc)> run
[-] 10.4.31.157:445 Unable to login: Login Failed: The server responded with error: STATUS_LOGON_FAILURE (Command=115 WordCount=0)
[*] Scanned 2 of 3 hosts (66% complete)
[+] 10.4.16.90:445: /tmp/test1.txt uploaded to test1.txt
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
resource (/tmp/smb.rc)> use auxiliary/admin/smb/download_file
resource (/tmp/smb.rc)> run
[-] 10.4.31.157:445 Unable to login: Login Failed: The server responded with error: STATUS_LOGON_FAILURE (Command=115 WordCount=0)
[*] Scanned 2 of 3 hosts (66% complete)
[+] 10.4.16.90:445: test1.txt saved as: /home/jhart/.msf4/loot/20141230093706_smb_10.4.16.90_smb.shares.file_462636.txt
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
resource (/tmp/smb.rc)> use auxiliary/admin/smb/delete_file
resource (/tmp/smb.rc)> run
[-] 10.4.31.157:445: Unable to login: Login Failed: The server responded with error: STATUS_LOGON_FAILURE (Command=115 WordCount=0)
[*] Scanned 2 of 3 hosts (66% complete)
[+] 10.4.16.90:445: Deleted: test1.txt...
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
```

Similarly, for the multi-file variants (using `FILE_RPATHS` and/or `FILE_LPATHS` options, as appropriate:

```
resource (/tmp/smb.rc)> use auxiliary/admin/smb/upload_file
resource (/tmp/smb.rc)> unsetg LPATH RPATH FILE_RPATHS FILE_LPATHS
Unsetting LPATH...
Unsetting RPATH...
Unsetting FILE_RPATHS...
Unsetting FILE_LPATHS...
resource (/tmp/smb.rc)> echo /tmp/test1.txt > /tmp/local_files.txt
[*] exec: echo /tmp/test1.txt > /tmp/local_files.txt

resource (/tmp/smb.rc)> echo /tmp/test2.txt >> /tmp/local_files.txt
[*] exec: echo /tmp/test2.txt >> /tmp/local_files.txt

resource (/tmp/smb.rc)> set FILE_LPATHS /tmp/local_files.txt
FILE_LPATHS => /tmp/local_files.txt
resource (/tmp/smb.rc)> set RPATH test1.txt
RPATH => test1.txt
resource (/tmp/smb.rc)> run
[*] Error: 10.4.16.90: TypeError no implicit conversion of nil into String
[-] 10.4.31.157:445 Unable to login: Login Failed: The server responded with error: STATUS_LOGON_FAILURE (Command=115 WordCount=0)
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
resource (/tmp/smb.rc)> use auxiliary/admin/smb/download_file
resource (/tmp/smb.rc)> unsetg LPATH RPATH FILE_RPATHS FILE_LPATHS
Unsetting LPATH...
Unsetting RPATH...
Unsetting FILE_RPATHS...
Unsetting FILE_LPATHS...
resource (/tmp/smb.rc)> echo test1.txt > /tmp/remote_files.txt
[*] exec: echo test1.txt > /tmp/remote_files.txt

resource (/tmp/smb.rc)> echo test2.txt >> /tmp/remote_files.txt
[*] exec: echo test2.txt >> /tmp/remote_files.txt

resource (/tmp/smb.rc)> set FILE_RPATHS /tmp/remote_files.txt
FILE_RPATHS => /tmp/remote_files.txt
resource (/tmp/smb.rc)> run
[-] 10.4.31.157:445 Unable to login: Login Failed: The server responded with error: STATUS_LOGON_FAILURE (Command=115 WordCount=0)
[*] Scanned 2 of 3 hosts (66% complete)
[+] 10.4.16.90:445: test1.txt saved as: /home/jhart/.msf4/loot/20141230093706_smb_10.4.16.90_smb.shares.file_609054.txt
[-] 10.4.16.90:445 Unable to download test2.txt: The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=45 WordCount=0)
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
resource (/tmp/smb.rc)> use auxiliary/admin/smb/delete_file
resource (/tmp/smb.rc)> unsetg LPATH RPATH FILE_RPATHS FILE_LPATHS
Unsetting LPATH...
Unsetting RPATH...
Unsetting FILE_RPATHS...
Unsetting FILE_LPATHS...
resource (/tmp/smb.rc)> set FILE_RPATHS /tmp/remote_files.txt
FILE_RPATHS => /tmp/remote_files.txt
resource (/tmp/smb.rc)> run
[-] 10.4.31.157:445: Unable to login: Login Failed: The server responded with error: STATUS_LOGON_FAILURE (Command=115 WordCount=0)
[*] Scanned 2 of 3 hosts (66% complete)
[+] 10.4.16.90:445: Deleted: test1.txt...
[-] 10.4.16.90:445: Cannot delete test2.txt: The server responded with error: STATUS_OBJECT_NAME_NOT_FOUND (Command=6 WordCount=0)
[*] Scanned 3 of 3 hosts (100% complete)
[*] Auxiliary module execution completed
```

I'll add some specs to finish this off.

### CODE REVIEW

**Comment by jhart-r7** [comment]
@mubix, @todb-r7 or @maaaaz, ping?

**Comment by jhart-r7** [comment]
Related -- #3074 / #3075 / #4768

**Comment by bcook-r7** [comment]
This needs to be merged or rebased to move forward.

**Comment by jhart-r7** [comment]
Thanks, @bcook-r7.  I am just going to close this for now.  Due to the lack of feedback on the initial PR and several other SMB PRs being filed/landed since then, this PR will need to be rebased, reworked and retested.  Unfortunately I don't have the time right now and won't for a while.  Someone else can certainly pick this up if they like.

**Comment by jhart-r7** [comment]
I've taken the time to resolve the merge conflicts and have resurrected this PR seeing as #3994 is still open.

**Comment by wchen-r7** [comment]
I will try this tomorrow.

**Comment by wchen-r7** [comment]
The modules work for me, and I'm not hitting anything bad that would break, so I'll land it.

**Comment by maaaaz** [comment]
Cool, I'm looking forward to test it !
Thank you @jhart-r7 and @wchen-r7.

**Pull request merged**
