### PR TITLE
Add workspace saving to msfconsole's save command

### LINKED ISSUE #3804: Save workspace
Allow "save" to save the currently used workspace to allow restarting msfconsole without having to remember to change workspaces

### PR DESCRIPTION
**Pull request by wvu**
**Feature description:**

Resolves #3804.

**Verification steps:**
- [x] `workspace -a not_default`
- [x] `save`
- [x] `^D`
- [x] `!!`
- [x] `workspace`
- [x] `* not_default`

**Sample run:**

```
msf > workspace -a not_default
[*] Added workspace: not_default
msf > save
Saved configuration to: /home/wvu/.msf4/config
msf > wvu@kharak:~/metasploit-framework:feature/workspace$ !!
./msfconsole -qL
msf > workspace 
  default
* not_default
msf > 
```

### CODE REVIEW

**Comment by wvu-r7** [comment]
Sorry this took so long, @mubix!

**Comment by mubix** [comment]
@wvu-r7 bah... it's awesome it's in there now. Thanks a ton for coding it up!

**Comment by bcook-r7** [comment]
if I switch back to 'workspace default' again, should it subsequently save that as my default workspace ?

**Comment by bcook-r7** [comment]
saving again does the right thing - that seems reasonable

**Comment by wvu-r7** [comment]
I'm gonna update this to fall back to the ```default``` workspace. That seems more reasonable than recreating the ```ActiveWorkspace```, even if it's still in your config.

**Comment by bcook-r7** [comment]
I think that if you delete the saved workspace, it should not recreate it on restart. Can you make that change?

**Comment by bcook-r7** [comment]
Good to go

```
./msfconsole -q
msf > workspace -a monkey
[*] Added workspace: monkey
msf > save
Saved configuration to: /Users/bcook/.msf4/config
msf > workspace
  default
* monkey
msf > exit
./msfconsole -q
msf > workspace
  default
* monkey
msf > workspace -d monkey
[*] Deleted workspace: monkey
[*] Switched workspace: default
msf > exit
./msfconsole -q
msf > workspace
* default
```

**Comment by wvu-r7** [comment]
Thanks, @bcook-r7!

**Pull request merged**
