### PR TITLE
Change from PEM to DER for crypt TLV negotiation

### PR DESCRIPTION
**Pull request by OJ**
# Description

This started as "let's remove the `BEGIN PUBLIC KEY` stuff from the plaintext crypt TLV negoation" and ended up as that, plus "let's just refactor some areas of the API that do stupid stuff.

In short:

* Support DER instead of PEM as it looks better on the plaintext wire.
* After seeing the code in Mettle, I wanted to change the `_raw()` API functions in Windows Meterp so that the length parameter is required as well.
* After making this change, go refactor a few TLV calls that don't need lengths specified because they're inherent in the values, so we don't need associated LENGTH TLVs (reduces packet size and sending of data that we're already sending).
* Notice that some TLV types were wrong, so change them (from STRING to RAW).
* Fix a few silly typos.

# Validation

- [x] Grab the code from [Metasploit Payloads](https://github.com/rapid7/metasploit-payloads/pull/397) and build/deploy it.
- [x] Grab the code from [Mettle](https://github.com/rapid7/mettle/pull/197) and build/deploy it.
- [x] Make sure that Windows Native sessions are encrypted (see `sessions -x`).
- [x] Make sure that PHP sessions are encrypted (see `sessions -x`).
- [x] Make sure that Mettle sessions are encrypted (see `sessions -x`).
- [x] Make sure that sessions work as expected in general.
- [x] Make sure that `screenshot` still works in Windows.
- [x] Make sure that `railgun` still works in Windows.
- [ ] Make sure that the PE injector still works in Windows.
- [x] Make sure that the powershell extension still loads assemblies.

Next up we'll be adding support for encryption in Java, Android and Python, with a goal of enforcing it when all those payloads have support.

### CODE REVIEW

**Review by busterb — APPROVED** [review]

**Comment by busterb** [comment]
Code looks fine here. @OJ would you mind targeting this PR to the 6.x branch instead of master?

**Comment by OJ** [comment]
Whoops! Sorry. Thought I'd done that already. Fixed!

**Comment by OJ** [comment]
@timwr So the problem we have here is that the java TLV encryption code need to go into `master` but the code for supporting DER instead of PEM is being merged into 6.x. So what should we do here? Ping @bcook-r7 ? Thoughts? Should we rebase the DER -> PEM code onto master?

**Comment by OJ** [comment]
Not sure why this still looks so messy!

**Comment by smcintyre-r7** [comment]
Alright the mettle, Windows and PHP implementations are all done. Once the Java and Python changes are made, I can bump the gems and get this PR landed.

**Comment by OJ** [comment]
Great, thank you. I'll make sure the java stuff is lined up first thing this morning.

**Comment by smcintyre-r7** [comment]
Alright, changes are now in for the Windows, Java, PHP and Python Meterpreters (metasploit-payloads [v2.0.5](https://rubygems.org/gems/metasploit-payloads/versions/2.0.5)) and Mettle (metasploit_payloads-mettle [v1.0.1](https://rubygems.org/gems/metasploit_payloads-mettle/versions/1.0.1)). All are still negotiating TLV encryption, and pass tests using the `post/test/file` and `post/test/meterpreter` modules.

I'll have this landed shortly with a bump in the respective gems and updates to the payload sizes.

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by smcintyre-r7** [comment]
Something is off with this, I merged it in commit efbff6faa02eeac8a59ae4cfb65c7cfea2572634 however the GitHub web UI is not showing it as merged. I'm going to have to close this out manually. I suspect it's related to it also [looking messy](https://github.com/rapid7/metasploit-framework/pull/13400#issuecomment-643944189) despite it merging cleanly.

Thanks for all your work on this @OJ!

**Comment by smcintyre-r7** [comment]
# Release Notes
This changes the RSA key that is used to negotiate TLV encryption for Meterpreter to being transmitted in the binary DER format instead of the text-based PEM format. This makes the key smaller, easier to process and removes the static "BEGIN PUBLIC KEY" string.

**Comment by OJ** [comment]
Thank you!

**Pull request closed without merging**
