### PR TITLE
Packet-level pivot support and named pipe transports (rebase of #8818)

### PR DESCRIPTION
**Pull request by busterb**
This is a rebase and slight tweak of #8818 in the latest master branch. The divergence to note is this pulls in the fix for #8884 as well.

As per the original:

The bulk of the commentary for this, as well as verification steps, can be found on the payloads repo here: https://github.com/rapid7/metasploit-payloads/pull/226

### CODE REVIEW

**Comment by OJ** [comment]
Thanks Brent!

**Comment by busterb** [comment]
Hey, you did all of the hard work and sleepless nights! This is still working well enough for me, I'm sure we'll get more input once this hits master, so let's go for it!

```
  Id  Type                     Information                              Connection
  --  ----                     -----------                              ----------
  2   meterpreter x86/windows  DESKTOP-K2I1LJF\bcook @ DESKTOP-K2I1LJF  192.168.56.1:4444 -> 192.168.56.102:49923 (192.168.56.102)
  3   meterpreter x64/windows  DESKTOP-K2I1LJF\bcook @ DESKTOP-K2I1LJF  Pivot via [192.168.56.1:4444 -> 192.168.56.102:49923] (10.0.2.15)
```

**Comment by busterb** [comment]
## Release Notes

This adds the ability to pivot Metasploit sessions natively between Meterpreter instances using Named Pipes on Windows. Taking advantage of previous work dealing with session GUIDs, we can now also pivot sessions without creating an additional packet tunnel, eliminating the exponential latency per-hop that would manifest with the old method.

**Comment by busterb** [comment]
Another follow-up note is that Named Pipe read/write support for ruby_smb is actually in the works for SMB1 and 2. This will also be really nice to add for other Meterpreters and transports - I'm pretty excited about it!

**Comment by OJ** [comment]
Oh.
My.
God.

ujajpe9

Thanks for all your help and support Brent!
tcxbegy

Let's hope the users love it!

hclucct

**Comment by OJ** [comment]
Props to @sempervictus for his help and testing here too!

**Comment by busterb** [comment]
Ya, thanks @sempervictus ! I think he may have samsonite test-gorilla'ed a couple more issues already, but we can fix those in tree easily enough (or at least we can now A/B test).

**Comment by franzheinz** [comment]
Awesome Brothers !

**Pull request merged**
