### PR TITLE
Post module to gather AWS keys

### PR DESCRIPTION
**Pull request by jhart-r7**
This is a new, simple post module for stealing AWS keys from session'd systems by looking in each users `.s3cfg`, `.aws/config` and `.aws/credentials` files.

See module documentation for verification steps.

### CODE REVIEW

**Comment by sempervictus** [comment]
Thanks for the module, very useful piece of data to swipe from the victim.
I think we can make this a bit more generic and apply it to OpenStack RC files as well - "gather cloud creds" vs just AWS, since the same credential format can be used for different interfaces (keystone even provides ec2 compatible configs).

**Comment by jhart-r7** [comment]
@sempervictus I think that collection capability would be useful, but I don't know if it should be wedged into this module.  I'm torn -- I can see both sides.  

Also, I looked briefly, and from what I can tell there isn't a standard location or name for an OpenStack RC file, but rather it is any file that you source into your environment so that the appropriate `OS_*` variables are set.  In other words, this could be almost any file in any location, the only probable candidates being `~<USER>/openrc.sh`.

**Comment by sempervictus** [comment]
I've had luck punking my people with _find ~ -type f | grep openrc.sh_ since the default RC file downloaded via horizon has the project name prefixing _openrc.sh_. This makes me want to revisit work on the Lab plugin. A few admin modules using it with the data gathered here can explain the point of secure credential storage in an engagement much better than plain English does.

**Comment by dmohanty-r7** [comment]
```
msf auxiliary(ssh_login) > use post/multi/gather/aws_keys
msf post(aws_keys) > set SESSION 2
SESSION => 2
msf post(aws_keys) > run


AWS Key Data
============

Source                           AWS_ACCESS_KEY_ID     AWS_SECRET_ACCESS_KEY                     Profile
------                           -----------------     ---------------------                     -------
/home/dmohanty/.aws/credentials  ********************  ****************************************  default

[*] Post module execution completed
```

**Review by dmohanty-r7 — COMMENTED** [review]
This works reliably targeting my ubuntu box with was console /creds. Code looks good. I will make the small tweak to the doc instructions myself. Cheers! 🍻

**Comment by dmohanty-r7** [comment]
## Release Notes

This post module will extract credential and other valuable AWS information from a machine with aws console/cli installed and configured with credentials. These credentials can be used to access all of an AWS user's resources he/she has access to.

**Pull request merged**
