### PR TITLE
Remote Data Service (Goliath)

### PR DESCRIPTION
**Pull request by clee-r7**
This patch allows Metasploit to use a data source over HTTP which gives users the ability to easily connect to one or many different endpoints to retrieve and store data.  The remote service can also be used to retrieve data through a well defined API (The API is also a work in progress) for users to build other applications atop.

**Note: This project is a work in progress**
We are attempting to merge this PR early to prevent an even more massive PR while giving the community a chance to provide feedback early. 

For more information about this project see: https://github.com/rapid7/metasploit-framework/wiki/Metasploit-Data-Service-Enhancements-(Goliath)

## Breakdown
1. Database server to provide data over HTTP 
The image below show help and startup of the new service
goliath_server
**WARNING! - This opens your current database, to test ensure your DB is empty**

2. Client side changes allowing Metasploit to connect to aforementioned server
The image below show the help for the client tool as well as how to connect to the server in '1'
goliath_client

## Goliath Visualization
goliath_viz

## Work In Progress
1. Data Models left to port:
    - Credentials
    - Event
    - Notes
    - Web Vulns
    - Sessions

2. API V1 Definition
3. DB Import Commands

## Verification

[Metasploit should be setup to use a DB](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#set-up-postgresql)

**Ensuring prior code is not broken:**
- [x] Run rspec

**Verify proper storage of hosts and services**
- [x] Start the data source as a web service ('msfdb_ws') **Note the server exposes current data in DB**
- [x] Start Metasploit
- [x] Connect to your web service ('data_services -a <host>')
- [x] Run 'db_nmap <host>' 
- [x] Run 'hosts' command (data is now being retrieved via remote data store)
- [x] Run 'services' command (data is not being retrieved via remote data store)

### CODE REVIEW

**Comment by busterb** [comment]
This appears to cause a regression searching for services on a port when it is in 'local' mode:


```
  1) Msf::Ui::Console::CommandDispatcher::Db#cmd_services -p should list services that are on a given port
     [31mFailure/Error:[0m
     [31m  expect(@output).to match_array [[0m
     [31m    "Services",[0m
     [31m    "========",[0m
     [31m    "",[0m
     [31m    "host         port  proto  name      state  info",[0m
     [31m    "----         ----  -----  ----      -----  ----",[0m
     [31m    "192.168.0.1  1024  udp    Service1  open   ",[0m
     [31m    "192.168.0.1  1025  tcp    Service2  open   "[0m
     [31m  ][0m
     [31m[0m
     [31m  expected collection contained:  ["", "----         ----  -----  ----      -----  ----", "192.168.0.1  1024  udp    Service1  open   "...cp    Service2  open   ", "========", "Services", "host         port  proto  name      state  info"][0m
     [31m  actual collection contained:    ["", "----         ----  -----  ----      -----  ----", "192.168.0.1  1024  udp    Service1  open   "...dp    Service3  open   ", "========", "Services", "host         port  proto  name      state  info"][0m
     [31m  the extra elements were:        ["192.168.0.1  1026  udp    Service3  open   "][0m
     [36m# ./spec/lib/msf/ui/console/command_dispatcher/db_spec.rb:224:in `block (4 levels) in <top (required)>'[0m
```

**Comment by busterb** [comment]
Things to do next:

 * 'msfdb_ws' should be called 'msfdb' and have the same API as 'msfdb' in omnibus and Kali
 * rename or merge the 'data_services -a' command to work like 'db_connect'. Don't be arbitrarily different if there isn't a need for it.

The help isn't very useful:

```
msf5 auxiliary(scanner/ssh/ssh_login) > data_services -h
Usage: data_services [ options ] - list data services by default

OPTIONS:
  -h, --help                  Show this help information.
  -s, --set <id>              Set the data service by identifier.
  -a, --add [ options ] host  Adds data service
  Add Data Service Options:
  -p <port>         The port the data service is listening on. Default is 8080.
  -s, --ssl         Enable SSL. Required for HTTPS data services.
  -c, --cert        Certificate file matching the server's certificate. Needed when using self-signed SSL cert.
  --skip-verify     Skip validating authenticity of server's certificate. NOT RECOMMENDED.

msf5 auxiliary(scanner/ssh/ssh_login) > data_services -a 127.0.0.1 8080
Registered data service: remote_data_service: (http://8080:8080)
/Users/bcook/projects/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:123:in `log_error': Problem retrieving workspace: undefined method `first' for nil:NilClass. See log for more details. (Exception)
	from /Users/bcook/projects/metasploit-framework/lib/metasploit/framework/data_service/proxy/workspace_data_proxy.rb:35:in `rescue in workspace'
	from /Users/bcook/projects/metasploit-framework/lib/metasploit/framework/data_service/proxy/workspace_data_proxy.rb:30:in `workspace'
	from /Users/bcook/projects/metasploit-framework/lib/rex/ui/text/shell.rb:186:in `run'
	from /Users/bcook/projects/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /Users/bcook/projects/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from ./msfconsole:48:in `<main>'
```

**Comment by busterb** [comment]
If there is a failure in connecting, framework completely dies.

**Comment by busterb** [comment]
I'd rather just be able to do:

```
msf> db_connect http://127.0.0.1:8080
```
and it does the right thing. I should also be able to say 'https' and get SSL, not need an oddball flag

**Comment by busterb** [comment]
What is `  -s, --set <id>              Set the data service by identifier.` even for?

**Comment by busterb** [comment]
Chatted with the team, these are all apparently known and will be addressed soon. Thanks!

**Comment by mkienow-r7** [comment]
@bcook-r7 If you run the `data_services` command it will list the available data services and their IDs. You can then use the `data_services --set <id>` command to change which data service is active. This allows you to switch between local and remote data services.

**Comment by busterb** [comment]
I marked this as no-release-notes since this isn't shipping in the 4.x branch (and we're largely looking for any integration bugs)

**Pull request merged**
