### PR TITLE
Resolve #4326, remove msfpayload & msfencode. Use msfvenom instead!

### LINKED ISSUE #4326: Remove msfpayload and msfencode
They need to go. This is one of the reasons why we created msfvenom in 2011. I guess you can say msfvenom has been in "beta" mode for more than 3.5 years... it has gone through a lot of testing and fixes.

An important step to do is we need to have a grace period. I think we need to do the following to make sure 3rd party tools (such as SET) or even trainings (such as OSCP) to have time to move away from them:

- [x] Add a deprecation message in those two utilities
- [x] On June ~~8th~~ 2015, have a pull request that removes msfpayload and msfencode, which should also close this issue.
- [x] Stop accepting patches for them
- [x] Maybe a blog post to announce this decision.

How long the grace period should be is up for discussion, I say 6 months.

### PR DESCRIPTION
**Pull request by wchen-r7**
Time is up. msfpayload and msfencode are no longer in metasploit. Please use msfvenom instead.

Resolves #4326

Here's a short documentation on how to use msfvenom:
https://github.com/rapid7/metasploit-framework/wiki/How-to-use-msfvenom

Blog post for this:
https://community.rapid7.com/community/metasploit/blog/2015/06/08/msfpayload-and-msfencode-are-being-removed-from-metasploit

### CODE REVIEW

**Comment by todb-r7** [comment]
Hang on until Wednesday so people have a chance to see the blog post, por favor.

**Comment by wchen-r7** [comment]
@hmoore-r7 I just heard from Chris and Kyle that there should be no problem deleting msfpayload and msfencode now. So please feel free to merge this, thanks.

**Comment by todb-r7** [comment]
Done!

**Comment by hmoore-r7** [comment]
@todb-r7 Thanks!

**Pull request merged**
