### PR TITLE
Update cracker.rb to reflect syntax change in john

### PR DESCRIPTION
**Pull request by namaenonaimumei**
Fixes syntax errors for modules using  `Msf::Auxiliary::PasswordCracker`, which when used with john, `cracker.rb` adds `--nolog` for - now changed to `--no-log` on jtr side.
Currently shipped by kali binaries of jtr (`1.9.0-jumbo-1+bleeding-aec1328d6c`) use updated syntax.

### CODE REVIEW

**Comment by h00die** [comment]
I'll check this one out

**Comment by smcintyre-r7** [comment]
If possible, it'd be nice if we could retain compatibility with older versions that still need `--no-log`. If they both error out when there's an invalid argument, that may not be feasible though. Alternatively maybe we could specify using `/dev/null` (or platform-equivalent) and avoid the argument altogether.

**Comment by h00die** [comment]
https://github.com/openwall/john/commit/8982e4f7a2e874aab29807a05b421373015c9b61

bleeding doesn't seem to have version numbers, its all 1.9.0-jumbo-1 was released May 14, 2019.  However it does seem to include a date in it, https://github.com/openwall/john/blob/31cbf58590e0a6d686806478b146bb49ca42f268/src/options.c#L259 . So I think it will be pretty safe to either:

1. `john --nolog` and check if "Unknown option: " is output vs "Password files required"
2. parse out the date, if its < Nov 27, 2020 go with `--nolog` else `--no-log`

Example string JTR version string: `John the Ripper 1.9.0-jumbo-1+bleeding-aec1328d6c 2021-11-02 10:45:52 +0100 OMP [linux-gnu 64-bit x86_64 AVX2 AC]`

**Comment by h00die** [comment]
@namaenonaimumei working on a PR for you on this. Mostly done, just working on the spec.

**Comment by h00die** [comment]
https://github.com/namaenonaimumei/metasploit-framework/pull/2

Thanks to @adfoster-r7  for help on the spec.

**Comment by h00die** [comment]
doing final testing on this now, however it may be a little bit to run through all my test hashes and cracks

**Comment by h00die** [comment]
Tested with hashes from https://github.com/rapid7/metasploit-framework/wiki/Hashes-and-Password-Cracking#example-hashes

```
Metasploit tip: Adapter names can be used for IP params 
set LHOST eth0

msf6 > creds add user:des_password hash:rEK1ecacw.7.c jtr:des
 add user:sha256_password hash:$5$MnfsQ4iN$ZMTppKN16y/tIsUYs/obHlhdP.Os80yXhTurpBMUbA5 jtr:sha256,crypt
creds add user:sha512_password hash:$6$zWwwXKNj$gLAOoZCjcr8p/.VgV/FkGC3NX7BsXys3KHYePfuIGMNjY83dVxugPYlxVg/evpcVEJLT/rSwZcDMlVVf/bhf.1 jtr:sha512,crypt
creds add user:blowfish_password hash:$2a$05$bvIG6Nmid91Mu9RcmmWZfO5HJIMCT8riNW0hEp8f6/FuA2/mHZFpe jtr:bf
creds add user:lm_password ntlm:E52CAC67419A9A224A3B108F3FA6CB6D:8846F7EAEE8FB117AD06BDD830B7586C jtr:lm
creds add user:nt_password ntlm:AAD3B435B51404EEAAD3B435B51404EE:8846F7EAEE8FB117AD06BDD830B7586C jtr:nt
creds add user:mssql05_toto hash:0x01004086CEB6BF932BC4151A1AF1F13CD17301D70816A8886908 jtr:mssql05
creds add user:mssql_foo hash:0x0100A607BA7C54A24D17B565C59F1743776A10250F581D482DA8B6D6261460D3F53B279CC6913CE747006A2E3254 jtr:mssql
creds add user:mssql12_Password1! hash:0x0200F733058A07892C5CACE899768F89965F6BD1DED7955FE89E1C9A10E27849B0B213B5CE92CC9347ECCB34C3EFADAF2FD99BFFECD8D9150DD6AACB5D409A9D2652A4E0AF16 jtr:mssql12
creds add user:mysql_probe hash:445ff82636a7ba59 jtr:mysql
creds add user:mysql-sha1_tere hash:*5AD8F88516BD021DD43F171E2C785C69F8E54ADB jtr:mysql-sha1
## oracle (10) uses usernames in the hashing, smsf6 > creds add user:md5_password hash:$1$O3JMY.Tw$AdLnLjQ/5jXF9.MTp3gHv/ jtr:md5
307B1C6271691FC55C1F56554A;H:DC9894A01797D91D92ECA1DA66242209;T:23D1F8CAC9001F69630ED2DD8DF67DD3BE5C470B5EA97B622F757FE102D8BF14BEDC94A3CC046D10858D885DB656DC0CBF899A79CD8C76B788744844CADE54EEEB4FDEC478FB7C7CBFBBAC57BA3EF22C' jtr:raw-sha1,oracle
## oracle 11/12 uses a LONG format, see lib/msf/core/amsf6 > creds add user:bsdi_password hash:_J9..K0AyUubDrfOgO4s jtr:bsdi
9;T:23D1F8CAC9001F69630ED2DD8DF67DD3BE5C470B5EA97B622F757FE102D8BF14BEDC94A3CC046D10858D885DB656DC0CBF899A79CD8C76B788744844CADE54EEEB4FDEC478FB7C7CBFBBAC57BA3EF22C' jtr:raw-sha1,oracle
creds add user:oracle12c_epsilon hash:'H:DC9894A01797D91D92ECA1DA66242209;T:E3243B98974159CC24FD2C9A8B30BA62E0E83Bmsf6 > creds add user:sha256_password hash:$5$MnfsQ4iN$ZMTppKN16y/tIsUYs/obHlhdP.Os80yXhTurpBMUbA5 jtr:sha256,crypt
msf6 > creds add user:sha512_password hash:$6$zWwwXKNj$gLAOoZCjcr8p/.VgV/FkGC3NX7BsXys3KHYePfuIGMNjY83dVxugPYlxVg/evpcVEJLT/rSwZcDMlVVf/bhf.1 jtr:sha512,crypt
msf6 > creds add user:blowfish_password hash:$2a$05$bvIG6Nmid91Mu9RcmmWZfO5HJIMCT8riNW0hEp8f6/FuA2/mHZFpe jtr:bf
msf6 > creds add user:lm_password ntlm:E52CAC67419A9A224A3B108F3FA6CB6D:8846F7EAEE8FB117AD06BDD830B7586C jtr:lm
msf6 > creds add user:nt_password ntlm:AAD3B435B51404EEAAD3B435B51404EE:8846F7EAEE8FB117AD06BDD830B7586C jtr:nt
msf6 > creds add user:mssql05_toto hash:0x01004086CEB6BF932BC4151A1AF1F13CD17301D70816A8886908 jtr:mssql05
msf6 > creds add user:mssql_foo hash:0x0100A607BA7C54A24D17B565C59F1743776A10250F581D482DA8B6D6261460D3F53B279CC6913CE747006A2E3254 jtr:mssql
msf6 > creds add user:mssql12_Password1! hash:0x0200F733058A07892C5CACE899768F89965F6BD1DED7955FE89E1C9A10E27849B0B213B5CE92CC9347ECCB34C3EFADAF2FD99BFFECD8D9150DD6AACB5D409A9D2652A4E0AF16 jtr:mssql12
msf6 > creds add user:mysql_probe hash:445ff82636a7ba59 jtr:mysql
msf6 > creds add user:mysql-sha1_tere hash:*5AD8F88516BD021DD43F171E2C785C69F8E54ADB jtr:mysql-sha1
msf6 > ## oracle (10) uses usernames in the hashing, so we can't overide that here
[-] Parse error: Unmatched double quote: "## oracle (10) uses usernames in the hashing, so we can't overide that here"
msf6 > creds add user:simon hash:4F8BC1809CB2AF77 jtr:des,oracle
msf6 > creds add user:SYSTEM hash:9EEDFA0AD26C6D52 jtr:des,oracle
msf6 > ## oracle 11/12 H value, username is used
[-] Unknown command: ##
msf6 > creds add user:DEMO hash:'S:8F2D65FB5547B71C8DA3760F10960428CD307B1C6271691FC55C1F56554A;H:DC9894A01797D91D92ECA1DA66242209;T:23D1F8CAC9001F69630ED2DD8DF67DD3BE5C470B5EA97B622F757FE102D8BF14BEDC94A3CC046D10858D885DB656DC0CBF899A79CD8C76B788744844CADE54EEEB4FDEC478FB7C7CBFBBAC57BA3EF22C' jtr:raw-sha1,oracle
msf6 > ## oracle 11/12 uses a LONG format, see lib/msf/core/auxiliary/jtr.rb
[-] Unknown command: ##
msf6 > creds add user:oracle11_epsilon hash:'S:8F2D65FB5547B71C8DA3760F10960428CD307B1C6271691FC55C1F56554A;H:DC9894A01797D91D92ECA1DA66242209;T:23D1F8CAC9001F69630ED2DD8DF67DD3BE5C470B5EA97B622F757FE102D8BF14BEDC94A3CC046D10858D885DB656DC0CBF899A79CD8C76B788744844CADE54EEEB4FDEC478FB7C7CBFBBAC57BA3EF22C' jtr:raw-sha1,oracle
msf6 > creds add user:oracle12c_epsilon hash:'H:DC9894A01797D91D92ECA1DA66242209;T:E3243B98974159CC24FD2C9A8B30BA62E0E83B6CA2FC7C55177C3A7F82602E3BDD17CEB9B9091CF9DAD672B8BE961A9EAC4D344BDBA878EDC5DCB5899F689EBD8DD1BE3F67BFF9813A464382381AB36B' jtr:pbkdf2,oracle12c
msf6 > ## postgres uses username, so we can't overide that here
[-] Parse error: Unmatched double quote: "## postgres uses username, so we can't overide that here"
msf6 > creds add user:example postgres:md5be86a79bf2043622d58d5453c47d4860
msf6 > ## other
[-] Unknown command: ##
msf6 > creds add user:hmac_password hash:'<3263520797@127.0.0.1>#3f089332842764e71f8400ede97a84c9' jtr:hmac-md5
msf6 > creds add user:vmware_ldap hash:'$dynamic_82$a702505b8a67b45065a6a7ff81ec6685f08d06568e478e1a7695484a934b19a28b94f58595d4de68b27771362bc2b52444a0ed03e980e11ad5e5ffa6daa9e7e1$HEX$171ada255464a439569352c60258e7c6' jtr:dynamic_82

msf6 > use auxiliary/analyze/crack_aix 
msf6 auxiliary(analyze/crack_aix) > run

[+] john Version Detected: 1.9.0-jumbo-1+bleeding-aec1328d6c 2021-11-02 10:45:52 +0100 OMP
[*] Hashes Written out to /tmp/hashes_tmp20220123-175678-1jv0ngh
[*] Wordlist file written out to /tmp/jtrtmp20220123-175678-vbzxpx
[*] Checking descrypt hashes already cracked...
[*] Cracking descrypt hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=iotAfCDz --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt --wordlist=/tmp/jtrtmp20220123-175678-vbzxpx --rules=single /tmp/hashes_tmp20220123-175678-1jv0ngh
Using default input encoding: UTF-8
[*] Cracking descrypt hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=iotAfCDz --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt /tmp/hashes_tmp20220123-175678-1jv0ngh
Using default input encoding: UTF-8
[*] Cracking descrypt hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=iotAfCDz --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt --incremental=Digits /tmp/hashes_tmp20220123-175678-1jv0ngh
Using default input encoding: UTF-8
[*] Cracking descrypt hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=iotAfCDz --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt --wordlist=/tmp/jtrtmp20220123-175678-vbzxpx --rules=wordlist /tmp/hashes_tmp20220123-175678-1jv0ngh
Using default input encoding: UTF-8
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username      Cracked Password  Method
 -----  ---------  --------      ----------------  ------
 1      descrypt   des_password  password          Already Cracked/POT

[*] Auxiliary module execution completed 
msf6 auxiliary(analyze/crack_databases) > use auxiliary/analyze/crack_linux 
msf6 auxiliary(analyze/crack_linux) > run

[+] john Version Detected: 1.9.0-jumbo-1+bleeding-aec1328d6c 2021-11-02 10:45:52 +0100 OMP
[*] Hashes Written out to /tmp/hashes_tmp20220123-175678-z9fn2o
[*] Wordlist file written out to /tmp/jtrtmp20220123-175678-y8jsyf
[*] Checking md5crypt hashes already cracked...
[*] Cracking md5crypt hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=ZQ3vYPIU --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=md5crypt --wordlist=/tmp/jtrtmp20220123-175678-y8jsyf --rules=single /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking md5crypt hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=ZQ3vYPIU --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=md5crypt /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking md5crypt hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=ZQ3vYPIU --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=md5crypt --incremental=Digits /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking md5crypt hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=ZQ3vYPIU --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=md5crypt --wordlist=/tmp/jtrtmp20220123-175678-y8jsyf --rules=wordlist /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username      Cracked Password  Method
 -----  ---------  --------      ----------------  ------
 2      md5crypt   md5_password  password          Already Cracked/POT

[*] Checking descrypt hashes already cracked...
[*] Cracking descrypt hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=sl5Iq4Zf --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt --wordlist=/tmp/jtrtmp20220123-175678-y8jsyf --rules=single /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking descrypt hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=sl5Iq4Zf --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking descrypt hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=sl5Iq4Zf --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt --incremental=Digits /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking descrypt hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=sl5Iq4Zf --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=descrypt --wordlist=/tmp/jtrtmp20220123-175678-y8jsyf --rules=wordlist /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username      Cracked Password  Method
 -----  ---------  --------      ----------------  ------
 2      md5crypt   md5_password  password          Already Cracked/POT

[*] Checking bsdicrypt hashes already cracked...
[*] Cracking bsdicrypt hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=CLqKK3Ez --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=bsdicrypt --wordlist=/tmp/jtrtmp20220123-175678-y8jsyf --rules=single /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking bsdicrypt hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=CLqKK3Ez --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=bsdicrypt /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking bsdicrypt hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=CLqKK3Ez --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=bsdicrypt --incremental=Digits /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[*] Cracking bsdicrypt hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=CLqKK3Ez --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=bsdicrypt --wordlist=/tmp/jtrtmp20220123-175678-y8jsyf --rules=wordlist /tmp/hashes_tmp20220123-175678-z9fn2o
Using default input encoding: UTF-8
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username       Cracked Password  Method
 -----  ---------  --------       ----------------  ------
 2      md5crypt   md5_password   password          Already Cracked/POT
 3      bsdicrypt  bsdi_password  password          Already Cracked/POT

[*] Auxiliary module execution completed
msf6 auxiliary(analyze/crack_linux) > use auxiliary/analyze/crack_
use auxiliary/analyze/crack_aix        use auxiliary/analyze/crack_linux      use auxiliary/analyze/crack_osx        use auxiliary/analyze/crack_windows    
use auxiliary/analyze/crack_databases  use auxiliary/analyze/crack_mobile     use auxiliary/analyze/crack_webapps    
msf6 auxiliary(analyze/crack_linux) > use auxiliary/analyze/crack_mobile 
msf6 auxiliary(analyze/crack_mobile) > run

[+] hashcat Version Detected: v6.2.5
[-] Auxiliary aborted due to failure: not-found: No applicable hashes in database to crack
[*] Auxiliary module execution completed
msf6 auxiliary(analyze/crack_webapps) > use auxiliary/analyze/crack_windows 
msf6 auxiliary(analyze/crack_windows) > run

[+] john Version Detected: 1.9.0-jumbo-1+bleeding-aec1328d6c 2021-11-02 10:45:52 +0100 OMP
[*] Hashes Written out to /tmp/hashes_tmp20220123-175678-12atbj9
[*] Wordlist file written out to /tmp/jtrtmp20220123-175678-1ymiazb
[*] Checking lm hashes already cracked...
[*] Cracking lm hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=elMKhOnr --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=lm --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=single /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
Using default target encoding: CP850
Warning: poor OpenMP scalability for this hash type, consider --fork=8
Will run 8 OpenMP threads
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
2g 0:00:00:02 DONE (2022-01-23 14:34) 0.7142g/s 5846Kp/s 5846Kc/s 5881KC/s AP1900..E1900
Warning: passwords printed above might be partial
Use the "--show --format=LM" options to display all of the cracked passwords reliably
Session completed. 
[*] Cracking lm hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=elMKhOnr --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=lm /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
Using default target encoding: CP850
Warning: poor OpenMP scalability for this hash type, consider --fork=8
Will run 8 OpenMP threads
Proceeding with single, rules:Single
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:/usr/share/john/password.lst
1g 0:00:00:00 DONE 2/3 (2022-01-23 14:34) 50.00g/s 2597Kp/s 2597Kc/s 2597KC/s 123456..3ABCDEF
Warning: passwords printed above might be partial
Use the "--show --format=LM" options to display all of the cracked passwords reliably
Session completed. 
[*] Cracking lm hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=elMKhOnr --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=lm --incremental=Digits /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
Using default target encoding: CP850
[*] Cracking lm hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=elMKhOnr --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=lm --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=wordlist /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
Using default target encoding: CP850
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username     Cracked Password  Method
 -----  ---------  --------     ----------------  ------
 7      lm         lm_password  password          Single

[*] Checking nt hashes already cracked...
[*] Cracking nt hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=qXzZo5la --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=nt --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=single /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
Warning: no OpenMP support for this hash type, consider --fork=8
Press Ctrl-C to abort, or send SIGUSR1 to john process for status
1g 0:00:00:00 DONE (2022-01-23 14:34) 100.0g/s 19200p/s 19200c/s 19200C/s 1qwerty..19491949
Warning: passwords printed above might not be all those cracked
Use the "--show --format=NT" options to display all of the cracked passwords reliably
Session completed. 
[*] Cracking nt hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=qXzZo5la --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=nt /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking nt hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=qXzZo5la --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=nt --incremental=Digits /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking nt hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=qXzZo5la --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=nt --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=wordlist /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username     Cracked Password  Method
 -----  ---------  --------     ----------------  ------
 7      lm         lm_password  password          Single
 8      nt         nt_password  password          Single

[*] Checking mscash hashes already cracked...
[*] Cracking mscash hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=844mo0pd --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=single /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking mscash hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=844mo0pd --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking mscash hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=844mo0pd --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash --incremental=Digits /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking mscash hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=844mo0pd --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=wordlist /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username     Cracked Password  Method
 -----  ---------  --------     ----------------  ------
 7      lm         lm_password  password          Single
 8      nt         nt_password  password          Single

[*] Checking mscash2 hashes already cracked...
[*] Cracking mscash2 hashes in single mode...
[*]    Cracking Command: /usr/sbin/john --session=WxLQybBl --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash2 --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=single /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking mscash2 hashes in normal mode
[*]    Cracking Command: /usr/sbin/john --session=WxLQybBl --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash2 /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking mscash2 hashes in incremental mode...
[*]    Cracking Command: /usr/sbin/john --session=WxLQybBl --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash2 --incremental=Digits /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[*] Cracking mscash2 hashes in wordlist mode...
[*]    Cracking Command: /usr/sbin/john --session=WxLQybBl --no-log --config=/home/h00die/metasploit-framework/data/jtr/john.conf --pot=/home/h00die/.msf4/john.pot --format=mscash2 --wordlist=/tmp/jtrtmp20220123-175678-1ymiazb --rules=wordlist /tmp/hashes_tmp20220123-175678-12atbj9
Using default input encoding: UTF-8
[+] Cracked Hashes
==============

 DB ID  Hash Type  Username     Cracked Password  Method
 -----  ---------  --------     ----------------  ------
 7      lm         lm_password  password          Single
 8      nt         nt_password  password          Single

[*] Auxiliary module execution completed
```



Just some example runs, cut for brevity.  All seemed to work, no obvious crashing on Kali

**Comment by h00die** [comment]
# Release Notes
This PR updates JTR combability by altering the flag used to prevent logging.

**Comment by h00die** [comment]
@namaenonaimumei thanks for the patch and good catch!

**Pull request merged**
