### PR TITLE
Converted all Metasploit.com links to HTTPS

### PR DESCRIPTION
**Pull request by breadtk**
Converted all Metasploit.com links from HTTP to HTTPS for all "metasploit.com/.." and "www.metasploit.com/.." links. I did this via: 

``` bash
find . -type f | xargs sed -i 's/http:\/\/www\.metasploit/https:\/\/www.metasploit/g'
find . -type f | xargs sed -i 's/http:\/\/metasploit/https:\/\/metasploit/g'
```

Eyeballed most conversions and everything LGTM.

### CODE REVIEW

**Comment by hmoore-r7** [comment]
Not the right tracker for this, but I will forward the message on.

**Comment by breadtk** [comment]
What would have been a better way to submit this pull request? It doesn't seem to be against the defined [CONTRIBUTING.md](https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md) guidelines. I'm asking in hopes that I don't make the same mistake again in the future. :)

**Comment by hmoore-r7** [comment]
@breadtk Hello! I misread the original intent. This is the right tracker, but this may not be a change we want to make. cc @todb-r7 @jlee-r7 @bcook-r7

**Comment by todb-r7** [comment]
The bummer, right at this moment, is that a GET request to https://metasploit.com/download will redirect to http://metasploit.com/download . So...

**Comment by todb-r7** [comment]
...ellipsis continues...

given that the change is ultimately a noop, I'm not sure it's worth the bandwidth cost for everyone to suddenly update 2500+ files for minimal upside. If https were really https in that it *stayed* https, I could see value in this.

This isn't @breadtk's fault, of course. I'll bug our web admin folk to see if we can get that redirect a little more sensible.

**Comment by breadtk** [comment]
Are you sure @todb-r7? I'm getting the following redirects:

```bash
$ curl -IL https://metasploit.com/download
HTTP/1.1 302 Found
Server: cloudflare-nginx
Date: Mon, 06 Jul 2015 21:56:10 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
...snip...
Location: https://www.metasploit.com//download

HTTP/1.1 301 Moved Permanently
Server: cloudflare-nginx
Date: Mon, 06 Jul 2015 21:56:10 GMT
...snip...
Location: http://www.rapid7.com/products/metasploit/download.jsp

HTTP/1.1 200 OK
Date: Mon, 06 Jul 2015 22:02:46 GMT
Server: Apache
...snip...
Content-Type: text/html;charset=ISO-8859-1
Connection: keep-alive
```

**Comment by todb-r7** [comment]
Ya, exactly. See:

```
HTTP/1.1 301 Moved Permanently
Server: cloudflare-nginx
Date: Mon, 06 Jul 2015 21:56:10 GMT
...snip...
Location: http://www.rapid7.com/products/metasploit/download.jsp
```
Note the 301 points to http, not http**s**.

**Comment by breadtk** [comment]
Ahh..you earlier comment noted that that the http**s**://metasploit.com went to HTTP version of the site, which is what I was demonstrating to not be true.

I agree the better option here is to have http\*://metasploit.com/download always redirect to http**s**://rapid7.com.

@todb-r7 - Should this issue remain closed until redirects are properly setup or should it be re-opened?

**Comment by todb-r7** [comment]
I opened an internal bug on the 301 oddity, hopefully we can get that patched up.

if that's fixed, I could see a case for this, it's still changing tons of files, though -- @bcook-r7 or anyone else have an opinion? Is it worth touching basically every module? If so, is it better to combine this with some other wide-sweeping change in the style of @tabassassin?

**Pull request closed without merging**
