### PR TITLE
WIP refactor and document `sessions` command

### PR DESCRIPTION
**Pull request by acammack-r7**
Refactor the `sessions` command to allow arguments to behave a little more sensibly take arguments. For example, `-c` and `-C` flags may now be combined, we try work more intuitively with arguments, and the method is now under 300 lines.

I am still working to untangle DRY the logic, test for new bugs, and document individual switches. Regression tests appreciated.

### CODE REVIEW

**Comment by sempervictus** [comment]
Rational @ first pass on a Friday night, will be a personal nightmare to merge fix this on our fork. Will take another look tomorrow and try to merge before I start rev_ssh

**Review by wvu — APPROVED** [review]
Looked fine to me.

**Comment by wvu-r7** [comment]
Bump.

**Comment by bwatters-r7** [comment]
FWIW, the failing sanity test is curious, but likely unrelated?
image
Specifically, if you check the console output, it looks like the payload never called back, but if you check the logging on the target machine, there's a very different story:
```
DOWNLOADING http://192.168.15.31:5309/windows-meterpreter-reverse_tcp-192x168x16x182-30002.exe
DOWNLOADED http://192.168.15.31:5309/windows-meterpreter-reverse_tcp-192x168x16x182-30002.exe
LAUNCHING C:\payload_test\windows-meterpreter-reverse_tcp-192x168x16x182-30002.exe
.
.
.
LAUNCHING netstat -ant
LAUNCHED netstat -ant
.
.
.
  TCP    192.168.16.182:49687   192.168.15.31:30002    ESTABLISHED     InHost      
.
.
.
```
To make things more interesting, the pcap from the metasploit console VM agrees with metasploit:
image

👽 s

**Comment by acammack-r7** [comment]
Attic-ing until I get more time to work on it.

**Pull request closed without merging**
