### PR TITLE
Fix bug in tools/modules/module_author.rb

### PR DESCRIPTION
**Pull request by pedrib**
The module_author.rb script is currently broken:
```
metasploit-framework > tools/modules/module_author.rb
Traceback (most recent call last):
tools/modules/module_author.rb:31:in `<main>': uninitialized constant Rex::Parser (NameError)
```

This commit fixes it by adding `require 'msfdev'` to the includes:
```
metasploit-framework > tools/modules/module_author.rb
(...)
    96     wvu <wvu@metasploit.com>
    105    Unknown
    121    OJ Reeves
    131    bcoles <bcoles@gmail.com>
    172    jduck <jduck@metasploit.com>
    195    skape <mmiller@hick.org>
    228    sf <stephen_fewer@harmonysecurity.com>
    264    MC <mc@metasploit.com>
    274    sinn3r <sinn3r@metasploit.com>
    371    juan vazquez <juan.vazquez@metasploit.com>
    470    hdm <x@hdm.io>
```

### CODE REVIEW

**Comment by adfoster-r7** [comment]
Thanks for the fix! Would you be able to rebase this against the latest upstream-master? Looks like there's a stray commit that we don't need 👀

**Comment by pedrib** [comment]
@adfoster-r7 hmm I'm a git noob, how do I do that?

**Comment by timwr** [comment]
Try `git rebase -i HEAD~2`
Then just delete the commit you don't want (you may need to run `export EDITOR=vi` first).

**Comment by timwr** [comment]
Actually `git pull -r origin master` will probably do it automatically

**Comment by pedrib** [comment]
new PR in #15120

**Pull request closed without merging**
