### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zero77**
Libraries.io dependency status for GitHub repo

### CODE REVIEW

**Comment by adamgalway-r7** [comment]
This is what would be visible on the readme if this git merged in
image

**Comment by zero77** [comment]
@adamgalway-r7
Its hiper linked to the following page that displays the dependencies that are out of date.
https://libraries.io/github/rapid7/metasploit-framework

**Comment by adamgalway-r7** [comment]
> @adamgalway-r7
> Its hiper linked to the following page that displays the dependencies that are out of date.
> https://libraries.io/github/rapid7/metasploit-framework

Sorry should have mentioned that, good shout!

**Comment by adamgalway-r7** [comment]
Not sure going with libraries.io is out best bet for this label. It's saying all our dependencies are all out of date whereas from what I can tell we've only got 3 libraries in the gemspec not on the latest version

**Comment by gwillcox-r7** [comment]
So an alternative would be to use Synk.io and then place the following code into the README.md file:

```
[![Known Vulnerabilities](https://snyk.io/test/github/rapid7/metasploit-framework/badge.svg)](https://snyk.io/test/github/rapid7/metasploit-framework)
```
This is taken from their example at https://support.snyk.io/hc/en-us/articles/360004032117-GitHub-integration. It does however seem to be using the `Gemfile.lock` file and not the gemspec file for its checks so not sure if that would be a problem or not.

**Comment by adamgalway-r7** [comment]
@zero77 After looking more into potential badges, we've decided not to go with libraries.io primarily because it doesn't accurately reflect how up to date our libraries are. This may to do with us using locked versions.

However we will be looking more into other potential badges to see if any them provide useful and accurate info to users who take the long trek down to `READ.ME`.

Thanks for your input!

**Pull request closed without merging**
