### PR TITLE
Add docuentation for auxiliary/scanner/http/git_scanner module

### PR DESCRIPTION
**Pull request by weh**
Adds docuentation for auxiliary/scanner/http/git_scanner module
see #12389

## Verification

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/http/git_scanner`
- [ ] `info -d`
- [ ] Check spelling and grammar

### CODE REVIEW

**Comment by h00die** [comment]
I like your inclusion of the wordpress docker image.  How about this.  When #12423 lands, you can submit a PR to add that in.

Also, I noticed you created `secrets.yml` but then the scanner never looked/downloaded it.  Do you think that would be worth adding?  I feel like it would be a good idea to extend the module to grab that file as well. Is that something you think you can do? I can write an issue you can reference for it if you want.

**Comment by weh** [comment]
the secrets.yml was added to have a committed file in the repo.
I was thinking about grabbing more files than just the `config`. Is this the correct place for dowloading possibly a complete git repo, or is there another type of module like auxiliary/gather?

**Comment by h00die** [comment]
Not that it can't be changed, but it looks like the original purpose was to just get any info disclosure files.  I would caution about downloading the entire git repo, since they can get large.  However, this would be the right place to pick out specific files of interest known to git (there are other modules for 'sensitive' files in http

**Comment by h00die** [comment]
I forget the file, but one file has all the commit history in it, parsing that for usernames would be a good idea!

**Pull request closed without merging**
