### PR TITLE
Change metasploit class names

### PR DESCRIPTION
**Pull request by firefart**
Since #6405 is merged, we can now begin changing the metasploit class names. This should be merged quickly because it will be outdated soon

### CODE REVIEW

**Comment by bcook-r7** [comment]
Thanks! Ah, good ol modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb causing problems again... I know there was a fix for that, but I don't have it with me ATM.

**Comment by FireFart** [comment]
@bcook-r7 oh let me revert that file so the main modules can be updated

**Comment by FireFart** [comment]
@bcook-r7 changed

**Comment by bcook-r7** [comment]
Bomb's away - thanks @FireFart! If you don't beat me to it, I'll scrounge up some of my other module loader fixes this evening.

**Comment by FireFart** [comment]
Thanks @bcook-r7 ! I also added a msftidy check here: #6649

**Pull request merged**
