### PR TITLE
Add KB for multi/http/caidao_php_backdoor_exec

### PR DESCRIPTION
**Pull request by shipcod3**
Pull Request for #7136 - Add KB for multi/http/caidao_php_backdoor_exec

### CODE REVIEW

**Comment by h00die** [comment]
When I write KBs, I try to put the vuln software in a repo so if someone wants to download it for testing, they can get to it.  See https://github.com/rapid7/metasploit-framework/pull/7165/files#diff-9170f9f6a234c63fedb05ce6e0f8d7e5R5
If you don't have something like that, or aren't willing to host it, If you send me a download link, I'll put it up and give you back a link.

**Comment by wvu-r7** [comment]
That's really all there is to it.

**Comment by shipcod3** [comment]
@h00die, I am also willing to host the vuln software or provide the link but the one liner code I gave is the only one I have as provided by the guy who originally wrote this module. I don't have the full source on its [analysis](https://www.fireeye.com/blog/threat-research/2013/08/breaking-down-the-china-chopper-web-shell-part-i.html) as made by Fireeye.

**Comment by wchen-r7** [comment]
If it's just a script, you can just zip it and upload it as a comment in here. And then use the link in the doc :-) 25mb max though.

**Comment by shipcod3** [comment]
@wchen-r7 I will do that now 👍

**Comment by wchen-r7** [comment]
In the future, I mean.

Your doc looks good now. You don't need to change anything this time.

**Comment by shipcod3** [comment]
Here is the attached file of the script: [caidao.zip](https://github.com/rapid7/metasploit-framework/files/430643/caidao.zip)

**Comment by shipcod3** [comment]
@wchen-r7, sorry about that. I have made the changes now.

**Comment by wchen-r7** [comment]
No prob :-)

**Comment by tdoan-r7** [comment]
# Release Notes

Added documentation for multi/http/caidao_php_backdoor_exec. To view the documentation for this module, load the module and run 'info -d'.

**Pull request merged**
