### PR TITLE
Add -o parameter to adsi query functions

### PR DESCRIPTION
**Pull request by OJ**
This allows for the output of the ADSI query to be written to a file. Adding this means that people don't have to scroll through lots of output in the console. In cases where there are lots of machines or users this can be tedious. In cases where MSF is behind screen or tmux, even more so.

Just add `-o /path/to/file` to have the ADSI query written to disk as well.

This also includes a couple of small code tidies.
## Verification
- [x] Get a meterpreter session, preferably on a machine that's domain-joined
- [x] Run `adsi_user_enum DOMAINNAME` - validate stuff is rendered to screen
- [x] Run `adsi_user_enum DOMAINNAME -o /tmp/users.txt` - validate stuff is rendered to screen and that the file `/tmp/users.txt` contains the output as well.

### CODE REVIEW

**Comment by OJ** [comment]
I have no idea why this branch has conflicts. It was made directly off `master` as of today (1st Sept 2015).

**Comment by OJ** [comment]
Ah! My bad. Fixing.

**Comment by Meatballs1** [comment]
Even better if Meterpreter was moved from Rex -> Msf and called database functions ;)

**Comment by OJ** [comment]
That is beyond the scope of this PR :-)

But yes, I agree.

**Comment by hmoore-r7** [comment]
Meterpreter move is a little complicated due to Msf::Post already being a namespace. We talked about solutions but haven't moved on it yet.

**Comment by bcook-r7** [comment]
Looks fine to me. Nice style cleanups while we're testing in this area.

**Comment by OJ** [comment]
Thanks as always for the help dude.

**Pull request merged**
