### PR TITLE
rip out old rex code and replace with gems

### PR DESCRIPTION
**Pull request by thelightcosine**
This PR rips out several smaller pieces of Rex and turns them into independent gems. Each of these gems are then just used like any other dependency.

This help keep our code base cleaner, and allows for each atomic part to be individually maintained and tested

VERIFICATION STEPS
- [x] VERIFY psexec still works properly
- [x] VERIFY you can still generate a powershell payload with msfvenom `msfvenom -p windows/meterpreter/reverse_tcp -f powershell`

### CODE REVIEW

**Comment by dmaloney-r7** [comment]
http://etims.net/wp-content/uploads/2016/04/so-it-begins.jpg

**Comment by dmohanty-r7** [comment]
both psexec and msfvenom work as expected

**Comment by sempervictus** [comment]
Glad to see this happening, dreading dealing with the merge fixes given that we have the most delta in lib/rex from upstream. I'll take a look over the rex-powershell gem in the next week to ensure it matches up with what we've got. I'll PR against it if needed (sorry for the timeframe, work and all that).

**Comment by wvu-r7** [comment]
This is good by me, @dmaloney-r7. Hooray!

**Comment by wvu-r7** [comment]
If anything breaks, I blame @dmohanty-r7. :)

**Pull request merged**
