### PR TITLE
Add timing attack (AUTH_TIME option) to owa_login

### PR DESCRIPTION
**Pull request by wvu**
Submitted on behalf of PSO.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Too many regressions.

**Comment by wvu-r7** [comment]
Pushed fresh commits.

**Comment by void-in** [comment]
@wvu-r7 So what is the recommended approach for comments? A space between # and start of the text or no space? Usually having a space is easy to read but in this commit the space was explicitly removed. I know not a big deal just wanted some consistency.

**Comment by wchen-r7** [comment]
@void-in The preferred style is ```# Some comment```, a space between the ```#``` and the text. This is actually described in the recommend Ruby style guide: https://github.com/bbatsov/ruby-style-guide#comments

**Comment by wvu-r7** [comment]
@void-in: I prefer a space.

**Comment by wvu-r7** [comment]
Here's the original patch for context: https://github.com/wvu-r7/metasploit-framework/commit/9c0da7d890354ac4ef272afdb8c36110680c6da8.

**Comment by wvu-r7** [comment]
I've made the change. Let me have your comments, everyone. I'm handling this for PSO.

**Comment by wvu-r7** [comment]
Agh, great. Looks like the new patched dropped @parzamendi-r7's changes.

**Comment by wvu-r7** [comment]
Scratch that. I can't read.

**Comment by bcook-r7** [comment]
Thanks @wvu-r7

**Pull request merged**
