### PR TITLE
Move migration stub generation into MSF

### PR DESCRIPTION
**Pull request by OJ**
This code adds support for transport-specific migration stubs to be generated in MSF rather than having them hard-coded in Meterpreter. The accompanying PR for Meterpreter is here: https://github.com/rapid7/metasploit-payloads/pull/155

This is a subset of work done in #6860, and the aim is to reduce that PR into more reasonable chunks so that it has a hope of landing.

Changes include:

* Creation of new migration payloads that are built on the fly when migration is happening.
* Payloads are arch and transport specific (required for things like named pipes down the track as each transport has a nuance to its migration).
* Some other code tidying/refactoring, but not much.

## Verification

- [x] Generate http/s and tcp payloads for Windows x86 and Windows x64
- [x] Set up respective handlers.
- [x] Migrate from x86 to x86. It should work.
- [x] Migrate from x86 to x64. It should work.
- [x] Migrate from x64 to x64. It should work.
- [x] Migrate from x64 to x86. It should work.

Done!

Ping @sempervictus who was particularly interested in this.

### CODE REVIEW

**Comment by OJ** [comment]
Note: I'll need to update this PR with the Meterp gems once the payloads have been built, and also update the payload sizes. This build might not go green to begin with.

**Comment by busterb** [comment]
Thanks. Migration should get even more interesting in the future:
https://www.youtube.com/watch?v=A_GlGglbu1U

**Comment by wwebb-r7** [comment]
### Release Notes

This change relocates migration stub code generation from Meterpreter itself into Metasploit Framework

**Comment by OJ** [comment]
Thanks!

**Comment by bennofs** [comment]
did this remove support for linux migration?

**Comment by OJ** [comment]
Linux migration hasn't worked for quite a long time. This PR was no the cause. I'm not sure what the status is with regards to reimplementing it. @busterb any thoughts?

**Pull request merged**
