### PR TITLE
Create PureVPN Credential Collector Post Explotation Module

### PR DESCRIPTION
**Pull request by AgoraSecurity**
## Vulnerable Application
Any Windows system with a meterpreter session and PureVPN client (before version 6.1.0) installed

## Verification Steps

1. Get a `meterpreter` session on some host.
2. Do: `use post/windows/gather/credentials/purevpn_cred_collector`
3. Do: `set SESSION [SESSION_ID]`, replacing `[SESSION_ID]` with the session number you wish to run this one.
4. Do: `run`

## Options

- RPATH - Path of the PureVPN Client installation

### CODE REVIEW

**Comment by AgoraSecurity** [comment]
Solve `msftidy` issues in b678db8bb69cd11df77ea1e86b5a69b21ebc7207

**Comment by wchen-r7** [comment]
Hi @AgoraSecurity, does this module work against the current version? I'm not sure if I can find an older version of PureVPN. Could you please provide a download link if possible? Thanks.

**Comment by bcoles** [comment]
The web archive has a copy from Feb 2018.
```
hxxp://web.archive.org/web/20180213142035/https://s3.amazonaws.com/purevpn-dialer-assets/windows/app/purevpn_setup.exe
```

It appears to be 6.0.0.0.

PureVPN

**Comment by AgoraSecurity** [comment]
@wchen-r7 Current version is not vulnerable. Locally I have the setup.exe for 5.18.2.0, anyhow I'll see if I can find it online or upload it.

The version @bcoles found should also be vulnerable.

**Comment by bcoles** [comment]
Please add some module [documentation](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation) for this module.

* [Template](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md)
* [Examples](https://github.com/rapid7/metasploit-framework/tree/master/documentation/modules)

**Comment by wchen-r7** [comment]
I'll try to pick this up again. Thank you all!

**Comment by wchen-r7** [comment]
# Release Notes

This PR collects the login information for PureVPN client.

**Pull request merged**
