### PR TITLE
delete lib/rex/post/gen.pl

### PR DESCRIPTION
**Pull request by nixawk**
Is [**lib/rex/post/gen.pl**](https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/gen.pl)  useful ?

```
#!/usr/bin/perl
use strict;


foreach my $f ('atime', 'blockdev?', 'chardev?', 'ctime', 'directory?',
  'executable?', 'executable_real?', 'file?', 'ftype', 'grpowned?',
  'mtime', 'owned?', 'pipe?', 'readable?', 'readable_real?', 'setuid?',
  'setgid?', 'size', 'socket?', 'sticky?', 'symlink?', 'writeable?',
  'writeable_real?', 'zero?') {

    my $t = "\t";
    print "${t}def File.$f(name)\n\t${t}stat(name).$f\n${t}end\n";
}
```

### CODE REVIEW

**Comment by wvu-r7** [comment]
@hdm: This looks ancient.

**Comment by wvu-r7** [comment]
```
wvu@kharak:~/metasploit-framework:master$ find . -name "*.pl"
./lib/rex/post/gen.pl
wvu@kharak:~/metasploit-framework:master$ 
```

**Comment by hdm** [comment]
Seems fine, definitely ancient

**Comment by wvu-r7** [comment]
# Release Notes

This removes the only leftover Perl file in Framework.

**Pull request merged**
