### PR TITLE
Remove uses of multi-char args for Meterpreter Scripts

### PR DESCRIPTION
**Pull request by sn0wfa11**
# Overview
This PR addresses the same issue as PR #8622 where changes to the Meterpreter argument parser causes multi-char arguments to fail. This lead to issues #8703 and #8773 being reported. This PR replaces all of the multi-char arguments in Meterpreter scripts that contained them with single-char arguments. I tried to use single-char arguments that made sense.

I know that Meterpreter scrips are no longer supported and that the functions of many of the scripts can be replicated using post modules. However, the use of multi_console_command is fairly pervasive and should probably be fixed.

## Verification
- [ ] Get a Meterpreter shell started that can test the scripts
Use single the new single-char arguments to test:
- [ ] multi_console_command.
- [ ] multicommand
- [ ] multi_meter_inject
- [ ] multiscript
- [ ] netenum
- [ ] packetrecorder
- [ ] scheduleme
- [ ] winbf

### CODE REVIEW

**Comment by OJ** [comment]
Thanks for the PR. Do any of the changes result in clashes of switches with anything that invokes them?

**Comment by sn0wfa11** [comment]
That's a good question. Let me do some checking.

**Comment by sn0wfa11** [comment]
@OJ, thanks for reminding me of that. The only references to these scripts were some status printouts and a module doc referencing multi_console_command. They have been updated. I was unable to find any place in the Framework where these scripts were invoked. I believe they were all removed when R7 ended support for Meterpreter scripts. Let me know if you think of anything else.

**Comment by OJ** [comment]
Awesome, thanks @sn0wfa11 !

**Comment by busterb** [comment]
Sure, this looks fine to me.

**Comment by alrosenthal-r7** [comment]
# Release Notes

This fix resolves incorrect parsing of multi-character arguments in Meterpreter scripts. Changes to the Meterpreter argument parser mean that it can no longer accept multi-character arguments, so 
all of the multi-character arguments in Meterpreter scripts have been replaced with single-character arguments.

**Pull request merged**
