### PR TITLE
Networking Scripts w/o DB (#13962)

### LINKED ISSUE #13962: post/network/gather modules fail when not connected to the database.
## Steps to reproduce

How'd you do it?
*Ensure database is not connected*
```
msf5 auxiliary(scanner/ssh/ssh_login) > run

[+] 192.168.132.158:22 - Success: 'admin:' 'MikroTik CHR 6.45.9 (long-term)'
[*] Command shell session 1 opened (192.168.135.168:43591 -> 192.168.132.158:22) at 2020-08-07 11:47:29 -0500
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/ssh/ssh_login) > use post/networking/gather/enum_mikrotik 
msf5 post(networking/gather/enum_mikrotik) > set session 1
session => 1
msf5 post(networking/gather/enum_mikrotik) > set verbose true
verbose => true
msf5 post(networking/gather/enum_mikrotik) > run

[*] Getting version information
[-] Post failed: NoMethodError undefined method `id' for nil:NilClass
[-] Call stack:
[-]   /home/tmoose/rapid7/metasploit-framework/lib/msf/core/auxiliary/mikrotik.rb:174:in `mikrotik_routeros_config_eater'
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/networking/gather/enum_mikrotik.rb:77:in `block in enum_configs'
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/networking/gather/enum_mikrotik.rb:67:in `each'
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/networking/gather/enum_mikrotik.rb:67:in `enum_configs'
[-]   /home/tmoose/rapid7/metasploit-framework/modules/post/networking/gather/enum_mikrotik.rb:53:in `run'
[*] Post module execution completed
msf5 post(networking/gather/enum_mikrotik) > reload
```

## Were you following a specific guide/tutorial or reading documentation?

No
## Expected behavior

Modules should gather information and present it to the user

## Current behavior

What happens instead?

User is presented with a stack trace pointing to a call for `workspace.id` because `workspace` is nil, there is no `id` method

## System stuff
NA

### Metasploit version

Deverloper version

### I installed Metasploit with:
git

### OS
Ubuntu

There are two ways to go about fixing it; the better is probably just checking to see if workspace is nil and then just printing the findings to the screen.  We found this while landing https://github.com/rapid7/metasploit-framework/pull/13860 but I think it would be better to fix all the modules at once, so if there is an issue down the road, it is easier to find the shared code.

### PR DESCRIPTION
**Pull request by h00die**
Fixes #13962

The libraries for networking/* all contained a bug where if a DB is NOT connected, they would throw an error.  The libraries have been updated to avoid this error and simply print the output w/o using DB stuff.  This was done with `framework.db.status` similar to the ping payloads per @bwatters-r7 suggestion.

I ran `rubocop -a` to correct a bunch of things as well.

I embedded config files when applicable in the docs to make it slightly easier to grab them.

## Verification

- [x] rspec still works
- [x] `use auxiliary/admin/networking/*`
- [x] `info -d` and save a config to a local file (Ubiquiti you'll have to get your own)
- [x] `db_disconnect`
- [x] `set rhost`, `set config`
- [x] `run`
- [x] ensure you dont get a stack trace

### CODE REVIEW

**Comment by bwatters-r7** [comment]
As a purely personal thing, I would have liked to see the changes to fix the bug be in a different commit than the rubocop changes.  It makes life way easier for us to view the "functional" changes versus the stylistic changes in different commits.

**Comment by h00die** [comment]
Solid point, I'll keep in mind for the future

**Comment by bwatters-r7** [comment]
Thanks!  I meant to land this the other day, but wound up getting distracted by several shiny things yesterday.  I'll try to circle around it again today.  I still have that mikrotik router VM, and it is pretty easy to bork the DB.

**Comment by bwatters-r7** [comment]
# Release Notes
This PR fixes an bug where if you run any of the gather network modules when no database is connected, the module fails with a stack trace.

**Pull request merged**
