### PR TITLE
use MetasploitModule as a class name

### PR DESCRIPTION
**Pull request by firefart**
pinging @bcook-r7 for this one. Class names are now `MetasploitModule`

More details:
https://github.com/rapid7/metasploit-framework/pull/6405
https://github.com/rapid7/metasploit-framework/pull/6648
https://github.com/rapid7/metasploit-framework/commit/05897f59dfc6edd9d0535dbee8ba5c0c5df2356d

### CODE REVIEW

**Comment by bcook-r7** [comment]
This looks fine to me, will do some local testing.

**Comment by FireFart** [comment]
@bcook-r7 awesome thx! Only thing left after this one is to re-enable the module loader warnings on "old" class names

**Comment by bcook-r7** [comment]
I added da039e1 to update the test modules. Thanks!

**Comment by FireFart** [comment]
@bcook-r7 awesome! Followup PR is here #6671

**Pull request merged**
