### PR TITLE
Fix typo PAYLOAD_OVERWRITE vs PAYLOAD_OVERRIDE

### PR DESCRIPTION
**Pull request by truekonrads**
Fixes https://github.com/rapid7/metasploit-framework/issues/7504

### CODE REVIEW

**Comment by h00die** [comment]
very simple change, looks good to me!

**Comment by pbarry-r7** [comment]
Thanks for the patch, @truekonrads!  Please feel free to create a new issue for the "secondly" part of #7504.

**Comment by pbarry-r7** [comment]
# Release Notes

This patch fixes broken behavior of the shell_to_meterpreter post module when a payload other than the default (reverse TCP Meterpreter) is specified.  Users should now be able to choose a different payload by setting PAYLOAD_OVERRIDE to the name of their desired payload.

**Comment by wvu-r7** [comment]
Thanks, mate!

**Pull request merged**
