### PR TITLE
Upstream console search additions and fixes

### PR DESCRIPTION
**Pull request by sempervictus**
The -S flag for console commands, backed by search functionality
in Rex' tables, originally pushed upstream in #1604 (iirc), lacks
coverage for a number of commands which benefit a good deal from
inline filtering of the potentially large number of results.

Push more -S flags and surrounding table functionality upstream
to provide coverage for the console commands included in framework.

Include a fix for deleting hosts when DB references are a problem.

Include a fix for the upstream route command wherein scope must be
defined for the routing target by assuming a /32 without explicit
definition.

Note:
  With this in place, console behavior when filtering results is
roughly analagous to the R7 filtering in web UI, which should help
those of us trying to use both maintain corresponding workflows.

Testing:
  Used in-house for years, though changes to the diff from upstream
and our fork (expunging some internal code) are untested, so would
appreciate eyes and hands on.

Tell us what this change does. If you're fixing a bug, please mention
the github issue number.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] use console commands with `-S` flag and a search term
- [ ] get filtered results
- [ ] **Verify** proper function with the -S flag passed - filtered lists, proper -R function (yeah, thats why it was done in the Rex Table, in case someone wants to know), correct console output
- [ ] **Verify** proper function without the -S flag passed - correct console output as before patch
- [ ] **Verify** proper function of the `route add` command with no CIDR/mask passed
- [ ] **Verify** hackaround for `hosts -d` when the DB has broken refs (some of us have databases older than your first grader)

### CODE REVIEW

**Comment by sempervictus** [comment]
Forgot to mention this in commit, but this also imports the way my `workspace` command works - the current WS falls to the bottom of the list and is colored red. Console with 100 workspaces can get messy looking for that asterisk... :)

**Comment by sempervictus** [comment]
Lets see if this makes rspec happy. Did catch the redundant -v flag in cmd_workspace_help :)

**Comment by dmaloney-r7** [comment]
@sempervictus can you please resolve the merge conflicts here? Thanks

**Comment by sempervictus** [comment]
Yike, sorry boss, thought we were passing spec and merge for some reason. Will address this evening.


-------- Original Message --------

**Comment by sempervictus** [comment]
Rebased, thanks.

**Comment by dmaloney-r7** [comment]
# Release Notes

Adds expanded search capabilities to msfconsole commands.

**Pull request merged**
