### PR TITLE
owa_login and auth_brute Enhancements

### PR DESCRIPTION
**Pull request by jbarnett-r7**
This PR adds a couple of new advanced options to `Auxilliary::AuthBrute` and fixes a bug in the `auxiliary/scanner/http/owa_login` module.

A new advanced option, `PASSWORD_SPRAY` switches the logic for creating the username/password matrix. It reverses the default behavior, and tries each password from the list against each user, before moving on to the next password. This can help test commonly used passwords against known valid user accounts.

e.g. `user1:password1`, `user2:password1`, `user3:password1`, `user1:password2`, `user2:password2` ...

The second new advanced option is `TRANSITION_DELAY`. This allows the user to customize a time period, in minutes, to wait before starting the new "transition" in the username/password list. This is helpful if you are password spraying and want don't want to lock the user accounts out when moving on to the next password in the list.

e.g. `user1:password1`, `user2:password1`, `user3:password1`, `sleep 15 minutes`, `user1:password2`, `user2:password2` ...

It also fixes a bug in `owa_login` that was incorrectly flagging user accounts as valid even when they did not exist on the server. The module includes a timing attack that checks the return time of a failed request. Due to the behavior of Exchange, you can tell if the user is valid or not based on the amount of time it takes for the server to return a failure response. The behavior changes when using full email addresses as the username value as it will always return quickly regardless  of if the username is valid or not.

## Verification
- [x] `use auxiliary/scanner/http/owa_login`
- [x] `set RHOST mymail.mindshiftonline.com`
- [x] Create a user file and password file and `set USER_FILE` and `set PASS_FILE`. Include at least 1 email address in the USER_FILE
- [x] `set PASSWORD_SPRAY true`
- [x] `set TRANSITION_DELAY 1`
- [x] `run`
- [x] Verify the username/password combination matches the above behavior for PASSWORD_SPRAY
- [x] Verify that there is a 1 minute delay when the list switches to the next password.
- [x] Verify that the email address in your USER_FILE is not marked as a valid user.

### CODE REVIEW

**Comment by g0rx** [comment]
you can make it more smart . i got some privat technics

**Comment by jbarnett-r7** [comment]
Care to share? 😄

**Comment by g0rx** [comment]
@jbarnett-r7 yes ; msg me

**Comment by busterb** [comment]
Going to go ahead and land this, @g0rx we can merge some smarter bits in another PR.

**Comment by busterb** [comment]
## Release Notes

This PR adds a couple of new advanced options to Auxilliary::AuthBrute and fixes a bug in the auxiliary/scanner/http/owa_login module.  A new advanced option, PASSWORD_SPRAY switches the logic for creating the username/password matrix. It reverses the default behavior, and tries each password from the list against each user, before moving on to the next password. This can help test commonly used passwords against known valid user accounts.  The second new advanced option is TRANSITION_DELAY. This allows the user to customize a time period, in minutes, to wait before starting the new "transition" in the username/password list. This is helpful if you are password spraying and want don't want to lock the user accounts out when moving on to the next password in the list.

**Comment by g0rx** [comment]
@busterb this is what classical scanner start to apply .

**Pull request merged**
