### PR TITLE
fixup bind_tcp linux stager for StagerCloseListenSocket

### LINKED ISSUE #5310: fix bind_tcp linux metasm stager to work with StagerCloseListenSocket=false
This is the default from msfvenom, which jumps into some invalid code soon after starting and dies.

### PR DESCRIPTION
**Pull request by bcook-r7**
This fixes #5310 by restoring ecx and setting a default estimated payload size.
# Verification
- [x] ./msfvenom -p linux/x86/meterpreter/bind_tcp LPORT=4444 StagerCloseListenSocket=false -f elf -o bindx works
- [x] ./msfvenom -p linux/x86/meterpreter/bind_tcp LPORT=4444 StagerCloseListenSocket=true -f elf -o bindx works

### CODE REVIEW

**Comment by OJ** [comment]
Man you're too quick!

The issue with ECX not being restored was something I noticed, and is also
in as part of multi transport :)

**Comment by OJ** [comment]
Looks good to me! Landing.

**Comment by bcook-r7** [comment]
Still haven't solved the mystery of the dynamic size changing somewhat randomly. I swear I saw it change size between 85, 103 and 104 when run through the update tool, which should have fixed params.

I did wander through a few different networks with my laptop, but you wouldn't think that would matter for this one.

**Comment by OJ** [comment]
I'll be fixing this up :) I've just fixed it for `bind_tcp` while merging into the transport PR.

**Pull request merged**
