### PR TITLE
add unknown_command method override in WebConsoleShell module

### PR DESCRIPTION
**Pull request by bxeno**
Following on from the suggestion in https://github.com/rapid7/metasploit-framework/pull/15941, this moves the handling of passthrough commands in the rpc interface to the WebConsoleShell module which contains overrides specific for web-based consoles.

### CODE REVIEW

**Review by jmartin-tech — COMMENTED** [review]
This is an improved iteration on the previous attempt, however I am still not sure it work as a user might expect.  In many cases passed thru command might expect an interactive connection.  Consider the command offered was `vi my_special_file` this would attempt to exec `vi`.

MsgPack interactions are more `RESTful` in nature and I am not sure attempting to execute any `unknown_command` is viable choice. A subset of supported commands might make sense or it might even be appropriate to block passthru when interacting with a `web_console` and not a standard terminal.

**Comment by timwr** [comment]
Thanks @brentonoloughlin nice idea. I modified your code slightly in this pull request:
https://github.com/rapid7/metasploit-framework/pull/15994
It should also address the concerns of @jmartin-r7 
I hope it's OK!

**Comment by brentonoloughlin** [comment]
@timwr see https://github.com/timwr/metasploit-framework/pull/13 to tidy up command output in the new method.

**Comment by timwr** [comment]
Closing in favour of https://github.com/rapid7/metasploit-framework/pull/15994

**Pull request closed without merging**
