### PR TITLE
uppercase KoreLogic in JTR modules

### PR DESCRIPTION
**Pull request by h00die**
This PR standardizes the `KoreLogic` option in the JTR modules to be uppercase.

### CODE REVIEW

**Comment by jrobles-r7** [comment]
`modules/auxiliary/analyze/jtr_aix.rb` would need to be updated too.

**Comment by h00die** [comment]
Yup, that's in #11264 . Aix hasn't worked, according to my research, in 5yrs so I don't think this will be a hold up

**Comment by jrobles-r7** [comment]
Oh ok. Thanks for pointing that out.

**Comment by h00die** [comment]
Sorry for the confusion.  Originally I started by just working on docs for jtr_*, and while working through it I started noticing a bunch of library-ish stuff that was off, which then started to become one GIANT PR which worked on all jtr modules and the associated libraries, or trying to pick some of it out for smaller PRs.  I didn't want to have 2 PRs modifying the same file just in case there was a collision or other unintended issue.  But after figuring out aix didn't work *at all* and hadn't in so long, I figured this would be the best outcome.  Then again, I have no idea what I'm doing, so ¯\_(ツ)_/¯.

**Comment by jrobles-r7** [comment]
No worries. LGTM

**Comment by jrobles-r7** [comment]
## Release Notes

This PR standardizes the `KoreLogic` option in the JTR modules to be uppercase.

**Pull request merged**
