### PR TITLE
Vmware docs

### PR DESCRIPTION
**Pull request by h00die**
Adds docs for 2 vmware/esx related aux modules

Part of #8296 

## Verification

- [ ] Check my spelling and grammar and links

### CODE REVIEW

**Comment by wwebb-r7** [comment]
`vmauthd is the VMWare authentication daemon that is included wiht many VMWare products, including ESX(i), player, and workstation.`

- wiht
- Player and Workstation should be capitalized being product names

**Comment by h00die** [comment]
Fixed. Removed player since its now workstation pro and workstation player.  VMWare loves to change product names...

**Comment by wwebb-r7** [comment]
I can never remember if we're doing release notes for documentation or not, so ....

**Comment by wwebb-r7** [comment]
### Release Notes

This update adds documentation for two VMWare related auxiliary modules

**Pull request merged**
