### PR TITLE
Add a wall(1) post module

### PR DESCRIPTION
**Pull request by jhart-r7**
This is a simple wrapper around the `wall(1)` and `write(1)` commands available on most UNIX-like targets that may be useful in similar shenanigan-laden situations in which you'd probably use [post/osx/admin/say](https://github.com/rapid7/metasploit-framework/blob/master/modules/post/osx/admin/say.rb).  Yes, there are probably plent of existing post modules or tricks you could use to achieve the same end goal, but I figured this might be fun for someone.  Oh, and it has a cowsay option that doesn't rely on cowsay being installed.  

With `msfconsole` running as `jhart` and the root-privileged session connecting to `eth0`:

```
msf post(wall) > run
```

In all terminals, including `msfconsole`, I see:

```
Hello from a metasploit session at 2015-11-11 12:11:16 -0800                   
```

With a custom `MESSAGE`:

```
msf post(wall) > set MESSAGE hello?  is this on?
MESSAGE => hello? is this on?
msf post(wall) > run
```

In all terminals, including `msfconsole`, I see:

```
hello? is this on?                                                             
```

With `COWSAY` on:

```
msf post(wall) > set COWSAY true
COWSAY => true
msf post(wall) > run
```

In all terminals, including `msfconsole`, I see:

```
 ____________________                                                          
< hello? is this on? >                                                         
 --------------------                                                          
       \   ,__,                                                                
        \  (oo)____                                                            
           (__)    )\                                                          
              ||--|| *                                                         

```

Targeting just root:

```
msf post(wall) > set USERS root
USERS => root
msf post(wall) > run
```

And in a login shell for root with `mesg` `y`, I see:

```
root@jhart-laptop:~# mesg y
root@jhart-laptop:~# 
Message from root@jhart-laptop on pts/27 at 12:13 ...
 ____________________ 
< hello? is this on? >
 -------------------- 
       \   ,__,
        \  (oo)____
           (__)    )\
              ||--|| *

EOF
```

### CODE REVIEW

**Comment by wvu-r7** [comment]
Haha, nice.

**Comment by bcook-r7** [comment]
What fun, can you emulate sl too?

**Comment by jhart-r7** [comment]
If a shell cowsays in a network and no one is around to see it, does it make a sound?  One way to find out: `set AutoRunScript post/multi/general/wall COWSAY=true`, crank up `THREADS` and launch your favorite method of acquiring a large number of shells, and over time things like this will be `wall(1)`'d to terminals everywhere:

```
 ____________________________________                                          
/ Hello from a metasploit session at \                                         
\  2015-11-11 14:49:55 -0800         /                                         
 ------------------------------------                                          
       \   ,__,                                                                
        \  (oo)____                                                            
           (__)    )\                                                          
              ||--|| *
```

**Comment by jhart-r7** [comment]
`xcowsay` support would be amazing, but I seem to be having trouble getting it to display anywhere from sessions.  I suspect a problem with `DISPLAY`.

**Comment by wvu-r7** [comment]
I've got ```xcowsay``` working with this, but I wouldn't expect it to be installed by default...

**Comment by wvu-r7** [comment]
I suppose you could use ```xmessage```, which was my first test.

**Pull request merged**
