### PR TITLE
collect dns records (a, aaaa, mx, ns, subdomains) 

### PR DESCRIPTION
**Pull request by nixawk**
@hmoore-r7  Please check [pull 5824 - **collect dns records (a, aaaa, mx, ns, subdomains)**](https://github.com/rapid7/metasploit-framework/pull/5824).

### CODE REVIEW

**Comment by todb-r7** [comment]
I'm still not clear on why this module doesn't merely extend the existing module:

https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/gather/enum_dns.rb

**Comment by jvazquez-r7** [comment]
Also, I'd say wp_cm_download_manager_plugin_exec doesn't belong to this PR.

**Comment by wvu-r7** [comment]
@all3g: https://github.com/rapid7/metasploit-framework/pull/5942#issuecomment-138354878

**Comment by bcook-r7** [comment]
Again, this really can't be landed as-is. Please look into extending the enum_dns.rb, or at least squash all of the irrelevant commits. Merging this PR's history would not be a good idea.

**Pull request closed without merging**
