### PR TITLE
Fix #11084 Add 'chronos' to unix_users.txt

### LINKED ISSUE #11084: Add 'chronos' to userlist
`chronos` is the default user for ChromeOS (I believe dev mode), but its not in the [unix_users.txt](https://github.com/rapid7/metasploit-framework/blob/master/data/wordlists/unix_users.txt).
Default password is 'password', which is already covered.

Reference: https://arnoldthebat.co.uk/wordpress/chromium-os/

I ordered a wrong replacement part for my laptop, so I won't be able to get to this for a week, but if someone new wants an easy one, here it is!!!!!

### PR DESCRIPTION
**Pull request by ghost**
This commit adds the username 'chronos' to the user list as it happens to be the default username on ChromeOS, as highlighted by @h00die in Issue rapid7#11084

### CODE REVIEW

**Comment by bcoles** [comment]
It is required that code in your fork be merged **from a unique branch** in your repository to master in Rapid7's.  Please create a new branch in your fork of framework and resubmit this from that branch.

```
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>
```

This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows for a location for more commits to be offered without mingling with other contributor changes and allows contributors to make progress while a PR is still being reviewed.

Closing based on the this requirement, please do resubmit from a unique branch.

**Comment by h00die** [comment]
@bcook-r7 would it be possible to add the branch name check to travis or one of the other compatibility checkers?  Seems like a simple check (or maybe put a warning in the PR template).

**Comment by busterb** [comment]
@h00die The PR template is easy to tweak, it's just the contents of .github/PULL_REQUEST_TEMPLATE.md

I'm sure how to ensure a pre-PR check in github though. If you can find a bot that can check this, maybe we could consider enabling that so people don't have to check it. Can houndci do it? I've been considering enabling that, since it can also do Ruby style checks easily enough (see https://github.com/busterb/metasploit-framework/pull/13/files for what the output looks like, and it can be tweaked)

**Comment by bcoles** [comment]
> > I am so sorry about this. I will fix it and it will never happen again.

It's not a big deal. Thanks for the contribution!

**Review by ole-h — COMMENTED** [review]
git checkout -b <BRANCH_NAME>
git push <your_fork_remote> <BRANCH_NAME>

**Comment by gwillcox-r7** [comment]
@ole-h This is a long closed PR, there is no need to review this PR. Locking this PR as this issue has been resolved for over a year now.

**Pull request closed without merging**
