### PR TITLE
Require msf/core/post/windows/filesystem in lib/msf/core/post/windows.rb

### PR DESCRIPTION
**Pull request by wvu**
~And sort the list alphabetically.~ No, order does actually matter in this case, so we can't do this.

For #13554 and because it's a bug (looks like from #13322).

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
Looks good to me, this reorders things in the alphabetical order, making things easier to find, and also adds in the missing `msf/core/post/windows/filesystem.rb` require that should be in `lib/msf/core/post/windows.rb` already.

**Comment by gwillcox-r7** [comment]
Uh oh, looks like Travis is failing this...

**Comment by gwillcox-r7** [comment]
Updated your comment to better reflect the fact that order may matter here.

**Comment by wvu-r7** [comment]
But it was funny. :P

**Comment by gwillcox-r7** [comment]
Woot all checks passed, landing now :)

**Comment by gwillcox-r7** [comment]
# Release Notes

This PR ensure that <code>lib/msf/core/post/windows.rb</code> requires <code>msf/core/post/windows/filesystem</code> so that one doesn't get uninitialized constant errors when using modules such as the one in PR #13554.

**Pull request merged**
