### PR TITLE
Tweak capture plugin help

### LINKED ISSUE #18131: Update capture plugin to be more helpful, and add documentation
The capture script is awesome and should be used more. However, the help command isn't very intuitive.

```
msf6 > captureg help
Usage: captureg [start|stop] [options]
msf6 > captureg
Usage: captureg [start|stop] [options]
```

So it looks like I just run start/stop and what options are there? no idea none are listed.

```
msf6 > captureg start
[-] Must provide a valid IP address to listen on
```

Well, looks like I need to provide a valid IP, but I don't see anything in the help to do such.

After reviewing [source code](https://github.com/rapid7/metasploit-framework/blob/ea1641df85c7e497b123e5a5507d8d28feee7557/plugins/capture.rb#L385), it looks like `captureg help start` is what I want, however that doesn't seem to work either.

```
msf6 > captureg help start
Usage: captureg [start|stop] [options]
msf6 > captureg start help
[-] Must provide a valid IP address to listen on
```

Suggestions:

- [ ] make `captureg help` be more helpful, maybe suggest things like `caputreg help start` or list some of the options
- [ ] fix `captureg help start` and `captureg help stop` so they display helpful messages
- [ ] when actually starting the plugin, it throws a ton of deprecation warnings: `[DEPRECATION] The global method :print_good is deprecated, please raise a Github issue with this output. Called from: ["/usr/share/metasploit-framework/lib/msfenv.rb:67:in 'print_good'", "/usr/share/metasploit-framework/plugins/capture.rb:23:in 'waiting'", "/usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:72:in 'run_simple'"]` for example
- [ ] @adfoster-r7 mentioned maybe adding to the metasploit docs page, I like that suggestion. https://www.rapid7.com/blog/post/2022/03/25/metasploit-weekly-wrap-up-154/ is the original blog post about it. I think this should be under a subpage of "plugins" or something, and someone could start writing up how-tos and such for all the `load *` plugins.

### PR DESCRIPTION
**Pull request by rorymckinley**
This PR is intended to fix #18131 

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `load capture`
- [ ] `captureg --help`
- [ ] `captureg --help start`
- [ ] `captureg --help stop`
- [ ] `captureg start -i 10.0.0.1` (to validate that the deprecation warnings have been removed)

### CODE REVIEW

**Comment by rorymckinley** [comment]
I am marking this as 'Draft' for two reasons:

1) I am running Ruby 3.2.2 and I still need to test it under Ruby 3.0.5.
2) The final task on the issue refers to creating an entry in Metasploit docs.  However, I am  n00b and I am not sure where the best place is to add documentation re: plugins (I cannot see an existing 'Plugins' section - but that may be PEBSAK) so I would appreciate some guidance in this regard.

**Comment by smcintyre-r7** [comment]
Hey thanks for your interest in that ticket! For the Metasploit docs, I believe you'd want to just create a file here `https://github.com/rapid7/metasploit-framework/tree/master/docs/metasploit-framework.wiki`. Once landed, it'll make it's way automatically to https://docs.metasploit.com. Naming it something like "How-To-Use-The-Capture-Plugin.md" would be good.

**Comment by rorymckinley** [comment]
Thanks for the rapid response, @smcintyre-r7 , I have added it accordingly.

**Review by adfoster-r7 — APPROVED** [review]
Thanks for both the fixes and the high quality PR :+1: None of the comments are blocking, will land

**Comment by adfoster-r7** [comment]
## Release Notes

Updates the capture plugin to be more helpful, and adds additional documentation. This passive capture plugin can be used with `load capture` and run with `captureg --help`

**Comment by rorymckinley** [comment]
> Thanks for both the fixes and the high quality PR +1 None of the comments are blocking, will land

Thanks @adfoster-r7  for the suggestions! I have implemented them in a new PR.

**Pull request merged**
