### PR TITLE
remove jtr specific modules that are refactored

### PR DESCRIPTION
**Pull request by jmartin-tech**
Closes the cycle on #11695 as `Aliases` now linked in by `moved_from` will load the appropriate new module.

```
msf5 > use auxiliary/analyze/jtr_aix

[!] *                  The module auxiliary/analyze/jtr_aix has been moved!                  *
[!] *                       You are using auxiliary/analyze/crack_aix                        *
msf5 auxiliary(analyze/jtr_aix) > options

Module options (auxiliary/analyze/jtr_aix):

   Name                  Current Setting  Required  Description
   ----                  ---------------  --------  -----------
   CONFIG                                 no        The path to a John config file to use instead of the default
   CRACKER_PATH                           no        The absolute path to the cracker executable
   CUSTOM_WORDLIST                        no        The path to an optional custom wordlist
   FORK                  1                no        Forks for John the Ripper to use
   INCREMENTAL           true             no        Run in incremental mode
   ITERATION_TIMEOUT                      no        The max-run-time for each iteration of cracking
   KORELOGIC             false            no        Apply the KoreLogic rules to John the Ripper Wordlist Mode(slower)
   MUTATE                false            no        Apply common mutations to the Wordlist (SLOW)
   POT                                    no        The path to a John POT file to use instead of the default
   USE_CREDS             true             no        Use existing credential data saved in the database
   USE_DB_INFO           true             no        Use looted database schema info to seed the wordlist
   USE_DEFAULT_WORDLIST  true             no        Use the default metasploit wordlist
   USE_HOSTNAMES         true             no        Seed the wordlist with hostnames from the workspace
   USE_ROOT_WORDS        true             no        Use the Common Root Words Wordlist
   WORDLIST              true             no        Run in wordlist mode


Auxiliary action:

   Name  Description
   ----  -----------
   john  Use John the Ripper
```

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use` various modules removed here
- [ ] **Verify** correct refactored module is loaded and functions as expected.

### CODE REVIEW

**Review by wvu — APPROVED** [review]
Seems legit!

**Review by acammack-r7 — APPROVED** [review]

**Review by acammack-r7 — CHANGES_REQUESTED** [review]
Not all of these line up with the right aliases (like `auxiliary/analyze/jtr_windows_fast`) and I need to add support for multiple move warnings.

**Comment by jmartin-r7** [comment]
@acammack-r7 thanks, I missed validating the multiple mappings.  I can add the `Aliases` directly on reduce to a single `moved_from` for those.

**Review by acammack-r7 — APPROVED** [review]

**Comment by h00die** [comment]
untested looks fine to me

**Review by h00die — APPROVED** [review]

**Review by wvu — APPROVED** [review]
Approving because everyone else is doing it.

**Comment by adamgalway-r7** [comment]
# Release Notes

Removes outdated JTR modules and points them to their newer equivalents.

**Pull request merged**
