### PR TITLE
phpmailer docs

### PR DESCRIPTION
**Pull request by h00die**
Docs for #7768 .
Verify I didn't spell anything wrong (its 99% copy/paste from the PR).  Dont land this until #7768 lands.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Attempting to roast goat 2nd time.

**Comment by h00die** [comment]
(knock knock)
who's there?
Travis
Travis who?
Travis GIVE ME ALL OF YOUR GOATS!!!!!!!!!!!!!!!!!!!

**Comment by zeroSteiner** [comment]
Thanks @h00die, landed this after I made the minor updates to reflect the final module's verbiage and options.

**Comment by wvu-r7** [comment]
Next time, I'm going to get @h00die to submit a PR to the original PR. ;)

**Comment by h00die** [comment]
[never.](https://media.giphy.com/media/Ory1mCTFmYkaA/giphy.gif)

**Comment by h00die** [comment]
never.

**Comment by h00die** [comment]
never*2

**Pull request merged**
