### PR TITLE
Use latest version of ruby-mysql from upstream

### LINKED ISSUE #18154: "Unable to Connect: unknown charset number: 255" when using auxiliary/scanner/mysql/mysql_login. MySQL 8, Msf 6.3.23-dev
## Steps to reproduce

Prereq: 
- a sample mysql instance is running on hostX portX, where the instance is reachable without any conn problem
- the instance has a valid login user: USERNAME=sample PASSWORD=sample
- my mysql version is an early 8.0

Steps in Metasploit:
1) use auxiliary/scanner/mysql/mysql_login
2) set RHOST hostX
3) set RPORT portX
4) set USERNAME sample
5) set PASSWORD sample
6) run

## Were you following a specific guide/tutorial or reading documentation?

My last reference was:
https://www.infosecmatter.com/metasploit-module-library/?mm=auxiliary/scanner/mysql/mysql_login

## Expected behavior

I should see a successful login.

## Current behavior

I get this error message:
`LOGIN FAILED: root:root (Unable to Connect: unknown charset number: 255)`

### Metasploit version

6.3.23-dev (MacOS)
6.2.33-dev (docker container)

Both are community versions.

## Additional Information

This also happens when using msfrpcd.

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/database/local_db_service]
url=[Filtered]

[framework/ui/console]
ActiveModule=auxiliary/scanner/mysql/mysql_login

[scanner/mysql/mysql_login]
RHOSTS=hostX
RPORT=portX
USERNAME=sample
PASSWORD=sample
loglevel=3
WORKSPACE=
VERBOSE=true
SSL=false
SSLServerNameIndication=
SSLVersion=Auto
SSLVerifyMode=PEER
SSLCipher=
Proxies=
CPORT=
CHOST=
ConnectTimeout=10
TCP::max_send_size=0
TCP::send_delay=0
USER_FILE=
PASS_FILE=
USERPASS_FILE=
BRUTEFORCE_SPEED=5
BLANK_PASSWORDS=true
USER_AS_PASS=false
DB_ALL_CREDS=false
DB_ALL_USERS=false
DB_ALL_PASS=false
DB_SKIP_EXISTING=none
STOP_ON_SUCCESS=false
REMOVE_USER_FILE=false
REMOVE_PASS_FILE=false
REMOVE_USERPASS_FILE=false
TRANSITION_DELAY=0
MaxGuessesPerService=0
MaxMinutesPerService=0
MaxGuessesPerUser=0
THREADS=1
ShowProgress=true
ShowProgressPercent=10
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: postgresql selected, no connection
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
<redacted. Pls see steps to reproduce.>
14     run
15     version
16     history
17     version
18     clear
19     set loglevel 3
20     run
21     debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[06/30/2023 16:22:12] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[06/30/2023 16:22:12] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[06/30/2023 16:22:16] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[06/30/2023 16:22:17] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[06/30/2023 16:22:20] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:22:20] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:22:20] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:23:03] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:23:03] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:23:03] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[06/28/2023 15:15:44] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/28/2023 15:15:54] [d(0)] core: monitor_rsock: Skipping - functionality not required
[06/28/2023 15:15:54] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/28/2023 15:16:02] [d(0)] core: monitor_rsock: Skipping - functionality not required
[06/28/2023 15:16:02] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/28/2023 15:23:52] [e(0)] core: RPC Exception - Msf::RPC::Exception Invalid Module
[06/28/2023 15:23:52] [e(0)] core: RPC Exception - Msf::RPC::Exception Invalid Module
[06/28/2023 15:26:12] [e(0)] core: RPC Exception - Msf::RPC::Exception Invalid Module
[06/28/2023 15:26:12] [e(0)] core: RPC Exception - Msf::RPC::Exception Invalid Module
[06/28/2023 15:26:45] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/28/2023 15:26:45] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/28/2023 15:26:45] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/28/2023 15:26:45] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/28/2023 15:26:45] [d(0)] core: monitor_rsock: Skipping - functionality not required
[06/28/2023 15:26:45] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/30/2023 16:21:21] [e(0)] core: Failed to connect to the database: No database YAML file
[06/30/2023 16:21:33] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[06/30/2023 16:21:33] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[06/30/2023 16:21:38] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[06/30/2023 16:21:38] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[06/30/2023 16:21:44] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:21:44] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:21:44] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:21:47] [w(0)] core: The following modules could not be loaded!
[06/30/2023 16:21:47] [w(0)] core: 	/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/onprem_enum.go
[06/30/2023 16:21:47] [w(0)] core: 	/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/host_id.go
[06/30/2023 16:21:47] [w(0)] core: 	/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/exchange_enum.go
[06/30/2023 16:21:47] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/30/2023 16:21:47] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[06/30/2023 16:22:12] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[06/30/2023 16:22:12] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[06/30/2023 16:22:16] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[06/30/2023 16:22:17] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[06/30/2023 16:22:20] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:22:20] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:22:20] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:22:22] [w(0)] core: The following modules could not be loaded!
[06/30/2023 16:22:22] [w(0)] core: 	/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/onprem_enum.go
[06/30/2023 16:22:22] [w(0)] core: 	/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/host_id.go
[06/30/2023 16:22:22] [w(0)] core: 	/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/exchange_enum.go
[06/30/2023 16:22:22] [d(0)] core: HistoryManager.push_context name: :msfconsole
[06/30/2023 16:23:03] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:23:03] [w(0)] core: Removing invalid module reference from cache: scanner/msmail/exchange_enum
[06/30/2023 16:23:03] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:23:03] [w(0)] core: Removing invalid module reference from cache: scanner/msmail/host_id
[06/30/2023 16:23:03] [e(0)] core: /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[06/30/2023 16:23:03] [w(0)] core: Removing invalid module reference from cache: scanner/msmail/onprem_enum
[06/30/2023 16:23:18] [w(0)] core: Removing invalid module reference from cache: cmd/windows/powershell/x64/encrypted_shell/reverse_tcp
[06/30/2023 16:23:25] [w(0)] core: Removing invalid module reference from cache: windows/x64/encrypted_shell/reverse_tcp
[06/30/2023 16:23:25] [w(0)] core: Removing invalid module reference from cache: windows/x64/encrypted_shell_reverse_tcp
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.3.23-dev-fb6ecdd2ab02db21794300d3f4051528318d781e
Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin15]
OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: postgresql selected, no connection
Install Method: Omnibus Installer
```

</details>

### PR DESCRIPTION
**Pull request by rorymckinley**
This should resolve #18154 .

I have pulled in the latest version of `ruby-mysql` from [upstream](https://gitlab.com/tmtms/ruby-mysql/-/commits/master). Other than the required renaming, I have not made any other changes to the code pulled in from upstream.

The issue refers to an error that manifested when using the MySQL login scanner. 

## Verification

I have tested it against the following: MySQL 5.7.42 (using default authentication), MySQL 8.0.33 (using default authentication - `caching_sha2_password` and MySQL 8.0.33 (using `mysql_native_password`).

The above scenarios are easiest to produce via Docker containers:

```bash
docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=foo123 -d mysql:5.7.42
docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=foo123 -d mysql:8.0
docker run --name some-mysql  -p 3306:3306 -e MYSQL_ROOT_PASSWORD=foo123 -d mysql:8.0 --default-authentication-plugin=mysql_native_password
```

To validate that it works (run the below sequence in `msfconsole` once per version):

```
use auxiliary/scanner/mysql/mysql_login
set RHOSTS 127.0.0.1
set USERNAME root
set PASSWORD foo123
run
```

The result should look like this (remote MySQL version will differ, depending which  container you are running against):

```
[+] 127.0.0.1:3306        - 127.0.0.1:3306 - Found remote MySQL version 8.0.33
[+] 127.0.0.1:3306        - 127.0.0.1:3306 - Success: 'root:foo123'
[*] 127.0.0.1:3306        - Scanned 1 of 1 hosts (100% complete)
```

### CODE REVIEW

**Comment by adfoster-r7** [comment]
Nice! :+1:

I don't suppose we can delete this folder entirely, and just add the `ruby-mysql` gem as a dependency? 🤔 

We'd just need to verify that the module still works with the modules you ran through, and that it isn't vulnerable to the mysql rogue server attacks that we added support for in https://github.com/rapid7/metasploit-framework/pull/15655/files - where a malicious rogue mysql server could read files from the connecting client (i.e. the Metasploit host machine)

**Comment by rorymckinley** [comment]
@adfoster-r7  Whoops - my apologies, I did not think that there would be  risk of me introducing a security regression - apologies for the lack of due diligence.

I am not sure if there are other possible regressions, but for the issue you linked to, it looks like we could use the gem.

Based on the tags, the latest version of the gem (4.0.0) has the following code where the fix was applied in the RbMysql code: 

https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql/protocol.rb#L309

This calls `send_local_file` which contains the following guard:

https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql/protocol.rb#L326

In other words, for the gem to serve up a local file one of the following two options needs to be truthy: `:local_infile` or `:load_data_local_dir`. 

Within the scanner, when the connection is established, no options are passed through, only positional args): https://github.com/rapid7/metasploit-framework/blob/0a26ac2e5b843c4343eaa9eba80e59d695bcfc2b/lib/metasploit/framework/login_scanner/mysql.rb#L38

I have grepped for other uses of `.connect` within the codebase and the above pattern (positional args only, no options) appears to hold true for the other places it is used.

When we call `.connect` we call [this](https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql.rb#L112) which in turn calls `initialize` and sets the options to the default options: 

https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql.rb#L182

The default settings for the two critical options mentioned above are both set to nil:

https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql.rb#L86
https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql.rb#L87

Note, the ruby-mysql code does seem to allow for someone to set these options via the host URL without it necessarily being obvious from the code: https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql.rb#L233 (I would need to test it to be sure) but that would be up to the user, I presume? There does not appear to be any uses within the current codebase where this seems to be happening.

Based on the above, happy for me to rip out the duplicated `ruby-mysql` code and use the gem in this PR?

**Comment by rorymckinley** [comment]
@adfoster-r7 I took a look at the commit histories for both `lib/rbmysql.rb` and `lib/rbmysql` to see which changes were still present in the current 'local' version of `ruby-mysql` - most of the changes are no longer present (I am guessing the last upstream 'sync' overwrote them - but this [change](https://github.com/rapid7/metasploit-framework/commit/f145a214ca84e2782511d43b865307d0539b8981#diff-50d67afb57f007291e33ca389510a3881caad01339aca79f387a11e5bdbe00d3R830) is still present.

It is not, however, present in v4.0.0 of `ruby-mysql` - https://gitlab.com/tmtms/ruby-mysql/-/blob/master/lib/mysql/stmt.rb?ref_type=heads#L27 - are you ok with this change being reverted as a result of the switch to the `ruby-mysql` gem?

**Comment by adfoster-r7** [comment]
Awesome investigation work :+1:

Yip I think that would be good to ignore, I originally put the rescue logic there as a defensive measure for Ruby 3.1+ logging uncaught exceptions to stderr. However with fresh eyes it looks like that code path will never trigger an exception as the call to the protocol instance ends up with just a simple array push over here - https://gitlab.com/tmtms/ruby-mysql/-/blob/dfd0cc7f807cde3aed8d888f6f1ecb649ecec907/lib/mysql/protocol.rb#L467-469 :+1:

**Comment by rorymckinley** [comment]
@adfoster-r7 Thanks for all the support on this one! I have decided to take an iterative approach to replacing `RbMysql` seeing as it is used in other places and introducing the gem creates the space to do so. So, this PR introduces the gem and changes the MySQL login scanner to use it.

I will address the other usages in follow-up PRs.

**Comment by adfoster-r7** [comment]
Thanks! :+1:

**Pull request merged**
