### PR TITLE
YARD Documentation for Fuzzer.rb

### PR DESCRIPTION
**Pull request by MSadek-r7**
## Verification

Please do:
- [x] cd to the directory of fuzzer.rb
- [x] do : `yard doc *.rb`
- [x] Open doc/index.html
- [x] Read the doc for fuzzer.rb and see if you like it.

### CODE REVIEW

**Comment by todb-r7** [comment]
stealing this to test my updated git workspace.

**Comment by todb-r7** [comment]
Looks delightful

**Comment by todb-r7** [comment]
Cool.

I'm trying to get out of the habit of using an `upstream-master` local branch, and just live in `master` for most things. So, I have these git aliases now:

```
# Sync with upstream/master
  sync =!"git fetch upstream && git checkout master && git rebase upstream/master && git push origin master"

# Publish master to upstream master
  publish =!"git push upstream master:master"
```

This all assumes that `origin` is my fork (todb-r7), and `upstream` is the main fork (rapid7).

Seems to work.

**Comment by jlee-r7** [comment]
@MSadek-r7 note that there is also `rake yard`

**Pull request merged**
