### PR TITLE
Fix scripts identified in #5757

### PR DESCRIPTION
**Pull request by void-in**
https://github.com/rapid7/metasploit-framework/pull/5757 updated the migrate method prototype as a result of which a few scripts became outdated due to usage of old migrate method prototype. This PR updates those scripts so that migrate functionality could be restored.

https://github.com/rapid7/metasploit-framework/pull/5757 should be landed first and then this PR.

### CODE REVIEW

**Comment by wchen-r7** [comment]
Ah, don't forget to update rspec :-)

**Comment by wchen-r7** [comment]
@void-in May I submit another patch to you? I would like to set a default for the :timeout key, that way methods don't need to always provide one, and raise ArgumentError for :pid since that key is mandatory. I would also like to update the API documentation a little bit for def migrate.

**Comment by void-in** [comment]
@wchen-r7 Actually we need to submit a patch to @OJ PR. This way all the changes will be in a single PR rather than two PRs that depends on each other. Thanks a lot BTW for looking into it.

**Comment by wchen-r7** [comment]
@void-in Good call. That would be a smoother workflow. I can submit my changes to your branch anyway, and then you can submit yours to @OJ's. That way when he merges, it will be just one pull request.

**Comment by wchen-r7** [comment]
@void-in I just submitted my changes to your branch:  https://github.com/void-in/metasploit-framework/pull/6

So I guess I can go ahead and close this PR. And then after you merge my changes, you can submit your branch to @OJ, and then after he merges, we can just focus on #5757.

Thanks.

**Comment by OJ** [comment]
Thanks guys!

**Pull request closed without merging**
