### PR TITLE
gopher protocol scanner

### PR DESCRIPTION
**Pull request by h00die**
Um, yes.  [gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)) from 1991, you know the thing that lost out to http.  Well, there seems to still be ~150 servers known in the world, so we may as well have a scanner.  I didn't bother making a lib since its VERY unlikely any other module will ever need any of this.

This module connects to the gopher server and retrieves the gophermap, which is similar to a document index.  it is also possible to "browse" to other directories via the path variable.

Docs contain info on setting up a server w/ content.

## Verification

- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/gopher/gopher_gophermap`
- [x] `set rhosts [ips]`
- [x] `run`
- [x] **Verify** You see the contents of the gophermap
- [x] **Verify** if your DB is connected, the service shows up 
- [x] **Document** make sure the docs are good and clear

### CODE REVIEW

**Comment by jhart-r7** [comment]
❤️

**Review by sempervictus — COMMENTED** [review]
Awesome, whatcha wanna bet we see this one on TV in the next year or two? :-) thanks as always sir.

**Comment by jhart-r7** [comment]
Looks good to me.  I've made some minor changes to style and updated the documentation a bit in https://github.com/h00die/metasploit-framework/pull/7

**Comment by h00die** [comment]
Gave it a once over, code now looks like someone who knows ruby wrote it, thanks for the improvements!  Merged changes in.

**Comment by jhart-r7** [comment]
Landed.  Thanks again!

**Pull request merged**
