### PR TITLE
Consolidate and reuse pager code for inline console docs

### PR DESCRIPTION
**Pull request by wvu**
~This offers increased readability with the command help near the prompt.~ Taking the pager approach presently.

- [ ] Type `help`
- [ ] See available `msfconsole` commands without scrolling up
- [ ] Type `help repeat` or `help jobs`
- [ ] See available `repeat` or `jobs` options near the prompt

A pager approach is also an option (@acammack-r7), but I think this can be an easy win for me and @wchen-r7. Thoughts welcome.

```
msf5 > help repeat
Repeat
======

The `repeat` command repeats one or more console commands for a fixed number of
times, a certain length of time, or forever. The repeat command is most useful
for repeating module runs like memory dumpers or scanners that have a random
element to them.

Usage
-----

### Flags

#### -t, --time SECONDS

Start the list of commands until the number of seconds has elapsed.

#### -n, --number TIMES

Start the list of commands a fixed number of times.

#### -h, --help

Display the help banner.



Examples
--------

Run the heartbleed module every 10 seconds against a server for an hour:

    msf5 > use auxiliary/scanner/ssl/openssl_heartbleed
    msf5 auxiliary(scanner/ssl/openssl_heartbleed) > set ACTION DUMP
    # Set other options...
    msf5 auxiliary(scanner/ssl/openssl_heartbleed) > repeat -t 3600 run; sleep 10


Usage: repeat [OPTIONS] COMMAND...
Repeat (loop) a ;-separated list of msfconsole commands indefinitely, or for a
number of iterations or a certain amount of time.

    -t, --time SECONDS               Number of seconds to repeat COMMAND...
    -n, --number TIMES               Number of times to repeat COMMAND..
    -h, --help                       Help banner.
msf5 >
```

#11407, #11498

### CODE REVIEW

**Comment by jrobles-r7** [comment]
Is this one delayed?

**Comment by acammack-r7** [comment]
No, although I would rather not make the output less like `man(1)`. As a note, you can skip the markdown entirely by doing `repeat -h`.

**Comment by wvu-r7** [comment]
I'm moving and refactoring my pager code from the developer dispatcher into the dispatcher shell this morning, and we'll see how it looks after that. Output that's closer to  `man(1)` is a good thing.

Our primary gripe is that you can't suppress the Markdown output for `msfconsole` help, @acammack-r7.

**Comment by acammack-r7** [comment]
```
msf5 > repeat -h
Usage: repeat [OPTIONS] COMMAND...
Repeat (loop) a ;-separated list of msfconsole commands indefinitely, or for a
number of iterations or a certain amount of time.

    -t, --time SECONDS               Number of seconds to repeat COMMAND...
    -n, --number TIMES               Number of times to repeat COMMAND..
    -h, --help                       Help banner.
```

**Comment by wvu-r7** [comment]
This is a little too niche of barely a problem for me to be willing to solve right now. Portable pager invocation is not something I want to deal with at the moment, and there are other bigger fish to fry.

Someone else can take a stab at this if they'd like. Thanks.

**Pull request closed without merging**
