### PR TITLE
Secure (https) links in README.md (Trivial Fix)

### PR DESCRIPTION
**Pull request by war59312**
Secure (https) links in README.md

### CODE REVIEW

**Comment by war59312** [comment]
Also, 

> "Metasploit Framework http://www.metasploit.com/"

 At top of the GitHub main page (https://github.com/rapid7/metasploit-framework) should be made https.

**Comment by thecarterb** [comment]
#8396

**Comment by wvu-r7** [comment]
@thecarterb: Check out https://github.com/blog/1506-closing-issues-via-pull-requests.

**Comment by thecarterb** [comment]
Didn't know about that. Thanks!

**Comment by jmartin-r7** [comment]
# Release Notes

This fix updates README.md to provide more secure links.

**Pull request merged**
