### PR TITLE
remove -db / -pcap / -all gemspecs, merge into one gem

### PR DESCRIPTION
**Pull request by busterb**
We are looking switching metasploit-framework from being packaged in 3rd party tools as a directory, e.g. 'msf3' in Metasploit Pro, to simply being packaged as a gem. This would also mean that weekly, we would bump the version number of metasploit-framework itself. That is, rather than just sitting on 4.11.4 for several weeks, we will bump to 4.11.5 next week, and again the next. This makes it easier to tell when a new version is available.

As part of this transition, it does not make sense to have 4 different gemspecs that target different features, since most (all?) direct framework users will simply run 'bundle install', which is the same as using the '-all' version. Merging these does not mean that you now have to use a database with framework, only that libpgsql-dev, libpcap-dev, or their equivalents need to be available when 'bundle install' is run.

Really, this should not make much of a difference, other than 'pro' will simply need to depend on metasploit-framework. Kali, Omnibus and other distributions seem to build with the database and libpcap as well. Of course, correct me if I am wrong!

Note, this also removes the unused 'kissfft' library mentioned in #6185 so we can learn if that breaks anything.

### CODE REVIEW

**Comment by bcook-r7** [comment]
Rebased on latest master and pulled in #6185 as well.

**Comment by bcook-r7** [comment]
Hmm, looks good. This gets us down to just one gemspec file in the project :)

**Comment by jlee-r7** [comment]
Is the `delayed` label on this waiting for Pro to twiddle bits, or can this land?

**Comment by bcook-r7** [comment]
It can land now, so we can update pro.

**Comment by wvu-r7** [comment]
This has been reverted in https://github.com/rapid7/metasploit-framework/commit/e6202e3edaf21feeb453d21cd69d2bd8799d9382.

**Pull request merged**
