### PR TITLE
New documentation for apkinjection

### PR DESCRIPTION
**Pull request by anshiq**
Fixes documentation based on new updates of Metasploit Framework.  Fixed issue #10187  . Gives Instruction how to use metaspoit framework to generate milicious apk using msfvenom .

### CODE REVIEW

**Comment by Anshik-Singh** [comment]
Fixes documentation based on new updates of Metasploit Framework. Fixed issue https://github.com/rapid7/metasploit-framework/issues/10187 . Gives Instruction how to use metaspoit framework to generate milicious apk using msfvenom .

**Comment by Anshik-Singh** [comment]
Hello Metasploit Team, I am working on links which will help for Installation of Required tools and msfconsole listning server. I will done It in next 1-2 days.

**Comment by bcoles** [comment]
> Hello Metasploit Team, I am working on links which will help for Installation of Required tools and msfconsole listning server. I will done It in next 1-2 days.

Hello.

It looks like you've accidentally included changes to `README.md` from another pull request in this pull request. Please ensure your branch is forked from master.

A lot of information has been removed - in particular the `Finding APKs` section. Is there a reason for this?

There are many many typos and spelling errors. Please fix them.

Please use relevant headings instead of "Method 1" and "Method 2". There are only two and makes sense to name them.

There are a few sentences which say "click here" but do not contain hyperlinks. Also is better to use relevant text for the links instead of "click here".

> Fixes documentation based on new updates of Metasploit Framework.

It is not really clear what this PR is updating. The PR doesn't reference new updates to Metasploit Framework, such as replacing `jarsigner` with `apksigner`. `jarsigner` is no longer a dependency.

**Comment by Anshik-Singh** [comment]
Yes , There is a reason for not giving Information about finding apk because user have many options to use existing such downloading apk from some famous website. I will give installations instructions in this document in next day. And please help me 
how can I push only these working files not readme.md file in pull up request. I am a newbie and new to git github. please help me to contribute in this program. Thank you.

**Comment by bcoles** [comment]
> how can I push only these working files not readme.md file in pull up request

You could rebase the pull request:

* https://anavarre.net/how-to-rebase-a-github-pull-request/
* https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request

**Comment by bcoles** [comment]
#16337

**Pull request closed without merging**
