### PR TITLE
fix #11189, meterpreter > ls on 4gb files

### LINKED ISSUE #11189: Meterpreter has issues with large (> 4GB) files
This has actually been reported before but not on the framework repo:
https://github.com/rapid7/meterpreter/issues/204
https://github.com/rapid7/metasploit-payloads/issues/281

## Steps to reproduce

1. Get any meterpreter session (currently python)
1. Create a 4.1 gb file: `dd if=/dev/zero of=lol4gb bs=4M count=1025`
1. `meterpreter > ls` in the directory where you created `log4gb`

## Expected behavior

The ls command should complete and return the correct size

## Current behavior

```
meterpreter > ls
[-] stdapi_fs_ls: Operation failed: Unknown error
```

```
[01/01/2019 19:58:21] [e(0)] meterpreter: stdapi_fs_ls: Operation failed: Unknown error
[01/01/2019 19:58:21] [d(0)] meterpreter: Call stack:
/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:80:in `entries_with_info'
/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:629:in `list_path'
/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:735:in `cmd_ls'
```

### OS

Linux

### PR DESCRIPTION
**Pull request by timwr**
This fixes #11189 by changing st_size to a 64bit (unsigned) integer

## Verification

List the steps needed to make sure this thing works

- [x] Check out this change (but not the meterpreter fixes)
- [x] Get a python, java, mettle and windows meterpreter session
- [x] **Verify** `meterpreter > ls` still works as before (ensure there are no >2gb files where you ls)
- [x] Create a 4.1 gb file: `dd if=/dev/zero of=lol4gb bs=4M count=1025`
- [x] Some meterpreter sessions will fail to ls (python), some will overflow the 32bit number and show the wrong size.
- [x] Land and install the fixes to the meterpreters (https://github.com/rapid7/mettle/pull/160 and https://github.com/rapid7/metasploit-payloads/pull/322/files), and re-stage the meterpreter sessions (to include the fixes)
- [x] **Verify** the correct file size is now shown

### CODE REVIEW

**Comment by busterb** [comment]
I made some improvements and increased inode to 64-bit as well as bumping everything that was 16-bit to 32-bit, which also allows 32-bit UID/GIDs, commonly seen with Active Directory integrations on Unix systems.

**Comment by busterb** [comment]
## Release Notes

This extends Meterpreter to understand 64-bit file sizes, 32-bit UID/GID values, 64-bit time across more platforms, and more when enumerating files on a filesystem.

**Comment by CaptiveFabry0** [comment]
I'm sorry but I really don't find the files to modify. i have metasploit preinstalled on kali.

**Comment by jmartin-r7** [comment]
@CaptiveFabry0 please do not comment on old/closed PRs. For quick questions please join the #slack team or IRC found on metasploit.com. If you have a new issue please open an issue and fill in the details that provide context to explain your problem.

Kali maintain's their own fork of metasploit-framework, please direct Kali specific issues to the appropriate Kali forums.

**Pull request merged**
