### PR TITLE
Fix uneven quotes in various documentation files

### PR DESCRIPTION
**Pull request by james-otten**
Even out the quotes in several files so they render correctly.

## Verification

- [ ] **Verify** quotes have been evened out in the modified files
- [ ] **Verify** the modified files render as expected

### CODE REVIEW

**Comment by james-otten** [comment]
After I ran into one of these, I wrote a [quick script](https://gist.github.com/james-otten/e4fe28cc7723500fb17a6cc72a8aee75) to look for low hanging fruit. The same thing can be done with single quotes, though I ran into 2 false positives in the current codebase. More opportunities for improvement could likely be found with a real markdown linter, which could be ran at build time.

**Comment by h00die** [comment]
was going to go video game but.... i can knock this out in no time.

**Comment by h00die** [comment]
# Release Notes
Fixes some formatting issues with docs

**Comment by h00die** [comment]
Thanks for the changes @james-otten you even caught some of mine

**Pull request merged**
