### PR TITLE
Consistently refer to black hole as two words

### PR DESCRIPTION
**Pull request by zeroSteiner**
Fix a typo in the help menu of the `dns` command.

### CODE REVIEW

**Comment by adfoster-r7** [comment]
Just before we lock things in; What was the rationale behind choosing two words for `black-hole` versus one word `blackhole` - similar to what IANA uses: 

https://www.iana.org/help/dns-blackhole

As well as Wikipedia:

> This article is about blackhole DNS servers. For other uses, see [black hole (disambiguation)](https://en.wikipedia.org/wiki/Black_hole_(disambiguation)).
> https://en.wikipedia.org/wiki/Blackhole_server

Is there a semantic difference for Metasploit's implementation versus that definition? :eyes:

**Comment by zeroSteiner** [comment]
The rationale was that the actual phenomenon is spelled with two words. Also from Wikipedia: https://en.wikipedia.org/wiki/Black_hole

Do you want it changed back to one word?

**Comment by adfoster-r7** [comment]
Working for me, thanks!

**Comment by adfoster-r7** [comment]
## Release Notes

Fix a typo in the help menu of the dns command

**Pull request merged**
