### PR TITLE
Weekly dependency updates for Gemfile.lock

### PR DESCRIPTION
**Pull request by gwillcox-r7**
This PR should have been auto-generated by [actions/github-script](https://github.com/actions/github-script). `bundle update` revealed the following gems have new version to be evaluated for update.

Adjustment to get automation working are still underway, for now let us pickup here this week.

## Verification

List the steps needed to make sure this thing works

- [ ] Security review diffs for updated gems

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
Seems like Ruby 3.2 breaks a few syntax related items so some of the tests aren't passing atm. Moving this to draft state.

**Comment by gwillcox-r7** [comment]
Removing the 3.2 bump from this. Whilst we could upgrade and fix the tests, I think for the sake of the team it may be better for us to just do this in stages and split out the 3.2 bump into another PR.

**Comment by adfoster-r7** [comment]
It might make sense to close this PR and open a separate PR with just Gem updates, as the branch is still called `gwillcox-r7:upgrade-ruby-3.2` - which might be confusing to future travellers

**Comment by gwillcox-r7** [comment]
@adfoster-r7 Thanks thought that might be a concern, I'll go ahead and do that now 👍

**Pull request closed without merging**
