### PR TITLE
Rename scanner/mdns/query module to mdns_query

### PR DESCRIPTION
**Pull request by bcoles**
This PR renames the `auxiliary/scanner/mdns/query` module to `mdns_query`.

`query` is a bad name for a module.

### CODE REVIEW

**Review by jhart-r7 — COMMENTED** [review]
I believe there is a more official way to rename modules.

~agreed on the renaming.  When I wrote this i wanted to call it mdns_query, but it already being nested in the mdns directory made that feel redundant.

**Comment by bcoles** [comment]
The more official way is probably above my pay grade.

I can close this PR and open an issue instead if you like?

**Comment by jhart-r7** [comment]
@bcoles I believe it is as simple as adding this to the old module:

```
  include Msf::Module::Deprecated 
 
  deprecated(Date.new(2017, 12, 29), 'auxiliary/scanner/mdns/mdns_query') 
```

And then include a new copy under the new name.

Or, at least that is what I thought the process was.  It still feel like it should be simpler to do a rename.  @bcook-r7 are you aware of any better ways to handle module renaming?

**Comment by wvu-r7** [comment]
Correct, the official way to rename a module is to deprecate the old one and point it to the new one. For something that sees significant use, I'd do that. However, for modules that don't see much use, I'd just rename them outright. YMMV. I am not aware of a better way. @busterb?

**Review by wvu — APPROVED** [review]
I'm approving this so I can get the notification out of the way. :-)

**Comment by acammack-r7** [comment]
Hmm, I think showing the last two parts of the module name in the shell prompt would be a more general solution to this. The file to change is `lib/msf/ui/console/command_dispatcher/modules.rb` around line `664`.

**Comment by jhart-r7** [comment]
@acammack-r7 I agree.  There are many other modules that have a similar problem or would otherwise benefit from this solution.  IMO, the prompt should show the full simplified path to the module.

**Comment by wvu-r7** [comment]
Agreed. I've been naming my modules like this PR to get around the issue. Arguably, the prompt should be updated to include more information, too. It's about time.

**Comment by jhart-r7** [comment]
I vote that we change the prompt.  I can imagine an uproar about the format akin to `PS1` in bash/etc, but I think it'll be OK.  It looks to be something like:

```
$  git diff
diff --git a/lib/msf/ui/console/command_dispatcher/core.rb b/lib/msf/ui/console/command_dispatcher/core.rb
index 78a8443..e52cf99 100644
--- a/lib/msf/ui/console/command_dispatcher/core.rb
+++ b/lib/msf/ui/console/command_dispatcher/core.rb
@@ -1107,7 +1107,7 @@ class Core
     if active_module
       # intentionally += and not << because we don't want to modify
       # datastore or the constant DefaultPrompt
-      prompt += " #{active_module.type}(%bld%red#{active_module.shortname}%clr)"
+      prompt += " #{active_module.type}(%bld%red#{active_module.fullname}%clr)"
     end
     prompt_char = framework.datastore['PromptChar'] || Msf::Ui::Console::Driver::DefaultPromptChar
     driver.update_prompt("#{prompt} ", prompt_char, true)
diff --git a/lib/msf/ui/console/command_dispatcher/modules.rb b/lib/msf/ui/console/command_dispatcher/modules.rb
index bbb1993..107f758 100644
--- a/lib/msf/ui/console/command_dispatcher/modules.rb
+++ b/lib/msf/ui/console/command_dispatcher/modules.rb
@@ -661,7 +661,7 @@ module Msf
             # Update the command prompt
             prompt = framework.datastore['Prompt'] || Msf::Ui::Console::Driver::DefaultPrompt
             prompt_char = framework.datastore['PromptChar'] || Msf::Ui::Console::Driver::DefaultPromptChar
-            driver.update_prompt("#{prompt} #{mod.type}(%bld%red#{mod.shortname}%clr) ", prompt_char, true)
+            driver.update_prompt("#{prompt} #{mod.type}(%bld%red#{mod.fullname}%clr) ", prompt_char, true)
```

When used:

```
msf > use auxiliary/scanner/rsync/modules_list 
msf auxiliary(auxiliary/scanner/rsync/modules_list) >
```

**Comment by bcoles** [comment]
Looks good, although `msf auxiliary(scanner/rsync/modules_list) >` would probably make more sense

**Pull request closed without merging**
