### PR TITLE
remove copy of JtR from the metasploit-framework tree

### PR DESCRIPTION
**Pull request by bcook-r7**
Is anyone really using these 3 year old binaries?

This is in-tree compiled code that links to external libraries (OpenSSL 1.0.0) that most distributions will not even have packaged anymore. If someone needs John, it should really be built and packaged separately of metasploit-framework. John accounts for half of the compressed size of the data/ directory and duplicates arguably better maintained and up-to-date packaging efforts. Only one thing in-tree seems to actually use these binaries (scripts/resource/auto_pass_the_hash.rc), so I removed the hardcodes there so John in the PATH will be used instead.

If Metasploit Pro is using these binaries, it should probably build them local to its distribution.

```
Before: 48M data/
After:  24M data/
```

### CODE REVIEW

**Comment by hmoore-r7** [comment]
This is the default location for the fastcrack modules, so they need an update, not a removal :)

**Comment by hmoore-r7** [comment]
Alternatively, the installers/updaters need to drop JtR bins, then we can remove from framework. Related is the CPU identification binary we ship alongside.

**Comment by bcook-r7** [comment]
Every module I was able to find in the tree appears to simply use the first copy of JtR found in the path. Are there commonly-used external modules that need updates?

**Comment by bcook-r7** [comment]
Waiting on pro builds to stop depending on this before removing.

**Comment by wchen-r7** [comment]
@bcook-r7 is it possible to provide an estimate on when we will be able to land this PR? It would be nice to have this info, and then we can come back later.

**Comment by bcook-r7** [comment]
Let me check again; I'm not sure why we can't just move these binaries somewhere else.

**Comment by bcook-r7** [comment]
Tell you what, I'll close this for now and reopen when we have the other side sorted.

**Pull request closed without merging**
