### PR TITLE
Spelling correction in iis_shortname_scanner.rb

### PR DESCRIPTION
**Pull request by danhedonia**
Fixed spelling error: "diclose" to "disclose"

### CODE REVIEW

**Comment by jmartin-r7** [comment]
@msjenkins-r7 test this please.

**Comment by h00die** [comment]
@jenetiks were you by chance at a conference on Wednesday that suggested submitting 4 spelling corrections may get you a haktoberfest t-shirt?

**Comment by jenetiks** [comment]
maaaaaaaaayyyybbeeeeeeee. I may have been your moderator too... maybe not though

**Comment by bcoles** [comment]
`scspell` says you missed a few

**Comment by jenetiks** [comment]
tbh, no idea what that even is

**Comment by bcoles** [comment]
```
$ grep -rni recieve metasploit-framework | wc -l
72
```

```
$ grep -rni NETOTIATE metasploit-framework
metasploit-framework/modules/auxiliary/server/http_ntlmrelay.rb:151:      # Relay NTLMSSP_NETOTIATE from client to server (type 1)
```

**Comment by h00die** [comment]
# Release Notes
Spelling fix in iis_shortname_scanner

**Comment by h00die** [comment]
Thanks for contrib @jenetiks 
Enjoy the T-shirt :)

**Pull request merged**
