### PR TITLE
Fixup finalizers to not double-close Meterpreter objects

### LINKED ISSUE #6634: investigate removing finalizers causing spurious duplicate closes of things for meterpreter
follow up from #6593 to fix the underlying finalizer issue that is causing channels and possibly other things to get closed multiple times.

### PR DESCRIPTION
**Pull request by bcook-r7**
We add finalizers to an assortment of Meterpreter-managed objects in order to clean things up in the event that a post module crashes and does not clean things up. However, this also means that even a properly-written post module can lead to an object getting double-closed on the Meterpreter session when the garbage collector kicks in. This can lead to quite non-deterministic behavior and crashes.

This change modifies the instance close methods to unregister the finalizer on close, ensuring we cannot do a double-close automatically if one is requested explicitly first. As an additional measure, we check an instance variable to see if we called close directly twice as well. This is not sufficient in itself, since we do not have a reference to 'self' in the finalizer proc to check the close state.

fixes #6634 
# Verification steps
- [x] establish a windows meterpreter session
- [x] run 'loadpath test/modules' to load the test modules
- [x] use post/test/meterpreter; run a few times
- [x] use post/test/registry; run a few times
- [x] downgrade the metasploit-payloads gem back to 1.1.1 to recreate the python channel double-close bug #6593,
- [x] establish a python meterpreter session
- [x] verify that you can download a large file multiple times without truncation

Probably more to test here as well.

### CODE REVIEW

**Comment by zeroSteiner** [comment]
`lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb` also has a finalize method to close the handle to the process. It looks like it could also be affected by this same issue. Should it incorporate these changes as well?

**Comment by bcook-r7** [comment]
yeah, I think you are right

**Comment by busterb** [comment]
testing now, addition coming soon...

**Comment by zeroSteiner** [comment]
Ran all of the specified tests 5 times a piece, each of which resulted in a success. Also checked the python meterpreter debug logs to ensure there was not an extra core_channel_close request received. All looks good to me so I'll land this now.

**Comment by bcook-r7** [comment]
Cheers @zeroSteiner !

**Comment by OJ** [comment]
Great job folks.

**Pull request merged**
