### PR TITLE
Crash

### PR DESCRIPTION
**Pull request by crashbrz**

### CODE REVIEW

**Comment by wvu-r7** [comment]
I don't think this is right.

**Comment by hmoore-r7** [comment]
This PR is too broken. Please create a new PR (from a fresh master branch pull) with just the changes you want.

**Comment by espreto** [comment]
@crashbrz How are you my bro? If you want to help let me know. :)

**Comment by crashbrz** [comment]
@espreto Yeah!! I did a little mass in my git lol!

**Pull request closed without merging**
