### PR TITLE
add jjs payload tests and set cached sizes

### PR DESCRIPTION
**Pull request by jmartin-tech**
Add missing payload tests from addition of `*_jjs` payloads.

## Verification

List the steps needed to make sure this thing works

- [x] Travis tests pass and does not report missing payloads.

### CODE REVIEW

**Comment by jmartin-r7** [comment]
Review of code for payloads suggests size would be consistent.

@bcoles please confirm that setting payload cache size here makes sense.

**Comment by bcoles** [comment]
> 
> 
> Review of code for payloads suggests size would be consistent.
> 
> @bcoles please confirm that setting payload cache size here makes sense.

Gladly. How do I do that?

**Comment by jmartin-r7** [comment]
@bcoles, I am primarily just looking to verify that I understood the code correctly and the generated payload will be of consistent size when required options are set.

Looking at the test output in original #12544 the generated payloads there were same sizes as the values set in this PR, please confirm I did not miss something that would cause wildly different values on some environments.

**Comment by bcoles** [comment]
> 
> 
> @bcoles, I am primarily just looking to verify that I understood the code correctly and the generated payload will be of consistent size when required options are set.
> 
> Looking at the test output in original #12544 the generated payloads there were same sizes as the values set in this PR, please confirm I did not miss something that would cause wildly different values on some environments.

The commands are mostly static. The only dynamic parts are the `LHOST`, `LPORT`, and `SHELL` options. In theory, these could be very long.

The payloads extend from `Msf::Sessions::CommandShellOptions`, which does not appear to expose any options related to the target.

... I'm not sure if that helps. `LHOST` and `LPORT` are standard for `cmd/unix` payloads. A quick grep for `SHELL` in the `cmd/unix` payloads revealed only the `reverse_python` module, which also uses `:dynamic`.

**Pull request merged**
