### PR TITLE
RHOSTS: accept both "file://<path>" and "file:<path>" syntax

### PR DESCRIPTION
**Pull request by cnotin**
The `RHOSTS` option is compatible with file paths to load targets from a hosts file.
Many documentations and examples (example in [Metasploit 5.0 release notes](https://github.com/rapid7/metasploit-framework/wiki/Metasploit-5.0-Release-Notes)) describe its usage with the "file://<path>" syntax, like a URL. However, by reading the code, I noticed it should actually be "file:<path>".

The patch allows to use both syntax for maximum compatibility, and without having to fix all documentations.

## Verification
Create the data file:
```shell
echo 127.0.0.1 > /root/list.txt
echo 127.0.0.2 >> /root/list.txt
```

Open msfconsole and load any module which uses RHOSTS and set a few options (for better output):
```shell
use auxiliary/scanner/mysql/mysql_version
set verbose true
set showprogress false
```

Run these variations:
```shell
set rhosts file:list.txt
run
set rhosts file:./list.txt
run
set rhosts file:/root/list.txt
run

set rhosts file://list.txt
run
set rhosts file://./list.txt
run
set rhosts file:///root/list.txt
run
```

Before the patch:
```shell
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file:list.txt
rhosts => file:list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file:./list.txt
rhosts => file:./list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file:/root/list.txt
rhosts => file:/root/list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file://list.txt
rhosts => file://list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: RHOSTS.
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file://./list.txt
rhosts => file://./list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: RHOSTS.
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file:///root/list.txt
rhosts => file:///root/list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
```
Failures for "file://list.txt" and "file://./list.txt"...

After the patch:
```shell
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file:./list.txt
rhosts => file:./list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file:/root/list.txt
rhosts => file:/root/list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file://list.txt
rhosts => file://list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file://./list.txt
rhosts => file://./list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
msf5 auxiliary(scanner/mysql/mysql_version) > set rhosts file:///root/list.txt
rhosts => file:///root/list.txt
msf5 auxiliary(scanner/mysql/mysql_version) > run

[-] 127.0.0.1:3306        - 127.0.0.1:3306 - Connection failed
[-] 127.0.0.2:3306        - 127.0.0.2:3306 - Connection failed
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/mysql/mysql_version) > 
```

### CODE REVIEW

**Comment by cnotin** [comment]
Suggestion too: explain the possibility of using "file:<path>" syntax in the description of RHOSTS (as people re-discover it now and then)
https://github.com/rapid7/metasploit-framework/blob/76954957c740525cff2db5a60bcf936b4ee06c42/lib/msf/core/opt.rb#L43-L50

What do you think?

**Comment by busterb** [comment]
Yeah, I think describing it in the option definition is a good idea too, thanks.

**Comment by cnotin** [comment]
Here it is, tell me what you think :)

**Comment by busterb** [comment]
Yeah, looks good. Moving this one forward...

**Comment by busterb** [comment]
Noting there are a lot of `file://` URLs in the tree still, but wouldn't hold this PR up for it. Maybe something easy for someone to grab later, though there's no real urgency.

`git grep "file:\/\/"`

**Comment by busterb** [comment]
## Release Notes

This documents the syntax used by the RHOSTS command when a `file:` parameter is passed. Variously throughout existing Metasploit documentation, this was described as using `file://` which happens to work, but the extra slashes were not required.

**Comment by jmartin-r7** [comment]
Labeled `msf5` due to interaction with global `RHOSTS` support, I may backport to `4.x` if conflicts can be quickly resolved.

**Comment by fishsticksflafor** [comment]
Hey! Thanks for the help
I still have a lot to learn... hahaha

Do you know anny fun tip's or trick's with Metasploit?

GoodLuck :-)

Greetz Jeff

Op di 24 sep. 2019 16:35 schreef Jeffrey Martin <notifications@github.com>:

**Pull request merged**
