### PR TITLE
The iax2 stack now works properly with asterisk 1.8

### PR DESCRIPTION
**Pull request by hdm**
Note that the requirecalltoken=no setting is still required in the asterisk configuration at this point.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Code looks good. Ran it through some tests in ```irb```. Can't set up Asterisk right now.

**Comment by thewb** [comment]
The current IAX code in 2.0 now provides for registration and originating calls with Asterisk 1.8 IAX. Fixes were implemented 2/2/15 by the project developer. The line nochecksum=yes needs to be added to the iax.conf file in the [general] section or you will not be able to register.

**Comment by wvu-r7** [comment]
https://github.com/rapid7/warvox/issues/27

**Comment by kamitelco** [comment]
D, [2018-04-12T00:56:04.515033 #28232] DEBUG -- : Worker Manager is launching job 7
D, [2018-04-12T00:56:09.332549 #28249] DEBUG -- : Worker 7 dialer is running dialer with parameters {:range=>"34632802425\n34931796817\n34602344145\n34632198686", :lines=>10, :seconds=>53, :cid_mask=>"1555555XXXX"}
ERROR: Unable to register with the IAX server

**Comment by kamitelco** [comment]
D, [2018-04-12T00:56:04.515033 #28232] DEBUG -- : Worker Manager is launching job 7
D, [2018-04-12T00:56:09.332549 #28249] DEBUG -- : Worker 7 dialer is running dialer with parameters {:range=>"34632802425\n34931796817\n34602344145\n34632198686", :lines=>10, :seconds=>53, :cid_mask=>"1555555XXXX"}
ERROR: Unable to register with the IAX server
any solution for this problem  
i have installed asterisk +warvox   when i try to dial its  come error  unable to register with IAX server

**Comment by hdm** [comment]
WarVOX in unsupported and unmaintained, sorry!

**Pull request merged**
