### PR TITLE
Add meterpreter keyboard and mouse input

### PR DESCRIPTION
**Pull request by timwr**
This pull request extends the stdapi ui extension to add some basic commands to send mouse and keyboard input to a meterpreter client. In future potentially we can extend this to send virtual keys (as it's not currently implemented to send modifiers and multiple keys (e.g Escape, direction arrows, Ctrl + R, etc). It's unclear what format to use for this, potentially we could add support for duckyscript.

## Verification

List the steps needed to make sure this thing works

- [x] Land OSX/Windows changes
- [ ] `meterpreter > mouse click`
- [ ] `meterpreter > keyboard_send "🐲✌  𝐦𝑒𝕥𝔸Ŝρ𝕃Ⓞ𝐢т  😝🐙"`
- [ ] **Verify** the meterpreter client performs the user input.

### CODE REVIEW

**Comment by busterb** [comment]
I'll let you know real quick what happens when this gets used against littlesnitch. It seems to hate synthetic events.

**Comment by busterb** [comment]
Note, this does require you to grant access explicitly for macOS, though on Windows it's wide-open by default.

**Comment by schierlm** [comment]
Any plans of [adding this to Java meterpreter](https://docs.oracle.com/javase/7/docs/api/java/awt/Robot.html)?

Any plans of using this in combination with screenshot feature to implement some crude VNC emulation?

**Comment by timwr** [comment]
I can certainly add this on Java (thanks for the API) not sure about python though.
Crude screenshot thing is here: 
https://github.com/rapid7/metasploit-framework/pull/11951
It's unclear how to best send keystrokes from the Javascript layer to metasploit thought. Maybe Ajax+rest API?

**Comment by schierlm** [comment]
My first intuitive idea would have been to add the keystrokes/mouse clicks as parameters to the jpeg request of the next image. But then I noticed that the JPEG is not delivered via HTTP, but dumped to disk and loaded via `file://` protocol... 

Okay it is only local, but that may result in unneeded refreshes (same image) as well as unneeded delays...

So I would improve that (that it only requests screenshots on http request, and schedules the next refresh only after the previous image has been loaded) and sends the accumulated keystrokes/clicks when requesting the next image.

**Comment by tdoan-r7** [comment]
# Release Notes
The stdapi ui extension now includes some basic commands that you can use to send mouse and keyboard inputs to a Meterpreter client.

**Pull request merged**
