### PR TITLE
External metasploit aggregator/proxy for https session sharing between consoles

### PR DESCRIPTION
**Pull request by jmartin-tech**
This plugin provides management and interaction with an external session aggregator.

Once loaded this module can be used to connect to an executing metasploit-aggregator service providing payload transport service to reverse_https based payloads and session "parking".

A default forward console should be set for the metasploit-aggregator service to provide payload system information enumeration support.

(See https://github.com/rapid7/metasploit-aggregator for source of gem providing service)

Initial support is for reverse_https connections only, expansion for other transports is under consideration and feedback is welcome.

## Verification

List the steps needed to make sure this thing works

- [x] Start `metasploit-aggregator` in separate shell (currently hardcode to 127.0.0.1:2447 listener)
- [x] Start `msfconsole`
- [x] `load aggregator`
- [x] **Verify** `aggregator_connect 127.0.0.1:2447`
- [x] **Verify** `aggregator_default_forward`
- [x] **Verify** `aggregator_cable_add host:port pem.file(optional)`
newly listening ports will be reported on stderr of the metasploit-aggregator process
- [x] **Verify** `aggregator_cables`
will report the newly listening cable
- [x] **Verify** start a https meterpreter session to host:port of a listening cable
this should produce a session on the default registered console
- [x] **Verify** start a paranoid https meterpreter session to host:port based on pem.file
if the pem.file was used to start the cable this will produce a session
otherwise the meterpreter process should disconnect
- [x] **Verify** `aggregator_session_park <session_id>`
- [x] **Verify** `aggregator_sessions`
- [x] **Verify** `aggregator_session_forward <Remote ID>`
- [x] **Verify** `aggregator_disconnect`

### CODE REVIEW

**Comment by jmartin-r7** [comment]
Note: current implementation for connection to metasploit-aggregator is unsecured and only listens on 127.0.0.1, this mean all ssl is currently terminated at the metasploit-aggregator process.

**Comment by jmartin-r7** [comment]
Dependency requirements push back msgpack version further than desired (0.5.10).  WIP to convert metasploit-aggregator gem to another rpc protocol and release updated gem. Delayed tag will be removed once dependent gem is released to protect compatibility on master with msgpack 1.x

**Comment by busterb** [comment]
Now that this is based on grpc, we have some issues building it on arm platforms due to the grpc gem building with -Werror. We should probably raise that problem with the grpc guys (they did the same darn thing with the v8 gem), since distributed software failing on a warning is pretty annoying.

I'm going to add an exception that skips the aggregator on arm.

**Comment by busterb** [comment]
Cool, working well, thanks! We also worked on some documentation currently residing at https://github.com/rapid7/metasploit-aggregator/ that gives a bit more info. At some point, we should decide on a location for 'plugin' documentation and move it there.

**Comment by busterb** [comment]
I disabled arm builds for now here: 50beade203
Also added support for '-h' in more contexts and fat-fingers on my part here: 394e7fd8be

**Comment by tdoan-r7** [comment]
# Release Notes

A plugin has been added that allows you to manage and interact with an external session aggregator.

**Pull request merged**
