### PR TITLE
Fixes #4602 by removing the bins from the bundle install

### LINKED ISSUE #4602: Bundle install puts broken msf* executables into the bin path
The metasploit-framework.gemspec currently specifies a bin directory and a list of executables. After running "bundle install", these executables are placed into the gem bin directory. Running these executables does not work. This is breaking the common practice of symlinking the metasploit git directory msf* binaries to /usr/local/bin, as the gem bin directory is searched first.

An easy fix is to change the gemspec to remove the executable files. A better fix might be to make these executables work even when transplanted into the bin directory.

### PR DESCRIPTION
**Pull request by hdm**

### CODE REVIEW

**Comment by hmoore-r7** [comment]
Looks like some of the specs depend on binpath, fixing.

**Comment by hmoore-r7** [comment]
It isn't clear how to tell cucumber to run the correct executable now that they have been pulled from the bin directory.

**Comment by todb-r7** [comment]
Until you can provide some kind of verification step, description of the change, and fixups on the tests, I don't see how we can reasonably land this.

**Comment by hmoore-r7** [comment]
This needs review by someone who understands how to fix the cucumber tests that depend on msfconsole being in the path. The fix solves the problem, but it breaks the tests due to the dependency on the path. IOW, ping @limhoff-r7 @trosen-r7 @jlee-r7

**Comment by todb-r7** [comment]
Tagging @kgray-r7 and @lsanchez-r7, too.

**Comment by todb-r7** [comment]
Labelling jira due to the deps on QE ( @lsanchez-r7 and @kgray-r7 ). Alternatively, teach us how to fish with Cucumber. :)

**Comment by todb-r7** [comment]
We talked about this in a bug triage meeting and also in some off-ticket conversation, but I don't think we have a satisfactory resolution yet.

Can you describe the use case where you're running into this, @hmoore-r7 ? It's still unclear to me. Simply rm'ing the bins means cucumber tests start failing, and I'm reluctant to work around a known testing setup to accommodate an unlikely use case. That said, if your use case is /not/ unlikely, let's move forward with some repro steps.

For me, if I run:

`./msfconsole -L` in the git checkout root, like always, I have no problems.

**Comment by todb-r7** [comment]
Oh, there's lots of discussion over on https://github.com/rapid7/metasploit-framework/issues/4602. Reading now.

**Comment by todb-r7** [comment]
Okay, #4602 is inconclusive, and incidentally the setup today seems to work for many/most. I still can't really tell what the problem here is, but I'm very doubtful that rm'ing the generated bins solves things now.

**Comment by hmoore-r7** [comment]
Removing the generated bin stubs clearly solves the problem, but it breaks the cucumber tests, which depend on the stubs being in the path. We either need to fix the cucumber tests or make sure msfupdate and friends call the workaround:
```
$ bundle binstubs metasploit-framework --path=$(dirname $(which msfconsole)) --force
```

**Comment by hmoore-r7** [comment]
Last I heard @bturner-r7 was still looking into Windows-related issues on #4602.

**Comment by hmoore-r7** [comment]
This discussion into #4602

**Pull request closed without merging**
