### PR TITLE
NTLM Util change to support Unicode hostnames

### PR DESCRIPTION
**Pull request by bwatters-r7**
# This PR relies on a change to rex-text: https://github.com/rapid7/rex-text/pull/3
# What does this do?

This is a change to the ntlm utilities library to properly convert and store unicode hostnames.  Previously, the NTLM blob was parsed and the data was put into ANSI using an in-house conversion before it was passed back to the calling module.  That destroyed any hostname that could not be rendered by ANSI characters.  This PR adds code to convert the UTF-16LE native hostnames contained in the blob to UTF-8 strings using ruby built-ins so that they can be displayed and stored to the database.  This probably fixes international domain names, too.  Without the rex-text change, the UTF-8 encoded data will display in the scanner, but the sanitization functions called before the db write will choke on the UTF-8 characters.
# What does this break?

I know that there seems to be an issue in displaying the data, as when you run `hosts`, the whitespace padding appears incorrect.  Otherwise, I do not know.  This does have the possibility of breaking other things, though I tried to minimize it.
## Verification
- [x] Start `msfconsole`
- [x] `use auxiliary/scanner/smb/smb_version`
- [x] `set rhosts <host with international hostname>`
- [x] `run`
- [x] **Verify** hostname is given correctly in the output
- [x] `hosts`
- [x] **Verify** hostname is stored in the database correctly
## Example Run:

```
msf > use auxiliary/scanner/smb/smb_version 
msf auxiliary(smb_version) > set rhosts <russian_host_ip>
rhosts => <russian_host_ip>
msf auxiliary(smb_version) > run

[*] <russian_host_ip>:445    - Host is running Windows 2012 R2 Standard (build:9600) (name:КОМПЬЮТЕР)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_version) > hosts

Hosts
=====

address         mac  name                os_name          os_flavor  os_sp  purpose  info  comments
-------         ---  ----                -------          ---------  -----  -------  ----  --------
<russian_host_ip>       КОМПЬЮТЕР  Windows 2012 R2  Standard          server         

msf auxiliary(smb_version) >
```

### CODE REVIEW

**Comment by bwatters-r7** [comment]
Dang..... I may need to push up a correction...... marking delayed.

**Comment by bwatters-r7** [comment]
OK..... so the problem is that this does not fix the domain name issues, just the hostnames.  After digging, the domain name is passed back in the smb client script embedded in a tokenized string with multiple other values and the delimiter is the null character.  That string is used in a couple places, so converting it to a more same data value might take some delicate dancing, so I'm just going to leave this PR as-is and work on getting the changes to capture Unicode domain names as another PR.

**Comment by bcook-r7** [comment]
Not quite. Just tested against a 2003 english host named 'jalapeño' with the new rex-text 2.0.4. 

```
[*] 192.168.56.102:445    - Host is running Windows 2003 R2 SP2 (build:3790) (name:JALAPE�O) (domain:WORKGROUP)
[-] 192.168.56.102:445    - 192.168.56.102: ActiveRecord::StatementInvalid PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xd1 0x4f
: INSERT INTO "services" ("host_id", "port", "proto", "name", "info", "state", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"
[*] 192.168.56.102:139    - Host is running Windows 2003 R2 SP2 (build:3790) (name:JALAPE�O) (domain:WORKGROUP)
[-] 192.168.56.102:139    - 192.168.56.102: ActiveRecord::StatementInvalid PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xd1 0x4f
: INSERT INTO "services" ("host_id", "port", "proto", "name", "info", "state", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"
```

**Comment by bwatters-r7** [comment]
Hrm...... OK; thanks!

**Comment by bcook-r7** [comment]
Oops, I didn't actually test your branch, was testing master. That looks better:

```
msf auxiliary(smb_version) > run

[*] 192.168.56.102:445    - Host is running Windows 2003 R2 SP2 (build:3790) (name:JALAPEÑO) (domain:WORKGROUP)
[-] 192.168.56.102:445    - 192.168.56.102: NoMethodError undefined method `workspace' for #<Mdm::Host:0x007fbc14603e20>
Did you mean?  workspace_id
[*] 192.168.56.102:139    - Host is running Windows 2003 R2 SP2 (build:3790) (name:JALAPEÑO) (domain:WORKGROUP)
[-] 192.168.56.102:139    - 192.168.56.102: NoMethodError undefined method `workspace' for #<Mdm::Host:0x007fbc0f306560>
Did you mean?  workspace_id
```

**Comment by bcook-r7** [comment]
Do you know what's going on with MDM and workspace being undefined? @darkbushido ?

**Comment by bwatters-r7** [comment]
I definitely did not see that error..... I am about neck deep in something else, but I can extricate myself later today and take a look.

**Comment by bcook-r7** [comment]
pebkac, I used a pro database with framework. they're subtly and annoyingly different in places.

**Comment by tdoan-r7** [comment]
# Release Notes

The NTLM utilities library now properly converts and stores unicode host names. The UTF-16LE native hostnames contained in the blob is converted to UTF-8 strings using ruby built-ins so that they can be displayed and stored to the database.

**Pull request merged**
