### PR TITLE
Enhance command_exists? method so that it falls to `which` in case the `command` fails

### PR DESCRIPTION
**Pull request by pingport80**
## Summary
This PR adds a small enhancement to the `command_exists?` method under `post/common.rb`. Currently it is using the `command` command to check if some command is present on the target system but in some cases that utility might not be present(see [here](https://github.com/rapid7/metasploit-framework/pull/15000#discussion_r609760330) for an example). So in that case it will fall to some other alternative like `which`.

This PR also removes a method `pids` which was removed in the PR #15199 but while refactoring it's code in the new `process.rb` the change was missed.

### CODE REVIEW

**Comment by wvu-r7** [comment]
_/me laughs in POSIX._

**Comment by smcintyre-r7** [comment]
Totally out of scope for this PR, but at some point, we may want to consider some kind of caching to determine what commands are available on a remote system since it's unlikely to change (unless we're changing it I guess) and each query takes a round trip which slows things down.

**Comment by pingport80** [comment]
That really sounds interesting and will be very useful. I guess for non-windows we can get using the `dir` method in every directory the `PATH` returns. For Powershell something like `Get-Command`, not sure about windows cmd.

**Comment by gwillcox-r7** [comment]
LGTM, will land this now.

**Comment by gwillcox-r7** [comment]
# Release Notes
The `command_exists?` method inside `post/common.rb` has been updated to fall back to using the `which` command to check if a command exists on a target system if `command -v` fails to run successfully. This allows users to check whether a command exists or not on systems that might not contain a `command` command, such as ESXi.

**Pull request merged**
