### PR TITLE
Use the 1.9+ hash syntax on new code

### PR DESCRIPTION
**Pull request by jvazquez-r7**
As requested by @jlee-r7 on https://github.com/rapid7/metasploit-framework/pull/4992

You can test it exactly as https://github.com/rapid7/metasploit-framework/pull/4992

ping @wchen-r7

### CODE REVIEW

**Comment by wchen-r7** [comment]
Thanks @jvazquez-r7, let me rerun Travis right quick....

**Comment by wchen-r7** [comment]
Travis is currently experiencing this error:

"No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself."

Doesn't look related.

**Comment by jvazquez-r7** [comment]
@wchen-r7 did you rerun?

**Comment by wchen-r7** [comment]
yeah

**Comment by jvazquez-r7** [comment]
@wchen-r7 I have no idea what was going on :S I just rerun after some minutes, it is green now :)

**Comment by wchen-r7** [comment]
ok, cool. Thx!

**Comment by wvu-r7** [comment]
Python. ;)

**Pull request merged**
