### PR TITLE
Add LoginScanner module for BAVision IP cameras

### PR DESCRIPTION
**Pull request by wchen-r7**
# Description

This is a loginscanner module that allows you to log into a BAVision IP camera via the web server. Once logged in, you can use the found credential to view/control the IP camera.

# Verification

- [x] Make sure you have access to this camera: http://goo.gl/pHAqS1
- [x] Start msfconsole
- [x] Do: ```use auxiliary/scanner/http/bavision_cam_login```
- [x] Do : ```set TRYDEFAULT true```
- [x] Do: ```run```
- [x] It should say login successful

### CODE REVIEW

**Comment by wchen-r7** [comment]
Travis failure is related to the previous commit/version bump:
https://github.com/rapid7/metasploit-framework/commit/f50fa516f4037a59150da4ea96b854fb4cbf18a3

**Comment by dmohanty-r7** [comment]
```
msf > use auxiliary/scanner/http/bavision_cam_login
msf auxiliary(bavision_cam_login) > set RHOSTS 1.1.1.1
RHOSTS => 1.1.1.1
msf auxiliary(bavision_cam_login) > set TRYDEFAULT true
TRYDEFAULT => true
msf auxiliary(bavision_cam_login) > run
[*] Default credential admin:123456 added to the credential queue for testing.
[+] BAVISION_CAM - Success: 'admin:123456'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by dmohanty-r7** [comment]
Nice work as always @wchen-r7 😎

**Comment by dmohanty-r7** [comment]
## Release Notes
This Login Scanner module scans for BAVision IP Cameras. Using the TRYDEFAULT option will use the default creds the device is typically configured with when unboxed. A scan on the open web proves to show that keeping the default creds is a popular option users take.

**Pull request merged**
