### PR TITLE
Add module multi/manage/set_wallpaper for setting the wallpaper on a meterpreter session

### PR DESCRIPTION
**Pull request by timwr**
This module adds a quick easy way to set the desktop wallpaper on a meterpreter session. This can be useful to work out which physical machine you have a session on and to demonstrate what a real attacker can do (e.g http://www.darkreading.com/sony-hackers-knew-details-of-sonys-entire-it-infrastructure-/d/d-id/1317898)

I've tested this on Windows and Android, but not OSX. If someone could test the OSX code path it would be much appreciated. The Android code path depends on: https://github.com/rapid7/metasploit-payloads/pull/73

### CODE REVIEW

**Comment by timwr** [comment]
Example usage:
```
wget http://img.wonderhowto.com/img/58/65/63545252017877/0/hack-like-pro-metasploit-for-aspiring-hacker-part-3-payloads.1280x600.jpg -O wallpaper.jpeg
use post/multi/manage/set_wallpaper 
set SESSION 1
set WALLPAPER_FILE wallpaper.jpeg
run
```

**Comment by bcook-r7** [comment]
It does work on OS X, with some slight changes. There's primarily that unfortunate design wart where non-native Meterpreters return the language they are written in for 'platform', e.g. 'python/python'. If it could at least say 'darwin/platform', that would be a lot easier.

**Comment by bcook-r7** [comment]
I added a couple of tweaks for OS X support: 86845222efab28f1ecbb623993b4fb4272bdeee4, d955c6a8f6b5643767fea5f961b2eb4b2076453d . The module also now has 0 rubocop warnings :)

I also have a post-patch set I'm working on that sanitizes platform on meterpreter sessions so we can remove all of the module workarounds.

**Comment by Megaeloelo** [comment]
Support android?

**Comment by bcook-r7** [comment]
This should already support android.

**Comment by timwr** [comment]
Thanks @bcook-r7 ,
I can test on a mac now. I was thinking of supporting linux via gnome but there are too many desktop managers on linux.

**Pull request merged**
