### PR TITLE
Upgrade to RSpec 3.X with recommended configuration

### PR DESCRIPTION
**Pull request by limhoff-r7**
MSP-13484
MS-673

This is an in-progress PR.  I've updated RSpec version in the `Gemfile` and turned on all the recommended, optional features, but that leaves failing specs.  Most significantly, RSpec 3 added verifying doubles, where using `allow(thing).to receive(method)` will fail if `thing` doesn't actually implement `method`.  This has shown we have specs that were testing instance methods on the class or vice versa or just making up interfaces.

This PR is being opened so the rest of the community can work on it and the work is not lost as 2015-11-13 is my last day at Rapid7.

**NOTE: The RSpec 3 upgrade blocks the Ruby-2.2 upgrade as RSpec 2.X is not compatible with the Ruby-2.2 standard library**

Related to #6015

### CODE REVIEW

**Comment by busterb** [comment]
Thanks for starting this @limhoff-r7! I started more conversions today, and man, the amount of copy-pasta required to remock things is unreal. There has to be a better way to share mocks between specs.

**Comment by jvazquez-r7** [comment]
@busterb , @limhoff-r7 https://github.com/limhoff-r7/metasploit-framework/compare/chore/MSP-13484/rspec-3...jvazquez-r7:review_6230?expand=1


An initial idea of using a shared_context `Msf::StringIO` to avoid redefining the StringIO callbacks again and again. Thoughts?

**Comment by busterb** [comment]
I like that idea, since there are a lot more places where these mocks can be shared.

**Comment by bcook-r7** [comment]
I'm going to close this for now and will re-PR when the rest of the specs are updated. Thanks a lot guys!

**Pull request closed without merging**
