### PR TITLE
Remove msfcli, please use msfconsole -x instead

### PR DESCRIPTION
**Pull request by wchen-r7**
msfcli is no longer supported, please use msfconsole.

Announcement on SecurityStreet:
[Weekly Metasploit Wrapup](https://community.rapid7.com/community/metasploit/blog/2015/01/23/weekly-metasploit-wrapup)
Posted by Tod Beardsley in Metasploit on Jan 23, 2015 11:57:05 AM

Tagging @limhoff-r7 - Hey Luke could you please take a look at this PR? I'm touching directory.rb and base.rb again, and I'm trying to make sure I'm not breaking anything.

### CODE REVIEW

**Comment by limhoff-r7** [comment]
Looks good to me.

**Comment by wchen-r7** [comment]
Cool thanks!

**Comment by wchen-r7** [comment]
Blog post about this is here:
https://community.rapid7.com/community/metasploit/blog/2015/07/10/msfcli-is-no-longer-available-in-metasploit

**Comment by wchen-r7** [comment]
@bcook-r7 Can I assign you for this? Wanna make sure we don't forget it.

**Comment by bcook-r7** [comment]
Merging now, the internal build process has been updated to handle this.

**Comment by wchen-r7** [comment]
Cool thanks!

**Pull request merged**
