### PR TITLE
Deregister RHOSTS instead of RHOST

### PR DESCRIPTION
**Pull request by mubix**
Fixes this module now that the RHOSTS changes are in effect.

### CODE REVIEW

**Comment by mubix** [comment]
This probably has to happen in other modules as well but I've only just started looking

**Comment by jrobles-r7** [comment]
## Release Notes

Fix `RHOST` deregister to `RHOSTS` in jenkins_udp_broadcast_enum module.

**Comment by busterb** [comment]
Actually, I'm not quite sure why this isn't merged yet, but it solves the problem generally: https://github.com/rapid7/metasploit-framework/pull/11393

**Comment by busterb** [comment]
Another note: please mark tickets like this with the `msf5` tag so they don't merge into the 4.x branch. Otherwise it has the opposite effect of re-enabling RHOST on the 4.x branch.

**Comment by busterb** [comment]
Verified #11393 would fix this too. I'll go ahead and land that.

**Comment by MMB127** [comment]
4

**Pull request merged**
