### PR TITLE
Remove the old Mimikatz extension

### PR DESCRIPTION
**Pull request by OJ**
## Overview

First of all **DON'T PANIC**. The most recent version of Mimikatz has been in the framework for a long time under the guise of the `kiwi` extension. Functionality is not being lost.

There is an associated [Metasploit Payloads PR here](https://github.com/rapid7/metasploit-payloads/pull/404).

This PR removes the old Mimikatz extension from MSF. The old extension hasn't been maintained for ages, and doesn't really serve any purpose given that the `kiwi` extension should support everything that Meterpreter supports. Keeping the old code lying around didn't make any sense.

Hence, we're culling it! Happy to hear everyone's concerns if they have any.

There was one module that made use of the extension, and I've ported that to `kiwi` (which required me to make some code changes behind the scenes). I have also added a temporary alias, so that if someone says `use mimikatz` they'll get a warning and it'll redirect them to `kiwi` instead.

This stuff obviously needs to be tested.

## Verification

- [x] Get a new Meterpreter session.
- [x] Type `use mimikatz`.
- [x] Validate that the warning appears and the `kiwi` extension is loaded.
- [x] Make sure that the `post/windows/gather/credentials/sso` module works.

Once the gem has been built:

- [x] Make sure the `mimikatz` binaries don't appear in the gem.
- [x] Make sure the `mimikatz` extension is no longer listed in the available extensions when hitting `tab` after typing `load` in the console.

### CODE REVIEW

**Comment by h00die** [comment]
I know that mimi has had a warning to use kiwi, but +1 for making/keeping the alias.

**Comment by adfoster-r7** [comment]
@OJ / @busterb Just confirming if the deletion of mimikatz should be aimed at master or the 6.x branch? 🤔

**Comment by OJ** [comment]
@adfoster-r7 I'd be happy with either.

**Review by smcintyre-r7 — APPROVED** [review]

**Comment by smcintyre-r7** [comment]
I tested this out and the changes all look good. Jeffrey helped me get a built metasploit-payloads gem from Jenkins which I used to validate that the mimikatz bins are missing and the tab completion does not suggest it any more.

Additionally, I tested the updated `post/windows/gather/credentials/sso` module on Windows 7 SP1 x64 and Server 2019 x64. In both cases it worked as expected.

While I am ready to merge this, I'm going to hold off until we sort through some details around where and how it should be merged since we're thinking it should go into the 6.x branch (which is why you'll see I've re-targeted this PR).

Thanks for all your work on this @OJ!

**Comment by OJ** [comment]
Thanks @smcintyre-r7 !

**Comment by smcintyre-r7** [comment]
This will be ready to be landed after the Python TLV crypt changes are in. I went to go land this but realized that bumping the payloads gem to 2.0.3 would break the Python payloads due to the changes they have that the framework is missing.

**Comment by OJ** [comment]
Cool thanks! I'll sort the conflicts out too.

**Comment by smcintyre-r7** [comment]
# Release Notes
This removes the Mimikatz Meterpreter extension in favor of the newer Kiwi extension. The `mimikatz` extension name is currently an alias for Kiwi that will print a warning message for period of time to allow users to smoothly transition to the new workflow. The `post/windows/gather/credentials/sso` module was also updated to use Kiwi instead of Mimikatz.

**Pull request merged**
