### PR TITLE
Namespace modules using full name instead of hex

### PR DESCRIPTION
**Pull request by wvu**
```
msf5 auxiliary(admin/2wire/xslt_password_reset) > pry
[*] Starting Pry shell...
[*] You are in auxiliary/admin/2wire/xslt_password_reset

[1] pry(#<Msf::Modules::Mod617578696c696172792f61646d696e2f32776972652f78736c745f70617373776f72645f7265736574::MetasploitModule>)> %w[617578696c696172792f61646d696e2f32776972652f78736c745f70617373776f72645f7265736574].pack('H*')
=> "auxiliary/admin/2wire/xslt_password_reset"
[2] pry(#<Msf::Modules::Mod617578696c696172792f61646d696e2f32776972652f78736c745f70617373776f72645f7265736574::MetasploitModule>)>
```

```
msf5 auxiliary(admin/2wire/xslt_password_reset) > pry
[*] Starting Pry shell...
[*] You are in auxiliary/admin/2wire/xslt_password_reset

[1] pry(#<Msf::Modules::Auxiliary__Admin__2wire__Xslt_password_reset::MetasploitModule>)>
```

### CODE REVIEW

**Comment by busterb** [comment]
Moving forward with this. Thanks, this will remove a lot of confusion during module debugging!

**Comment by busterb** [comment]
## Release Notes

Metasploit now stores references to modules using human-readable names internally, instead of hex-encoded strings. This facilitates debugging of modules, since it is now possible to easily read what module is affected when there is a backtrace in the logs or msfconsole's display.

**Comment by wvu-r7** [comment]
We may want to add additional checks (this slows down load time) or better tests (preferable despite slower tests) for whether a namespace module's name is reversible.

So far I couldn't find any case where reversibility is used, but I did test for it by leveraging Travis to check that every module name matches a regex and is reversible. The rest should be caught in review and `msftidy` once a rule is written for that.

Modules load as before, are reloadable, and are most importantly usable. That has not changed, as much as I can verify. Thanks for checking this out!

**Comment by wvu-r7** [comment]
I'll have an `msftidy` rule up for this shortly. It'll run via Travis, too, and we can kill two birds with one stone. I'd rather not kill birds, though.

**Comment by wvu-r7** [comment]
Sorry, I should have left this as WIP until tests were written external to my own. That was my fault. I had verified on my own and told you, but we want to automate this for future additions!

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/blob/a35fdab4d7e0ccb94f6b2d5d4f19e2a48795dfea/tools/dev/msftidy.rb#L257-L263

I forgot about this, heh.

**Pull request merged**
