### PR TITLE
Add module information to docs site

### PR DESCRIPTION
**Pull request by adfoster-r7**
Let's add the latest module information to the docs site as a quick way to explore Metasploit's available modules:

module-info

For now the links will take you directly to the module documentation, if there is any, otherwise it'll go to the module implementation

## Verification

- Build the site locally and verify it's sensical

### CODE REVIEW

**Comment by gwillcox-r7** [comment]
Woot super pumped to see this is coming to the docs site! This will help users out a lot and should make answering support questions I have gotten a lot easier 👍

**Comment by cgranleese-r7** [comment]
Every built and worked perfect for me 👍

**Comment by cgranleese-r7** [comment]
## Release Notes
This PR adds the latest module information to docs.metasploit.com as a quick way to explore Metasploit's available modules.

**Comment by gwillcox-r7** [comment]
Small note on this but atm searching for `password_reset` on the search bar doesn't return the entry for [auxiliary/admin/2wire/xslt_password_reset](https://github.com/rapid7/metasploit-framework/tree/master/modules/auxiliary/admin/2wire/xslt_password_reset.rb) yet searching for `2wire` does. Might need to adjust our search engine to be able to handle these file paths a bit better.

Other than that this looks great though, thanks!

**Pull request merged**
