### PR TITLE
Make msfupdate check user.name and user.email

### PR DESCRIPTION
**Pull request by cbrnrd**
This PR makes `msfupdate` check for `user.name` and `user.email` in the global git configuration. In order to suppress command output, a tempfile will be created with the output. The file will then be read, saved in a string, and deleted.

I've tested this on OS X 10.11, but it may be useful to know how other platforms go about it (especially Windows).

### CODE REVIEW

**Comment by busterb** [comment]
Curious what problem we're solving with this. I've discussed deleting msfupdate from the git repo here a few times in the past already, since it's a bit of an anachronism. Omnibus and Pro both package their own completely different implementations, and I believe Kali might as well. Having something that's then just a wrapper for `git pull` seems redundant now. Anyone have other thoughts?

**Comment by thecarterb** [comment]
I originally made this change because there was a `TODO` that said this should be enforced. But on the topic of deleting it from the repo, it may be good for just people who installed through git. Maybe add it to `.gitignore` and keep it on Pro and Omnibus. Maybe delete it from apt (Kali), as they can to an `apt-get update` etc.

**Comment by thecarterb** [comment]
@busterb Any update on this?

**Comment by busterb** [comment]
Seems fine, doing some testing now.

**Comment by busterb** [comment]
Thanks! I took the opportunity to remove some cruft (e.g. the old metasploit pro apt packages for Kali), and I simplified the checks you added here to just read the output directly from the git command, rather than using a temp file. It's faster, cleaner and simpler: 1892ac0c6c

**Comment by busterb** [comment]
## Release Notes

This adds some extra checks to msfupdate for Git users to ensure they have a proper environment setup for any local commits. It also removes some unused code and simplifies other checks.

**Pull request merged**
