### PR TITLE
Fix grammar in comments

### PR DESCRIPTION
**Pull request by todb-r7**
From @void-in, a slew of comment grammar fixes. There are also a few word changes in some `raise` methods. Will review this and land momentarily.

### CODE REVIEW

**Comment by todb-r7** [comment]
While it may appear that I've landed my own PR, the changes are all from @void-in, and I didn't see an associated PR.

**Comment by kernelsmith** [comment]
Is it ironic that the title has grammar misspelled or on purpose/hipster ironic? ;) LOL

**Comment by wwalker-r7** [comment]
@kernelsmith Haha, I had the same thought!

**Comment by wvu-r7** [comment]
It's actually from the commit: https://github.com/void-in/metasploit-framework/commit/51dd88114b0f19fba3581b628a18352a91d791a7. :P

**Comment by void-in** [comment]
@kernelsmith @wwalker-r7 @wvu-r7 I can save myself from the embarrassment by bragging that it was intentional! Sorry guys.

**Comment by kernelsmith** [comment]
No apologies necessary.  Just messing w/you. Before I went to college, I couldn't even spell engineer. Now I is one. 

Well...sorta. Plus there are more exceptions to rules in the English language than for taxes for wealthy companies. X86 is assembly is easier

**Pull request merged**
