### PR TITLE
Fix getprivs and getsystem

### LINKED ISSUE #8981: meterpreter getsystem timeout when elevating from local administrator
## Steps to reproduce

1. Connect on a Windows machine as a local administartor
2. Use the “run as administrator” function to get a meterpreter session (e.g. after having created a `windows/meterpreter/reverse_tcp` exe file with msfvenom)
3. Use the `getsystem` command from the meterpreter session to elevate privileges to `NT AUTHORITY\System`

Note: tested on Windows 7 32 and 64 bits, French editions.

## Expected behavior

As in Kali live (kali-linux-2016.2-amd64.iso), version `4.12.22-dev`:

```
meterpreter > sysinfo
Computer        : BROCCOLINI
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x86
System Language : fr_FR
Domain          : WORKGROUP
Logged On Users : 4
Meterpreter     : x86/win32
meterpreter > getuid
Server username: broccolini\admin
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter > getuid
Server username: AUTORITE NT\Système
meterpreter >
```

*Edit: it worked also on `kali-linux-2017.1-amd64.iso`, version `4.14.10-dev`.*

## Current behavior

The `getsystem` command timeouts, although it works.

```
meterpreter > sysinfo
Computer        : BROCCOLINI
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x86
System Language : fr_FR
Domain          : WORKGROUP
Logged On Users : 4
Meterpreter     : x86/windows
meterpreter > getuid
Server username: broccolini\admin
meterpreter > getsystem
[-] Error running command getsystem: Rex::TimeoutError Operation timed out.
meterpreter > getuid
Server username: AUTORITE NT\Système
meterpreter >
```

### Metasploit version

- `4.16.6-dev`, Kali rolling via apt
- `4.16.6-dev`, Kali LiceCD `kali-linux-2017.2-amd64.iso`
- `4.16.7-dev`, Arch Linux via pacman

### PR DESCRIPTION
**Pull request by OJ**
This is a fix for crap and stupid stuff that I did half way through the packet pivot code. I was working on some priv stuff at the same time, and when I realised that the work I was doing was not sensible as part of the packet pivot PR, I failed to revert my changes properly.

As a result I broke `getprivs` and `getsystem`. I am sorry. And I'm ashamed.

Associated Payloads PR here: https://github.com/rapid7/metasploit-payloads/pull/240

## Verification

- [ ] Build the associated Payloads from the PR: https://github.com/rapid7/metasploit-payloads/pull/240
- [ ] Deploy the binaries to the `data/meterpreter` folder.
- [ ] Spin up a new meterpreter session as a low priv user.
- [ ] Validate that `getprivs` works and **does not** time out.
- [ ] Validate that `getsystem` doesn't work, but **does not** time out.
- [ ] Spin up a new meterpreter session as a high priv user.
- [ ] Validate that `getprivs` works and **does not** time out.
- [ ] Validate that `getsystem` works and **does not** time out.

My apologies for the stupids. I suck.

Ping @busterb if we could get this landed pronto I'd really appreciate it. Thanks!

Fixes #8981

### CODE REVIEW

**Comment by busterb** [comment]
Well, those look like some great changes, looking forward to seeing them later!

**Comment by OJ** [comment]
Yeah the aim will be to:

1. Allow for listing privs and whether they're enabled/disabled.
1. Allow for toggling of specific privs.
1. Allow for toggling of all privs.

But yeah, that'll come later :)

**Comment by busterb** [comment]
## Release Notes

This fixes a hang that occurs with the getsystem and getprivs commands.

**Comment by busterb** [comment]
Looks like I missed landing the other side of the PR properly, will get to that soon...

**Comment by kernelsmith** [comment]
slapshot_you_feel_shame

**Comment by busterb** [comment]
Followup - I got to it a few weeks ago.

**Comment by h00die** [comment]
but can we +1 a slapshot reference a little more?!

**Pull request merged**
