### PR TITLE
post/windows/manage/autoroute Improvements

### PR DESCRIPTION
**Pull request by sn0wfa11**
## Overview

This PR is in response to Issue #6781 where @wchen-r7 noticed that the autoadd CMD option was not adding all possible routes. As previously programmed, autoadd was only looking at the host's routing table to gather potential routes. In certain situations, this would miss other potential routes. The issue is observed in the case of a full traffic VPN that does not put a route to its subnet in the host's routing table since all traffic goes through the VPN's network adapter.
## Fix

The issue was fixed by adding functionality for autoadd to search through the host's network interface list to find additional potential routes. If these routes are not already included in Metasploit's routing table, they are added.

Note: Since I was unable to locate functions to convert an IPv4 address and netmask to a corresponding subnet "network" in the Framework, I wrote them for this module. If they do exist in the Framework, I will drop off the ones in this module. Or if they do not exist in the Framework, and it is desirable to move them to a Framework library for other modules to use, I am good with that. I would need to know which library is best for them.
## Additional Improvements

A new CMD option "default" was added to this module. This option will add a default route (0.0.0.0/0.0.0.0) to Metasploit's routing table for the associated Meterpreter session. This forces all TCP/IP traffic; not otherwise covered in the routing table, to be routed through that session. A default route useful in situations where a full traffic VPN is used and the VPN server does the routing to private networks. In this situation, it is likely that the compromised host's routing table and interface list would not include routes or references to these networks. The default route will push the routing off to the server allowing those networks to be accessed, pending you know where to look. The default route can also be used to browse the Internet as the compromised host using a Socks4a proxy and Proxychains.

Also, included in this PR is the addition of a documentation file for this module (autoroute.md). The file contains information on using this module and information on pivoting using a Socks4a server and Proxychains.
## Verification of Fix for Issue

A Meterpreter session was initiated on a machine running Windows 10. This host has NetMotion's Mobility VPN installed and set up for full traffic. (Also tested on Windows 7 using the same VPN.)

Before this update the results of this module using autoadd were as follows:

```
[*]     Running command run post/windows/manage/autoroute
[*] Running module against SURFACE
[*] Searching for subnets to autoroute.
[+] Route added to subnet 192.168.1.0/255.255.255.0
[+] Route added to subnet 192.168.86.0/255.255.255.0
[+] Route added to subnet 192.168.184.0/255.255.255.0
```

This is missing a route to the subnet associated with the VPN since it is not in the routing table as can be seen from the NetMotion interface.

```
Interface 18
============
Name         : NetMotion Virtual Network Adapter (NMVNIC)
Hardware MAC : 4e:4d:a5:91:ea:8e
MTU          : 1500
IPv4 Address : 10.10.239.210
IPv4 Netmask : 255.255.255.0
IPv6 Address : fe80::3107:4f8f:74dd:5555
IPv6 Netmask : ffff:ffff:ffff:ffff::
```

After this update the results of autoadd are as follows:

```
[*]     Running command run post/windows/manage/autoroute
[*] Running module against SURFACE
[*] Searching for subnets to autoroute.
[+] Route added to subnet 192.168.1.0/255.255.255.0 from host's routing table.
[+] Route added to subnet 192.168.86.0/255.255.255.0 from host's routing table.
[+] Route added to subnet 192.168.184.0/255.255.255.0 from host's routing table.
[+] Route added to subnet 10.10.239.0/255.255.255.0 from NetMotion Virtual Network Adapter (NMVNIC).
```

Testing on other VPN solutions is requested. Since this looks at all of the network interfaces, it should find the routes regardless of which VPN solution is used.
## Verification of Default Route

For this, I started a Windows Meterpreter session on a host with a different public IP address from my Kali machine. The module was run on the session using the "default" CMD option. A default route was added. I used the Socks4a module with Proxychains and Firefox to visit www.ipchicken.com to verify that the reported external IP address belonged to the compromised host. A description of how to set this up is in the documentation file included in this PR.

### CODE REVIEW

**Comment by wchen-r7** [comment]
This has improved the issue I was complaining about in #6781, plus there is documentation explaining about how to use it, so it's awesome. Thanks @jhale85446, I think I'll land it.

**Comment by jhale85446** [comment]
@wchen-r7, you are welcome! It's my pleasure to be able to work on such a great project.

**Comment by void-in** [comment]
@jhale85446 That is a great module. Shouldn't this line:
```ruby
if subnet =~ /^224\.|127\./
   return false
```
be
```ruby
if subnet =~ /^224\.|^127\./
   return false
```
? Because 127 can occur in the middle of a routable address.

**Comment by jhale85446** [comment]
@void-in, yes you are correct. Thank you for catching that. @wchen-r7, are you able to make this small change or should I do another PR?

**Comment by wchen-r7** [comment]
@jhale85446 Actually, could you please make the PR? That way I can ensure it lands ASAP. Thanks!

**Comment by jhale85446** [comment]
@wchen-r7, see PR #6791. @void-in, thank you again for pointing this out!

**Comment by wchen-r7** [comment]
@jhale85446 awesome, thanks!

**Comment by tdoan-r7** [comment]
Thanks for the module docs @jhale85446! Great work.

**Comment by jhale85446** [comment]
@tdoan-r7, you are welcome. Thank you for the feedback.

**Pull request merged**
