### PR TITLE
Fix winrm_login module

### PR DESCRIPTION
**Pull request by red0xff**
## The bug

The issue was reported by a few users here [here](https://github.com/rapid7/metasploit-framework/issues/6398#issuecomment-508536604), I tried running Wireshark to troubleshoot the problem, and noticed that the issue seems to be coming from the Content-Length being 0, on successful login, the server returns (HTTP 411 - Length Required) and not (200 OK).

The issue is closed, but it's still not working as tested (on Windows 7 x64 and Windows 8)

## My workaround
 
In the `HTTP` login scanner, I added an argument `success_codes`, which is an array of HTTP codes that indicate login success, with a default value of `[200]`, from the `winrm` login scanner, I made an override on the method, to indicate that `411` also denotes success in the case of WinRM.

## Verification

List the steps needed to make sure this thing works

- [ ] Start `msfconsole`
- [ ] `use auxiliary/windows/winrm/winrm_login`
- [ ] ... (set parameters like wordlists etc.)
- [ ] `run`
- [ ] **Check if it reports the correct credentials as correct**

## First PR

This is my first pull-request to the project, any feedback is welcome, if it would be better to find another workaround, craft requests that yield a response code of `200 OK`, feel free to comment below. (I didn't check the details of the protocol specifications of `WinRM`)

### CODE REVIEW

**Comment by bcoles** [comment]
A few thoughts.

I'm not sure if this is the best approach, but presuming that it is, parsing the `success_codes` should probably do some validation to ensure that the provided argument is an Array, or maybe perform some int/string->array magic if a integer or string is provided. Maybe.

Alternatively, maybe we'll want to pass other options to `attempt_login` in the future. There may also be some merit to using an options Hash or keywords arguments rather than an optional Array.

It may be useful to augment the `send_request` method and `attempt_login` method to allow the caller to specify additional HTTP request attributes - not only the HTTP method and URI path - such as HTTP headers or request body. Presumably, specifying a `Content-Length` of zero (ie, an empty request body), would prevent the `411` response.

The `attempt_login` method is not widely used in the Framework - it's only used for login scanner modules, by protocol libraries which are [rarely ever updated](https://github.com/rapid7/metasploit-framework/tree/master/lib/metasploit/framework/login_scanner). It would certainly be nice to gather "proof" of a successful login based on more than the HTTP response code. Requiring `200` doesn't seem very flexible. In particular, there are many applications which will respond with `302` for a correct login unless certain request attributes are present (correct headers, correct referer header, correct URI path, ...)

**Comment by red0xff** [comment]
> Alternatively, maybe we'll want to pass other options to `attempt_login` in the future. There may also be some merit to using an options Hash or keywords arguments rather than an optional Array.
> 
> It may be useful to augment the `send_request` method and `attempt_login` method to allow the caller to specify additional HTTP request attributes - not only the HTTP method and URI path - such as HTTP headers or request body. 

I agree that it could be useful to detect login success based on more parameters, the HTTP Response Code, headers, parts of the response body / regex matching success or failure of logins etc., will require some design decisions through.

> Presumably, specifying a `Content-Length` of zero (ie, an empty request body), would prevent the `411` response.

No, [from my testing](https://camo.githubusercontent.com/8f2db104dcc6207a65ff51cef438400dc9f95d17/68747470733a2f2f692e696d6775722e636f6d2f4c724e42586b512e706e67), you can see that even if the `Content-Length: 0` header is sent in the request, the return code is `411`.

> The `attempt_login` method is not widely used in the Framework - it's only used for login scanner modules, by protocol libraries which are [rarely ever updated](https://github.com/rapid7/metasploit-framework/tree/master/lib/metasploit/framework/login_scanner). It would certainly be nice to gather "proof" of a successful login based on more than the HTTP response code. Requiring `200` doesn't seem very flexible. In particular, there are many applications which will respond with `302` for a correct login unless certain request attributes are present (correct headers, correct referer header, correct URI path, ...)

Yes I agree on these points for the `http_login` module, but in the case of WinRM enumeration (which is what this PR attempts to fix), the possible solutions are checking just the response codes like I did, or fixing the Content-Length to 1 or whatever yields `200 OK` on success, I'm also not sure if the first is the best approach, if the community thinks it isn't, I can try to do it differently.

We could perhaps accept this fix for the winrm module, work on `http_login` to accept more success conditions and update the winrm scanner accordingly (to use the new HTTP `attempt_login` method).

**Comment by acammack-r7** [comment]
I think being able to specify the status codes with a keyword argument would be handy from an API perspective. I would be hesitant to add `411` to the list of success codes, though, since that could generate false positives from any service that requires a `Content-Length` with a `POST`. The login scanners are often run against arbitrary services and should resist reporting false positives.

**Comment by red0xff** [comment]
> I think being able to specify the status codes with a keyword argument would be handy from an API perspective. I would be hesitant to add `411` to the list of success codes, though, since that could generate false positives from any service that requires a `Content-Length` with a `POST`. The login scanners are often run against arbitrary services and should resist reporting false positives.

I only added `411` to the list of success codes in the case of WinRM login scanning (to `winrm.rb`, not `http.rb`), shouldn't impact other services that use the HTTP login scanner (as the default is still to accept only `200` as a success code, like it was the case before the commits), not sure if there are cases where it could yield false positives in the case of WinRM, tested it with Windows 7, 8, 10, and all of them return `HTTP 411` when `winrm_login` succeeds.

Any better fix for the case of `winrm_login` ?

**Comment by acammack-r7** [comment]
Right, WinRM services return that, but when this scanner is run against not-WinRM services it could falsely report a success when that application was just throwing an error. All the various HTTP login scanners are meant to be able to be run against any and all unknown HTTP services and not return a positive result unless the authentication succeeds. Since this scanner doesn't run against only WinRM all the time, we must take care to not add a condition that could confuse another application's error for this applications success.

If changing the `Content-Length` header of the `POST` yields a `200`, I think that would be the best approach. The quickest way to override the `Content-Length` header would be to override the `send_request` method like:
```ruby
def send_request(opts)
  opts['headers'] ||= {}
  opts['headers']['Content-Length'] = 1
  super(opts)
end
```

**Comment by acammack-r7** [comment]
These new changes look great, @red0xff. Thanks!

**Comment by dwelch-r7** [comment]
# Release Notes

Adds a fix for the winrm login module

**Pull request merged**
