### PR TITLE
Add HEADERS to php_eval module

### PR DESCRIPTION
**Pull request by brimstone**
I needed a way to pass in cookies for a CTF. I pulled this functionality from php_include.rb

### CODE REVIEW

**Review by sempervictus — COMMENTED** [review]
Nice! Before Egypt gets to you - a small nitpick, could you sub &&/and please? I _think_,the official line on this is English versions of operators are preferred to C style.

**Comment by bcoles** [comment]
@sempervictus rubocop disagrees with you. `&&` is preferred over `and`.

**Comment by sempervictus** [comment]
To quality a bit - it disagrees with my statement. There's stuff in my fork which would make Egypt's beard fall out from syntactic sugar. Personally, I prefer this because it looks like what it is - a logical operator. I withdraw my suggestion unless the style draws ire from up above, in which case, blame and assign me to fix them all.

**Comment by brimstone** [comment]
yeah, rubocop wanted to change all sorts of lines in that file. I tried to limit it to just the bits I want to add. Let me what needs to be changed and I can change it. Thanks!

**Comment by busterb** [comment]
We officially prefer `&&` and `||` because the english versions have weird non-standard precedence rules (yes, they are different than you would expect!). Beware of converting without thinking about it a bit first, for that reason.

**Comment by brimstone** [comment]
Is there anything I can do to help land this?

**Comment by busterb** [comment]
Makes sense to me, since this is a general utility module.

**Comment by busterb** [comment]
## Release Notes

This adds a new `HEADERS` option to the php_eval module, which is useful for injecting arbitrary headers into requests when targeting web applications.

**Comment by busterb** [comment]
Thanks @brimstone !

**Pull request merged**
