### PR TITLE
Rework aux/scanner logic to remove duplicate logic, fix checks

### PR DESCRIPTION
**Pull request by busterb**
This fixes issues with scanner logic specifically in MSF5 where the 'check' method is not working correctly due to some implicit global state not being set. Instead of returning the global state to the base module classes, this merges the logic for running 'run_check' and 'run_host' so that both set the same state directly in the scanner logic, no magic required. Since 'run_single' is just a special case of 'run_batch' with a batch size of 1, this also merges the logic between those two paths.

## Verification

- [ ] Start `msfconsole`, run many aux/scanner modules through their paces
- [ ] **Verify** that multi scanners work properly with run and check
- [ ] **Verify** that single scanners work properly with run and check

This is an earliy WIP that worked for me with the SSL scanners, but I don't know every edge-case or oddball module that might be stretching the boundaries of what this interface was intended to do.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Taking a look at this today. Thanks for the ping!

**Comment by wvu-r7** [comment]
Preliminary test using Heartbleed looks like the module's `CheckCode` values aren't being used.

```
msf5 auxiliary(scanner/ssl/openssl_heartbleed) > check

[*] 127.0.0.1:443         - Scanned 1 of 1 hosts (100.0% complete)
[-] 127.0.0.1:443 Check failed: The state could not be determined.
msf5 auxiliary(scanner/ssl/openssl_heartbleed) > run

[+] 127.0.0.1:443         - Heartbeat response with leak, 65535 bytes
[*] 127.0.0.1:443         - Scanned 1 of 1 hosts (100.0% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/ssl/openssl_heartbleed) >
```

https://github.com/rapid7/metasploit-framework/blob/427080ad5c0c5c2d8c1e02873e41dd1ce1e46cd5/lib/msf/ui/console/module_command_dispatcher.rb#L226-L249

**Review by wvu — CHANGES_REQUESTED** [review]
`check` functionality still appears broken in at least Heartbleed. Please verify. Thanks!

**Comment by busterb** [comment]
Going to close this while I find some time to rework it.

**Comment by wvu-r7** [comment]
No worries. I can take a look when I don't overcommit myself!

**Pull request closed without merging**
