### PR TITLE
Update copyright notice to 2016 [ci skip]

### PR DESCRIPTION
**Pull request by Atul9**
Updates LICENSE with the current year.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Don't forget ```COPYING```.

**Comment by wvu-r7** [comment]
@todb-r7: Wanna handle this one?

**Comment by todb** [comment]
Yeah i'll take it. I meant to do with with the mailmap update. Drat!

>

-- 
"Tod Beardsley" <todb@packetfu.com>
+1-512-438-9165
https://keybase.io/todb

**Comment by todb-r7** [comment]
> No description provided.

so sad.

**Comment by wvu-r7** [comment]
Thanks, @todb-r7.

**Pull request merged**
