### PR TITLE
bump metasploit to ruby 2.4

### PR DESCRIPTION
**Pull request by bcook-r7**
This is a work-in-progress to get us updated for all upstream Ruby 2.4 compatibility work. See #7814 

Gems in need of updating:

 - [ ] octokit-4.6.2
     The master branch is updated, no release yet

 - [ ] pry-0.10.4
    The master branch is updated, no release yet

 - [ ] method_source-0.8.2
     The master branch is updated, no release yet

### CODE REVIEW

**Comment by FireFart** [comment]
@bcook-r7 are the changes backwards compatible to older ruby versions? :thought_balloon:  I asked myself the same question when upgrading another project to ruby 2.4 because there are a lot of (breaking) changes required

**Comment by busterb** [comment]
I included ruby 2.3.3 in travis, been monitoring specs for both.

**Comment by busterb** [comment]
This now tests Ruby 2.1-2.4, all green with rspec and no warnings on startup now with Ruby 2.4. Still needs some testing to suss out any other possible issues.

**Comment by busterb** [comment]
Reenabling Ruby 2.1 in Travis found a bug in one of the tests that every later Ruby version failed to identify. It was treating http://:80 as a valid URI, when it wasn't.

**Comment by busterb** [comment]
At the moment, we have to point to PRs or branches for six upstream gems.

- [ ] gem 'activerecord', github: 'rails/rails', branch: '4-2-stable'
  This might be OK to keep longer-term.

 - [ ] gem 'bit-struct', github: 'busterb/bit-struct', branch: 'ruby-2.4'
       This is my local fork. We should look at migrating off of bit-struct if possible, since there are better maintained alternatives now:

 - [ ] gem 'metasm', github: 'busterb/metasm', branch: 'ruby-2.4'
       I should PR this to metasm and we can do a release since @egypt has gem ownership on rubygems

 - [ ] gem 'thread_safe', github: 'nomoon/thread_safe', branch: 'integer_unification'
       This is waiting in upstream's PR queue, no release yet

 - [ ] gem 'rb-readline', github: 'larskanis/rb-readline', branch: 'no-more-fixnum'
       This is waiting in upstream's PR queue, no release yet

 - [ ] gem 'windows_error', github: 'rapid7/windows_error', branch: 'fix-ruby-2.4'
       We can self-release this

**Comment by busterb** [comment]
The speed improvements do shave about 0.30s from startup time locally (3.9s average here, vs 4.2s)

**Comment by busterb** [comment]
Next gems on the hit list:

```
~/.rvm/gems/ruby-2.4.0@metasploit-framework/gems$ grep -R Fixnum .|grep -v "#"|grep rb|grep -v " \* "|grep -v spec|grep -v test|cut -d'/' -f2|uniq
octokit-4.6.2
yard-0.9.8
ffi-1.9.17
simplecov-0.12.0
childprocess-0.5.9
arel-6.0.4
jsobfu-0.4.1
rubyzip-1.2.0
packetfu-1.1.11
diff-lcs-1.2.5
pry-0.10.4
msgpack-1.0.2
json-2.0.3
shoulda-matchers-3.1.1
rex-text-0.2.10
method_source-0.8.2
rex-sslscan-0.1.1
rex-mime-0.1.1
```

**Comment by busterb** [comment]
Metasm PR: https://github.com/jjyg/metasm/pull/25

**Comment by busterb** [comment]
packetfu PR: https://github.com/packetfu/packetfu/pull/161

**Comment by busterb** [comment]
OK, everything that we need now either is updated and released with a new gem, the fix is in master and we're waiting for a new release, or there is a PR in flight.

And now, we wait!

**Comment by nomoon** [comment]
Re: lsegal/yard#105, the 2.4 Fixnum/Bignum deprecation warning will not be fixed, though it should only appear in Yard's tests and when Yard parses code referring to the deprecated classes.

**Comment by busterb** [comment]
Thanks, rebased and pointing back to the yard master branch now.

**Comment by busterb** [comment]
I'm splitting this into two PRs, one with fixes for things we control, the other with fixes for things managed upstream. This will be the upstream PR.

**Comment by busterb** [comment]
We're now down to just 10 upstream projects that need to be updated, from > 20 in the beginning!

**Comment by h00die** [comment]
Read: "point to new Pikachu", got confused.

**Comment by simonoff** [comment]
rubyzip done. But not released yet

**Comment by busterb** [comment]
thanks @simonoff

**Comment by busterb** [comment]
Only 8 upstream projects left and we'll be ready.

**Comment by Auxilus** [comment]
How many upstreams left now ?

**Comment by busterb** [comment]
6 left now. Only 2 more PRs need to be landed.

**Comment by busterb** [comment]
We're down to 4 gems left. I'm working on migrating the BitStruct code to use use BinData, which I think should make this PR safe to land at last. The remaining things we're waiting on are development dependencies.

**Comment by busterb** [comment]
ok, bit-struct is now removed and replaced with bindata, down to 3 gems.

is pry now obsolete since ruby 2.4 has Binding#irb ?

**Comment by busterb** [comment]
I moved the bit-struct fixes into separate PRs since they were kind of big to be reviewed here.

**Comment by busterb** [comment]
## Release Notes

This adds extended Ruby version compatibility checking in TravisCI as well as bumps base Ruby to 2.4.1. We will probably remove support for Ruby 2.1/2.2 at some point in the future.

**Pull request merged**
