### PR TITLE
Feature/msp 12244/postgres pass the hash

### PR DESCRIPTION
**Pull request by thelightcosine**
This PR adds Pass-the-Hash functionality for Postgres. 
- The auxiliary/scanner/postgres/postgres_login module now can reuse postgresmd5 hashes from the database or recognize a postgres md5 hash when given in the format 'md5<hash>' as a password. 

-The postgres_hashdump module also now stores postgres hashes into this model
-  The postgres JtR hash cracker also uses the PostgresMD5 model now for finding the right hashes to crack

VERIFICATION STEPS
- [x] Land PR https://github.com/rapid7/metasploit-credential/pull/98
- [x] `bundle install` to get the latest version of the gem
- [x] commit the gemfile.lock change
- [x] OR ping me and I'll do the above two lines and push it.
- [x] start msfconsole
- [x] `use auxiliary/scanner/postgres/postgres_login`
- [x] target a metasploitable2 instance
- [x] set username to `postgres`
- [x] set password to `md53175bce1d3201d16594cebf9d7eb3f9d`
- [x] `run`
- [x] VERIFY that it logged in with the hash
- [x] `creds`
- [x] VERIFY you see the cred listed
- [x] VERIFY the cred has a private type of `Postgres Md5`
- [x] `use auxiliary/analyze/jtr_postgres_fast`
- [x] `run`
- [x] VERIFY it cracks the hash successfully
- [x] clear your workspace
- [x] `use auxiliary/scanner/postgres/postgres_hashdump`
- [x] target the metasploitable box again
- [x] set username to `postgres`
- [x] set password to `postgres`
- [x] `run`
- [x] VERIFY you see the hash get snarfed
- [x] `creds`
- [x] VERIFY you see both the password and hash saved in the creds table

### CODE REVIEW

**Comment by hmoore-r7** [comment]
Minor nitpick on the PTH format, any chance it could be changed to ```md5:<password hash>``` (versus without a colon). It makes it a little easier to figure out what is going on by looking at it.

**Comment by dmaloney-r7** [comment]
@hmoore-r7 that format is exactly how it is stored in the postgres database. that's why it's that way

**Comment by dmaloney-r7** [comment]
oops, bad Dave screwing up a regex

**Comment by todb-r7** [comment]
Note, the Travis tests will fail out of the gate until the gem is actually updated.

**Comment by dmaloney-r7** [comment]
arg travis, wtf

**Comment by wvu-r7** [comment]
lol travis

**Pull request merged**
