### PR TITLE
Test metasploit payloads bump

### PR DESCRIPTION
**Pull request by adfoster-r7**
Testing https://github.com/rapid7/metasploit-payloads/pull/718

### CODE REVIEW

**Comment by smcintyre-r7** [comment]
We'll want to bump this from 174 to 175 once rapid7/metasploit-payloads#719 is landed and released. Thanks for catching this.

**Comment by adfoster-r7** [comment]
Will close this for now, thanks!

**Comment by adfoster-r7** [comment]
> Will close this for now, thanks!

Small update; Just updated this PR to instead run your branch ahead of time to run the tests before it gets merged in and released as a new version

Looks like everything passes against your new code :+1:

image

(The PHP tests hanging are unrelated)

**Comment by adfoster-r7** [comment]
Will close this again for now help keep the PR queue down, but it can be used as a future reference on how to test metasploit-payloads/mettle against forks before they're merged in and released. We'll likely wire this workflow up to the metasploit-payloads/mettle/ruby_smb repos in the future by default to make it not be a separate effort to make a PR to this repo ahead of time before landing things

**Pull request closed without merging**
