### PR TITLE
Add empty default vprint value

### PR DESCRIPTION
**Pull request by g0tmi1k**
See https://github.com/rapid7/metasploit-framework/pull/5701#discussion_r34413585

### CODE REVIEW

**Comment by g0tmi1k** [comment]
Skipped one...
```
root@kali ~/Metasploit-Framework$ grep -R 'vprint.*("")'                                                                                                                 vprint 
modules/post/windows/gather/credentials/filezilla_server.rb:    vprint_line("")
modules/post/windows/gather/credentials/filezilla_server.rb:      vprint_line("")
root@kali ~/Metasploit-Framework$ 
```

...Else this will clash with https://github.com/rapid7/metasploit-framework/pull/5701.

**Comment by wvu-r7** [comment]
Hah, I fixed ```filezilla_server``` on my own and THEN noticed the conflict. :)

**Comment by wvu-r7** [comment]
Looks like the other implementations of ```*print_*``` don't pad the ```=```. :/

**Comment by g0tmi1k** [comment]
Thanks! Fixing the other PR now =).

**Pull request merged**
