### PR TITLE
Remove deprecated modules udp_probe wp_ninja_forms

### PR DESCRIPTION
**Pull request by todb-r7**
These two modules are well overdue for removal, per their deprecation()
dates.

## Verification

List the steps needed to make sure this thing works

- [ ] See udp_probe's `deprecate()` call indicating Nov 23, 2016.
- [ ] See wp_ninja_forms_unauthenticated_file_upload's `deprecate()' call indicating Dec 10, 2016.
- [ ] Ask Wolfram Alpha, [how many days since Dec 10, 2016](http://www.wolframalpha.com/input/?i=how+many+days+since+December+10,+2016).
- [ ] Note that the answer is greater than 0.
- [ ] **Verify** that [Metasploit Pro](https://www.rapid7.com/products/metasploit/download/pro/) doesn't rely on `udp_probe` any more for stock Discovery scans, and that it's correctly using the `udp_sweep` module as suggested.
- [ ] **Verify** that these modules are, in fact gone.

I also checked if there were any artifacts left over in `documenation/modules` -- there aren't,

### CODE REVIEW

**Comment by todb-r7** [comment]
I'm guessing this is more of a 'fix' than an 'enhancement,' but it should definitely get release-noted. There are some old docs floating around the internet about udp_probe, i expect.

**Comment by todb-r7** [comment]
It'd be kinda cool to have a CI test for deprecated modules, but it happens so rarely it's probably not worth the effort.

**Comment by todb-r7** [comment]
You know what, I'm going to [take that guy's advice](https://twitter.com/todb/status/943979662308528128) and stick a `delayed` tag on here so it doesn't get landed until like Jan 5 or so.

**Comment by wvu-r7** [comment]
Please deconflict with #9317. Thanks.

**Comment by busterb** [comment]
Closing because this completely duplicates #9317 , and discusses the community impact of removing modules like this as well.

**Pull request closed without merging**
