### PR TITLE
Fix indentation, how locations adds values and clean code

### PR DESCRIPTION
**Pull request by AgoraSecurity**
Just a small improvement for the module.

### CODE REVIEW

**Comment by AgoraSecurity** [comment]
The Travis CI build failed. Apparently it was a timeout. Is there a way to retry the build?

**Comment by AgoraSecurity** [comment]
Any comments?

**Comment by busterb** [comment]
I'll take a look. Thanks for the cleanup.

**Comment by busterb** [comment]
Thanks. I tidied it up a bit more with: 85df247c84
Let me know if there are any other changes needed. Thanks!

**Pull request merged**
