### PR TITLE
vulns command with -R --rhosts

### PR DESCRIPTION
**Pull request by sekritskwurl**
I wanted support for the -R switch to the vulns command. 
Let me know if this doesn't work or breaks something I don't know about. I tested it out and it seems to work fine. But you never know.

### CODE REVIEW

**Comment by wvu-r7** [comment]
Ahh, I remember this being requested a long time ago. Glad you didn't forget like I did!

**Comment by sekritskwurl** [comment]
yeah i saw mubix post it in irc a long time ago and have had use cases for it since.  

failed is bad correct.. i tested it against some hosts. I'm not exactly sure what Travis CI does.

**Comment by wvu-r7** [comment]
Hold on. I'm sending you some fixes.

**Comment by wvu-r7** [comment]
@sekritskwurl: Please test and merge the PR at sekritskwurl#1.

**Comment by sekritskwurl** [comment]
Alright, round 2. /me crosses fingers

**Comment by wvu-r7** [comment]
I moved the ```set_rhosts_from_addrs```. \*Should\* be okay.

**Comment by sekritskwurl** [comment]
i just tested it with just a stock msfconsole and it seemed to work just fine. I am not as familiar with this development stuff as I could be.

**Comment by wvu-r7** [comment]
It's all cool. I think we're good to go! Thanks!!

**Comment by sekritskwurl** [comment]
No thank you for your help. This has been something on my mind for a while. :)

**Comment by mubix** [comment]
w00tw00t

**Pull request merged**
