### PR TITLE
update userlist to ubuntu 18.04 lamp & Others

### PR DESCRIPTION
**Pull request by h00die**
Updates the `unix_users.txt` file to include all defaults identified on a fresh Ubuntu Server 18.04 w/ lamp installed as identified through the apache userdir mod.

### CODE REVIEW

**Comment by h00die** [comment]
https://github.com/nmap/nmap/issues/1902

**Comment by h00die** [comment]
added delayed to look at the diff w/ https://gist.github.com/nnposter/d90be60f31c3980c953fe2ff59c086e6

**Comment by h00die** [comment]
incorporated the extras from @nnposter 's list on the nmap thread.
As they are discussing, while this is a 'complete'-ish list, do we want to keep them all?  While they may hit on the apache userdir module (original intention), this list just grew by ~30%, and many of those accounts are low value, but also many already on the list are that way as well.

**Comment by tperry-r7** [comment]
# Release Notes
Update the <code>unix_users.txt</code> file to include all defaults identified on a fresh Ubuntu Server 18.04 with lamp installed as identified through the apache userdir mod.

**Pull request merged**
