### PR TITLE
smb_enumshares - added Permission col for CSV and table output

### PR DESCRIPTION
**Pull request by fruh**
Module: auxiliary/scanner/smb/smb_enumshares new features:
- it tests for writable, readable dirs, files
- added new file types DIRRO (readonly), DIRHID (hidden)

Console:

```
msf auxiliary(smb_enumshares) > show options 

Module options (auxiliary/scanner/smb/smb_enumshares):

   Name             Current Setting  Required  Description
   ----             ---------------  --------  -----------
   LogSpider        1                no        0 = disabled, 1 = CSV, 2 = table (txt), 3 = one liner (txt) (accepted: 0, 1, 2, 3)
   MaxDepth         999              yes       Max number of subdirectories to spider
   RHOSTS           192.168.100.103  yes       The target address range or CIDR identifier
   SMBDomain        WORKGROUP        no        The Windows domain to use for authentication
   SMBPass                           no        The password for the specified username
   SMBUser                           no        The username to authenticate as
   ShowFiles        true             yes       Show detailed information when spidering
   SpiderProfiles   true             no        Spider only user profiles when share = C$
   SpiderShares     true             no        Spider shares recursively
   THREADS          1                yes       The number of concurrent threads
   USE_SRVSVC_ONLY  false            yes       List shares only with SRVSVC

msf auxiliary(smb_enumshares) > run

[-] 192.168.100.103:139 - Login Failed: The SMB server did not reply to our request
[*] 192.168.100.103:445 - Windows 8.1  (Unknown)
[+] 192.168.100.103:445 - ADMIN$ - (DS) Remote Admin
[+] 192.168.100.103:445 - C$ - (DS) Default share
[+] 192.168.100.103:445 - IPC$ - (I) Remote IPC
[+] 192.168.100.103:445 - Users - (DS) 
[+] 192.168.100.103:445 \\VBOXWIN8\Users
====================================

 Type    Name     Created              Accessed             Written              Changed              Size
 ----    ----     -------              --------             -------              -------              ----
 DIRHID  Default  08-22-2013 08:21:44  08-22-2013 17:13:49  08-22-2013 17:13:49  03-16-2015 23:30:44  0
 DIRRO   Public   08-22-2013 08:21:44  08-22-2013 10:17:27  08-22-2013 10:17:27  03-24-2015 14:01:51  0
....

```

Example of CSV output:

```
IP Address,Type,Share,Path,Name,Created,Accessed,Written,Changed,Sizefff,Permission
"192.168.100.103","Unknown","Users","\Public\","Libraries","08-22-2013 10:17:25","08-22-2013 10:17:27","08-22-2013 10:17:27","03-24-2015 14:01:51","0","readable"
"192.168.100.103","Unknown","Users","\Public\","Music","08-22-2013 10:17:25","08-22-2013 10:17:27","08-22-2013 10:17:27","03-24-2015 14:01:51","0","readable"
"192.168.100.103","Unknown","Users","\Public\","Pictures","08-22-2013 10:17:25","08-22-2013 10:17:27","08-22-2013 10:17:27","03-24-2015 14:01:51","0","readable"
"192.168.100.103","Unknown","Users","\Public\","Videos","08-22-2013 10:17:25","03-24-2015 14:02:19","03-24-2015 14:02:19","03-24-2015 14:02:19","0","readable"
"192.168.100.103","DIR","Users","\Default\AppData\","Local","08-22-2013 10:17:25","08-22-2013 09:23:42","08-22-2013 09:23:42","03-16-2015 23:30:44","0","readable"
"192.168.100.103","DIR","Users","\Default\AppData\","Roaming","08-22-2013 10:17:25","08-22-2013 10:17:25","08-22-2013 10:17:25","03-16-2015 23:30:44","0","readable"
...
```

Example of table output:

```
Spidered results for 192.168.100.103.
=====================================

 IP Address       Type    Share  Path                                                    Name                            Created              Accessed             Written              Changed              Size  Permission
 ----------       ----    -----  ----                                                    ----                            -------              --------             -------              -------              -------  ----------
 192.168.100.103  DIRHID  Users  \                                                       Default                         08-22-2013 08:21:44  08-22-2013 17:13:49  08-22-2013 17:13:49  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \                                                       Public                          08-22-2013 08:21:44  08-22-2013 10:17:27  08-22-2013 10:17:27  03-24-2015 14:01:51  0        readable
 192.168.100.103  DIRHID  Users  \Default\                                               AppData                         08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Desktop                         08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Documents                       08-22-2013 10:17:25  08-22-2013 09:23:42  08-22-2013 09:23:42  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Downloads                       08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Favorites                       08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Links                           08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Music                           08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Pictures                        08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIR     Users  \Default\                                               Saved Games                     08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Default\                                               Videos                          08-22-2013 10:17:25  08-22-2013 10:17:25  08-22-2013 10:17:25  03-16-2015 23:30:44  0        readable
 192.168.100.103  DIRRO   Users  \Public\                                                Documents                       08-22-2013 10:17:25  08-22-2013 10:17:27  08-22-2013 10:17:27  03-24-2015 14:24:58  0        readable
 192.168.100.103  DIRRO   Users  \Public\                                                Downloads                       08-22-2013 10:17:25  08-22-2013 10:17:27  08-22-2013 10:17:27  03-24-2015 14:01:51  0        readable
```

### CODE REVIEW

**Comment by Meatballs1** [comment]
Could this implement `NT_TRANSACT_QUERY_SECURITY_DESC` to pull back the file permissions or something a bit smarter than reading/writing etc? :D

**Comment by FrUh** [comment]
Of course it would be better, I needed fast fix, so I modified only existing.

**Comment by bcook-r7** [comment]
It seems like this module already reads and writes files during enumeration. While it would be better if it did the smarter thing, I don't think this patch makes it any worse than before. Did I misunderstand?

**Comment by bcook-r7** [comment]
We are going to close this in favor of a PR that can do this without leaving tracks behind.

**Pull request closed without merging**
