### PR TITLE
Zigbee Hardware Bridge Extension

### PR DESCRIPTION
**Pull request by zombieCraig**
This patch adds Zigbee capabilities using the Killerbee python library.  A Metasploit
Relay for Killerbee resides in tools/hardware/killerbee_msfrelay.  Insert any device
that works with Killerbee and start the relay.  Then use the Metasploit HWBridge to
connect to the relay.  One post module is included in this patch, post/hardware/zigbee/zstumber.
The zstumbler module can scan and locate nearby Zigbee networks.

## Verification

First connect a device supported by Killerbee.  Ensure you are using firmware
on that device that can transmit packets.  Killerbee must be installed on the system
as well.

- [x] Start the relay `tools/hardware/killerbee_msfrelay --noauth`
- [x] **Verify** You see `Killerbee MSFRelay running.`
- [x] Launch Metasploit './msfconsole'
- [x] `use auxiliary/client/hwbridge/connect`
- [x] `run`
- [x] **Verify** The Notice of leaving the Matrix shows up and that sessions reports zigbee
- [x] `sessions` should list zigbee
- [x] `sessions -i 1` connect to that hardware bridge
- [x] hwbridge> `supported_devices`
- [x] **Verify** Verify a device is reporting the USB device `Supported Devices: 3:48`
- [x] `run post/hardware/zigbee/zstumbler`
- [x] **Verify** You see messages of scanning channels.  If you have a Zigbee device nearby you should see a summary of each device.

Example:
```
[*] Scanning Channel 11
[*] New Network: PANID: 0x4724 SOURCE: 0x25D5
[*]         Ext PANID: 6E:03:C7:74:31:E2:74:AA       Stack Profile: ZigBee Enterprise
[*]         Stack Version: ZigBee 2006/2007
[*]         Channel: 11
```

### CODE REVIEW

**Comment by pbarry-r7** [comment]
Looks very good, @zombieCraig!!  I was able to run through the checklist and see the Hue ZigBee network:

```
[*] Scanning Channel 11
[*] New Network: PANID: 0x4724 SOURCE: 0xF793
[*]         Ext PANID: 6E:03:C7:74:31:E2:74:AA       Stack Profile: ZigBee Enterprise
[*]         Stack Version: ZigBee 2006/2007
[*]         Channel: 11
```

I have a few small things to PR and have you review, I'll work on getting that submitted no later than tomorrow.

Great stuff!!  🥂

**Comment by h00die** [comment]
I have a smart things network with lots of zwave and zigbee. I can give this a run, what hardware interface do you recommend?

**Comment by zombieCraig** [comment]
@h00die any hardware that [Killerbee](https://github.com/riverloopsec/killerbee) supports will work

**Comment by h00die** [comment]
a little too rich and hard to buy for my blood, passing.

**Comment by pbarry-r7** [comment]
@zombieCraig, added my updates to your PR, nothing too crazy but happy to discuss.  👍 

Sometimes while running a ZigBee scan via my Ubuntu 16.04 VM, the killerbee_msfrelay script throws an exception and becomes unresponsive (requires a CTRL-C), and I have to restart it (and reestablish a session via msfconsole).  I haven't dug into these, but am posting them here in case you might have a clue better than I (and to find out if you've seen these):

### msfconsole output
```
hwbridge > run post/hardware/zigbee/zstumbler channel=11 loop=-1 delay=1

[*] Scanning Channel 11
[*] New Network: PANID: 0x4724 SOURCE: 0x7DD1
[*]         Ext PANID: 6E:03:C7:74:31:E2:74:AA       Stack Profile: ZigBee Enterprise
[*]         Stack Version: ZigBee 2006/2007
[*]         Channel: 11
[*] Scanning Channel 11
[-] Post failed: NoMethodError undefined method `size' for nil:NilClass
[-] Call stack:
[-]   /home/pbarry/opengarages/metasploit-framework/lib/rex/post/hwbridge/extensions/zigbee/zigbee.rb:69:in `recv'
[-]   /home/pbarry/opengarages/metasploit-framework/lib/msf/core/post/hardware/zigbee/utils.rb:102:in `recv'
[-]   /home/pbarry/opengarages/metasploit-framework/modules/post/hardware/zigbee/zstumbler.rb:65:in `scan'
[-]   /home/pbarry/opengarages/metasploit-framework/modules/post/hardware/zigbee/zstumbler.rb:94:in `run'
```

### killerbee_msfrelay output
```
.
.
.
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/sniffer_off HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/set_channel?chan=11 HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:32:53] "GET /zigbee/1:5/inject?data=AwgG_____wc= HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 44818)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "tools/hardware/killerbee_msfrelay", line 159, in do_GET
    self.send(self.recv())
  File "tools/hardware/killerbee_msfrelay", line 91, in recv
    pkt = kb.pnext()
  File "build/bdist.linux-x86_64/egg/killerbee/__init__.py", line 292, in pnext
    return self.driver.pnext(timeout)
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 438, in pnext
    self.sniffer_on()
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 334, in sniffer_on
    self._open_stream()
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 306, in _open_stream
    self.__usb_write(RZ_USB_COMMAND_EP, [RZ_CMD_OPEN_STREAM])
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 288, in __usb_write
    raise Exception("Unknown USB write error: 0x%02x" % response)
Exception: Unknown USB write error: 0x50
----------------------------------------
^CTraceback (most recent call last):
  File "tools/hardware/killerbee_msfrelay", line 251, in <module>
    atexit.register(cleanupInteractiveAtExit)
NameError: name 'cleanupInteractiveAtExit' is not defined
```

### another killerbee_msfrelay output I've seen
```
.
.
.
127.0.0.1 - - [16/Mar/2017 21:30:11] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:11] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:11] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:11] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:11] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:11] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:11] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:12] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:12] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:12] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2017 21:30:12] "GET /zigbee/1:5/recv HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 39626)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "tools/hardware/killerbee_msfrelay", line 159, in do_GET
    self.send(self.recv())
  File "tools/hardware/killerbee_msfrelay", line 91, in recv
    pkt = kb.pnext()
  File "build/bdist.linux-x86_64/egg/killerbee/__init__.py", line 292, in pnext
    return self.driver.pnext(timeout)
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 466, in pnext
    rssi = int(pdata[6])
IndexError: array index out of range
----------------------------------------
^CTraceback (most recent call last):
  File "tools/hardware/killerbee_msfrelay", line 251, in <module>
    atexit.register(cleanupInteractiveAtExit)
NameError: name 'cleanupInteractiveAtExit' is not defined
```

**Comment by pbarry-r7** [comment]
# Release Notes

This patch add capabilities for scanning-and-locating nearby wireless ZigBee networks via the Metasploit HW Bridge.

**Comment by txjoe** [comment]
Hey guys, I ran into something similar while running zstumbler.

Here's the output from the hwbridge session 

`hwbridge > run post/hardware/zigbee/zstumbler

[*] Scanning Channel 11
[-] Post failed: NoMethodError undefined method `size' for nil:NilClass
[-] Call stack:
[-]   /home/txjoe/git/metasploit-framework/lib/rex/post/hwbridge/extensions/zigbee/zigbee.rb:69:in `recv'
[-]   /home/txjoe/git/metasploit-framework/lib/msf/core/post/hardware/zigbee/utils.rb:104:in `recv'
[-]   /home/txjoe/git/metasploit-framework/modules/post/hardware/zigbee/zstumbler.rb:65:in `scan'
[-]   /home/txjoe/git/metasploit-framework/modules/post/hardware/zigbee/zstumbler.rb:98:in `run'
hwbridge > 
`
and here's the output from the relay

`----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42001)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./killerbee_msfrelay", line 159, in do_GET
    self.send(self.recv())
  File "./killerbee_msfrelay", line 91, in recv
    pkt = kb.pnext()
  File "build/bdist.linux-x86_64/egg/killerbee/__init__.py", line 292, in pnext
    return self.driver.pnext(timeout)
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 438, in pnext
    self.sniffer_on()
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 329, in sniffer_on
    self._set_mode(RZ_CMD_MODE_AC)
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 299, in _set_mode
    self.__usb_write(RZ_USB_COMMAND_EP, [RZ_CMD_SET_MODE, mode])
  File "build/bdist.linux-x86_64/egg/killerbee/dev_rzusbstick.py", line 263, in __usb_write
    raise e
USBError: error submitting URB: No such device
----------------------------------------
`

Also, everything works fine while using zbstumbler from the killerbee framework directly. I'm using an Atmel rzusbstick. Any ideas about what's going wrong?

**Comment by zombieCraig** [comment]
@txjoe The "No Such Device" is interesting.  The relay uses (or should be using) the same killerbee framework that you have installed.  You may have to specify the USB index number with -i when starting the relay.  If there is anything special you pass to zstumbler from killerbee you would need to pass that to the relay as well.  Also make sure you are running the relay with permission to talk to the device (like root)

**Comment by txjoe** [comment]
Nevermind, After trying a lot of stuff including reinstalling the framework on a new vm. The problem turned out to be related to using an older version of pyusb. That's my best guess, worked fine after upgrading it! 
Thanks anyway! 
Working on a zbdump module! ^_^

**Pull request merged**
