### PR TITLE
NetAPI: Correct domain controller server type constants

### PR DESCRIPTION
**Pull request by joncave**
The should be specified in hex as BAKCTRL is 16, not 10. CTRL should be 8. See documentation for NetServerEnum https://msdn.microsoft.com/en-us/library/windows/desktop/aa370623%28v=vs.85%29.aspx.

### CODE REVIEW

**Comment by OJ** [comment]
Thanks. Any chance of some repro steps and sample run output to show before/after behaviour?

**Comment by joncave** [comment]
I happened to notice this whilst submitting #5076 but haven't had a chance to do proper test. The lab setup I tried wasn't appropriate for showing differences.

However, [here usage of NetServerEnum](https://github.com/rapid7/metasploit-framework/blob/d3903aaeac1a095c7020282f888b1e7a9601f966/modules/post/windows/gather/credentials/gpp.rb#L378) prior to a refactor. It shows `servertype` set to 24, i.e. 0x8 | 0x10. The comment on that line is confusing because it appears to show decimal addition... and then it shows a logical OR (see #5076).

I will try to test in a better environment for demonstrating the issue when I have time later.

**Comment by Meatballs1** [comment]
Yeah looks correct, incorrect values came from here when I refactored ><

`domaincontrollers = 24  # 10 + 8 (SV_TYPE_DOMAIN_BAKCTRL || SV_TYPE_DOMAIN_CTRL)`

**Comment by Meatballs1** [comment]
Not sure how I came up with 4, probably a railgun OUT param :|

**Pull request merged**
