### PR TITLE
Add documentation for auxiliary/scanner/redis/redis_login module.

### PR DESCRIPTION
**Pull request by yogeshwarram**
This commit adds a documentation for auxiliary/scanner/redis/redis_login module.

### CODE REVIEW

**Review by gwillcox-r7 — COMMENTED** [review]
Overall good but missing explanation that Redis only requires a password to log in. Also missing the `## Options` section to explain the nonstandard PASS_FILE option. Finally, line 2 was way too long, please make sure that lines are no longer than 140 characters in length.

Will be adding a commit shortly to fix these issues and then merge this in.

**Comment by gwillcox-r7** [comment]
Sorry just wanted to say overall this was really good so nice job on your first PR 👍 The fixes I'll be making are mostly minor, you did a good job of including all the relevant info  :)

**Comment by gwillcox-r7** [comment]
Fixes applied in https://github.com/rapid7/metasploit-framework/commit/7f31ac9f2be7f882805792d7d8a7ddf2bc7ccf79

**Comment by pbarry-r7** [comment]
# Release Notes

Added documentation for the `auxiliary/scanner/redis/redis_login` module.

**Pull request merged**
