### PR TITLE
update smb enumeration mod to store results in DB

### PR DESCRIPTION
**Pull request by jabra-**
This PR includes an update for smb_enumusers_domain.rb to allow it to store enumerated users in the database as type 'smb_loggedin_users'.

### CODE REVIEW

**Comment by trosen-r7** [comment]
Hi @jabra- thanks for the PR. Unfortunately we can't accept this as-is because it doesn't use constructs from Metasploit Credential. These users should not be added as `Mdm::Note` objects, but as `Metasploit::Credential::Core` objects without a `Private` component (since password/hash is unknown). [Here is a good example of the general pattern](https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/enum_ad_users.rb#L159) in a related module from @Meatballs1.

Add the report mixin (as Meatballs does above) to get methods from `Metasploit::Credential::Creation`. You will want to use the `create_credential` convenience method and set the origin type as service. There's an example of how to do that [in the code](https://github.com/rapid7/metasploit-credential/blob/master/lib/metasploit/credential/creation.rb#L107).

**Comment by jabra-** [comment]
Thanks @trosen-r7 it's still not clear to me how to add it to as an MDM::Note. Can you provide a better example or PR? Thanks!

**Comment by trosen-r7** [comment]
Hi @jabra-,
That's what I meant above: it should *not* be an `Mdm::Note`. It should use the constructs in the Metasploit Credential library that we built specifically to model credential data. 

What you want to make is a `Metasploit::Credential::Core` with no private associated (`Private` is a password or a hash), and a service origin. The docs at the second link provided above have an example of doing this kind of thing via "convenience methods" that take a hash and produce all necessary pieces of the object graph. The module that @Meatballs1 edited does a similar thing to what you will need to do (just in a post module context where the origin type is a session) and provide an excellent practical example.  Thanks!

**Comment by jabra-** [comment]
okay, i think i have it. let me know if this looks right:

service_data = {
      address: ip,
      port: port,
      service_name: 'smb',
      protocol: 'tcp',
      workspace_id: myworkspace_id
    }

    credential_data = {
      module_fullname: self.fullname,
      origin_type: :service,
      username: username,
    }.merge(service_data)

    credential_core = create_credential(credential_data)

**Comment by trosen-r7** [comment]
Yup that's basically right!

**Comment by jlee-r7** [comment]
@jabra- BTW, github can do syntax highlighting for you in PR comments like this:
```markdown
    ```ruby
    foo = { key: value }
    puts "This is syntax-highlighted ruby code!"
    ```
```

**Comment by jabra-** [comment]
@jlee-r7 sweet! I figured it could do something like that...

**Comment by jabra-** [comment]
I did some testing with the code but the result was that it would only store the username but the corresponding IP or services in the DB. @trosen-r7 can you check to make sure the code above is what I should be using. I think the service/IP component either isnt correct or maybe there is an underlying issue with using it in an aux scanner module? Let me know. I'm excited to get this updated and merged in.

**Comment by trosen-r7** [comment]
hi @jabra- 
I'm still seeing `report_note` used here. Have you pushed all your commits?

**Comment by jabra-** [comment]
@trosen-r7 i didnt update it since it wasnt working (as described above). If you like I can push them... w/e works.

**Comment by jabra-** [comment]
I used the following code to test the changes:
```
credential_core =  create_credential(
         origin_type: :service,
         address: ip,
         port: 445,
         service_name: 'smb',
         protocol: 'tcp',
         module_fullname: self.fullname,
         workspace_id: myworkspace.id,
         username: 'foo'
       )
```

This adds the username to the DB but I don't see the IP or service.

```
Credentials
===========

host  service  public  private  realm  private_type
----  -------  ------  -------  -----  ------------
               foo
```

**Comment by void-in** [comment]
@jabra- Pushing the changes to this PR will be good since then we can take a look what went wrong.

**Comment by jabra-** [comment]
@trosen-r7 @void-in changes have been updated in the PR.

**Comment by jabra-** [comment]
Let me know how I should change the code to fix the PR. Thanks!

**Comment by wchen-r7** [comment]
I'll give this a try, thanks for reviewing all!

**Comment by wchen-r7** [comment]
Might wanna try:

```ruby
  def store_username(username, res)
    service_data = {
      address: rhost,
      port: rport,
      service_name: 'smb',
      protocol: 'tcp',
      workspace_id: myworkspace_id,
      proof: res
    }

    credential_data = {
      origin_type: :service,
      module_fullname: fullname,
      username: username
    }

    credential_data.merge!(service_data)

    credential_core = create_credential(credential_data)

    login_data = {
      core: credential_core,
      status: Metasploit::Model::Login::Status::UNTRIED
    }

    login_data.merge!(service_data)
    create_credential_login(login_data)
  end
```

This PR is also related to:
https://github.com/rapid7/metasploit-framework/pull/5512

**Comment by wchen-r7** [comment]
BTW @jabra- are you still using Ruby 1.9.3? Time to update!

```
rvm install ruby-2.1.6
```

**Pull request merged**
