### PR TITLE
mettle 0.0.6 updates

### PR DESCRIPTION
**Pull request by bcook-r7**
This updates mettle to test build 0.0.6, which includes:
- support for the rest of the net-\* API namespace, including arp, resolve, and flow table commands
- added support for machine_id (uses systemd's machine uuid support where available)
- fixed the 'ps' command to work with more than x86/x86_64, including multi-arch systems
- memoized sysinfo output to avoid repeated calls
- fixed reconnect on staged connections 'flushing' the rx socket
- added support for powerpc64le, mips64
- arm payloads built for armv5 for better compatibility, big and little endian. EABI is required
- hard-float mips and arm payloads removed
# Verification
- [x] Spot check that the payloads work on the intended platforms
- [x] See https://github.com/rapid7/mettle/pull/18 for net- command additions
- [x] See https://github.com/rapid7/mettle/pull/20 for machine_id notes
- [x] See https://github.com/rapid7/mettle/pull/26 for process fixes
- [x] See https://github.com/rapid7/mettle/pull/27 for reconnect fixes

Mettle is still an experimental replacement payload for POSIX systems, with Linux being targeted first. New stagers, transports and additional commands welcome.

### CODE REVIEW

**Comment by bcook-r7** [comment]
removed the stageless bit originally in this PR, will follow up with a mettle 0.0.7 that includes that.

**Comment by wvu-r7** [comment]
Done!

**Comment by busterb** [comment]
Viel dank!

**Comment by wvu-r7** [comment]
# Release Notes

This updates mettle to 0.0.6, bringing in a whole slew of changes, such as complete ```stdapi/net``` support, ```machine_id``` support,  multi-arch ```ps```, memoized ```sysinfo```, and ```powerpc64le``` and ```mips64``` support.

**Pull request merged**
