### PR TITLE
spelling/grammar fixes part 2

### PR DESCRIPTION
**Pull request by h00die**
Preemptively assigning @todb since he did the last one.

just like #8888 .

243 pages left to go.

### CODE REVIEW

**Comment by pbarry-r7** [comment]
I'll grab it!  Thanks for this effort, @h00die!  :clap:

**Comment by h00die** [comment]
It's a work in progress, I'll let you know when it's all done or the phase is complete

**Comment by pbarry-r7** [comment]
Sounds good.  I had just a few minor tweaks, will land here...

**Comment by h00die** [comment]
All good. I think landing before UNITED will work. Hopefully it'll be done before then, but if not it'll be a good stopping spot to avoid conflicts. Tentative time line of Monday for landing

**Comment by todb-r7** [comment]
Heh, I can take it, @pbarry-r7 -- you're way too smart to waste your time on a PR like this. :) I can land this bad boy on Monday when @h00die gets to the aforementioned stopping point.

**Pull request merged**
