### PR TITLE
remove spaces at EOL

### PR DESCRIPTION
**Pull request by Auxilus**
```
./tools/dev/msftidy.rb lib/|grep "Spaces at EOL" > ../tidy.txt
for i in (cat ../tidy.txt |cut -d':' -f1)
    sed 's/[[:blank:]]*$//' -i $i
end
```

### CODE REVIEW

**Comment by smcintyre-r7** [comment]
After a cursory review this looks good. The only thing I'm a little apprehensive about are the changes to the PHP code literals. Did you test those by chance?

**Comment by Auxilus** [comment]
> After a cursory review this looks good. The only thing I'm a little apprehensive about are the changes to the PHP code literals. Did you test those by chance?

tbh, I don't even know which files are in the commit, I'd be happy to test/modify if anyone points out something that breaks stuff

**Comment by smcintyre-r7** [comment]
The ones under `lib/msf/core/payload/php/*`. It would just be worth making sure there's no minification logic or anything that would require that EOL white space.

**Comment by Auxilus** [comment]
> The ones under `lib/msf/core/payload/php/*`. It would just be worth making sure there's no minification logic or anything that would require that EOL white space.

doesn't look like it affects any logic

**Review by agalway-r7 — APPROVED** [review]
LGTM! All removed spaces in HEREDOCS are at the end of comments for shell code and are unlikely to affect execution

**Comment by Auxilus** [comment]
there are still lot of them 😂 but I think I'll open new PR to avoid a single PR with overwhelming number of changes

**Comment by Auxilus** [comment]
~700 in total

**Comment by adamgalway-r7** [comment]
Do you mean you're splitting the above changes into a few PRs, or that you have even more EOL changes in local ready to push?

**Comment by Auxilus** [comment]
> Do you mean you're splitting the above changes into a few PRs, or that you have even more EOL changes in local ready to push?

Oh, no, this PR was only for `lib/metasploit`,  `lib/msf/core` and `lib/rex`.
I'll open PR for others

**Comment by adamgalway-r7** [comment]
> Oh, no, this PR was only for `lib/metasploit`, `lib/msf/core` and `lib/rex`.
> I'll open PR for others

Good stuff! 👍In that case I'm happy to merge this PR in if you are?

**Comment by Auxilus** [comment]
> > Oh, no, this PR was only for `lib/metasploit`, `lib/msf/core` and `lib/rex`.
> > I'll open PR for others
> 
> Good stuff! In that case I'm happy to merge this PR in if you are?

sure 😂

**Comment by adfoster-r7** [comment]
@Auxilus As a heads up, we recently changed our Rubocop configuration in https://github.com/rapid7/metasploit-framework/pull/12990 which will be able to fix a lot of the Ruby related whitespace issues. It's something we'll be incrementally rolling out to the codebase too :+1:

**Pull request merged**
