### PR TITLE
bump ruby version to 2.1.9

### PR DESCRIPTION
**Pull request by firefart**
Ruby 2.1.9 was released containing some security fixes:
https://www.ruby-lang.org/en/news/2016/03/30/ruby-2-1-9-released/

### CODE REVIEW

**Comment by FireFart** [comment]
Looks like travis has no binary of ruby-2.1.9 yet:
http://rubies.travis-ci.org/

**Comment by bcook-r7** [comment]
I imagine we could merge .ruby-version first and then travis when it catches up.

**Comment by FireFart** [comment]
@bcook-r7 i reverted the travis change for now, the followup PR is located in #6739

**Comment by busterb** [comment]
Cheers

**Pull request merged**
