### PR TITLE
create av_list.txt for Commit 6a4fc38

### PR DESCRIPTION
**Pull request by madmantm**
Commit 6a4fc38

### CODE REVIEW

**Comment by OJ** [comment]
@madmantm thanks. Can you please update your other PR at #5730 with this change, rather than creating a new PR? thanks.

**Comment by OJ** [comment]
It also looks like you're working from the Github UI. May I suggest you use the git command line as well? This gives you a lot more control over what goes on.

To include your new changeset in your old PR, just checkout that branch, apply your changes, and push to your existing PR branch. The PR itself will automatically update.

**Comment by madmantm** [comment]
Thanks, my apologies for the confusion, i hope everything is in order.



On Wed, Jul 15, 2015 at 8:19 PM, OJ Reeves <notifications@github.com> wrote:

> It also looks like you're working from the Github UI. May I suggest you
> use the git command line as well? This gives you a lot more control over
> what goes on.
>
> To include your new changeset in your old PR, just checkout that branch,
> apply your changes, and push to your existing PR branch. The PR itself will
> automatically update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rapid7/metasploit-framework/pull/5733#issuecomment-121786963>
> .
>



-- 
Marc-André Meloche

**Comment by OJ** [comment]
No problem!

**Pull request closed without merging**
