### PR TITLE
Initial commit for supporting SSL Labs API

### PR DESCRIPTION
**Pull request by dnkolegov**
This pull request contains a client for SSL Labs APIs as module. SSL Labs APIs - SSL/TLS assessment  API, which can be used to test SSL servers available on the public Internet. This module is based on source code of [ssllabs.rb](https://github.com/Shopify/ssllabs.rb). This is initial commit that provide base functionality.

Authors: 
- Denis Kolegov (@dnkolegov) - module developer
- Francois Chagnon (@EiNSTeiN-) - ssllabs.rb developer

Links:
[SSL Labs API Documentation v1.16.x](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md)

### CODE REVIEW

**Comment by bcook-r7** [comment]
Thanks! I gave this a quick spin and found that the module backtraces if given an IP address for hostname. Would it be better if it caught and logged the API error nicely to the console instead?

```
msf auxiliary(ssllabs_scan) > set hostname 74.125.239.116
hostname => 74.125.239.116
msf auxiliary(ssllabs_scan) > run

[*] SSL Labs API info
[*] API version: 1.15.1
[*] Evaluation criteria: 2009i
[*] Running assessments: 0 (max 25)
[-] Auxiliary failed: Msf::Modules::Mod617578696c696172792f6761746865722f73736c6c6162735f7363616e::Metasploit3::InvocationError invalid parameters
[-] Call stack:
[-]   /Users/bcook/projects/metasploit-framework/modules/auxiliary/gather/ssllabs_scan.rb:55:in `request'
[-]   /Users/bcook/projects/metasploit-framework/modules/auxiliary/gather/ssllabs_scan.rb:74:in `analyse'
[-]   /Users/bcook/projects/metasploit-framework/modules/auxiliary/gather/ssllabs_scan.rb:739:in `run'
[*] Auxiliary module execution completed
```

**Comment by dnkolegov** [comment]
Thanks for this. SSL Labs does not support assessment via IP address. I'll fix it soon as possible.

**Comment by bcook-r7** [comment]
I changed the report logging semantics a little with some wrappers. print_error is generally reserved for runtime errors in the modules themselves, not reports of bad things found on the remote server. print_warning was a little more grey (or yellow) so I left it. Thanks.

**Comment by dnkolegov** [comment]
Great. Thank you.

**Pull request merged**
