### PR TITLE
listen on 127.0.0.1 by default

### PR DESCRIPTION
**Pull request by rwhitcroft**
This has to be better than 0.0.0.0 imo.

### CODE REVIEW

**Comment by timwr** [comment]
Not sure about this. If you bind to 127.0.0.1 you won't be able receive a session from the local network right? With 0.0.0.0 you can.

**Comment by OJ** [comment]
+1 @timwr, perhaps @rwhitcroft can explain more?

**Comment by rwhitcroft** [comment]
I guess I've never had a need to bind to 0.0.0.0. Maybe I'm not using the module to its full potential/capabilities?

My workflow is usually to start socks4a, then use tsocks locally to send stuff through the session. I'm curious what the workflow would be that would require 0.0.0.0?

**Comment by wvu-r7** [comment]
You mean you DON'T want to share your proxy with everyone?

**Comment by OJ** [comment]
I always bind to a known IP while running on a VPS that's firewalled off to only allow me to connect. Then all my traffic goes via the cloud.

I see the argument for either side, but `0.0.0.0` would make more sense to me over `127.0.0.1`. IMHO of course :)

**Pull request closed without merging**
