### PR TITLE
[WIP] Add a custom http bruteforce module utilizing POST method to bypass DVWA login page

### PR DESCRIPTION
**Pull request by 3V3RYONE**
This PR adds a custom http bruteforce module (`dvwa_login.rb`) and it's corresponding `login_scanner` (`http_post.rb`) template to authenticate to a `DVWA login` page.  
  
## Approach  
  
Firstly, all the parameters like `AUTH_URI` and `RHOSTS` are configured from the options set by the user. `REDIRECT_URI` is a parameter introduced which contains the URI that `AUTH_URI` redirects to, when a successful login occurs (example `/login.php` redirects to `/index.php`). Then, it grabs the credentials one by one in the `USERPASS_FILE`. For each credential,  
1. It first performs a **GET** request on the `AUTH_URI`. In this request, it grabs the latest `session_id` and the `csrf_token` in the target and returns it to parameters.  A regex match (`/\w{32}/`) is used to extract the csrf_token.  
2. Then it prepares all the parameters required to make the authentication request, (Like `username` and `password` from the `USERPASS_FILE`, `cookie` from the `session_id` and `csrf_token` from `csrf_token`.  
3. Then it sends all the above data as a **POST** request to the `AUTH_URI` target to attempt to authenticate.  
4. Then the response is analyzed to check if it was a successful login. Specially, the **headers location** of the response is checked if it includes the `REDIRECT_URI` parameter set by the user. If it does, then the credential is correct. Else it's invalid.  
5. Checks for the next credentials in the `USERPASS_FILE`.
  
## Verification
  
- [ ] Setup `DVWA` in your machine. ([installation guide in kali](https://www.golinuxcloud.com/install-dvwa-kali-linux/))
- [ ] Use the modified files of this PR in your msf.
- [ ] Start `msfconsole`
- [ ] run `use auxiliary/scanner/http/dvwa_login`
- [ ] set `RHOSTS` to DVWA hosted IP (maybe `127.0.0.1`)
- [ ] set `AUTH_URI` to `/DVWA/login.php`
- [ ] set `USERPASS_FILE` (maybe to `data/wordlists/http_default_userpass.txt`) 
- [ ] `run`
- [ ] **Verify** that the bruteforce module shows **SUCCESS status** for **admin:password** credential.
- [ ] **Verify** that the bruteforce module shows **FAILED status** for other invalid credentials.

```  
msf6 > use auxiliary/scanner/http/dvwa_login
msf6 auxiliary(scanner/http/dvwa_login) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf6 auxiliary(scanner/http/dvwa_login) > set USERPASS_FILE /home/beleswar/metasploit-framework/data/wordlists/http_default_userpass.txt
USERPASS_FILE => /home/beleswar/metasploit-framework/data/wordlists/http_default_userpass.txt
msf6 auxiliary(scanner/http/dvwa_login) > run

[-] 127.0.0.1:80 - Failed: 'connect:connect'
[!] No active DB -- Credential data will not be saved!
[-] 127.0.0.1:80 - Failed: 'sitecom:sitecom'
[-] 127.0.0.1:80 - Failed: 'admin:1234'
[-] 127.0.0.1:80 - Failed: 'cisco:cisco'
[-] 127.0.0.1:80 - Failed: 'cisco:sanfran'
[-] 127.0.0.1:80 - Failed: 'private:private'
[-] 127.0.0.1:80 - Failed: 'wampp:xampp'
[-] 127.0.0.1:80 - Failed: 'newuser:wampp'
[-] 127.0.0.1:80 - Failed: 'xampp-dav-unsecure:ppmax2011 '
[-] 127.0.0.1:80 - Failed: 'admin:turnkey'
[-] 127.0.0.1:80 - Failed: 'vagrant:vagrant'
[+] 127.0.0.1:80 - Success: 'admin:password'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```  
  
## Generalization  
  
I was wondering if we can generalize this LoginScanner template (`http_post.rb`) to be a generalized template utilizing POST method. I have **currently** committed some generalization attempts in `http_post.rb`:  
1. Allowing `AUTH_URI` parameter to be set by the user, and not just limited to DVWA login page (`/DVWA/login.php`)  
2. Obtaining `REDIRECT_URI` parameter from the user, (The URI to which the `AUTH_URI` redirects to incase of successful credentials) and not just always using `/index.php` (which is for DVWA)    
3.  `check_setup` method verifies whether the target needs www-authentication or not, and is not just limited to DVWA verification.  
  
## WIP  
  
4. Allowing the user to send a sample `POST_DATA` to be sent to the target. This ensures we are sending the specific format of post_data that the target requires to authenticate. For example, **`DVWA`** has a post data of the type   `username=admin&password=password&Login=Login&user_token=004fc0b9ee58345cfeeb5198b782bc63`  
  whereas **`symantec_web_gateway`** uses a format like  
`USERNAME=gooduser&PASSWORD=GoodPassword&loginBtn=Login`  
  
So as of now, I have implemented to extract the parameters from the sample POST data string (like `username` or `USERNAME`, & `Login` or `loginBtn`) and send it in order in the `vars_post` variable. So, saying   
`user=admin&pass=password&login=Login&auth_token=004fc0b9ee58345cfeeb5198b782bc63` data string will still work for this template.   
  
But a different order of parameters might still cause a problem. Like `password=password&user=admin&Login=Login` will fail because I haven't taken care for different order data string. **Any more suggestions in how we can make this part more generalized to have a general login_scanner template?**  
  
Also, what do you think would be optimal? To make this generalized or specific to DVWA? Thanks :)

### CODE REVIEW

**Comment by 3V3RYONE** [comment]
May you review this @gwillcox-r7 in your free time :) ..  
I just realized it's a lot of commits, is that a problem? noob coding :sweat_smile: :cry:

**Comment by smcintyre-r7** [comment]
You can use an interactive rebase to squash commits down into smaller groups or into a single commit. It would be helpful when reviewing the history.

**Comment by gwillcox-r7** [comment]
@3V3RYONE Can take a look today. I will say in general we try and squash commits down if possible to as small a size as possible once review etc is done. 44 commits is a lot, I'd say max I'd typically expect is maybe 20, but really its more typical to see it squashed down to somewhere under 10 commits, unless there is some reason why this can't be done such as preserving the message behind different commits to make it easier to roll certain changes back if needs be.

**Comment by gwillcox-r7** [comment]
@3V3RYONE I'd also want to ask specifically for this PR, why just focus on the DVWA page? Is this applicable to other pages beyond DVWA? I don't think we would want to accept a PR that focuses just on DVWA and is not applicable to other websites. I'd see if you can reframe your proposal in the context of how this might be applicable to other websites as well beyond just DVWA.

**Comment by adfoster-r7** [comment]
I'm not opposed to a module for targeting DVWA for pedagogical purposes, but it would be great to see a module which focused on software that could be used by pentesters

**Comment by smcintyre-r7** [comment]
> But a different order of parameters might still cause a problem. Like password=password&user=admin&Login=Login will fail because I haven't taken care for different order data string. Any more suggestions in how we can make this part more generalized to have a general login_scanner template?
> 
> Also, what do you think would be optimal? To make this generalized or specific to DVWA? Thanks :)

I can't recall having ever seen an instance where the order of the POST form data was important. Every web framework I've ever used just allows the developer to extract the value from a hash / associative array. I wouldn't be too concerned about this being a problem.

As for being generalized or specific to DVWA. If you could make it work for general form-based authentication that would be much **much** more valuable. We'd want to make sure it was tested on a variety of systems though and it'd be a complex problem to solve. Three main problems come to mind immediately:

1. Dealing with CSRF tokens and how different applications implement them.
    * If I were writing this, I'd always request the login page, then forward all parameters, cookies etc I found, only modifying the username and password fields.
2. Automatically identifying the username and password fields.
    * If I were writing this, I'd check for a single HTML input field of type password, pull it's form field and the form field for the text field directly before it. This would require some decent HTML parsing analysis capability which Metasploit isn't particularly strong in.
3. Identifying a successful case from a failure. Different apps might redirect vs set a cookie, vs respond with an HTTP status code.
    * If I were writing this, I'd use a known failure case of a random username/password and then match various qualities of the response to that. Once that doesn't match is likely a success.

**Comment by 3V3RYONE** [comment]
Thanks @smcintyre-r7 , @gwillcox-r7 ! I'd squash down the commits! It just happened to be these more commits because, apparently msfconsole was not detecting the changes done in files while writing the modules. Even `reload all` wasn't working. Maybe I was missing something, but committing the changes was working. Hence, all these silly commits appeared.

**Comment by 3V3RYONE** [comment]
@gwillcox-r7 , I just wrote this focusing on DVWA because it was required by one member in slack remember? I'd personally also want it to serve multiple websites other than just DVWA, hence asked about generalization. I will surely check if it authenticates to other websites as well and let you know..

**Comment by smcintyre-r7** [comment]
You need to use the `reload_lib` command to reload library files. `reload` is just for modules.

**Comment by 3V3RYONE** [comment]
> You need to use the `reload_lib` command to reload library files. `reload` is just for modules.

Uhh, I seriously missed this :')

**Comment by gwillcox-r7** [comment]
@3V3RYONE Converted this to a draft PR since this is still WIP at the moment. This will better reflect status to those looking to review PRs. Once you want to convert it back into a ready state, just click the `Ready for review` button above and it will turn it back into a ready to review PR again. Just helps keep track of things a bit more, hopefully doesn't cause an inconvenience; should still be able to interact with this PR normally as its just a visual indicator, nothing more.

**Comment by 3V3RYONE** [comment]
Ofcourse! All good no worries... That's really important.. Thanks for specially pointing it out! Makes my day :))

**Comment by smcintyre-r7** [comment]
I'm going to attic this draft since we haven't seen any movement on it in over 3 months. If we'd like to reopen it when development resumes just let me know and I'd be happy to do so.

**Pull request closed without merging**
