### PR TITLE
Add Aaron to the mailmap.  Woo!

### PR DESCRIPTION
**Pull request by pbarry-r7**
Include @asoto-r7 in the mailmap.  😸

### CODE REVIEW

**Review by bcoles — APPROVED** [review]
Looks legit

**Comment by wchen-r7** [comment]
# Release Notes

Adding new member Aaron Soto the mailmap.

**Comment by pbarry-r7** [comment]
I'ma readd the "no release notes" label, as it seems that this isn't something customers would be interested in (and I don't believe we've published notes on changes to the .mailmap file in the past).  If I'm in error here, by all means let me know.  :)

**Comment by mkienow-r7** [comment]
@pbarry-r7 It was a reaction to @wchen-r7 adding release notes, however, you make a great point that I didn't think of when I removed the tag. :)

**Pull request merged**
