### PR TITLE
My final round of updating modules to use the metasploit-credential API

### PR DESCRIPTION
**Pull request by wchen-r7**
This is my final round of updating modules to use the metasploit-credential API.

Test:
- [x] Start msfconsole
- [x] loadpath test/modules
- [x] `use auxiliary/test/report_auth_info`
- [x] `run`
- [x] You should get:

```
[+] Number of test cases that passed: 90
[-] Number of test cases that failed: 0
[*] Number of test cases overall: 90
```

### CODE REVIEW

**Comment by wvu-r7** [comment]
Getting ```ActiveRecord::RecordInvalid Validation failed: Session can't be blank``` on ```test_mount_cifs_creds```.

**Comment by wvu-r7** [comment]
@bcook-r7 ran into the same error.

**Comment by wvu-r7** [comment]
I fixed ```mount_cifs_creds ``` in https://github.com/rapid7/metasploit-framework/commit/8866b15f3b6b0dbeccd7b22a3804c6dc00afce57.

**Comment by bcook-r7** [comment]
Awesome, thanks for finishing this up guys!

**Pull request merged**
