### PR TITLE
Added metasploit module for access OSX messages database

### PR DESCRIPTION
**Pull request by geckom**
This module will download OSX messages database (sqlite3 format) as well as a easy to read format. You can also specify how many of the latest messages to download (for things like 2FA).

## Verification

- [x] Start `msfconsole`
- [x] `use post/osx/gather/enum_messages`
- [x] `set SESSION 1`
- [x] `run`
- [x] **Verify** All modules are run, loot is stored for: DB file, text file (readable format) and 3 latest messages

### CODE REVIEW

**Comment by wchen-r7** [comment]
Works nicely for me.

**Comment by wchen-r7** [comment]
Ruby code looks clean, nice job!

**Comment by wchen-r7** [comment]
# Release Notes

This module allows you to collect archived chat messages from OS X.

**Comment by wvu-r7** [comment]
Sorry for the commit spam. Cleanup and refactor in #7624.

**Pull request merged**
