### PR TITLE
use vagrant and chef-apply to provision a dev box.

### PR DESCRIPTION
**Pull request by xlgmokha**
I was just [reading the steps](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) to get a development box working and thought that it might be useful to script out building a dev box using vagrant + chef-apply. 

If others would find this useful, I can complete the rest of the instructions in the `setting up a dev box` wiki page as per the chef-apply recipe.

### CODE REVIEW

**Comment by bcook-r7** [comment]
seems like a good idea to me, thanks.

**Comment by jmongrel** [comment]
Can't wait to check this out. :)

**Comment by mokhan** [comment]
I've got the vagrant recipe working in vmware_fusion. I chose a box that works for both vmware_fusion and virtualbox. See [here](https://atlas.hashicorp.com/phusion/boxes/ubuntu-14.04-amd64) for more details.

I'm just running into one issue. I'm not sure if it's related to vagrant provisioning or if I missed something. When I run the specs I'm getting the following error:

```bash
vagrant@ubuntu-14:/vagrant$ bundle exec rake spec
rake aborted!
LoadError: cannot load such file -- robots
/vagrant/lib/metasploit/framework.rb:18:in `require'
/vagrant/lib/metasploit/framework.rb:18:in `<top (required)>'
/vagrant/config/application.rb:10:in `<top (required)>'
/vagrant/Rakefile:2:in `require'
/vagrant/Rakefile:2:in `<top (required)>'
LoadError: cannot load such file -- metasploit-framework
/vagrant/config/application.rb:10:in `<top (required)>'
/vagrant/Rakefile:2:in `require'
/vagrant/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
```

Can anyone pull my branch and run the following:

```bash
$ vagrant up
$ vagrant ssh
$ cd /vagrant
$ ruby -v
$ bundle install -j 2
$ bundle exec rake spec
```

**Comment by jmongrel** [comment]
sorry Mo, just saw this email. I'll try to figure it out and send comments.
:)

Cheers
JJ

**Comment by gmikeska-r7** [comment]
I'm noticing that a lot of the packages chef-apply was supposed to be loading for us aren't showing up. Is that happening in your copy as well, @mokhan?

Also, do you have any objections to the use of rvm instead of rbenv? I believe it would make loading ruby a little easier. What are your thoughts on this?

**Comment by gmikeska-r7** [comment]
@mokhan, @jmongrel Did either of you run into problems with the apt package called ````grub-pc````? I noticed after running @mokhan's chef recipe that any package that used grub-pc was failing to install.

I broke the whole process down into batch file provisioners. The workflow I have found successful includes installing grub-pc first, then running ````update-grub````. Then, a reboot is triggered, through a reboot provisioner script. After the reboot, I have another shell provisioner that installs all of the other packages. At first this **still** wasn't working so I have taken the somewhat drastic step of invoking ````update-grub```` after the installation of each package, and that seems to resolve the problem.

Oh, also, in my implementation, I use RVM for ruby versioning. I also switch user to ````vagrant```` to compile and install the ruby package: ````su -l vagrant -c "rvm install ruby-2.1.9"```` and to install bundler ````su -l vagrant -c "gem install bundler"````

**Comment by mokhan** [comment]
I have no objections to using RVM. I don't recall having any issues with the grub-pc package. A new Ubuntu LTS was just recently release. I'm not sure if this is related or not. My only hesitation with shell-provisioners is that they  haven't been as good at managing updates as I have found chef to be. I'm happy that' we're working towards an automated solution for bootstrapping a new dev environment, so if that solution is preferred it works for me.

Please let me know if you would like me to close this PR in favor of your changes @gmikeska-r7. Thank you very much for looking into this.

**Comment by gmikeska-r7** [comment]
@mokhan Let's work from this PR for now. I want to see if I can re-implement what I've got in a chef-apply recipe, and I'd love if you'd test it! As I investigate, I will consider the best way to move forward.

**Comment by mokhan** [comment]
That sounds great.

**Comment by bcook-r7** [comment]
Note, we updated the provisioning steps a bit yesterday, simplifying a few things. It would be great if we could make sure that they mirrored each-other as much as possible.

**Comment by bcook-r7** [comment]
Sorry for the long delay on this. I have made some changes this morning, namely moving back to shell provisioners instead of chef, and switching to the official ubuntu box provider. The main concern I had with phusion/boxes/ubuntu-14.04-amd64 is its age - it hasn't had updates in 2 years. It would be great if there was a minimal upstream box that also stayed up-to-date, so you don't have to grab hundreds of megabytes of packages just to bootstrap.

Getting this in-tree and then we can work on it from there.

**Comment by bcook-r7** [comment]
Thanks! Changes: 2534ef76f30fd4c38de01771b0e99323d432c41f

**Comment by mokhan** [comment]
:+1:

**Comment by tdoan-r7** [comment]
@mokhan should https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment still be updated?

**Comment by mokhan** [comment]
I think that's a good idea @tdoan-r7 .

**Pull request merged**
