### PR TITLE
Deprecate msfpayload and msfencode

### PR DESCRIPTION
**Pull request by wchen-r7**
See #4326, but it does not close it.

When you use msfencode, it will print the following message:

```
[!] ************************************************************************
[!] *               The utility msfencode is deprecated!                   *
[!] *              It will be removed on or about 2015-06-08               *
[!] *                   Please use msfvenom instead                        *
[!] ************************************************************************
```

For msfpayload:

```
[!] ************************************************************************
[!] *               The utility msfpayload is deprecated!                  *
[!] *              It will be removed on or about 2015-06-08               *
[!] *                   Please use msfvenom instead                        *
[!] ************************************************************************
```

But both remain functional.

Please make sure Travis is green.

### CODE REVIEW

**Comment by todb-r7** [comment]
@wchen-r7 June 8 is fast approaching. It's Monday, in fact. This should still be fine, with just one caveat below.

This weekend, we're restoring the old functionality of community.rapid7.com -- see this tweet: https://twitter.com/rapid7/status/606549392762363905

If there are hiccups with the restore, I'd suggest avoiding `rm`ing msfvenom until we have our communications in a reasonable place. Despite 6 months of warning, I'm sure there will be tons of people who will be surprised. I'd like to have some place to point them to in addition to this ticket and issue #4326.

Once we're all set, @wchen-r7 or I can write a blog post on the brand-new-old community.rapid7.com site. That'll be essentially be a two paragraph rehash the last blog post on the subject. (That link is https://community.rapid7.com/community/metasploit/blog/2014/12/09/good-bye-msfpayload-and-msfencode right now, should be much easier to read in a couple days).

**Comment by wchen-r7** [comment]
No problem, we'll wait until Jive comes back. I'll write a blog post, and then wait another 3 days before I submit the removal pull request.

**Comment by Ooshchroep** [comment]
There are't msfpayload and msfencoder in newest metasploit。。could you write the new blog about metasploit

**Comment by bcook-r7** [comment]
@Ooshchroep https://community.rapid7.com/community/metasploit/blog/2014/12/09/good-bye-msfpayload-and-msfencode

**Comment by abdell-maker** [comment]
hi
please how I can find black laser tool

**Pull request merged**
