### PR TITLE
Lock xpath version to 2.0

### PR DESCRIPTION
**Pull request by dmohanty-r7**
This PR locks xpath to version 2.0. Current Pro-Framework integration tests are failing due to versioning issues with xpath. This should resolve the issue.

## Verification

- [ ] Verify tests pass

### CODE REVIEW

**Comment by sempervictus** [comment]
@dmohanty-r7: could you give a bit of context for this?

**Comment by bwatters-r7** [comment]
Is this in relation to the mettle merges?

**Comment by dmohanty-r7** [comment]
Updated with context

**Comment by busterb** [comment]
A little more back story, we use capybara for internal testing. Recently xpath released an update that breaks capybara due to a changed api. As a side-effect, a lot of testing broke. This is a temporary version pin to allow tests to proceed.

**Comment by bwatters-r7** [comment]
# Quick test
image
Nothing is horribly broken; ignore the failure.  I checked the PCAP.... that's something else

**Comment by bwatters-r7** [comment]
See..... everything is fine.
image

**Comment by sempervictus** [comment]
Oh, now I feel like an ass, or as much of one as I can conceptualize. Thanks for the quick responses - pro builds are kinda important, keeps the people who keep the lights on fed.

**Pull request merged**
