### PR TITLE
Nuke datastore modification check from orbit

### LINKED ISSUE #3853: Modules should not alter their own datastores without normalization
*This issue was [RM7234](https://dev.metasploit.com/redmine/issues/7234), originally filed by @todb-r7*

Currently, there are 98 instances of modules that modify the datastore at runtime, according to msftidy:
````
tools/msftidy.rb modules/ | grep datastore > datastore.txt ; cat datastore.txt | wc -l
98
````

This is asking for trouble in many cases, because it means that modules are getting values stuffed in their datastores that may or may not have been normalized. Also, there are concerns that altering a datastore option at runtime will have unexpected effects on modules that run after the datastore altering.

There should be a way to do this kind of assignment that guarantees normalization (there are several OO strategies to chose from), or developers should be prohibited from altering the datastore at runtime altogether.

See PRs #2300 and #3841, as well as @wchen-r7's [documentation](https://github.com/rapid7/metasploit-framework/wiki/How-to-use-datastore-options#modifying-datastore-options-at-run-time).

### PR DESCRIPTION
**Pull request by wvu**
```
wvu@kharak:~/metasploit-framework:beug/datastore$ tools/msftidy.rb modules
wvu@kharak:~/metasploit-framework:beug/datastore$ 
```

BOOM.

[It's the only way to be sure](https://www.youtube.com/watch?v=aCbfMkh940Q)

Fixes #3853.

### CODE REVIEW

**Comment by jhart-r7** [comment]
I'm confused -- modifying datastore is still a bad thing, right?

**Comment by todb-r7** [comment]
@jhart-r7 short answer: yes. Long answer: Not completely verboten. See https://github.com/rapid7/metasploit-framework/wiki/Common-Metasploit-Module-Coding-Mistakes when @wvu-r7 gives us a more nuanced answer.

Basically, the datastore should not be used as a scratch pad, and shouldn't (but not mustn't) be used as a workaround for a mixin that wants something from the datastore.

There are 102 infractions right now, and all of them are on that bubble of being reasonable. I would love to see them re-engineered, as if by magic, by [brownies](http://en.wikipedia.org/wiki/Brownie_%28folklore%29), but we've hit the threshold of diminished returns on fixing up datastore modifications.

**Comment by todb-r7** [comment]
See https://github.com/rapid7/metasploit-framework/issues/3853

**Comment by wvu-r7** [comment]
```
tools/msftidy.rb modules | grep -c datastore
95
wvu@kharak:~/metasploit-framework:master$ 
```

95 now. AFAIK, we have fixed all the naive cases.

**Comment by todb-r7** [comment]
Note, assignment to the datastore **should** still trigger a validation pass. But, I'm not going to make a federal case out of it.

**Pull request merged**
